#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
######################################################################
#
# Helper program to share details
#
######################################################################
#
# How to use:
# ------------
# Run: lynis show <option>
#
######################################################################

COMMANDS="audit configure generate show update upload-only"
HELPERS="audit configure show update"
OPTIONS="--auditor\n--cronjob (--cron)\n--debug\n--developer\n--devops\n--forensics\n--help (-h)\n--log-file\n--manpage (--man)\n--no-colors\n--no-log\n--no-plugins\n--pentest\n--profile\n--plugin-dir\n--quick (-Q)\n--quiet (-q)\n--report-file\n--reverse-colors\n--tests\n--tests-from-category\n--tests-from-group\n--usecwd\n--upload\n--verbose\n--version (-V)\n--wait\n--warnings-only"

SHOW_ARGS="categories changelog commands dbdir details environment eol groups help hostids includedir language license logfile man options os pidfile plugindir profiles release releasedate report settings tests version workdir"
SHOW_HELP="lynis show ${BROWN}categories${NORMAL}              （显示检查分类）
lynis show ${BROWN}changelog${NORMAL} ${GRAY}[版本]${NORMAL}        （显示版本更新记录）
lynis show ${BROWN}commands${NORMAL}                （显示全部可用命令）
lynis show ${BROWN}dbdir${NORMAL}                   （显示数据库目录）
lynis show ${BROWN}details${NORMAL}                 （从日志中显示指定检查的详细信息）
lynis show ${BROWN}environment${NORMAL}             （显示物理机、虚拟机或容器环境）
lynis show ${BROWN}eol${NORMAL}                     （显示操作系统停止支持状态）
lynis show ${BROWN}groups${NORMAL}                  （显示检查分组）
lynis show ${BROWN}help${NORMAL}                    （显示参数的详细帮助）
lynis show ${BROWN}hostids${NORMAL}                 （显示本机的唯一标识）
lynis show ${BROWN}includedir${NORMAL}              （显示检查与函数文件所在目录）
lynis show ${BROWN}language${NORMAL}                （显示已配置或检测到的语言）
lynis show ${BROWN}license${NORMAL}                 （显示许可证信息）
lynis show ${BROWN}logfile${NORMAL}                 （显示日志文件位置）
lynis show ${BROWN}man${NORMAL}                     （显示手册使用方法）
lynis show ${BROWN}options${NORMAL}                 （显示可用选项）
lynis show ${BROWN}os${NORMAL}                      （显示操作系统及版本）
lynis show ${BROWN}pidfile${NORMAL}                 （显示保存进程编号的文件）
lynis show ${BROWN}plugindir${NORMAL}               （显示插件目录）
lynis show ${BROWN}profiles${NORMAL}                （显示已发现的配置文件）
lynis show ${BROWN}release${NORMAL}                 （显示程序版本）
lynis show ${BROWN}releasedate${NORMAL}             （显示版本发布日期）
lynis show ${BROWN}report${NORMAL}                  （显示报告数据文件位置）
lynis show ${BROWN}settings${NORMAL}                （显示当前设置，${WHITE}选项：${NORMAL} ${CYAN}--brief --nocolors${NORMAL}）
lynis show ${BROWN}tests${NORMAL} ${GRAY}[检查编号]${NORMAL}        （显示一个或多个检查项目的信息）
lynis show ${BROWN}tests skipped${NORMAL}           （显示配置文件要求跳过的检查）
lynis show ${BROWN}version${NORMAL}                 （显示 ${PROGRAM_NAME} 版本）
lynis show ${BROWN}workdir${NORMAL}                 （显示工作目录）"

AUDIT_ARGS="( dockerfile | system )"
AUDIT_HELP="
  ${WHITE}lynis audit <目标>${NORMAL}

  ${CYAN}audit dockerfile ${BROWN}<文件>${NORMAL}

  对 Dockerfile 执行安全审计
  ${GRAY}示例：${NORMAL}
    lynis audit dockerfile Dockerfile


  ${CYAN}audit system ${GRAY}[选项]${NORMAL}

  对本机执行系统安全审计

  ${GRAY}示例：${NORMAL}
    lynis audit system
    lynis audit system --cronjob
    lynis audit system --profile developer.prf
    lynis audit system --quick


  ${CYAN}audit system remote ${BROWN}<目标> ${GRAY}[选项]${NORMAL}

  对远程目标执行系统安全审计

  ${GRAY}示例：${NORMAL}
    lynis audit system remote 192.168.1.100
    lynis audit system remote 192.168.1.100 --no-colors

"

GENERATE_ARGS="( --save )"
GENERATE_HELP="
  为 hostid 和 hostid2 生成随机值
  ${WHITE}lynis generate hostids${NORMAL}

  生成并保存这些值
  ${WHITE}lynis generate hostids --save${NORMAL}

  生成用于定期运行 Lynis 的 systemd 单元，例如每天运行一次
  ${WHITE}lynis generate systemd-units${NORMAL}

"


UPDATE_ARGS="check | info"
UPDATE_HELP="
  ${CYAN}update info${NORMAL}

  检查并显示版本信息

  ${CYAN}update check${NORMAL}

  仅检查当前版本是否为最新版

"

UPLOAD_ONLY_HELP="
  ${CYAN}upload-only${NORMAL}

  仅执行数据上传

"

SHOW_SETTINGS_ARGS="--brief --configured-only --nocolors"
SHOW_TESTS_ARGS="skipped"

COMMANDS_AUDIT_SYSTEM_USAGE="用法：lynis audit system"
COMMANDS_AUDIT_SYSTEM_FUNCTION="功能：对当前系统执行安全审计"

if [ $# -gt 0 ]; then
    case $1 in
        "categories")
            ViewCategories
            ;;
        "changelog")
            # Allow providing a version
            if [ $# -gt 1 ]; then
                shift; SEARCH_VERSION="$1"
            fi
            PROGRAM_NAME_LOWER=$( echo ${PROGRAM_NAME} | tr '[:upper:]' '[:lower:]')
            CHANGELOG_PATHS="/usr/share/doc/${PROGRAM_NAME} /usr/share/doc/${PROGRAM_NAME}-${PROGRAM_VERSION} /usr/share/doc/${PROGRAM_NAME_LOWER} ."
            CHANGELOG=""
            if [ -z "${SEARCH_VERSION}" ]; then SEARCH_VERSION="${PROGRAM_VERSION}"; fi
            STARTED=0
            for FILEPATH in ${CHANGELOG_PATHS}; do
                if [ -f ${FILEPATH}/CHANGELOG.md ]; then
                    CHANGELOG="${FILEPATH}/CHANGELOG.md"
                # Check also for gzipped changelog
                elif [ -f ${FILEPATH}/changelog.gz ]; then
                    ZCAT=$(which zcat 2> /dev/null | grep -v "no [^ ]* in ")
                    if [ -n "${ZCAT}" ]; then
                        CreateTempFile
                        CHANGELOG="${TEMP_FILE}"
                        LogText "Result: found gzipped changelog in ${FILEPATH}"
                        LogText "Action: Creating temporary file to store text"
                        ${ZCAT} ${FILEPATH}/changelog.gz > ${CHANGELOG}
                    else
                        DisplayError "找不到用于读取压缩更新记录的 zcat 工具"
                    fi
                fi
                if [ -n "${CHANGELOG}" ]; then LogText "Result: found changelog file: ${CHANGELOG}"; break; fi
            done
            if [ -n "${CHANGELOG}" ]; then
                SEARCH=$(sed 's/^## //' ${CHANGELOG} | grep -E "^${PROGRAM_NAME} ${SEARCH_VERSION}")
                if [ $? -eq 0 ]; then
                    while read -r LINE; do
                        if [ ${STARTED} -eq 0 ]; then
                            SEARCH=$(echo ${LINE} | sed 's/^## //' | grep -E "^${PROGRAM_NAME} ${SEARCH_VERSION}")
                            if [ $? -eq 0 ]; then STARTED=1; ${ECHOCMD} "${BOLD}${LINE}${NORMAL}"; fi
                        else
                            # Stop if we find the next Lynis version
                            SEARCH=$(echo ${LINE} | sed 's/^## //' | grep -E "^${PROGRAM_NAME} [0-9]\.[0-9]\.[0-9]")
                            if [ $? -eq 0 ]; then
                                break
                            else
                                ${ECHOCMD} "${LINE}"
                            fi
                        fi
                    done < ${CHANGELOG}
                else
                    DisplayError "在更新记录中找不到这个版本"
                    ${ECHOCMD} ""
                    ${ECHOCMD} "${HEADER}用法：${NORMAL}"
                    ${ECHOCMD} "$0 lynis show changelog [版本]"
                    ${ECHOCMD} ""
                    ${ECHOCMD} "${HEADER}${PROGRAM_NAME} 版本：${NORMAL}"
                    SEARCH=$(sed 's/^## //' ${CHANGELOG} | grep -E "^Lynis [0-9]\.[0-9]\.[0-9] " | awk '{print $2}' | sort -n)
                    ${ECHOCMD} ${SEARCH}
                    ExitFatal
                fi
            else
                DisplayError "找不到更新记录文件（已搜索：${CHANGELOG_PATHS}）"
                ExitFatal
            fi
            ;;
        "commands")
            if [ $# -eq 1 ]; then
                ${ECHOCMD} "\n${WHITE}可用命令：${NORMAL}"
                for ITEM in ${COMMANDS}; do
                    ${ECHOCMD} "lynis ${CYAN}${ITEM}${NORMAL}"
                done
                ${ECHOCMD} ""
            else
                shift
                if [ $# -eq 1 ]; then
                    case $1 in
                        "audit") ${ECHOCMD} "${AUDIT_HELP}" ;;
                        "configure") ${ECHOCMD} "暂时没有可用的帮助说明" ;;
                        "generate") ${ECHOCMD} "${GENERATE_HELP}" ;;
                        "show") ${ECHOCMD} "${SHOW_HELP}" ;;
                        "update")  ${ECHOCMD} "${UPDATE_HELP}" ;;
                        "upload-only") ${ECHOCMD} "${UPLOAD_ONLY_HELP}" ;;
                        *) DisplayError "无法识别 commands 后面的参数"
                    esac
                else
                    shift
                    case $1 in
                        "dockerfile")
                            ${ECHOCMD} "用法：lynis audit dockerfile <文件>"
                        ;;
                        "system")
                            ${ECHOCMD} "${COMMANDS_AUDIT_SYSTEM_USAGE}\n${COMMANDS_AUDIT_SYSTEM_FUNCTION}\n"
                        ;;
                        *)
                            DisplayError "commands 无法识别参数 '$1'"
                        ;;
                    esac
                fi
            fi
            ;;
        "dbdir")
            ${ECHOCMD} "${DBDIR}"
            ;;
        "details")
            if [ -z "${LOGFILE}" ]; then DisplayError "找不到可供分析的日志文件"; fi
            if [ $# -eq 1 ]; then
                DisplayError "此命令需要一个检查编号，例如 CORE-1000。请先完成扫描（lynis audit system），再使用此命令查询。执行 'lynis show tests' 可以查看全部检查项目。"
            else
                shift
                if [ $# -eq 1 ]; then
                    TESTID="$1"
                    awk -v search="Performing test ID $TESTID" '$0 ~ search {++f;p=1}p&&f==1;/====/{p=0}' ${LOGFILE}
                fi
            fi
            ;;
        "environment")
            if [ -z "${CONTAINER_TYPE}" ]; then
                ${ECHOCMD} "container=0"
            else
                ${ECHOCMD} "container=1"
                ${ECHOCMD} "container-type=${CONTAINER_TYPE}"
            fi
            if [ ${ISVIRTUALMACHINE} -eq 1 ]; then
                ${ECHOCMD} "virtual-machine=1"
                ${ECHOCMD} "virtual-machine-type=${VMTYPE}"
            else
                ${ECHOCMD} "hardware=1"
                ${ECHOCMD} "virtual-machine=0"
            fi
            ;;
        "eol")
            ${ECHOCMD} "Operating-system=${OS_FULLNAME}"
            if [ ${EOL} -eq 0 ]; then
                ${ECHOCMD} "End-of-life=No"
            elif [ ${EOL} -eq 1 ]; then
                ${ECHOCMD} "End-of-life=Yes"
            elif [ ${EOL} -eq 255 ]; then
                ${ECHOCMD} "End-of-life=Not tested"
            else
                ${ECHOCMD} "End-of-life=Unknown"
            fi
            ;;
        "groups")
            ViewGroups
            ;;
        "help" | "--help" | "-h")
            if [ $# -eq 1 ]; then
                ${ECHOCMD} "${PROGRAM_NAME} ${PROGRAM_VERSION} - 帮助"
                ${ECHOCMD} "=========================="
                ${ECHOCMD} ""
                ${ECHOCMD} "${WHITE}命令${NORMAL}："
                for ITEM in ${COMMANDS}; do
                    ${ECHOCMD} "${CYAN}${ITEM}${NORMAL}"
                done
                ${ECHOCMD} ""
                ${ECHOCMD} "执行 'lynis show help ${CYAN}<命令>${NORMAL}' 查看详细说明"
                ${ECHOCMD} ""; ${ECHOCMD} ""
                ${ECHOCMD} "${WHITE}选项${NORMAL}：\n${GRAY}${OPTIONS}${NORMAL}"
            else
                shift
                case $1 in
                   "audit") ${ECHOCMD} "${AUDIT_HELP}" ;;
                   "configure") ${ECHOCMD} "暂时没有可用的帮助说明" ;;
                   "generate") ${ECHOCMD} "${GENERATE_HELP}" ;;
                   "show") ${ECHOCMD} "${SHOW_HELP}" ;;
                   "update") ${ECHOCMD} "${UPDATE_HELP}" ;;
                   "upload-only") ${ECHOCMD} "${UPLOAD_ONLY_HELP}" ;;
                   "?") ${ECHOCMD} "${SHOW_ARGS}" ;;
                   *) ${ECHOCMD} "lynis show help 无法识别所提供的参数" ;;
                esac
            fi
            ;;
        "helpers")              for ITEM in ${HELPERS}; do ${ECHOCMD} ${ITEM}; done ;;
        "hostids" | "hostid")
            ${ECHOCMD} "hostid=${HOSTID}"
            ${ECHOCMD} "hostid2=${HOSTID2}"
            ${ECHOCMD} "machineid=${MACHINEID}"
            ;;
        "includedir")
            ${ECHOCMD} "${INCLUDEDIR}"
            ;;
        "language")             ${ECHOCMD} "简体中文" ;;
        "license")              ${ECHOCMD} "${PROGRAM_LICENSE}" ;;
        "logfile")              ${ECHOCMD} "${LOGFILE}" ;;
        "man")                  ${ECHOCMD} "请执行 ./lynis --man 或 man lynis 查看手册" ;;
        "options")              ${ECHOCMD} "${OPTIONS}" ;;
        "os")
                                ${ECHOCMD} "OS=${OS}"
                                ${ECHOCMD} "OS_NAME=${OS_NAME}"
                                ${ECHOCMD} "OS_FULLNAME=${OS_FULLNAME}"
                                ${ECHOCMD} "OS_VERSION=${OS_VERSION}"
        ;;
        "pidfile")              ${ECHOCMD} "${PIDFILE}" ;;
        "profile" | "profiles") for ITEM in ${PROFILES}; do ${ECHOCMD} ${ITEM}; done ;;
        "profiledir")           ${ECHOCMD} "${PROFILEDIR}" ;;
        "plugindir")            ${ECHOCMD} "${PLUGINDIR}" ;;
        "release")              ${ECHOCMD} "${PROGRAM_VERSION}-${PROGRAM_RELEASE_TYPE}" ;;
        "releasedate")          ${ECHOCMD} "${PROGRAM_RELEASE_DATE}" ;;
        "report")               ${ECHOCMD} "${REPORTFILE}" ;;
        "settings")
            BRIEF_OUTPUT=0
            COLORED_OUTPUT=1
            CONFIGURED_ONLY_OUTPUT=0
            while [ $# -gt 1 ]; do
                shift
                case $1 in
                   "--brief" | "--br") BRIEF_OUTPUT=1 ;;
                   "--configured-only" | "--co") CONFIGURED_ONLY_OUTPUT=1 ;;
                   "--nocolors" | "--no-colors" | "--nc") COLORED_OUTPUT=0; COLORS=0 ;;
                   *)
                       ${ECHOCMD} "${RED}错误${NORMAL}：'lynis show settings' 收到了无效参数\n\n"
                       ${ECHOCMD} "可用方式："
                       for ITEM in ${SHOW_SETTINGS_ARGS}; do ${ECHOCMD} "lynis show settings ${ITEM}"; done
                       ExitFatal
                   ;;
                esac
            done
            if [ ${COLORED_OUTPUT} -eq 0 ]; then RemoveColors; fi
            # Sort all settings and display them
            SETTINGS=$(sort ${SETTINGS_FILE} | sed 's/ /:space:/g')
            for LINE in ${SETTINGS}; do
                SETTING=$(echo ${LINE} | awk -F';' '{print $1}')
                VALUE=$(echo ${LINE} | awk -F';' '{print $2}')
                DESCRIPTION=$(echo ${LINE} | awk -F';' '{print $3}' | sed 's/:space:/ /g')
                if [ -z "${VALUE}" -a ${CONFIGURED_ONLY_OUTPUT} -eq 0 ]; then VALUE="${GRAY}[未配置]${NORMAL}"; fi
                if [ -n "${VALUE}" ]; then
                    if [ ${BRIEF_OUTPUT} -eq 0 ]; then ${ECHOCMD} "${GRAY}# ${DESCRIPTION}${NORMAL}"; fi
                    ${ECHOCMD} "${WHITE}${SETTING}${NORMAL}=${CYAN}${VALUE}${NORMAL}"
                    if [ ${BRIEF_OUTPUT} -eq 0 ]; then ${ECHOCMD} ""; fi
                fi
            done
            if [ ${BRIEF_OUTPUT} -eq 0 -a ${CONFIGURED_ONLY_OUTPUT} -eq 0 -a ${COLORED_OUTPUT} -eq 1 ]; then
                if [ ${COLORS} -eq 1 ]; then
                    ${ECHOCMD} "# 可添加 --brief 隐藏说明，添加 --configured-only 只显示已配置项目，或添加 --nocolors 关闭颜色"
                else
                    ${ECHOCMD} "# 可添加 --brief 隐藏说明，或添加 --configured-only 只显示已配置项目"
                fi
            fi

            ;;
        "tests")
            if [ $# -gt 1 ]; then
                shift
                case $1 in
                    "skipped")
                        if [ -z "${SKIP_TESTS}" ]; then
                            ${ECHOCMD} "# ${CYAN}配置文件没有要求跳过任何检查${NORMAL}"
                        else
                            ${ECHOCMD} "# 配置文件要求跳过的检查"
                            ${ECHOCMD} "${SKIP_TESTS}"
                        fi
                    ;;
                    *)
                        if [ -f ${DBDIR}/tests.db ]; then
                            SEARCH="$1"
                            FIND=$(grep "^${SEARCH}" ${DBDIR}/tests.db | sed "s/ /:space:/g")
                            if [ -z "${FIND}" ]; then
                                ${ECHOCMD} "${WARNING}错误${NORMAL}：${BOLD}在检查数据库中找不到这个项目${NORMAL}\n\n"
                                ExitFatal
                            else
                                for ITEM in ${FIND}; do
                                    TEST_DESCRIPTION=$(echo ${ITEM} | sed "s/:space:/ /g" | awk -F: '{print $6}')
                                    TEST=$(echo ${ITEM} | awk -F: '{print $1}')
                                    TEST_TYPE=$(echo ${ITEM} | awk -F: '{print $2}')
                                    TEST_CATEGORY=$(echo ${ITEM} | awk -F: '{print $3}')
                                    TEST_GROUP=$(echo ${ITEM} | awk -F: '{print $4}')
                                    TEST_OS=$(echo ${ITEM} | awk -F: '{print $5}')
                                    TEST_SKIPPED=0
                                    ${ECHOCMD} "${CYAN}${TEST}${NORMAL}"
                                    ${ECHOCMD} "==================================="
                                    ${ECHOCMD} ""
                                    ${ECHOCMD} "${WHITE}类型：${NORMAL} ${TEST_TYPE}"
                                    ${ECHOCMD} ""
                                    ${ECHOCMD} "${WHITE}说明：${NORMAL}"
                                    ${ECHOCMD} "${TEST_DESCRIPTION}"
                                    ${ECHOCMD} ""
                                    ${ECHOCMD} "${WHITE}分类：${NORMAL} ${TEST_CATEGORY}，${WHITE}分组：${NORMAL} ${TEST_GROUP}"
                                    ${ECHOCMD} ""
                                    ${ECHOCMD} "${WHITE}是否执行：${NORMAL}"
                                    if [ "${TEST_OS}" = "" ]; then
                                        ${ECHOCMD} "  操作系统：          ${GREEN}是${NORMAL}（适用于所有系统）"
                                    elif [ "${TEST_OS}" = "${OS}" ]; then
                                        ${ECHOCMD} "  操作系统：          ${GREEN}是${NORMAL}（仅限 ${TEST_OS}）"
                                    else
                                        ${ECHOCMD} "  操作系统：          ${RED}否${NORMAL}（仅限 ${TEST_OS}）"
                                        TEST_SKIPPED=1
                                    fi
                                    if [ -z "${SKIP_TESTS}" ]; then
                                        ${ECHOCMD} "  配置文件：          ${GREEN}是${NORMAL}（未设置跳过项目）"
                                    else
                                        FIND=$(echo ${SKIP_TESTS} | grep -E "${TEST}")
                                        if [ -z "${FIND}" ]; then
                                            ${ECHOCMD} "  配置文件：          ${GREEN}是${NORMAL}（未标记为跳过）"
                                        else
                                            ${ECHOCMD} "  配置文件：          ${RED}否${NORMAL}（已标记为跳过）"
                                            TEST_SKIPPED=1
                                        fi
                                    fi
                                    if [ ${TEST_SKIPPED} -eq 1 ]; then ${ECHOCMD} ""; ${ECHOCMD} "  此检查不会在当前系统上执行"; fi

                                    ${ECHOCMD} ""
                                    ${ECHOCMD} ""

                                done
                            fi
                        else
                            ShowError "找不到检查数据库"
                            ${ECHOCMD} "系统中可能没有安装检查数据库。详细信息请查看 ${PROGRAM_SOURCE}。"
                            ExitFatal
                        fi
                    ;;
                esac
            else
                if [ -f ${DBDIR}/tests.db ]; then
                    ${ECHOCMD} "# 检查编号   系统       说明"
                    ${ECHOCMD} "# ======================================================================================"
                    awk -F: '{ if ($1 !~ /^#/) printf("%-10s %-10s %s (%s)\n",$1,$5,$6,$3)}' ${DBDIR}/tests.db
                else
                    ShowError "找不到检查数据库"
                    ${ECHOCMD} "系统中可能没有安装检查数据库。详细信息请查看 ${PROGRAM_SOURCE}。"
                    ExitFatal
                fi
            fi
            ;;
        "version")              ${ECHOCMD} "${PROGRAM_VERSION}" ;;
        "workdir")              ${ECHOCMD} "${WORKDIR}" ;;
        "?")                    ${ECHOCMD} "${SHOW_ARGS}" ;;
        *)                      ${ECHOCMD} "lynis show 无法识别参数 '${RED}$1${NORMAL}'" ;;
    esac
else
    ${ECHOCMD} "\n  ${WHITE}请再提供一个参数${NORMAL}\n\n"
    for ITEM in ${SHOW_ARGS}; do
        ${ECHOCMD} "    lynis show ${BROWN}${ITEM}${NORMAL}"
    done
    ${ECHOCMD} "\n"
    ${ECHOCMD} ""
    ${ECHOCMD} "需要查看 show 命令的详细帮助时，请执行：$0 show commands show"
fi


ExitClean

# More additions:
# - categories
# - workdir

# EOF
