#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
######################################################################
#
# Helper program to configure Lynis
#
######################################################################
#
# How to use:
# ------------
#
# Run:
#   lynis configure settings quick
#   lynis configure settings quick=yes:debug=yes
#
######################################################################

    CONFIGURE_CRONJOB=0
    CONFIGURE_SETTINGS=0

    # Check configure mode
    if [ "${HELPER_PARAMS}" = "" ]; then
        ${ECHOCMD} "${YELLOW}请提供一个或多个配置项${NORMAL}"
        ${ECHOCMD} ""
        ${ECHOCMD} "示例："
        ${ECHOCMD} "  $0 configure cronjob"
        ${ECHOCMD} ""
        ${ECHOCMD} "  $0 configure settings quick"
        ${ECHOCMD} "  $0 configure settings debug:developer-mode:quick"
        ${ECHOCMD} "  $0 configure settings debug=yes:developer-mode=no:quick=yes"
        ${ECHOCMD} ""
        ExitClean
    elif [ "$1" = "cronjob" ]; then
        CONFIGURE_CRONJOB=1
    elif [ "$1" = "settings" ]; then
        CONFIGURE_SETTINGS=1
    fi


    # Perform activities depending on requested task
    if [ ${CONFIGURE_CRONJOB} -eq 1 ]; then

        ${ECHOCMD} "暂未实现定时任务的自动配置。"
        ExitClean

    elif [ ${CONFIGURE_SETTINGS} -eq 1 ]; then

        # Determine where profiles are stored
        if [ -z "${PROFILEDIR}" ]; then
            ${ECHOCMD} "无法配置 Lynis：未能确定配置文件目录"
            ExitFatal
        fi
        if [ -z "${CUSTOM_PROFILE}" ]; then
            ${ECHOCMD} "尚未找到自定义配置文件。"
            ${ECHOCMD} "建议：执行 'touch custom.prf' 或 'touch /etc/lynis/custom.prf' 创建配置文件"
            ExitFatal
        fi

        CONFIGURE_SETTINGS=$(echo $2 | sed 's/:/ /g')
        for I in ${CONFIGURE_SETTINGS}; do
            SETTING=$(echo ${I} | awk -F= '{print $1}')
            VALUE=$(echo ${I} | awk -F= '{print $2}')
            if [ "${VALUE}" = "" ]; then
                ${ECHOCMD} "配置文件：      ${CUSTOM_PROFILE}"
                Debug "命令行中没有为配置项 ${SETTING} 提供值"
                #read VALUE
                else
                  Debug "配置项 '${SETTING}' 将设置为 '${VALUE}'"
                  FIND=$(grep "^${SETTING}" ${CUSTOM_PROFILE})
                  if [ "${FIND}" = "" ]; then
                      ${ECHOCMD} "正在配置 '${CYAN}${SETTING}${NORMAL}'"
                      echo "${SETTING}=${VALUE}" >> ${CUSTOM_PROFILE}
                      if [ $? -eq 0 ]; then ${ECHOCMD} "${GREEN}配置已修改${NORMAL}"; fi
                    else
                      ${ECHOCMD} "${YELLOW}提示${NORMAL}：配置项 '${CYAN}${SETTING}${NORMAL}' 已存在，因此未作修改${NORMAL}"
                      ${ECHOCMD} "        当前值：${WHITE}${FIND}${NORMAL}"
                      ${ECHOCMD} ""
                  fi
            fi
            # Now check if value is in line with expected type (boolean, integer, string)
            # =To be implemented=
        done
        ${ECHOCMD} ""
        ${ECHOCMD} ""
        ExitClean

    fi

    ExitClean

# EOF
