#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
######################################################################
#
# Helper program to perform a remote scan
#
######################################################################
#
# Options:
# ---------
# 1) lynis update info     - Show version information (external)
# 2) lynis update release  - Check and install new release (internal)
#
# How to use:
# ------------
# Run option 1 to know about current and latest release information.
# Run option 2 to query internal server for possible upgrade of Lynis.
#
# Steps for updating to new release:
# 1) Run Lynis with: lynis update release
# 2) Lynis will use this helper and check the profile
# 3) The configured web server will be queried (lynis-latest-version)
# 4) The contents of this file will be compared with a local file
# 5) If there is a difference, download package
# 6) Check paths and extract files
# 7) Quit program
#
# Suggested documentation if you want to use this functionality:
# https://cisofy.com/documentation/lynis/upgrading/
#
######################################################################

    # Enable screen output again
    QUIET=0

    SCP_BINARY=$(which scp 2> /dev/null | grep -v "no [^ ]* in ")
    SSH_BINARY=$(which ssh 2> /dev/null | grep -v "no [^ ]* in ")
    if [ "${SCP_BINARY}" = "" ]; then echo "找不到 scp 命令"; ExitFatal; fi
    if [ "${SSH_BINARY}" = "" ]; then echo "找不到 ssh 命令"; ExitFatal; fi

    LYNIS_TARBALL="lynis-remote.tar.gz"
    echo ""
    echo  " ${BLUE}* ${WHITE}第 1 步${NORMAL}：${CYAN}创建压缩包${NORMAL}"
    printf "%s\n\n" " mkdir -p ./files && cd .. && tar czf ./lynis/files/${LYNIS_TARBALL} --exclude=files/${LYNIS_TARBALL} ./lynis && cd lynis"

    echo " ${BLUE}* ${WHITE}第 2 步${NORMAL}：${CYAN}将压缩包复制到目标 ${REMOTE_TARGET}${NORMAL}"
    LYNIS_TARBALL="./files/lynis-remote.tar.gz"
    printf "%s\n\n" " scp -q ${LYNIS_TARBALL} ${REMOTE_TARGET}:~/tmp-lynis-remote.tgz"
    #if [ $? -gt 0 ]; then echo "Could not copy tarball to target"; ExitFatal; fi

    echo " ${BLUE}* ${WHITE}第 3 步${NORMAL}：${CYAN}执行审计命令${NORMAL}"

    printf "%s\n\n" " ssh ${REMOTE_TARGET} \\"mkdir -p ~/tmp-lynis && cd ~/tmp-lynis && tar xzf ../tmp-lynis-remote.tgz && rm ../tmp-lynis-remote.tgz && cd lynis && ${REMOTE_COMMAND}\\""
    #if [ $? -gt 1 ]; then echo "Could not perform remote audit"; ExitFatal; fi

    echo " ${BLUE}* ${WHITE}第 4 步${NORMAL}：${CYAN}清理远程工作目录${NORMAL}"
    printf "%s\n\n" " ssh ${REMOTE_TARGET} \\"rm -rf ~/tmp-lynis\\""

    echo " ${BLUE}* ${WHITE}第 5 步${NORMAL}：${CYAN}取回日志和报告${NORMAL}"
    printf "%s\n" " scp -q ${REMOTE_TARGET}:/tmp/lynis.log ./files/${REMOTE_TARGET}-lynis.log"
    printf "%s\n\n" " scp -q ${REMOTE_TARGET}:/tmp/lynis-report.dat ./files/${REMOTE_TARGET}-lynis-report.dat"

    echo " ${BLUE}* ${WHITE}第 6 步${NORMAL}：${CYAN}清理临时文件（使用普通用户时）${NORMAL}"
    printf "%s\n\n" " ssh ${REMOTE_TARGET} \\"rm /tmp/lynis.log /tmp/lynis-report.dat\\""

    # No more Lynis output
    QUIET=1

# EOF