#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Read profile/template
#
#################################################################################
#
    # Set default values (should be equal to default.prf)
    SETTING_LOG_TESTS_INCORRECT_OS=1
    SETTING_SHOW_REPORT_SOLUTION=0
    DEPRECATED_OPTION=""
#
#################################################################################
#
    for PROFILE in ${PROFILES}; do

        LogText "读取配置文件/配置 ${PROFILE}"

        # Show deprecation message for old config entries such as 'config:' and 'apache:'
        FOUND=0
        DATA=$(grep -E "^[a-z-]{1,}:" ${PROFILE})
        if ! IsEmpty "${DATA}"; then FOUND=1; fi

        if [ ${FOUND} -eq 1 ]; then
            Display --text " "
            Display --text "=================================================================================================="
            DisplayWarning "您的配置文件包含旧式配置条目。有关更多详细信息以及如何转换这些条目，请参阅日志文件"
            Display --indent 2 --text "* ${RED}问题${NORMAL}"
            Display --indent 2 --text "配置文件中有一行或多行采用旧格式（key:value），需要转换为新格式（key=value）或将其禁用。"
            Display --text " "
            Display --indent 2 --text "* ${GREEN}解决方法${NORMAL}"
            Display --indent 2 --text "使用grep查看相关匹配项（grep -E \\"^[a-z-]{1,}:\\" custom.prf）"
            Display --text " "
            Display --text "=================================================================================================="
            Display --text " "
            LogText "提示：配置文件 '${PROFILE}' 包含一个或多个旧格式配置项"
            ReportWarning "GEN-0020" "您的配置文件包含一个或多个旧式配置条目"
            sleep 10
        fi

        # Security check for unexpected and possibly harmful escape characters (hyphen should be listed as first or last character)
        DATA=$(grep -Ev '^$|^ |^#|^config:' "${PROFILE}" | tr -d '[a-zA-Z0-9]/\[\]\(\)_\|,\.:;= \n\r-')
        if ! IsEmpty "${DATA}"; then
            DisplayWarning "配置文件 '${PROFILE}' 包含异常字符，详情请查看日志文件。"
            LogText "在配置文件 '${PROFILE}' 中发现异常或可能有害的字符。请查看下方匹配结果并与配置文件对照。"
            for I in $(printf ${DATA} | od -An -ta); do
                LogText "输出：${I}"
            done
            LogText "建议：使用 '#' 注释不正确的行后重试。如果合法字符被阻止，请提交 GitHub issue"
            ExitFatal "配置文件中包含异常字符，出于安全考虑停止执行"
        fi

        # Now parse the profile and filter out unwanted characters
        DATA=$(grep -E "^config:|^[a-z-].*=" ${PROFILE} | tr -dc '[a-zA-Z0-9]/\[\]\(\)_\|,\.:;= \n\r-' | sed 's/ /!space!/g')
        for CONFIGOPTION in ${DATA}; do
            if ContainsString "^config:" "${CONFIGOPTION}"; then
                # Old style configuration
                OPTION=$(echo ${CONFIGOPTION} | cut -d ':' -f2)
                VALUE=$(echo ${CONFIGOPTION} | cut -d ':' -f3 | sed 's/!space!/ /g')
                DEPRECATED_OPTION="${OPTION}"
            else
                OPTION=$(echo ${CONFIGOPTION} | cut -d '=' -f1)
                VALUE=$(echo ${CONFIGOPTION} | cut -d '=' -f2 | sed 's/!space!/ /g')
            fi
            Debug "Profile option set: ${OPTION} (with value ${VALUE})"

            case ${OPTION} in

                # Is Lynis Enterprise allowed to purge this system when it is becomes outdated?
                allow-auto-purge)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)$")
                    if [ -n "${FIND}" ]; then
                        Report "allow-auto-purge=1"
                    else
                        Report "allow-auto-purge=0"
                    fi
                ;;

                # Define which compliance standards are enabled
                # For this to work, the Enterprise plugins are needed
                compliance_standards | compliance-standards | check-compliance)  # deprecated: compliance_standards
                    COMPLIANCE_STANDARDS_ENABLED=$(echo ${VALUE} | tr ',' ' ')
                    for STANDARD in ${COMPLIANCE_STANDARDS_ENABLED}; do
                        case ${STANDARD} in
                            cis)      COMPLIANCE_ENABLE_CIS=1      ; Debug "Compliance scanning for CIS Benchmarks is enabled" ;;
                            hipaa)    COMPLIANCE_ENABLE_HIPAA=1    ; Debug "Compliance scanning for HIPAA is enabled" ;;
                            iso27001) COMPLIANCE_ENABLE_ISO27001=1 ; Debug "Compliance scanning for ISO27001 is enabled" ;;
                            pci-dss)  COMPLIANCE_ENABLE_PCI_DSS=1  ; Debug "Compliance scanning for PCI DSS is enabled" ;;
                            *) LogText "结果：配置了未知的合规性标准" ;;
                        esac
                    done
                ;;

                # Check for a specific value
                check-value)
                    STRING=$(echo ${VALUE} | tr -d "[" | tr -d "]" | sed "s/, /,/g")
                    CHECK_VALUE_ARRAY="${CHECK_OPTION_ARRAY} ${STRING}"
                ;;

                # Colored output
                colors)
                    # Quick mode (SKIP_PLUGINS) might already be set outside profile, so store in different variable
                    SETTING_COLORS=1 # default is yes
                    FIND=$(echo "${VALUE}" | grep -E "^(0|false|no)$") && COLORS=0
                    if [ -n "${FIND}" ]; then SETTING_COLORS=0; RemoveColors; fi
                    Debug "Colors set to ${SETTING_COLORS}"
                    AddSetting "colors" "${SETTING_COLORS}" "彩色屏幕输出"
                    unset SETTING_COLORS
                ;;

                # Ignore configuration data
                config-data | permdir | permfile)
                    Debug "Ignoring configuration option, as it will be used by a specific test"
                ;;

                # Maximum number of WAITing connections
                connections-max-wait-state | connections_max_wait_state)
                    OPTIONS_CONN_MAX_WAIT_STATE="${VALUE}"
                    AddSetting "connections-max-wait-state" "${OPTIONS_CONN_MAX_WAIT_STATE}" "连接数（最大等待状态）"
                ;;

                # Append something to URL for control information
                control-url-append | control_url_append)
                    CONTROL_URL_APPEND="${VALUE}"
                    AddSetting "control-url-append" "${CONTROL_URL_APPEND}" "控制 URL（追加内容）"
                ;;

                # Prepend an URL before control information link
                control-url-prepend | control_url_prepend)
                    CONTROL_URL_PREPEND="${VALUE}"
                    AddSetting "control-url-prepend" "${CONTROL_URL_PREPEND}" "控制 URL（前置内容）"
                ;;

                # Protocol to use for control information link
                control-url-protocol | control_url_protocol)
                    CONTROL_URL_PROTOCOL="${VALUE}"
                    AddSetting "control-url-protocol" "${CONTROL_URL_PREPEND}" "控制 URL（协议）"
                ;;

                # Append something to URL for control information (only applies to CUST-*)
                custom-url-append | custom_url_append)
                    CUSTOM_URL_APPEND="${VALUE}"
                    AddSetting "custom-url-append" "${CUSTOM_URL_APPEND}" "自定义 URL（追加内容）"
                ;;

                # Prepend an URL before control information link (only applies to CUST-*)
                custom-url-prepend | custom_url_prepend)
                    CUSTOM_URL_PREPEND="${VALUE}"
                    AddSetting "custom-url-prepend" "${CUSTOM_URL_PREPEND}" "自定义 URL（前置内容）"
                ;;

                # Protocol to use for control information link
                custom-url-protocol | custom_url_protocol)
                    CUSTOM_URL_PROTOCOL="${VALUE}"
                    AddSetting "custom-url-protocol" "${CUSTOM_URL_PREPEND}" "自定义 URL（协议）"
                ;;

                # Do not check security repository in sources.list (Debian/Ubuntu)
                debian-skip-security-repository | debian_skip_security_repository)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && OPTION_DEBIAN_SKIP_SECURITY_REPOSITORY=1 
                    AddSetting "debian-skip-security-repository" "OPTION_DEBIAN_SKIP_SECURITY_REPOSITORY" "跳过安全软件仓库检查（Debian 等系统）"
                ;;

                # Debug status to show more details while running program
                debug)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && DEBUG=1
                    Debug "Debug mode set to '${DEBUG}'"
                    AddSetting "debug" "${DEBUG}" "调试模式"
                ;;

                # Development mode (--developer)
                developer-mode)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && DEVELOPER_MODE=1
                    Debug "Developer mode set to ${DEVELOPER_MODE}"
                    AddSetting "developer" "${DEVELOPER_MODE}" "开发者模式"
                ;;

                # Show non-zero exit code when errors are found
                error-on-warnings)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && ERROR_ON_WARNINGS=1
                    Debug "Exit with different code on warnings is set to ${ERROR_ON_WARNINGS}"
                    AddSetting "error-on-warnings" "${ERROR_ON_WARNINGS}" "发现一个或多个警告时使用非零退出码"
                ;;

                # Skip FreeBSD port audit
                freebsd-skip-portaudit | freebsd_skip_portaudit)
                    LogText "选项集：跳过 FreeBSD portaudit"
                    OPTION_FREEBSD_SKIP_PORTAUDIT="${VALUE}"
                ;;

                # Lynis Enterprise: group name - deprecated option
                group)
                    GROUP_NAME="${VALUE}"
                    AddSetting "group" "${GROUP_NAME}" "组"
                    DEPRECATED_OPTION="group"
                ;;

                hostalias | host-alias)
                    if [ -n "${VALUE}" ]; then Report "hostname_alias=${VALUE}"; fi
                ;;

                hostid)
                    HOSTID="${VALUE}"
                ;;

                hostid2)
                    HOSTID2="${VALUE}"
                ;;

                # Home directories to ignore during scans
                ignore-home-dir)
                    Report "ignore-home-dir[]=${VALUE}"
                ;;

                # Language
                language | lang)
                    LogText "通过配置文件将语言设置为 '${VALUE}'"
                    if [ -n "${VALUE}" ]; then LANGUAGE="${VALUE}"; fi
                    AddSetting "language" "${LANGUAGE}" "语言"
                ;;

                # Lynis Enterprise license key
                license-key | license_key)
                    if [ -n "${VALUE}" ]; then
                        LICENSE_KEY="${VALUE}"
                        Report "license_key=${VALUE}"
                    fi
                    AddSetting "license-key" "${VALUE}" "许可证密钥"
                ;;

                # Do (not) log tests if they have an different operating system
                log-tests-incorrect-os | log_tests_incorrect_os)
                    FIND=$(echo "${VALUE}" | grep -E "^(0|false|no)") && SETTING_LOG_TESTS_INCORRECT_OS=0
                    Debug "Logging of tests with incorrect operating system set to ${SETTING_LOG_TESTS_INCORRECT_OS}"
                    LOG_INCORRECT_OS=${SETTING_LOG_TESTS_INCORRECT_OS}
                ;;

                # What type of machine we are scanning (eg. personal, workstation or server)
                machine-role | machine_role)
                    MACHINE_ROLE="${VALUE}"
                    AddSetting "machine-role" "${MACHINE_ROLE}" "机器角色（个人设备、工作站或服务器）"
                ;;

                # Define if any found NTP daemon instance is configured as a server or client
                ntpd-role | ntpd_role)
                    NTPD_ROLE="${VALUE}"
                    AddSetting "ntpd-role" "${NTPD_ROLE}" "NTP 角色（服务器或客户端）"
                ;;

                # How much seconds to wait between tests
                pause_between_tests | pause-between-tests)
                    TEST_PAUSE_TIME="${VALUE}"
                    AddSetting "pause-between-tests" "${TEST_PAUSE_TIME}" "检查之间的暂停时间（秒）"
                ;;

                # Plugin
                plugin)
                    LogText "根据配置文件（${PROFILE}）启用插件 '${VALUE}'"
                ;;

                disable-plugin)
                    LogText "根据配置文件（${PROFILE}）禁用插件 '${VALUE}'"
                    DISABLED_PLUGINS="${DISABLED_PLUGINS} ${VALUE}"
                ;;

                # Plugin directory
                plugindir | plugin-dir)
                    if IsEmpty "${PLUGINDIR}"; then
                        PLUGINDIR="${VALUE}"
                    else
                        LogText "插件目录此前已设置为 ${PLUGINDIR}（很可能通过程序参数设置），不进行覆盖"
                    fi
                    AddSetting "plugin-dir" "${PLUGINDIR}" "插件目录"
                ;;

                # Profile name
                profile-name | profile_name)
                    PROFILE_NAME="${VALUE}"
                ;;

                # Quick (no waiting for keypresses)
                quick)
                    # Quick mode might already be set outside profile, so store in different variable
                    SETTING_QUICK_MODE=1 # default is yes
                    FIND=$(echo "${VALUE}" | grep -E "^(0|false|no)$") && QUICKMODE=0
                    if [ -n "${FIND}" ]; then SETTING_QUICK_MODE=1; fi
                    Debug "Quickmode set to ${SETTING_QUICK_MODE}"
                    AddSetting "quick" "${SETTING_QUICK_MODE}" "快速模式（非交互）"
                ;;

                # Refresh software repositories
                refresh-repositories)
                    SETTING_REFRESH_REPOSITORIES=1 # default is yes
                    FIND=$(echo "${VALUE}" | grep -E "^(0|false|no)$") && REFRESH_REPOSITORIES=0
                    if [ -n "${FIND}" ]; then SETTING_REFRESH_REPOSITORIES=0; fi
                    Debug "Refreshing repositories set to ${SETTING_REFRESH_REPOSITORIES}"
                    AddSetting "refresh-repositories" "${SETTING_REFRESH_REPOSITORIES}" "刷新软件仓库（用于检测存在漏洞的软件包）"
                ;;

                # Show more details in report
                show-report-solution)
                    SETTING_SHOW_REPORT_SOLUTION=${SHOW_REPORT_SOLUTION}
                    FIND=$(echo "${VALUE}" | grep -E "^(0|false|no)$") && SHOW_REPORT_SOLUTION=0
                    if [ -n "${FIND}" ]; then SETTING_SHOW_REPORT_SOLUTION=0; fi
                    Debug "Show report details (solution) set to ${SETTING_SHOW_REPORT_SOLUTION}"
                ;;

                # Inline tips about tool (default enabled)
                show_tool_tips | show-tool-tips)
                    SETTING_SHOW_TOOL_TIPS=1 # default is yes
                    FIND=$(echo "${VALUE}" | grep -E "^(0|false|no)$") && SHOW_TOOL_TIPS=0
                    if [ -n "${FIND}" ]; then SETTING_SHOW_TOOL_TIPS=0; fi
                    Debug "Show tool tips set to ${SETTING_SHOW_TOOL_TIPS}"
                    AddSetting "show-tool-tips" "${SETTING_SHOW_TOOL_TIPS}" "显示工具提示"
                ;;

                # Show warnings only
                show-warnings-only)
                    QUIET=1
                    QUICKMODE=1
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)$") && SHOW_WARNINGS_ONLY=1
                    Debug "Show warnings only set to ${SHOW_WARNINGS_ONLY}"
                    AddSetting "show-warnings-only" "${SHOW_WARNINGS_ONLY}" "仅显示警告"
                ;;

                # Skip plugins
                skip-plugins)
                    # Skip plugins (SKIP_PLUGINS) might already be set, so store in different variable
                    SETTING_SKIP_PLUGINS=0 # default is no
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)$") && SKIP_PLUGINS=1
                    if [ -n "${FIND}" ]; then SETTING_SKIP_PLUGINS=1; fi
                    Debug "Skip plugins is set to ${SETTING_SKIP_PLUGINS}"
                    AddSetting "skip-plugins" "${SETTING_SKIP_PLUGINS}" "跳过插件"
                ;;

                # Which tests to skip (skip-test=ABCD-1234 or skip-test=ABCD-1234:subtest)
                skip-test)
                    STRING=$(echo ${VALUE} | awk '{print toupper($0)}')
                    SKIP_TESTS="${SKIP_TESTS} ${STRING}"
                ;;

                # Do not check the latest version on the internet
                skip_upgrade_test | skip-upgrade-test)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && SKIP_UPGRADE_TEST=1
                    Debug "Skip upgrade test set to ${SKIP_UPGRADE_TEST}"
                ;;

                # SSL paths
                ssl-certificate-paths)
                    SSL_CERTIFICATE_PATHS="${VALUE}"
                    Debug "SSL paths set to ${SSL_CERTIFICATE_PATHS}"
                    AddSetting "ssl-certificate-paths" "${SSL_CERTIFICATE_PATHS}" "SSL 证书路径"
                ;;

                ssl-certificate-paths-to-ignore)
                    # Retrieve paths to ignore when searching for certificates. Strip special characters, replace possible spaces
                    SSL_CERTIFICATE_PATHS_TO_IGNORE=$(echo ${VALUE} | tr -d '[\001-\037]' | sed 's/ /__space__/g' | tr ':' ' ')
                    Debug "SSL paths to ignore: ${SSL_CERTIFICATE_PATHS_TO_IGNORE}"
                    AddSetting "ssl-certificate-paths-to-ignore" "${SSL_CERTIFICATE_PATHS_TO_IGNORE}" "搜索 SSL 证书时要忽略的路径"
                ;;

                # Check also certificates provided by packages?
                ssl-certificate-include-packages)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && SSL_CERTIFICATE_INCLUDE_PACKAGES=1
                    Debug "Check also certificates provided by packages set to ${SSL_CERTIFICATE_INCLUDE_PACKAGES}"
                ;;


                # Set strict mode for development and quality purposes
                strict)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && SET_STRICT=1
                ;;

                # The name of the customer/client that uses this system
                system-customer-name)
                    if [ -n "${VALUE}" ]; then Report "system-customer-name=${VALUE}"; fi
                ;;

                # The groups linked to a system (system-groups=customers,webservers,production)
                system-groups)
                    if [ -n "${VALUE}" ]; then Report "system-groups=${VALUE}"; fi
                ;;

                # Tags (tags=db,production,ssn-1304)
                tags)
                    if [ -n "${VALUE}" ]; then Report "tags=${VALUE}"; fi
                ;;

                # Define what kind of scan we are performing
                test_scan_mode | test-scan-mode)
                    if [ "${VALUE}" = "light" ]; then   SCAN_TEST_LIGHT="YES"; SCAN_TEST_MEDIUM="NO";  SCAN_TEST_HEAVY="NO";  fi
                    if [ "${VALUE}" = "normal" ]; then  SCAN_TEST_LIGHT="YES"; SCAN_TEST_MEDIUM="YES"; SCAN_TEST_HEAVY="NO";  fi
                    if [ "${VALUE}" = "full" ]; then    SCAN_TEST_LIGHT="YES"; SCAN_TEST_MEDIUM="YES"; SCAN_TEST_HEAVY="YES"; fi
                    AddSetting "test-scan-mode" "${VALUE}" "扫描模式"
                ;;

                # Perform upload
                upload)
                    SETTING_UPLOAD=no # default
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)$") && UPLOAD_DATA=1
                    if [ -n "${FIND}" ]; then SETTING_UPLOAD=1; fi
                    Debug "Upload set to ${SETTING_UPLOAD}"
                    AddSetting "upload" "${SETTING_UPLOAD}" "扫描后上传数据"
                    unset SETTING_UPLOAD
                ;;


                # Compression of uploads (enabled by default)
                upload_compressed | compressed-uploads)
                    if [ "${VALUE}" = "0" ]; then COMPRESSED_UPLOADS=0; fi
                    AddSetting "compressed-uploads" "${COMPRESSED_UPLOADS}" "压缩上传数据"
                ;;

                # Options during upload of data
                upload_options | upload-options)
                    UPLOAD_OPTIONS="${VALUE}"
                    AddSetting "upload-options" "${UPLOAD_OPTIONS}" "上传选项"
                ;;

                # Proxy settings
                upload_proxy_port | proxy-port | upload-proxy-port)
                    UPLOAD_PROXY_PORT="${VALUE}"
                    AddSetting "upload-proxy-port" "${UPLOAD_PROXY_PORT}" "代理端口"
                ;;
                upload_proxy_protocol | proxy-protocol)
                    UPLOAD_PROXY_PROTOCOL="${VALUE}"
                    AddSetting "upload-proxy-protocol" "${UPLOAD_PROXY_PROTOCOL}" "代理协议"
                ;;
                upload_proxy_server | proxy-server)
                    UPLOAD_PROXY_SERVER="${VALUE}"
                    AddSetting "upload-proxy-server" "${UPLOAD_PROXY_PORT}" "代理服务器"
                ;;

                # Receiving system (IP address or hostname)
                upload-server)
                    UPLOAD_SERVER="${VALUE}"
                    AddSetting "upload-server" "${UPLOAD_SERVER}" "上传服务器（IP 或主机名）"
                ;;

                # Specify an alternative upload tool
                upload-tool)
                    if [ -f "${VALUE}" ]; then UPLOAD_TOOL="${VALUE}"; fi
                    AddSetting "upload-tool" "${UPLOAD_TOOL}" "上传工具"
                ;;

                # Specify arguments for an alternative upload tool
                upload-tool-arguments)
                    UPLOAD_TOOL_ARGS="${VALUE}"
                    AddSetting "upload-tool-arguments" "${UPLOAD_TOOL_ARGS}" "上传工具（参数）"
                ;;

                # Verbose output (--verbose)
                verbose)
                    FIND=$(echo "${VALUE}" | grep -E "^(1|true|yes)") && VERBOSE=1
                    Debug "Verbose set to ${VERBOSE}"
                    AddSetting "verbose" "${VERBOSE}" "详细输出"
                ;;

                ########################################################################################################
                ## DEPRECATED ITEMS
                ########################################################################################################

                # Deprecated: skip tests
                test_skip_always)
                    STRING=$(echo ${VALUE} | awk '{print toupper($0)}')
                    SKIP_TESTS="${SKIP_TESTS} ${STRING}"
                    LogText "[已弃用的选项] 要跳过的检查：${VALUE}"
                    DisplayToolTip "将已弃用的选项 'test_skip_always' 替换为 'skip-test'（添加到 custom.prf）"
                ;;

                # Deprecated: receiving system (IP address or hostname)
                upload_server)
                    UPLOAD_SERVER="${VALUE}"
                    AddSetting "upload-server" "${UPLOAD_SERVER}" "上传服务器（IP 或主机名）"
                    DisplayToolTip "将已弃用的选项 'upload_server' 替换为 'upload-server'（添加到 custom.prf）"
                ;;


                # Catch all bad options and bail out
                *)
                    LogText "未知选项 ${OPTION}（值为：${VALUE}）"

                    ${ECHOCMD:-echo} ""
                    ${ECHOCMD:-echo} "${RED}错误${NORMAL}：配置文件 ${PROFILE} 中发现一个或多个错误"
                    ${ECHOCMD:-echo} ""
                    ${ECHOCMD:-echo} ""
                    ${ECHOCMD:-echo} "完整配置行：${CONFIGOPTION}"
                    ${ECHOCMD:-echo} "${WHITE}详情${NORMAL}：发现未知选项 '${YELLOW}${OPTION}${NORMAL}'（值：${VALUE}）"
                    ${ECHOCMD:-echo} ""
                    ExitFatal
                ;;

            esac

        done
    done
#
#################################################################################
#
    SKIP_TESTS=$(echo ${SKIP_TESTS} | sed "s/^ //")
    if [ -n "${SKIP_TESTS}" ]; then LogText "跳过检查：${SKIP_TESTS}"; fi
#
#################################################################################
#
    # Add group name to report - deprecated
    if [ -n "${GROUP_NAME}" ]; then Report "group=${GROUP_NAME}"; fi
#
#################################################################################
#
    # Set default values (only if not configured in profile)
    if [ -z "${MACHINE_ROLE}" ]; then
        MACHINE_ROLE="server"
        LogText "将选项设置为默认值：MACHINE_ROLE --> ${MACHINE_ROLE}"
    fi

    if [ -z "${NTPD_ROLE}" ]; then
        NTPD_ROLE="client"
        LogText "将选项设置为默认值：NTPD_ROLE --> ${NTPD_ROLE}"
    fi
#
#################################################################################
#
    # Register the discovered settings
    AddSetting "log-tests-incorrect-os" "${SETTING_LOG_TESTS_INCORRECT_OS}" "记录适用于其他操作系统的检查"
    AddSetting "show-report-solution" "${SETTING_SHOW_REPORT_SOLUTION}" "在报告中显示更多详情（解决方案）"
    AddSetting "skip-upgrade-test" "${SKIP_UPGRADE_TEST}" "跳过升级检查"
    AddSetting "strict" "${SET_STRICT}" "对脚本执行严格代码检查"

    unset SETTING_LOG_TESTS_INCORRECT_OS SETTING_SHOW_REPORT_SOLUTION
#
#################################################################################
#
    if [ -n "${DEPRECATED_OPTION}" ]; then
        ReportWarning "GEN-0030" "配置文件中使用的一个或多个已弃用的选项" "${DEPRECATED_OPTION}" "更新配置文件"
    fi
#
#################################################################################
#

    Display --indent 2 --text "- 检查配置文件……" --result "DONE" --color GREEN


#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
