#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# File systems
#
#################################################################################
#
    # Number of days to mark a file as old
    TMP_OLD_DAYS=90
    LVM_VG_USED=0
#
#################################################################################
#
    InsertSection "${SECTION_FILE_SYSTEMS}"
#
#################################################################################
#
    # Test        : FILE-6310
    # Description : Checking if some mount points are separated from /
    # Goal        : Users should not be able to fill their home directory or temporary directory and creating a Denial of Service
    Register --test-no FILE-6310 --weight L --network NO --category security --description "检查 /tmp、/home 和 /var 目录"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 检查 mount 分"
        SEPARATED_FILESYTEMS="/home /tmp /var"
        for I in ${SEPARATED_FILESYTEMS}; do
            LogText "检查： 检查 如果 ${I} 是 mounted separately 或 mounted 在 / 文件 系统"
            if [ -L ${I} ]; then
                ShowSymlinkPath ${I}
                LogText "结果： ${I} 是 一个 符号链接. Manual 检查 必需 到 确定 exact 文件 系统 选项"
                ReportSuggestion "${TEST_NO}" "Symlinked mount 得分 needs 到 为 checked manually" "${I}" ""
                Display --indent 4 --text "- 检查 ${I} mount 得分" --result SYMLINK --color WHITE
            elif [ -d ${I} ]; then
                LogText "结果： 目录 ${I} 存在"
                case "${OS}" in
                    "AIX") FIND=$(${MOUNTBINARY} | ${AWKBINARY} -v MP=${I} '{ if ($2==MP) { print $2 }}') ;;
                    "HP-UX") FIND=$(${MOUNTBINARY} | ${AWKBINARY} -v MP=${I} '{ if ($1==MP) { print $1 }}') ;;
                    *) FIND=$(${MOUNTBINARY} | ${AWKBINARY} -v MP=${I} '{ if ($3==MP) { print $3 }}') ;;
                esac

                if IsEmpty "${FIND}"; then
                    LogText "结果： ${I} 未找到 在 mount 列表. 目录 大多数 很可能 stored 在 / 文件 系统"
                    Display --indent 4 --text "- 检查 ${I} mount 得分" --result "${STATUS_SUGGESTION}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "为降低 ${I} 文件系统占满带来的影响，请将 ${I} 放在独立分区中"
                    AddHP 9 10
                else
                    LogText "结果： 发现 ${I} 作为 一个 separated mount 得分"
                    Display --indent 4 --text "- 检查 ${I} mount 得分" --result "${STATUS_OK}" --color GREEN
                    AddHP 10 10
                fi
            else
                LogText "结果： 目录 ${I} 不存在"
            fi
        done
    fi
#
#################################################################################
#
    # Test        : FILE-6311
    # Description : Checking LVM Volume Groups
    # Notes       : No volume groups found is sent to STDERR for unclear reasons. Filtering both STDERR redirecting and grep.
    if [ ! "${VGDISPLAYBINARY}" = "" -o ! "${LSVGBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6311 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 LVM 卷 组"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 用于 LVM 卷 组"
        case ${OS} in
            AIX)
                 FIND=$(${LSVGBINARY} -o)
            ;;
            Linux)
                 FIND=$(${VGDISPLAYBINARY} 2> /dev/null | ${GREPBINARY} -v "No volume groups found" | ${GREPBINARY} "VG Name" | ${AWKBINARY} '{ print $3 }' | ${SORTBINARY})
            ;;
            *)
                 ReportException "${TEST_NO}:1" "发现了卷组管理器，但尚不支持识别此操作系统"
            ;;
        esac
        if [ -n "${FIND}" ]; then
            LogText "结果： 发现 一个 或 更多 卷 组"
            for I in ${FIND}; do
                LogText "发现 LVM 卷 组： ${I}"
                Report "lvm_volume_group[]=${I}"
            done
            LVM_VG_USED=1
            Display --indent 2 --text "- 检查 LVM 卷 组" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果： 没有 LVM 卷 组 发现"
            if IsVerbose; then Display --indent 2 --text "- 检查 LVM 卷 组" --result "${STATUS_NONE}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6312
    # Description : Checking LVM volumes
    if [ ${LVM_VG_USED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6312 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 LVM volumes"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 用于 LVM volumes"
        case ${OS} in
            AIX)
                 ACTIVE_VG_LIST=$(${LSVGBINARY} -o)
                 FIND=$(for I in ${ACTIVE_VG_LIST}; do ${LSVGBINARY} -l ${I} | ${AWKBINARY} 'NR>2 { print $1 }'; done)
            ;;
            Linux)
                 FIND=$(${LVDISPLAYBINARY} | ${GREPBINARY} -v "No volume groups found" | ${GREPBINARY} "LV Name" | ${AWKBINARY} '{ print $3 }' | ${SORTBINARY})
            ;;
            *)
                 ReportException "${TEST_NO}:1" "Need specific 检查 用于 正在收集 卷管理器 数据"
            ;;
        esac
        if [ ! "${FIND}" = "" ]; then
            LogText "结果： 发现 一个 或 更多 volumes"
            for I in ${FIND}; do
                LogText "发现 LVM 卷： ${I}"
                Report "lvm_volume[]=${I}"
            done
            Display --indent 4 --text "- 检查 LVM volumes" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果： 没有 LVM 卷 组 发现"
            Display --indent 4 --text "- 检查 LVM volumes" --result "${STATUS_NONE}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6316
    # Description : Checking /etc/fstab file permissions
    #Register --test-no FILE-6316 --os Linux --weight L --network NO --category security --description "Checking /etc/fstab"
    #if [ ${SKIPTEST} -eq 0 ]; then
    # 644
#
#################################################################################
#
    # Test        : FILE-6323
    # Description : Checking Linux EXT2, EXT3, EXT4 file systems
    Register --test-no FILE-6323 --os Linux --weight L --network NO --category security --description "检查 EXT 文件 systems"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 用于 Linux EXT 文件 systems"
        FIND=$(${MOUNTBINARY} -t ext2,ext3,ext4 | ${AWKBINARY} '{ print $3","$5 }')
        if [ -n "${FIND}" ]; then
            LogText "结果： 发现 一个 或 更多 EXT 文件 systems"
            for I in ${FIND}; do
                FILESYSTEM=$(echo ${I} | ${CUTBINARY} -d ',' -f1)
                FILETYPE=$(echo ${I} | ${CUTBINARY} -d ',' -f2)
                LogText "文件 系统： ${FILESYSTEM} (类型： ${FILETYPE})"
                Report "file_systems_ext[]=${FILESYSTEM}|${FILETYPE}|"
            done
        else
            LogText "结果： 没有 EXT 文件 systems 发现"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6324
    # Description : Checking Linux XFS file systems
    Register --test-no FILE-6324 --os Linux --weight L --network NO --category security --description "检查 XFS 文件 systems"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 用于 Linux XFS 文件 systems"
        FIND=$(${MOUNTBINARY} -t xfs | ${AWKBINARY} '{ print $3","$5 }')
        if [ -n "${FIND}" ]; then
            LogText "结果： 发现 一个 或 更多 XFS 文件 systems"
            for I in ${FIND}; do
                FILESYSTEM=$(echo ${I} | ${CUTBINARY} -d ',' -f1)
                FILETYPE=$(echo ${I} | ${CUTBINARY} -d ',' -f2)
                LogText "文件 系统： ${FILESYSTEM} (类型： ${FILETYPE})"
                Report "file_systems_xfs[]=${FILESYSTEM}|${FILETYPE}|"
            done
        else
            LogText "结果： 没有 XFS 文件 systems 发现"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6329
    # Description : Query all FFS/UFS mounts from /etc/fstab
    if [ -f /etc/fstab ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6329 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 FFS/UFS 文件 systems"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： Query /etc/fstab 用于 可用 FFS/UFS mount 分"
        FIND=$(${AWKBINARY} '{ if ($3 == "ufs" || $3 == "ffs" ) { print $1":"$2":"$3":"$4":" }}' /etc/fstab)
        if [ -z "${FIND}" ]; then
            if IsVerbose; then Display --indent 2 --text "- Querying FFS/UFS mount 分 (fstab)" --result "${STATUS_NONE}" --color WHITE; fi
            LogText "结果： unable 到 find 任何 single mount 得分 (FFS/UFS)"
        else
            Display --indent 2 --text "- Querying FFS/UFS mount 分 (fstab)" --result "${STATUS_FOUND}" --color GREEN
            Report "filesystem[]=ufs"
            for I in ${FIND}; do
                LogText "FFS/UFS mount 发现: ${I}"
                Report "mountpoint_ufs[]=${I}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6330
    # Description : Query ZFS mounts
    # Note        : mount -p does not work under Linux
    Register --test-no FILE-6330 --os FreeBSD --weight L --network NO --category security --description "检查 ZFS 文件 systems"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 发现 用于 可用 ZFS mount 分"
        FIND=$(${MOUNTBINARY} -p | ${AWKBINARY} '{ if ($3 == "zfs") { print $1":"$2":"$3":"$4":" }}')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- Querying ZFS mount 分 (mount -p)" --result "${STATUS_NONE}" --color WHITE
            LogText "结果： unable 到 find 任何 single mount 得分 (ZFS)"
        else
            Display --indent 2 --text "- Querying ZFS mount 分 (mount -p)" --result "${STATUS_FOUND}" --color GREEN
            Report "filesystem[]=zfs"
            for I in ${FIND}; do
                LogText "ZFS mount 发现： ${I}"
                Report "mountpoint_zfs[]=${I}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6439
    # Description : Query all HAMMER PFS mounts from /etc/fstab
    Register --test-no FILE-6439 --os DragonFly --weight L --network NO --category security --description "检查 HAMMER PFS mounts"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： Query /etc/fstab 用于 可用 HAMMER PFS mount 分"
        FIND=$(${MOUNTBINARY} -p | ${AWKBINARY} '{ if ($3 == "null") { print $1":"$2":"$3":"$4":" }}')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- Querying HAMMER PFS mount 分 (mount -p)" --result "${STATUS_NONE}" --color WHITE
            LogText "结果： unable 到 find 任何 single PFS mount 得分"
        else
            Display --indent 2 --text "- Querying HAMMER PFS mount 分 (mount -p)" --result "${STATUS_FOUND}" --color GREEN
            Report "filesystem[]=hammer"
            for I in ${FIND}; do
                LogText "HAMMER mount 发现： ${I}"
                Report "mountpoint_hammer[]=${I}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6332
    # Description : Check swap partitions
    if [ -f /etc/fstab ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6332 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 交换分区 partitions"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查： query 交换分区 partitions 从 /etc/fstab 文件"
        # Check if third field contains 'swap'
        FIND=$(${AWKBINARY} '{ if ($2=="swap" || $3=="swap") { print $1 }}' /etc/fstab | ${GREPBINARY} -v "^#")
        for I in ${FIND}; do
            FOUND=1
            REAL=""
            UUID=""
            LogText "交换分区 分区 发现： ${I}"
            # TODO Add a test if partition is not a normal partition (e.g. UUID=)
            # Can be ^/dev/mapper/vg-name_lv-name
            # Can be ^/dev/partition

            # Test for UUID usage (e.g. UUID=uuid --> /dev/disk/by-uuid/<uuid>)
            HAS_UUID=$(echo ${I} | ${GREPBINARY} "^UUID=")
            if [ -n "${HAS_UUID}" ]; then
                UUID=$(echo ${HAS_UUID} | ${AWKBINARY} -F= '{ print $2 }')
                LogText "结果： 使用 ${UUID} 作为 UUID"
                if [ -n "${BLKIDBINARY}" ]; then
                    FIND2=$(${BLKIDBINARY} | ${AWKBINARY} '{ if ($2=="UUID=\"${UUID}\"") print $1 }' | ${SEDBINARY} 's/:$//')
                    if [ -n "${FIND2}" ]; then
                        REAL="${FIND2}"
                    fi
                else
                    LogText "结果：未找到 blkid 程序，尝试检查设备列表"
                    sFILE=""
                    if [ -L /dev/disk/by-uuid/${UUID} ]; then
                        LogText "结果： 发现 磁盘 通过 /dev/disk/by-uuid listing"
                        ShowSymlinkPath /dev/disk/by-uuid/${UUID}
                        if [ -n "${sFILE}" ]; then
                            REAL="${sFILE}"
                            LogText "结果： 磁盘 是 ${REAL}"
                        fi
                    else
                        LogText "结果： 没有 符号链接 发现 到 /dev/disk/by-uuid/${UUID}"
                    fi
                fi
            fi
            # Set real device
            if [ -z "${REAL}" ]; then
                REAL="${I}"
            fi
            Report "swap_partition[]=${I},${REAL},"
        done
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- Query 交换分区 partitions (fstab)" --result "${STATUS_OK}" --color GREEN
        else
            Display --indent 2 --text "- Query 交换分区 partitions (fstab)" --result "${STATUS_NONE}" --color YELLOW
            LogText "结果： 没有 交换分区 partitions 发现 在 /etc/fstab"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6336
    # Description : Check swap mount options
    # Examples    : [partition] swap swap defaults 0 0
    #               [partition] none swap sw 0 0
    if [ -f /etc/fstab ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6336 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 交换分区 挂载选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Swap partitions should be mounted with 'sw' or 'swap'
        LogText "检查： 检查 交换分区 partitions 使用 不正确 挂载选项"
        FIND=$(${AWKBINARY} '{ if ($3=="swap" && ($4!~/sw/ && $4!="defaults")) { print $1 }}' /etc/fstab)
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- Testing 交换分区 partitions" --result "${STATUS_OK}" --color GREEN
            LogText "结果： 所有 交换分区 partitions 有 正确 选项 (sw 或 交换分区)"
        else
            Display --indent 2 --text "- Testing 交换分区 partitions" --result "${STATUS_CHECK_NEEDED}" --color YELLOW
            LogText "结果： 可能 不正确 挂载选项 已使用 用于 mounting 交换分区 分区 (${FIND})"
            #ReportWarning "${TEST_NO}" "Possible incorrect mount options used for swap partition (${FIND})"
            ReportSuggestion "${TEST_NO}" "检查 你的 /etc/fstab 文件 用于 交换分区 分区 挂载选项"
            LogText "说明：交换分区的选项字段（第 4 列）通常包含 'sw' 或 'swap'"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6344
    # Description : Check proc mount options (Linux >=3.3 only)
    #               hidepid textual values available kernel >= 5.8 only)
    # Examples    : proc /proc proc defaults,hidepid=2 0 0
    # Goal        : Users should not be able to see processes of other users
    if [ "${OS}" = "Linux" -a -f ${ROOTDIR}proc/version ]; then
        LINUX_KERNEL_MAJOR=$(echo $OS_KERNELVERSION | ${AWKBINARY} -F. '{print $1}')
        LINUX_KERNEL_MINOR=$(echo $OS_KERNELVERSION | ${AWKBINARY} -F. '{print $2}')
        if [ -n "${LINUX_KERNEL_MAJOR}" -a -n "${LINUX_KERNEL_MINOR}" ]; then
            if [ ${LINUX_KERNEL_MAJOR} -ge 3 -a ${LINUX_KERNEL_MINOR} -ge 3 ]; then
                PREQS_MET="YES";
            elif [ ${LINUX_KERNEL_MAJOR} -ge 4 ]; then
                PREQS_MET="YES";
            else
                PREQS_MET="NO";
            fi
        else
            PREQS_MET="NO";
        fi
    fi
    Register --test-no FILE-6344 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 proc 挂载选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Proc should be mounted with 'hidepid=2' or 'hidepid=1' at least
        # https://www.kernel.org/doc/html/latest/filesystems/proc.html#chapter-4-configuring-procfs
        LogText "检查： 检查 proc mount 使用 不正确 挂载选项"
        FIND=$(${MOUNTBINARY} | ${GREPBINARY} -E "${ROOTDIR}proc " | ${GREPBINARY} -E -o "hidepid=([0-9]|[a-z][a-z]*)")
        if [ "${FIND}" = "hidepid=4" -o "${FIND}" = "hidepid=ptraceable" ]; then  # https://lwn.net/Articles/817137/
            Display --indent 2 --text "- Testing /proc mount (hidepid)" --result "${STATUS_OK}" --color GREEN
            LogText "结果： proc mount mounted 使用 ${FIND}"
            AddHP 3 3
        elif [ "${FIND}" = "hidepid=2" -o "${FIND}" = "hidepid=invisible" ]; then
            Display --indent 2 --text "- Testing /proc mount (hidepid)" --result "${STATUS_OK}" --color GREEN
            LogText "结果： proc mount mounted 使用 ${FIND}"
            AddHP 3 3
        elif [ "${FIND}" = "hidepid=1" -o "${FIND}" = "hidepid=noaccess" ]; then
            Display --indent 2 --text "- Testing /proc mount (hidepid)" --result "${STATUS_OK}" --color GREEN
            LogText "结果： proc mount mounted 使用 ${FIND}"
            AddHP 2 3
        elif [ -z "${FIND}" ]; then
            # HIDEPID1_SUGGESTION=" (or at least hidepid=1)"
            AddHP 0 3
            Display --indent 2 --text "- Testing /proc mount (hidepid)" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "结果： /proc filesystem 是 不 mounted 使用 选项 hidepid=1 或 hidepid=2"
            # TODO ReportSuggestion "${TEST_NO}" "Consider mounting /proc via /etc/fstab with mount option hidepid=2" "/proc" "-"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6354
    # Description : Search files within /tmp which are older than 3 months
    if [ -d ${ROOTDIR}tmp ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6354 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "搜索 用于 旧 文件 在 /tmp"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 搜索 用于 旧 文件 在 ${ROOTDIR}tmp"
        # Search for files only in ${ROOTDIR}tmp, with an access time older than X days
        FIND=$(${FINDBINARY} ${ROOTDIR}tmp -xdev -type f -atime +${TMP_OLD_DAYS} 2> /dev/null | ${SEDBINARY} 's/ /!space!/g')
        if IsEmpty "${FIND}"; then
            Display --indent 2 --text "- 检查 用于 旧 文件 在 ${ROOTDIR}tmp" --result "${STATUS_OK}" --color GREEN
            LogText "结果： 没有 文件 发现 在 ${ROOTDIR}tmp which 是 较旧 比 3 个月"
        else
            Display --indent 2 --text "- 检查 用于 旧 文件 在 ${ROOTDIR}tmp" --result "${STATUS_FOUND}" --color RED
            COUNT=0
            for ITEM in ${FIND}; do
                FILE=$(echo ${ITEM} | ${SEDBINARY} 's/!space!/ /g')
                LogText "旧 临时文件： ${FILE}"
                COUNT=$((COUNT + 1))
            done
            LogText "结果：在 ${ROOTDIR}tmp 中发现过去 ${TMP_OLD_DAYS} 天内未修改的旧文件"
            LogText "Advice： 检查 和 clean up unused 文件 在 ${ROOTDIR}tmp. 旧 文件 可以 fill up 一个 磁盘 或 contain"
            LogText "private 信息 和 应 为 deleted 它 不 正在 已使用 actively. 使用 一个 工具 like lsof 到"
            LogText "see which programs possibly 是 使用 一个 particular 文件. 一些 systems 可以 cleanup 临时"
            LogText "目录 由 设置 一个 启动 选项."
            ReportSuggestion "${TEST_NO}" "检查 ${COUNT} 文件 在 ${ROOTDIR}tmp which 是 较旧 比 ${TMP_OLD_DAYS} 天"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6362
    # Description : Check for sticky bit on /tmp
    if [ -d ${ROOTDIR}tmp -a ! -L ${ROOTDIR}tmp ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="No /tmp or /tmp is symlinked"; fi
    Register --test-no FILE-6362 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "检查 /tmp sticky bit"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Depending on OS, number of field with 'tmp' differs
        FIND=$(${LSBINARY} -ld ${ROOTDIR}tmp | ${AWKBINARY} '$1 ~ /[tT]/ { print 1 }')
        if [ "${FIND}" = "1" ]; then
            Display --indent 2 --text "- 检查 ${ROOTDIR}tmp sticky bit" --result "${STATUS_OK}" --color GREEN
            LogText "结果： sticky bit 发现 在 ${ROOTDIR}tmp 目录"
            AddHP 3 3
        else
            Display --indent 2 --text "- 检查 ${ROOTDIR}tmp sticky bit" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "为 ${ROOTDIR}tmp 设置粘滞位，防止用户删除 /tmp 中属于其他用户的文件。" "/tmp" "text：设置粘滞位"
            AddHP 0 3
        fi
        unset FIND
    else
        LogText "结果：已跳过 /tmp 的粘滞位检查。可能原因：目录不存在、目录为符号链接或检查被跳过。"
    fi
#
#################################################################################
#
    # Test        : FILE-6363
    # Description : Check for sticky bit on /var/tmp
    if [ -d ${ROOTDIR}var/tmp -a ! -L ${ROOTDIR}var/tmp ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="No /var/tmp or /var/tmp is symlinked"; fi
    Register --test-no FILE-6363 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "检查 /var/tmp sticky bit"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Depending on OS, number of field with 'tmp' differs
        FIND=$(${LSBINARY} -ld ${ROOTDIR}var/tmp | ${AWKBINARY} '$1 ~ /[tT]/ { print 1 }')
        if [ "${FIND}" = "1" ]; then
            Display --indent 2 --text "- 检查 ${ROOTDIR}var/tmp sticky bit" --result "${STATUS_OK}" --color GREEN
            LogText "结果： sticky bit 发现 在 ${ROOTDIR}var/tmp 目录"
            AddHP 3 3
        else
            Display --indent 2 --text "- 检查 ${ROOTDIR}var/tmp sticky bit" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "为 ${ROOTDIR}var/tmp 设置粘滞位，防止用户删除 /var/tmp 中属于其他用户的文件。" "/var/tmp" "text：设置粘滞位"
            AddHP 0 3
        fi
        unset FIND
    else
        LogText "结果：已跳过 /var/tmp 的粘滞位检查。可能原因：目录不存在、目录为符号链接或检查被跳过。"
    fi
#
#################################################################################
#
    # Test        : FILE-6366
    # Description : Check for noatime option
    # More info   : especially useful for profile 'desktop' and 'server-storage'

    # Want to contribute to Lynis? Create this test

#
#################################################################################
#
    # Test        : FILE-6368
    # Description : Checking Linux root file system ACL support
    Register --test-no FILE-6368 --os Linux --weight L --network NO --root-only YES --category security --description "检查 ACL 支持 在 根 文件 系统"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查： 检查 acl 选项 在 ext[2-4] 根 文件 系统"
        FIND=$(${MOUNTBINARY} | ${AWKBINARY} '{ if ($3=="/" && $5~/ext[2-4]/) { print $6 } }' | ${GREPBINARY} acl)
        if [ -n "${FIND}" ]; then
            LogText "结果： 发现 ACL 选项"
            FOUND=1
        else
            LogText "结果： mount 得分 可能 mounted 使用 defaults"
            LogText "检查： 检查 设备 which holds 根 文件 系统"
            # Get device on which root file system is mounted. Use /dev/root if it exists, or
            # else check output of mount
            if [ -b ${ROOTDIR}dev/root ]; then
                FIND1="${ROOTDIR}dev/root"
            else
                # Only determine device if it is EXT2/3/4
                #FIND1=$(mount | ${GREPBINARY} "on / " | ${AWKBINARY} '{ if ($5~/ext[2-4]/) { print $1 }}')
                FIND1=$(${MOUNTBINARY} -t ext2,ext3,ext4 | ${GREPBINARY} "on / " | ${AWKBINARY} '{ print $1 }')
            fi
            # Trying to determine default mount options from EXT2/EXT3/EXT4 file systems
            if [ -n "${FIND1}" ]; then
                LogText "结果： 发现 ${FIND1}"
                LogText "检查： 检查 默认选项s 在 ${FIND1}"
                FIND2=$(${TUNE2FSBINARY} -l ${FIND1} 2> /dev/null | ${GREPBINARY} "^Default mount options" | ${GREPBINARY} "acl")
                if [ -n "${FIND2}" ]; then
                    LogText "结果： 发现 ACL 选项 在 default 挂载选项"
                    FOUND=1
                else
                    LogText "结果： 没有 ACL 选项 发现 在 default 挂载选项 列表"
                fi
            else
                LogText "结果： 没有 文件 系统 发现 使用 根 文件 系统"
            fi
        fi

        LogText "检查： 检查 acl 选项 在 xfs 根 文件 系统"
        FIND=$(${MOUNTBINARY} | ${AWKBINARY} '{ if ($3=="/" && $5~/xfs/) { print $6 } }' | ${GREPBINARY} -E 'no_acl|no_user_xattr')
        if [ -z "${FIND}" ]; then
            FOUND=1
            # some other tests to do ?
        fi

        if [ ${FOUND} -eq 0 ]; then
            LogText "结果： ACL 选项 NOT 已启用 在 根 文件 系统"
            LogText "补充信息：如需进一步限制文件访问，可使用 ACL。请安装 acl 工具，并使用 acl 选项重新挂载文件系统"
            LogText "可执行 mount -o remount,acl / 为活动文件系统启用 ACL，并在 fstab 中添加 acl 选项"
            Display --indent 2 --text "- ACL 支持 根 文件 系统" --result "${STATUS_DISABLED}" --color YELLOW
            AddHP 0 1
        else
            LogText "结果： ACL 选项 已启用 在 根 文件 系统"
            Display --indent 2 --text "- ACL 支持 根 文件 系统" --result "${STATUS_ENABLED}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6372
    # Description : Check / mount options for Linux
    # Notes       :
    Register --test-no FILE-6372 --os Linux --weight L --network NO --category security --description "检查 / 挂载选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f ${ROOTDIR}etc/fstab ]; then
            FIND=$(${GREPBINARY} -w "/" ${ROOTDIR}etc/fstab | ${GREPBINARY} -v "^#" | ${CUTBINARY} -f1 -d"#" | ${AWKBINARY} '{ if ($2=="/") { print $4 }}')
            NODEV=$(echo ${FIND} | ${AWKBINARY} '{ if ($1 ~ "nodev") { print "YES" } else { print "NO" } }')
            NOEXEC=$(echo ${FIND} | ${AWKBINARY} '{ if ($1 ~ "noexec") { print "YES" } else { print "NO" } }')
            NOSUID=$(echo ${FIND} | ${AWKBINARY} '{ if ($1 ~ "nosuid") { print "YES" } else { print "NO" } }')

            if [ -n "${FIND}" ]; then
                LogText "结果： mount 系统 / 是 已配置 使用 选项: ${FIND}"
                if [ "${FIND}" = "defaults" ]; then
                    Display --indent 2 --text "- Mount 选项 的 /" --result "${STATUS_OK}" --color GREEN
                else
                    Display --indent 2 --text "- Mount 选项 的 /" --result "${STATUS_NON_DEFAULT}" --color YELLOW
                fi
            else
                LogText "结果： 没有 mount 得分 / 或 预期 选项 发现"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6374
    # Description : Check mount options for Linux
    # Notes       : This test determines if the mount point exists. If it does not exist as mount point, yet it is an directory,
    #               you might consider to make it a separate mount point with restrictions.
    #
    #               Depending on the primary goals of a machine, some mount points might be too restrictive. Before applying any
    #               mount flags, test them on a similar or cloned test system.
    #
    #            ---------------------------------------------------------
    #               Mount point              nodev  noexec  nosuid
    #               /boot                      v      v       v
    #               /dev                              v       v
    #               /dev/shm                   v      v       v
    #               /home                      v              v
    #               /run                       v              v
    #               /tmp                       v      v       v
    #               /var                       v              v
    #               /var/log                   v      v       v
    #               /var/log/audit             v      v       v
    #               /var/tmp                   v      v       v
    #            ---------------------------------------------------------

    FILESYSTEMS_TO_CHECK="/boot:nodev,noexec,nosuid /dev:noexec,nosuid /dev/shm:nosuid,nodev,noexec /home:nodev,nosuid /run:nodev,nosuid /tmp:nodev,noexec,nosuid /var:nodev,nosuid /var/log:nodev,noexec,nosuid /var/log/audit:nodev,noexec,nosuid /var/tmp:nodev,noexec,nosuid"
    Register --test-no FILE-6374 --os Linux --weight L --network NO --category security --description "Linux 挂载选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f ${ROOTDIR}etc/fstab ]; then
            for I in ${FILESYSTEMS_TO_CHECK}; do
                FILESYSTEM=$(echo ${I} | ${CUTBINARY} -d: -f1)
                EXPECTED_FLAGS=$(echo ${I} | ${CUTBINARY} -d: -f2 | ${SEDBINARY} 's/,/ /g')
                FS_FSTAB=$(${AWKBINARY} -v fs=${FILESYSTEM} '{ if ($2==fs) { print $3 } }' ${ROOTDIR}etc/fstab)
                if [ "${FS_FSTAB}" = "glusterfs" ]; then
                    EXPECTED_FLAGS=$(echo ${EXPECTED_FLAGS} | ${SEDBINARY} 's/\<\(nodev\|nosuid\)\> *//g')
                    if [ -z "${EXPECTED_FLAGS}" ]; then
                        FS_FSTAB=""
                    fi
                fi
                if [ -z "${FS_FSTAB}" ]; then # not found in fstab, check if mounted otherwise
                    FS_FSTAB=$(mount | ${AWKBINARY} -v fs=${FILESYSTEM} '{ if ($3==fs) { print $6 } }')
                    FOUND_FLAGS=$(mount | ${AWKBINARY} -v fs=${FILESYSTEM} '{ if ($1~"[^#]" && $3==fs) { print $6 } }' | ${SEDBINARY} 's/,/ /g' | ${TRBINARY} '\n' ' ')
                else
                    FOUND_FLAGS=$(${AWKBINARY} -v fs=${FILESYSTEM} '{ if ($1~"[^#]" && $2==fs) { print $4 } }' ${ROOTDIR}etc/fstab | ${SEDBINARY} 's/,/ /g' | ${TRBINARY} '\n' ' ')
                fi
                if [ -n "${FS_FSTAB}" ]; then
                    # In awk using caret/circumflex as first character between brackets, means 'not' (instead of beginning of line)
                    LogText "文件 系统： ${FILESYSTEM}"
                    LogText "预期 flags： ${EXPECTED_FLAGS}"
                    LogText "发现 flags： ${FOUND_FLAGS}"
                    PARTIALLY_HARDENED=0
                    FULLY_HARDENED=1
                    for FLAG in ${EXPECTED_FLAGS}; do
                        FLAG_AVAILABLE=$(echo ${FOUND_FLAGS} | ${GREPBINARY} ${FLAG})
                        if [ -z "${FLAG_AVAILABLE}" ]; then
                            LogText "结果： 可以 不 find 挂载选项 ${FLAG} 在 文件 系统 ${FILESYSTEM}"
                            FULLY_HARDENED=0
                        else
                            LogText "结果：正常，文件系统 ${FILESYSTEM} 上已设置挂载选项 ${FLAG}"
                            PARTIALLY_HARDENED=1
                        fi
                    done
                    if [ ${FULLY_HARDENED} -eq 1 ]; then
                        LogText "结果： 标记 ${FILESYSTEM} 作为 fully hardened"
                        Display --indent 2 --text "- Mount 选项 的 ${FILESYSTEM}" --result "${STATUS_HARDENED}" --color GREEN
                        AddHP 5 5
                    elif [ ${PARTIALLY_HARDENED} -eq 1 ]; then
                        LogText "结果： 标记 ${FILESYSTEM} 作为 partially hardened"
                        Display --indent 2 --text "- Mount 选项 的 ${FILESYSTEM}" --result "${STATUS_PARTIALLY_HARDENED}" --color YELLOW
                        AddHP 4 5
                    else
                        if ContainsString "defaults" "${FOUND_FLAGS}"; then
                            LogText "结果： 标记 ${FILESYSTEM} 选项 作为 default (不 hardened)"
                            Display --indent 2 --text "- Mount 选项 的 ${FILESYSTEM}" --result "${STATUS_DEFAULT}" --color YELLOW
                            AddHP 3 5
                        else
                            LogText "结果： 标记 ${FILESYSTEM} 选项 作为 non-default (不确定 about 加固)"
                            Display --indent 2 --text "- Mount 选项 的 ${FILESYSTEM}" --result "${STATUS_NON_DEFAULT}" --color YELLOW
                            AddHP 4 5
                        fi
                    fi
                else
                    LogText "结果： 文件 系统 ${FILESYSTEM} 未找到 在 ${ROOTDIR}etc/fstab"
                fi
            done
        fi
        NMOUNTS=$(mount | ${WCBINARY} -l)
        NDEVMOUNTS=$(mount | ${AWKBINARY} '{print $6}' | ${GREPBINARY} -v nodev | ${WCBINARY} -l)
        NEXECMOUNTS=$(mount | ${AWKBINARY} '{print $6}' | ${GREPBINARY} -v noexec | ${WCBINARY} -l)
        NSUIDMOUNTS=$(mount | ${AWKBINARY} '{print $6}' | ${GREPBINARY} -v nosuid | ${WCBINARY} -l)
        NWRITEANDEXECMOUNTS=$(mount | ${AWKBINARY} '{print $6}' | ${GREPBINARY} -v noexec | ${GREPBINARY} -E -v '^\(ro[,)]' | ${WCBINARY} -l)
        LogText "结果：共 ${NMOUNTS} 个挂载点，其中缺少 nodev：${NDEVMOUNTS}，缺少 noexec：${NEXECMOUNTS}，缺少 nosuid：${NSUIDMOUNTS}，缺少 ro 或 noexec（W^X）：${NWRITEANDEXECMOUNTS}"
        Display --indent 2 --text "- 共 ${NMOUNTS} 个挂载点，缺少 nodev：${NDEVMOUNTS}，noexec：${NEXECMOUNTS}，nosuid：${NSUIDMOUNTS}，ro 或 noexec（W^X）：${NWRITEANDEXECMOUNTS}"
    fi
#
#################################################################################
#
    # Test        : FILE-6376
    # Description : Bind mount the /var/tmp directory to /tmp
    Register --test-no FILE-6376 --os Linux --weight L --network NO --category security --description "确定 如果 /var/tmp 是 bound 到 /tmp"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f ${ROOTDIR}etc/fstab ]; then
            FIND=$(${AWKBINARY} '{ if ($2=="/var/tmp") { print $4 } }' ${ROOTDIR}etc/fstab)
            BIND=$(echo ${FIND} | ${AWKBINARY} '{ if ($1 ~ "bind") { print "YES" } else { print "NO" } }')
            if [ -n "${FIND}" ]; then
                LogText "结果： mount 系统 /var/tmp 是 已配置 使用 选项: ${FIND}"
                if [ "${BIND}" = "YES" ]; then
                    Display --indent 2 --text "- /var/tmp 是 bound 到 /tmp" --result "${STATUS_OK}" --color GREEN
                    LogText "结果 ： /var/tmp 是 bind 到 /tmp"
                else
                    Display --indent 2 --text "- /var/tmp 是 不 bound 到 /tmp" --result "${STATUS_NON_DEFAULT}" --color YELLOW
                    LogText "结果： /var/tmp 是 不 bind 到 /tmp"
                fi
            else
                LogText "结果： 没有 mount 得分 /var/tmp 或 预期 选项 发现"
                if IsVerbose; then Display --indent 2 --text "- /var/tmp 是 不 bound 到 /tmp" --result "INFO" --color WHITE; fi
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6378 TODO
    # Description : Check for nodirtime option

    # Want to contribute to Lynis? Create this test
#
#################################################################################
#
    # Test        : FILE-6380 TODO
    # Description : Check for relatime

    # Want to contribute to Lynis? Create this test
#
#################################################################################
#
    # Test        : FILE-6390 TODO
    # Description : Check writeback/journalling mode (ext3)
    # More info   : data=writeback | data=ordered | data=journal

    # Want to contribute to Lynis? Create this test

#
#################################################################################
#
    # Test        : FILE-6394
    # Description : Check vm.swappiness (Linux)
    Register --test-no FILE-6394 --os Linux --weight L --network NO --category security --description "确定 level 的 swappiness."
    if [ ${SKIPTEST} -eq 0 ]; then
        SWAPLEVEL=$(${CAT_BINARY} /proc/sys/vm/swappiness)
        LogText "检查： 检查 level 的 vm.swappiness： ${SWAPLEVEL}"
        PHYSDISK=$(${LSBLKBINARY} | ${GREPBINARY} -E 'disk|SWAP' | ${GREPBINARY} -B1 SWAP | ${HEADBINARY} -n1 | ${AWKBINARY} '{print $1}')
        if [ ${SWAPLEVEL} -gt 60 ]; then
            LogText "结果： vm.swappiness=${SWAPLEVEL} meaning 该 swapping 是 更多 frequent 比 default."
            # Check if swap is on a HDD or SDD for frequent swapping
            if [ -d "/sys/block/${PHYSDISK}" ]; then
                HDDORSDD=$(${CAT_BINARY} "/sys/block/${PHYSDISK}/queue/rotational")
                if [ ${HDDORSDD} -eq 1 ]; then
                    ReportSuggestion "${TEST_NO}" "vm.swappiness 设置为 ${SWAPLEVEL}，高于默认值 60；建议为交换分区使用 SSD 以提高性能。"
                fi
            fi
        elif [ ${SWAPLEVEL} -eq 0 ]; then
            LogText "结果： vm.swappiness=${SWAPLEVEL} meaning swapping 是 已禁用."
            ReportSuggestion "${TEST_NO}" "vm.swappiness 设置为 ${SWAPLEVEL}。可考虑至少设置为 1，以尽量减少交换但不完全禁用，从而避免物理内存耗尽时 OOM killer 过早终止进程。"
        elif [ ${SWAPLEVEL} -eq 1 ]; then
            LogText "结果： vm.swappiness=${SWAPLEVEL} meaning 该 swapping 可以 仍然 occur but 在 very 最小."
        elif [ ${SWAPLEVEL} -eq 10 ]; then
            LogText "结果： vm.swappiness=${SWAPLEVEL} which 是 preferred 设置 用于 数据库 servers."
        elif [ ${SWAPLEVEL} -lt 60 ]; then
            LogText "结果： vm.swappiness=${SWAPLEVEL} meaning 该 swapping 是 更少 frequent 比 default. 此 是 仅 recommended 用于 servers."
        else
            LogText "结果： vm.swappiness=${SWAPLEVEL} which 是 standard level 的 swappiness 和 works well 用于 desktop systems."
        fi
        if IsVerbose; then Display --indent 2 --text "- Swappiness： ${SWAPLEVEL}" --result "INFO" --color WHITE; fi
    fi
#
#################################################################################
#
    # Test        : FILE-6398
    # Description : Check if JBD (Journal Block Device) driver is loaded
    # Notes       : Test is temporarily disabled, as JBD might be in a kernel (built-in) - https://github.com/CISOfy/lynis/issues/1508
#    Register --test-no FILE-6398 --os Linux --weight L --network NO --category security --description "Checking if JBD (Journal Block Device) driver is loaded"
#    if [ ${SKIPTEST} -eq 0 ]; then
#        LogText "Test: Checking if JBD (Journal Block Device) driver is loaded"
#        NOTINUSE=0
#        # Only perform testing if we know that KRNL-5723 performed tests
#        if [ ${MONOLITHIC_KERNEL_TESTED} -eq 1 ]; then
#            # Cannot check if driver is loaded/present if kernel is monolithic
#            if [ ${MONOLITHIC_KERNEL} -eq 0 ]; then
#                JBD=$(${LSMODBINARY} | ${GREPBINARY} ^jbd)
#                if [ -n "${JBD}" ]; then
#                    LogText "Result: JBD driver is loaded"
#                    INUSE=$(echo ${JBD} | ${AWKBINARY} '{if ($3 -ne 0) {print $4}}')
#                    if [ -n "${INUSE}" ]; then
#                        LogText "Result: JBD driver is in use by drivers: ${INUSE}"
#                        Report "JBD driver is in use by drivers: ${INUSE}"
#                        Display --indent 2 --text "- JBD driver loaded and in use" --result "${STATUS_OK}" --color GREEN
#                    else
#                        NOTINUSE=1
#                        LogText "Result: JBD driver loaded, but not in use"
#                        Report "JBD driver is loaded, but not in use."
#                        Display --indent 2 --text "- JBD driver loaded, but not in use" --result "${STATUS_SUGGESTION}" --color YELLOW
#                    fi
#                else
#                    NOTINUSE=2
#                    LogText "Result: JBD driver not loaded"
#                    Report "JBD driver not loaded."
#                    Display --indent 2 --text "- JBD driver is not loaded" --result "${STATUS_CHECK_NEEDED}" --color YELLOW
#                fi
#                if [ ${NOTINUSE} -eq 1 ]; then
#                    ReportSuggestion "${TEST_NO}" "The JBD (Journal Block Device) driver is loaded but not in use." "You are currently not using any filesystems with journaling, i.e. you have greater risk of data corruption in case of system crash."
#                elif [ ${NOTINUSE} -eq 2 ]; then
#                    ReportSuggestion "${TEST_NO}" "The JBD (Journal Block Device) driver is not loaded." "Since boot-time, you have not been using any filesystems with journaling. Alternatively, reason could be driver is blacklisted."
#                fi
#            else
#                Display --indent 2 --text "- JBD driver: unable to check" --result "${STATUS_UNKNOWN}" --color YELLOW
#                LogText "Kernel is monolithic - cannot check if JBD driver is part of compiled kernel."
#            fi
#        else
#            Display --indent 2 --text "- JBD driver: test skipped" --result "${STATUS_UNKNOWN}" --color YELLOW
#            LogText "Test skipped as the kernel type (monolithic/modular) is unknown"
#        fi
#    fi
#
#################################################################################
#
    # Test        : FILE-6410
    # Description : Checking locate database (file index)
    # Notes       : Linux     /var/lib/mlocate/mlocate.db or /var/lib/slocate/slocate.db
    #                       or /var/cache/locate/locatedb
    #               FreeBSD /var/db/locate.database
    if [ ! "${LOCATEBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no FILE-6410 --preqs-met ${PREQS_MET} --os Linux --weight L --network NO --category security --description "检查 Locate 数据库"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 locate 数据库"
        FOUND=0
        LOCATE_DBS="${ROOTDIR}var/cache/locate/locatedb ${ROOTDIR}var/db/locate.database ${ROOTDIR}var/lib/locate/locatedb ${ROOTDIR}var/lib/locatedb ${ROOTDIR}var/lib/mlocate/mlocate.db ${ROOTDIR}var/lib/plocate/plocate.db ${ROOTDIR}var/lib/slocate/slocate.db"
        for FILE in ${LOCATE_DBS}; do
            if [ -f ${FILE} ]; then
                LogText "结果： locate 数据库 发现 (${FILE})"
                FOUND=1
                LOCATE_DB="${FILE}"
            else
                LogText "结果： 文件 ${FILE} 未找到"
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 检查 Locate 数据库" --result "${STATUS_FOUND}" --color GREEN
            Report "locate_db=${LOCATE_DB}"
        else
            LogText "结果： 数据库 未找到"
            Display --indent 2 --text "- 检查 Locate 数据库" --result "${STATUS_NOT_FOUND}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "找不到 'locate' 所需的数据库。请运行 'updatedb' 或 'locate.updatedb' 创建该文件。"
        fi
    fi
#
#################################################################################
#
    # Test        : FILE-6420 TODO
    # Description : Check automount process

    # Want to contribute to Lynis? Create this test

#
#################################################################################
#
    # Test        : FILE-6422 TODO
    # Description : Check automount maps (files or for example LDAP based)
    # Notes       : Warn when automounter is running

    # Want to contribute to Lynis? Create this test

#
#################################################################################
#
    # Test        : FILE-6424 TODO
    # Description : Check automount map files

    # Want to contribute to Lynis? Create this test

#
#################################################################################
#
    # Test        : FILE-6425 TODO
    # Description : Check mounted files systems via automounter
    # Notes       : Warn when no systems are mounted?

    # Want to contribute to Lynis? Create this test

#
#################################################################################
#
    # Test        : FILE-6430
    # Description : Disable mounting of some filesystems
    # Rationale   : Unless there is a specific reason to use a particular file system, disable it.
    # Data        : cramfs freevxfs hfs hfsplus jffs2 squashfs udf
    Register --test-no FILE-6430 --weight L --network NO --category security --description "禁用 mounting 的 一些 filesystems"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${LSMODBINARY}" -a -f /proc/modules ]; then
            Display --indent 2 --text "- 禁用 内核 支持 的 一些 filesystems"
            LIST_FS_NOT_SUPPORTED="cramfs freevxfs hfs hfsplus jffs2 squashfs udf"
            FOUND=0
            AVAILABLE_FS=""
            AVAILABLE_MODPROBE_FS=""
            for FS in ${LIST_FS_NOT_SUPPORTED}; do
                # Check if filesystem is present in modprobe output
                FIND=$(${MODPROBEBINARY} -v -n ${FS} 2>/dev/null | ${GREPBINARY} -E "/${FS}.ko" | ${TAILBINARY} -1)
                if [ -n "${FIND}" ]; then
                    LogText "结果： 发现 ${FS} 支持 在 内核 (输出 = ${FIND})"
                    Debug "Module ${FS} present in the kernel"
                    LogText "检查： 检查 如果 ${FS} 是 当前"
                    # Check if FS is present in lsmod output
                    FIND=$(${LSMODBINARY} | ${GREPBINARY} -E "^${FS}")
                    if IsEmpty "${FIND}"; then
                        LogText "结果： 模块 ${FS} 是 当前 不 已加载 在 内核."
                        AddHP 2 3
                        if IsDebug; then Display --indent 6 --text "- 模块 ${FS} 不 已加载 (lsmod)" --result OK --color GREEN; fi
                    else
                        LogText "结果： 模块 ${FS} 是 已加载 在 内核"
                        Display --indent 4 --text "- 模块 $FS 已加载 在 内核 (lsmod)" --result "FOUND" --color WHITE
                        FOUND=1
                        AVAILABLE_MODPROBE_FS="${AVAILABLE_MODPROBE_FS}${FS} "
                    fi
                else
                    AddHP 3 3
                    if IsDebug; then Display --indent 6 --text "- 模块 ${FS} 不 present 在 内核" --result OK --color GREEN; fi
                fi
                
                for SUBDIR in "${ROOTDIR}etc" "${ROOTDIR}usr/lib"; do
                    if [ -d "${SUBDIR}/modprobe.d" ]; then
                        LogText "结果： 目录 ${SUBDIR}/modprobe.d 存在"
                        FIND=$(${LSBINARY} "${SUBDIR}/modprobe.d/*" 2> /dev/null)
                        if [ -n "${FIND}" ]; then
                            FIND1=$(${GREPBINARY} -E "^blacklist[[:space:]]+${FS}$" ${ROOTDIR}etc/modprobe.d/* | ${GREPBINARY} -v "#")
                            FIND2=$(${GREPBINARY} -E "^install[[:space:]]+${FS}[[:space:]]+/bin/(true|false)$" ${ROOTDIR}etc/modprobe.d/* | ${GREPBINARY} -v "#")
                            if [ -n "${FIND1}" ] || [ -n "${FIND2}" ]; then
                                Display --indent 4 --text "- 模块 $FS 是 blacklisted" --result "OK" --color GREEN
                                LogText "结果： 模块 ${FS} 是 blacklisted"
                                break
                            fi
                        fi
                    fi
                done
            done
            if [ ${FOUND} -eq 1 ]; then
                Display --indent 4 --text "- 发现 内核模块： ${AVAILABLE_MODPROBE_FS}"
                ReportSuggestion "${TEST_NO}" "建议禁用未使用的内核模块" "/etc/modprobe.d/blacklist.conf" "添加 安装 MODULENAME /bin/true（不含引号）"
            fi
        else
            LogText "检查 已跳过 lsmod 程序 未找到 或 /proc/modules 可以 不 为 opened"
        fi
        unset AVAILABLE_FS AVAILABLE_MODPROBE_FS
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
