#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Memory and processes
#
#################################################################################
#
    InsertSection "${SECTION_MEMORY_AND_PROCESSES}"
#
#################################################################################
#
    # Test        : PROC-3602
    # Description : Query /proc/meminfo
    Register --test-no PROC-3602 --os Linux --weight L --network NO --category security --description "检查 /proc/meminfo 中的内存信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f ${ROOTDIR}proc/meminfo ]; then
            LogText "结果：发现 ${ROOTDIR}proc/meminfo"
            Display --indent 2 --text "- 正在检查 ${ROOTDIR}proc/meminfo" --result "${STATUS_FOUND}" --color GREEN
            FIND=$(${AWKBINARY} '/^MemTotal/ { print $2, $3 }' ${ROOTDIR}proc/meminfo)
            MEMORY_SIZE=$(echo ${FIND} | ${AWKBINARY} '{ print $1 }')
            MEMORY_UNITS=$(echo ${FIND} | ${AWKBINARY} '{ print $2 }')
            LogText "结果：发现 ${MEMORY_SIZE} ${MEMORY_UNITS} 内存"
            Report "memory_size=${MEMORY_SIZE}"
            Report "memory_units=${MEMORY_UNITS}"
        else
            LogText "结果：系统中未找到 ${ROOTDIR}proc/meminfo 文件"
        fi
    fi
#
#################################################################################
#
    # Test        : PROC-3604
    # Description : Query /proc/meminfo
    # Notes       : TODO - prtconf replacement
    Register --test-no PROC-3604 --os Solaris --weight L --network NO --category security --description "通过 prtconf 查询内存信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 /usr/sbin/prtconf"
        if [ -x /usr/sbin/prtconf ]; then
            Display --indent 2 --text "- 通过 prtconf 查询已安装内存" --result "${STATUS_DONE}" --color GREEN
            MEMORY_SIZE=$(/usr/sbin/prtconf | ${GREPBINARY} "^Memory size:" | ${CUTBINARY} -d ' ' -f3)
            MEMORY_UNITS=$(/usr/sbin/prtconf | ${GREPBINARY} "^Memory size:" | ${CUTBINARY} -d ' ' -f4)
            LogText "结果：发现 ${MEMORY_SIZE} ${MEMORY_UNITS} 内存"
            Report "memory_size=${MEMORY_SIZE}"
            Report "memory_units=${MEMORY_UNITS}"
        else
            Display --indent 2 --text "- 通过 prtconf 查询已安装内存" --result "${STATUS_SKIPPED}" --color WHITE
            LogText "结果：未找到 /usr/sbin/prtconf"
        fi
    fi
#
#################################################################################
#
    # Test        : PROC-3612
    # Description : Searching for dead and zombie processes
    # Notes       : Don't perform test on Solaris
    if [ ! "${OS}" = "Solaris" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PROC-3612 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查已终止或僵尸进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ "${OS}" = "AIX" ]; then
            FIND=$(${PSBINARY} -Ae -o pid,stat,comm | ${AWKBINARY} '{ if ($2 ~ /Z|X/) print $1 }' | ${XARGSBINARY})
        else
            FIND=$(${PSBINARY} x -o pid,stat,comm | ${AWKBINARY} '{ if ($2 ~ /Z|X/) print $1 }' | ${XARGSBINARY})
        fi
        if [ -z "${FIND}" ]; then
            LogText "结果：未发现僵尸进程"
            Display --indent 2 --text "- 正在搜索已终止或僵尸进程" --result "${STATUS_NOT_FOUND}" --color GREEN
        else
            LogText "结果：发现一个或多个已终止或僵尸进程"
            LogText "输出：进程 ID ${FIND}"
            Display --indent 2 --text "- 正在搜索已终止或僵尸进程" --result "${STATUS_FOUND}" --color RED
            ReportSuggestion "${TEST_NO}" "检查 ps 输出中的已终止或僵尸进程"
        fi
    fi
#
#################################################################################
#
    # Test        : PROC-3614
    # Description : Searching for heavy IO based waiting processes
    # Notes       : Don't perform test on Solaris
    if [ ! "${OS}" = "Solaris" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PROC-3614 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查因大量 I/O 而等待的进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ "${OS}" = "AIX" ]; then
            FIND=$(${PSBINARY} -Ae -o pid,stat,comm | ${AWKBINARY} '{ if ($2=="D") print $1 }' | ${XARGSBINARY})
        else
            FIND=$(${PSBINARY} x -o pid,stat,comm | ${AWKBINARY} '{ if ($2=="D") print $1 }' | ${XARGSBINARY})
        fi
        if [ -z "${FIND}" ]; then
            LogText "结果：没有进程在等待优先处理 I/O 请求"
            Display --indent 2 --text "- 正在搜索等待 I/O 的进程" --result "${STATUS_NOT_FOUND}" --color GREEN
        else
            LogText "结果：发现一个或多个等待优先处理 I/O 请求的进程"
            LogText "更多信息：状态标志为 'D' 的进程通常会一直等待，直到磁盘 I/O 事件完成。例如网络存储连接或协议配置不当时可能出现这种情况。"
            LogText "输出：进程 ID ${FIND}"
            Display --indent 2 --text "- 正在搜索等待 I/O 的进程" --result "${STATUS_FOUND}" --color RED
            ReportSuggestion "${TEST_NO}" "检查进程列表中等待 I/O 请求的进程"
        fi
    fi
#
#################################################################################
#
    # Test        : PROC-3802
    # Description : Check presence of prelink tooling
    Register --test-no PROC-3802 --package-manager-required --os Linux --weight L --network NO --category security --description "检查是否存在 prelink 工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        if PackageIsInstalled "prelink"; then
            LogText "结果：已安装 prelink 软件包"
            # TODO
            # - Add item to website with rationale
            #ReportSuggestion "${TEST_NO}" "Disable and remove prelinking of binaries"
            AddHP 1 3
            Display --indent 2 --text "- 搜索 prelink 工具" --result "${STATUS_FOUND}" --color YELLOW
        else
            Display --indent 2 --text "- 搜索 prelink 工具" --result "${STATUS_NOT_FOUND}" --color GREEN
            LogText "结果：未安装 prelink 软件包"
            AddHP 3 3
        fi
    fi
#
#################################################################################
#


WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
