#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
    InsertSection "${SECTION_STORAGE}"
#
#################################################################################
#
    AUTOMOUNTER_DAEMON_RUNNING=0
    NFS_DAEMON_RUNNING=0
    AUTOMOUNTER_DAEMON_TOOL=""
#
#################################################################################
#
    # Test        : STRG-1846
    # Description : Check for disabled firewire storage
    # Explanation : Best option is to use the install function, otherwise drivers can still be loaded manually
    Register --test-no STRG-1846 --os Linux --weight L --network NO --category security --description "检查是否禁用 FireWire 存储"
    if [ "${SKIPTEST}" -eq 0 ]; then
        FOUND=0
        LogText "检查：/etc/modprobe.d 目录和 /etc/modprobe.conf 配置文件中的 FireWire 存储驱动"
        if [ -d "${ROOTDIR}etc/modprobe.d" ]; then
            FIND=$(${LSBINARY} ${ROOTDIR}etc/modprobe.d/* 2> /dev/null)
            if [ -n "${FIND}" ]; then
                FIND1=$(${GREPBINARY} -E "blacklist (ohci1394|firewire[-_]ohci|firewire-core)" ${ROOTDIR}etc/modprobe.d/* | ${GREPBINARY} -v "#")
                FIND2=$(${GREPBINARY} -E "install (ohci1394|firewire[-_]ohci|firewire-core) /bin/(false|true)" ${ROOTDIR}etc/modprobe.d/* | ${GREPBINARY} -v "#")
                if [ -n "${FIND1}" ] || [ -n "${FIND2}" ]; then
                    FOUND=1
                    LogText "结果：发现 FireWire OHCI 驱动已被禁用"
                fi
            else
                LogText "结果：${ROOTDIR}etc/modprobe.d 目录存在但其中没有文件，跳过"
            fi
        fi
        if [ -f "${ROOTDIR}etc/modprobe.conf" ]; then
            FIND1=$(${GREPBINARY} -E -r "blacklist (ohci1394|firewire[-_]ohci|firewire-core)" "${ROOTDIR}etc/modprobe.conf" | ${GREPBINARY} -v "#")
            FIND2=$(${GREPBINARY} -E -r "install (ohci1394|firewire[-_]ohci|firewire-core) /bin/(false|true)" "${ROOTDIR}etc/modprobe.conf" | ${GREPBINARY} -v "#")
            if [ -n "${FIND1}" ] || [ -n "${FIND2}" ]; then
                FOUND=1
                LogText "结果：发现 FireWire OHCI 驱动已被禁用"
            fi
        fi

        if [ ${FOUND} -eq 0 ]; then
            LogText "结果：FireWire OHCI 驱动未被明确禁用"
            Display --indent 2 --text "- 正在检查 FireWire OHCI 驱动（modprobe 配置）" --result "${STATUS_NOT_DISABLED}" --color WHITE
            ReportSuggestion "${TEST_NO}" "不使用 FireWire 存储等驱动时将其禁用，以防止未经授权的存储设备接入或数据被窃取"
            # after blacklisting modules, make sure to remove them from the initram filesystem: update-initramfs -u
            AddHP 2 3
        else
            LogText "结果：FireWire OHCI 驱动已禁用"
            Display --indent 2 --text "- 正在检查 FireWire OHCI 驱动（modprobe 配置）" --result "${STATUS_DISABLED}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

# EOF
