#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Ports and packages
#
#################################################################################
#
    InsertSection "${SECTION_PORTS_AND_PACKAGES}"
    PACKAGE_MGR_PKG=0
    PACKAGE_AUDIT_TOOL=""
    PACKAGE_AUDIT_TOOL_FOUND=0
    PACMANCONF="${ROOTDIR}etc/pacman.conf"
    INSTALLED_PACKAGES=""
#
#################################################################################
#
    Display --indent 2 --text "- 搜索软件包管理器"
#
#################################################################################
#
    # Test        : PKGS-7200
    # Description : Check Alpine Package Keeper (apk)
    if [ -x ${ROOTDIR}/sbin/apk ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7200 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 apk"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        Display --indent 4 --text "- 搜索 apk 软件包管理器" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 apk 可执行文件"
        Report "package_manager[]=apk"
        PACKAGE_MGR_PKG=1
        LogText "检查：运行 apk info -v 获取软件包列表"
        Display --indent 6 --text "- 查询软件包管理器"
        LogText "输出："
        SPACKAGES=$(apk info -v | ${SEDBINARY} -r -e 's/([a-z,A-Z,0-9,_,-,.]{1,250})-([a-z,A-Z,0-9,.]+-r[a-z,A-Z,0-9]+)/\1,\2/' | sort)
        for J in ${SPACKAGES}; do
            COUNT=$((COUNT + 1))
            PACKAGE_NAME=$(echo ${J} | ${CUTBINARY} -d ',' -f1)
            PACKAGE_VERSION=$(echo ${J} | ${CUTBINARY} -d ',' -f2)
            LogText "发现软件包：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION}"
        done
        Report "installed_packages=${COUNT}"
    else
        LogText "结果：未找到 apk，已跳过检查"
    fi
#
#################################################################################
#
    # Test        : PKGS-7301
    # Description : Query FreeBSD pkg
    if [ -x ${ROOTDIR}usr/sbin/pkg ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7301 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 FreeBSD pkg"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(pkg -N 2>&1; echo $?)
        if [ "${FIND}" = "0" ]; then
            Display --indent 4 --text "- 使用 pkg 搜索软件包" --result "${STATUS_FOUND}" --color GREEN
            Report "package_manager[]=pkg"
            PACKAGE_MGR_PKG=1
            LogText "结果：发现 pkg"
            LogText "检查：查询 pkg 获取软件包列表"
            Display --indent 6 --text "- 使用 pkg 查询已安装的软件包"
            LogText "输出："; LogText "-----"
            SPACKAGES=$(${ROOTDIR}usr/sbin/pkg query %n,%v)
            for ITEM in ${SPACKAGES}; do
                sPKG_NAME=$(echo ${ITEM} | ${CUTBINARY} -d ',' -f1)
                sPKG_VERSION=$(echo ${ITEM} | ${CUTBINARY} -d ',' -f2)
                LogText "已安装的软件包：${sPKG_NAME}（版本：${sPKG_VERSION}）"
                INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${ITEM}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7302
    # Description : Query FreeBSD/NetBSD pkg_info
    if [ -x ${ROOTDIR}usr/sbin/pkg_info ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7302 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 FreeBSD/NetBSD pkg_info"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        Display --indent 4 --text "- 检查 pkg_info" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 pkg_info"
        Report "package_manager[]=pkg_info"
        LogText "检查：查询 pkg_info 获取软件包列表"
        Display --indent 6 --text "- 使用 pkg_info 查询已安装的软件包"
        LogText "输出："; LogText "-----"
        SPACKAGES=$(${ROOTDIR}usr/sbin/pkg_info 2>&1 | ${SORTBINARY} | ${TRBINARY} -s ' ' | ${CUTBINARY} -d ' ' -f1 | ${SEDBINARY} -e 's/^\(.*\)-\([0-9].*\)$/\1,\2/g')
        for ITEM in ${SPACKAGES}; do
            COUNT=$((COUNT + 1))
            sPKG_NAME=$(echo ${ITEM} | ${CUTBINARY} -d ',' -f1)
            sPKG_VERSION=$(echo ${ITEM} | ${CUTBINARY} -d ',' -f2)
            LogText "已安装的软件包：${sPKG_NAME}（版本：${sPKG_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${ITEM}"
        done
        Report "installed_packages=${COUNT}"
    fi
#
#################################################################################
#
    # Test        : PKGS-7303
    # Description : Query brew package manager
    FIND=$(which brew 2> /dev/null | grep -v "no [^ ]* in ")
    if [ -n "${FIND}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7303 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 brew 软件包管理器"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 4 --text "- 搜索 brew" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 brew"
        PACKAGE_MGR_PKG=1
        Report "package_manager[]=brew"
        LogText "检查：查询 brew 获取软件包列表"
        Display --indent 4 --text "- 使用 brew 查询已安装的软件包"
        LogText "输出："; LogText "-----"
        GPACKAGES=$(brew list --versions)
        while IFS= read -r PKG; do
            PACKAGE_NAME=$(echo ${PKG} | ${CUTBINARY} -d ' ' -f1)
            PACKAGE_VERSION=$(echo ${PKG} | ${CUTBINARY} -d ' ' -f2)
            LogText "发现软件包：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION}"
        done << EOF
$GPACKAGES
EOF
    else
        LogText "结果：此系统上未找到 brew"
    fi
#
#################################################################################
#
    # Test        : PKGS-7304
    # Description : Gentoo packages
    if [ -x ${ROOTDIR}usr/bin/emerge -a -x ${ROOTDIR}usr/bin/equery ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7304 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 Gentoo 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 4 --text "- 搜索 emerge" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 Gentoo emerge"
        Report "package_manager[]=emerge"
        LogText "检查：查询 Portage 获取软件包列表"
        Display --indent 4 --text "- 使用 Portage 查询已安装的软件包"
        LogText "输出："; LogText "-----"
        GPACKAGES=$(equery l '*' | ${SEDBINARY} -e 's/[.*]//g')
        for PKG in ${GPACKAGES}; do
            LogText "发现软件包 ${PKG}"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PKG},0,"
        done
    else
        LogText "结果：此系统上未找到 emerge"
    fi
#
#################################################################################
#
    # Test        : PKGS-7305
    # Description : Query macOS Apps in /Applications and CoreServices
    Register --test-no PKGS-7305 --os macOS --weight L --network NO --category security --description "查询 /Applications 和 CoreServices 中的 macOS 应用"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：查询 /Applications 中的应用"
        Display --indent 4 --text "- 查询 /Applications 中的 macOS 应用"
        LogText "输出："; LogText "-----"
        for APP in /Applications/*.app; do
            PACKAGE_NAME=$(basename "$APP" .app)
            PACKAGE_VERSION=$(defaults read "$APP/Contents/Info" CFBundleShortVersionString 2>/dev/null || echo "N/A")
            LogText "发现软件包：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION}"
        done
        Display --indent 4 --text "- 查询 Apple CoreServices"
        for CS in /Library/Apple/System/Library/CoreServices/*.app; do
            PACKAGE_NAME=$(basename "$CS" .app)
            PACKAGE_VERSION=$(defaults read "$CS/Contents/Info" CFBundleShortVersionString 2>/dev/null || echo "N/A")
            LogText "发现 CoreServices：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION}"
        done   
    fi
#
#################################################################################
#
    # Test        : PKGS-7306
    # Description : Solaris packages
    if [ -x ${ROOTDIR}usr/bin/pkginfo ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7306 --os Solaris --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 Solaris 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 4 --text "- 搜索 pkginfo" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：发现 Solaris pkginfo"
            Report "package_manager[]=pkginfo"
            PACKAGE_MGR_PKG=1
            LogText "检查：查询 pkginfo 获取软件包列表"
            Display --indent 4 --text "- 使用 pkginfo 查询已安装的软件包"
            LogText "输出："; LogText "-----"
            # Strip SUNW from strings
            SPACKAGES=$(${ROOTDIR}usr/bin/pkginfo -i | ${TRBINARY} -s ' ' | ${CUTBINARY} -d ' ' -f2 | ${SEDBINARY} "s#^SUNW##")
            for J in ${SPACKAGES}; do
                LogText "发现软件包 ${J}"
                INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${J},0,"
            done
    else
        LogText "结果：此系统上未找到 pkginfo"
    fi
#
#################################################################################
#
    # Test        : PKGS-7308
    # Description : RPM package based systems
    if [ -n "${RPMBINARY}" -a -z "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7308 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 RPM 检查软件包列表"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        Display --indent 4 --text "- 搜索 RPM 软件包管理器" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 rpm 可执行文件（${RPMBINARY}）"
        Report "package_manager[]=rpm"
        LogText "检查：运行 rpm -qa 获取软件包列表"
        Display --indent 6 --text "- 查询 RPM 软件包管理器"
        LogText "输出："; LogText "--------"
        SPACKAGES=$(${RPMBINARY} -qa --queryformat "%{NAME},%{VERSION}-%{RELEASE}.%{ARCH}\n" 2> /dev/null | sort)
        if [ -z "${SPACKAGES}" ]; then
            LogText "结果：RPM 可执行文件可用，但软件包列表似乎为空"
            LogText "信息：rpm 已安装，但似乎未用于安装软件包"
            ReportSuggestion "${TEST_NO}" "检查 RPM 数据库：rpm 可用，但未返回任何软件包"
        else
            for PKG in ${SPACKAGES}; do
                COUNT=$((COUNT + 1))
                PACKAGE_NAME=$(echo ${PKG} | ${AWKBINARY} -F, '{print $1}')
                PACKAGE_VERSION=$(echo ${PKG} | ${AWKBINARY} -F, '{print $2}')
                LogText "发现软件包：${PKG}"
                INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION},"
            done
            Report "installed_packages=${COUNT}"
        fi
    else
        LogText "结果：此系统上未找到 RPM，已跳过检查"
    fi
#
#################################################################################
#
    # Test        : PKGS-7310
    # Description : pacman package based systems
    if [ -n "${PACMANBINARY}" -a -f "${PACMANCONF}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7310 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 pacman 检查软件包列表"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        Display --indent 4 --text "- 搜索 pacman 软件包管理器" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 pacman 可执行文件（${PACMANBINARY}）"
        Report "package_manager[]=pacman"
        PACKAGE_MGR_PKG=1
        LogText "检查：运行 pacman -Q 获取软件包列表"
        Display --indent 6 --text "- 查询 pacman 软件包管理器"
        LogText "输出："; LogText "--------"
        SPACKAGES=$(${PACMANBINARY} -Q | ${SORTBINARY} | ${SEDBINARY} 's/ /,/g')
        if [ -z "${SPACKAGES}" ]; then
            LogText "结果：pacman 可用，但软件包列表似乎为空"
            LogText "信息：pacman 已安装，但似乎未用于安装软件包"
        else
            for PKG in ${SPACKAGES}; do
                COUNT=$((COUNT + 1))
                PACKAGE_NAME=$(echo ${PKG} | ${AWKBINARY} -F, '{ print $1 }')
                PACKAGE_VERSION=$(echo ${PKG} | ${AWKBINARY} -F, '{ print $2 }')
                LogText "发现软件包：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
                INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PKG}"
            done
            Report "installed_packages=${COUNT}"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7312
    # Description : Check for available package updates when pacman package is used
    if [ -n "${PACMANBINARY}" -a -f "${PACMANCONF}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7312 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 pacman 系统的可用更新"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        FIND=$(which checkupdates 2> /dev/null | grep -v "no [^ ]* in ")
        if [ -n "${FIND}" ]; then
            FIND=$(checkupdates)
            for I in ${FIND}; do
                LogText "结果：${I} 有可用更新"
                Report "available_update[]=${I}"
                FOUND=1
            done
            if [ ${FOUND} -eq 1 ]; then
                Display --indent 4 --text "- 使用 checkupdates 检查更新状态" --result "有待更新" --color YELLOW
                ReportSuggestion "${TEST_NO}" "此系统采用滚动更新，请安装可用的系统更新"
            else
                Display --indent 4 --text "- 使用 checkupdates 检查更新状态" --result "已是最新" --color GREEN
            fi
        else
            LogText "结果：未找到 checkupdates，跳过此检查"
        fi
    else
        LogText "结果：此系统上未找到 pacman，已跳过检查"
    fi
#
#################################################################################
#
    # Test        : PKGS-7314
    # Description : Check pacman.conf options
    if [ -n "${PACMANBINARY}" -a -f "${PACMANCONF}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7314 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 pacman 配置选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        # Check configuration options (options start with a capital)
        LogText "检查：搜索 ${PACMANCONF} 中的配置选项"
        FIND=$(${GREPBINARY} "^[A-Z]" ${PACMANCONF} | ${SORTBINARY} -u | ${SEDBINARY} 's/ /:space:/g')
        for I in ${FIND}; do
            PMOPTION=$(echo ${I} | ${SEDBINARY} 's/:space:/ /g' | ${AWKBINARY} -F= '{ print $1 }')
            PMVALUE=$(echo ${I} | ${SEDBINARY} 's/:space:/ /g' | ${AWKBINARY} -F= '{ print $2 }')
            LogText "结果：发现选项 ${PMOPTION}，配置值为 ${PMVALUE}"
            Report "pacman_option[]=${PMOPTION}:${PMVALUE}:"
        done

        # Check software repositories
        LogText "检查：检查可用的软件仓库"
        FIND=$(${GREPBINARY} "^\[.*\]$" ${PACMANCONF} | ${TRBINARY} -d '[]')
        for I in ${FIND}; do
            COUNT=$((COUNT + 1))
            Report "package_repository[]=${I}"
        done
        LogText "结果：发现 ${COUNT} 个软件仓库"
    fi
#
#################################################################################
#
    # TODO

    ## Test        : PKGS-7318
    ## Description : APT configuration
    #if [ -x ${ROOTDIR}usr/bin/apt-config ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no PKGS-7318 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "APT configuration"
    #if [ ${SKIPTEST} -eq 0 ]; then
    #    LogText "Test: check APT configuration"
    #    if ! SkipAtomicTest ${TEST_NO}:atomicname; then
    #    # Acquire::AllowInsecureRepositories should be 0 (could be 1)
    #    # Acquire::AllowDowngradeToInsecureRepositories should be 0
    #    # Binary::apt::Acquire::AllowInsecureRepositories should be 0
    #fi
#
#################################################################################
#
    # Test        : PKGS-7320
    # Description : Check available of arch-audit
    if [ "${OS_FULLNAME}" = "Arch Linux" ] || [ "${OS_FULLNAME}" = "Arch Linux 32" ] || [ "${OS_FULLNAME}" = "Garuda Linux" ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="此检查仅适用于 Arch Linux 和 Garuda Linux"; fi
    Register --test-no PKGS-7320 --os "Linux" --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "检查 arch-audit 工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -z "${ARCH_AUDIT_BINARY}" ]; then
            LogText "结果：未找到 arch-audit 可执行文件"
            AddHP 1 2
            ReportSuggestion "${TEST_NO}" "建议安装 arch-audit，以检测存在漏洞的软件包" "arch-audit" "text:安装 arch-audit"
        else
            PACKAGE_AUDIT_TOOL_FOUND=1
            PACKAGE_AUDIT_TOOL="arch-audit"
            LogText "结果：发现 arch-audit 可执行文件（${ARCH_AUDIT_BINARY}）"
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7322
    # Description : Discover vulnerable packages with arch-audit
    if [ -n "${ARCH_AUDIT_BINARY}" ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="未找到 arch-audit"; fi
    Register --test-no PKGS-7322 --os "Linux" --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "使用 arch-audit 检测存在漏洞的软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：分析 arch-audit 输出中的漏洞软件包"
        FIND=$(${ARCH_AUDIT_BINARY} | ${SEDBINARY} 's/ High risk!//' | ${SEDBINARY} 's/ Medium risk!//' | ${SEDBINARY} 's/ Low risk!//' | ${SEDBINARY} 's/\.\..*$//' | ${SEDBINARY} 's/, /,/g' | ${SEDBINARY} 's/\(\["\|"\]\)//g' | ${SEDBINARY} 's/""/,/g' | ${AWKBINARY} '{if ($0 ~ /is affected by CVE\-/) {print $1"|"$5"|"} else {ORS=""; print $1"|"; for (i=5; i<=NF; i++)print $i; print "\n"; ORS="\n"}}'| ${AWKBINARY} -F'|' 'NF>1{a[$1] = a[$1]","$2}END{for(i in a){print i""a[i]"|"}}' | ${SEDBINARY} 's/,CVE-/|cve=CVE-/' | ${SORTBINARY})
        if [ -z "${FIND}" ]; then
            LogText "结果：arch-audit 未发现存在漏洞的软件包"
            AddHP 10 10
        else
            LogText "结果：发现一个或多个存在漏洞的软件包"
            VULNERABLE_PACKAGES_FOUND=1
            for ITEM in ${FIND}; do
                LogText "发现记录：${ITEM}"
                Report "vulnerable_package[]=${ITEM}"
                AddHP 1 2
            done
            ReportWarning "${TEST_NO}" "发现存在漏洞的软件包" "arch-audit 返回了结果" "text:运行 arch-audit 查看结果，并在需要时使用 pacman -Suy 更新软件包"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7328
    # Description : Check installed packages with Zypper
    if [ -n "${ZYPPERBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7328 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 Zypper 查询已安装的软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        PACKAGE_AUDIT_TOOL_FOUND=1
        PACKAGE_AUDIT_TOOL="zypper"
        FIND=$(${ZYPPERBINARY} --non-interactive -n se -t package -i | ${AWKBINARY} '{ if ($1=="i") { print $3 } }')
        if [ -n "${FIND}" ]; then
            for PKG in ${FIND}; do
                COUNT=$((COUNT + 1))
                LogText "已安装的软件包：${PKG}"
                INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PKG},0,"
            done
            Report "installed_packages=${COUNT}"
        else
            # Could not find any installed packages
            ReportException "${TEST_NO}" "Zypper 未找到已安装的软件包"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7330
    # Description : Check vulnerable packages with Zypper
    if [ -n "${ZYPPERBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7330 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 Zypper 查询存在漏洞的软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${ZYPPERBINARY} --non-interactive pchk | ${GREPBINARY} "(0 security patches)")
        if [ -n "${FIND}" ]; then
            LogText "结果：Zypper 未发现安全更新"
            Display --indent 2 --text "- 使用 Zypper 查找存在漏洞的软件包" --result "${STATUS_NONE}" --color GREEN
        else
            Display --indent 2 --text "- 使用 Zypper 查找存在漏洞的软件包" --result "${STATUS_WARNING}" --color RED
            LogText "结果：Zypper 发现一个或多个已安装软件包存在漏洞。"
            ReportWarning "${TEST_NO}" "发现一个或多个已安装软件包存在漏洞"
            # Unfortunately zypper does not properly give back which package it is. Usually best guess is last word on the line
            FIND=$(${ZYPPERBINARY} --non-interactive lp | ${AWKBINARY} '{ if ($5=="security" || $7=="security") { print $NF }}' | ${SEDBINARY} 's/:$//' | ${GREPBINARY} -v "^$" | ${SORTBINARY} -u)
            LogText "存在漏洞的软件包/版本列表："
            for PKG in ${FIND}; do
                VULNERABLE_PACKAGES_FOUND=1
                Report "vulnerable_package[]=${PKG}"
                LogText "存在漏洞的软件包：${PKG}"
                # Decrease hardening points for every found vulnerable package
                AddHP 1 2
            done
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7332
    # Description : Query macOS ports
    if [ -x ${ROOTDIR}opt/local/bin/port ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7332 --os "macOS" --preqs-met ${PREQS_MET} --weight L --network NO --description "查询 macOS ports"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${ROOTDIR}opt/local/bin/port installed 2>&1 | ${GREPBINARY} active | ${SORTBINARY}; ${ROOTDIR}bin/echo $?)
        if [ "${FIND}" = "0" ]; then
            Display --indent 4 --text "- 使用 port 搜索软件包" --result "{STATUS_FOUND}" --color GREEN
            Report "package_manager[]=port"
            PACKAGE_MGR_PKG=1
            LogText "结果：发现 port 工具"
            LogText "检查：查询 port 获取软件包列表"
            Display --indent 6 --text "- 使用 port 查询已安装的软件包"
            LogText "输出："; LogText "-----"
            SPACKAGES=$(${ROOTDIR}opt/local/bin/port installed | ${GREPBINARY} active)
            for ITEM in ${SPACKAGES}; do
                SPORT_NAME=$(echo ${ITEM} | ${CUTBINARY} -d@ -f1)
                SPORT_VERSION=$(echo ${ITEM} | ${CUTBINARY} -d@ -f2 | ${CUTBINARY} -d' ' -f1)
                LogText "已安装的软件包：${SPORT_NAME}（版本：${SPORT_VERSION}）"
                INSTALLED_PACKAGES="${INSTALLED_PORTS}|${ITEM}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7334
    # Description : Query macOS ports for available port upgrades
    if [ -x ${ROOTDIR}opt/local/bin/port ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7334 --os "macOS" --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 port 查询可用升级"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "检查：查询 ports 的可用升级"
        UPACKAGES=$(${ROOTDIR}opt/local/bin/port outdated 2> /dev/null | ${CUTBINARY} -d' ' -f1)
        for J in ${UPACKAGES}; do
            COUNT=$((COUNT + 1))
            LogText "有可用升级（新版本）：${J}"
            Report "upgrade_available[]=${J}"
        done
        Report "upgrade_available_count=${COUNT}"
        if [ ${COUNT} -eq 0 ]; then
            LogText "结果：未发现可用升级"
            Display --indent 2 --text "- 检查 ports 更新" --result "${STATUS_NONE}" --color GREEN
            AddHP 2 2
        else
            Display --indent 2 --text "- 检查 ports 更新" --result "${STATUS_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7345
    # Description : Debian package based systems (dpkg)
    if [ -x ${ROOTDIR}usr/bin/dpkg ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7345 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询 dpkg"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        Display --indent 4 --text "- 搜索 dpkg 软件包管理器" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 dpkg 可执行文件"
        Report "package_manager[]=dpkg"
        PACKAGE_MGR_PKG=1
        LogText "检查：运行 dpkg -l 获取软件包列表"
        Display --indent 6 --text "- 查询软件包管理器"
        LogText "输出："
        SPACKAGES=$(dpkg -l 2>/dev/null | ${GREPBINARY} "^ii" | ${TRBINARY} -s ' ' | ${TRBINARY} ' ' ',' | sort)
        for J in ${SPACKAGES}; do
            COUNT=$((COUNT + 1))
            PACKAGE_NAME=$(echo ${J} | ${CUTBINARY} -d ',' -f2)
            PACKAGE_VERSION=$(echo ${J} | ${CUTBINARY} -d ',' -f3)
            LogText "发现软件包：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION}"
        done
        Report "installed_packages=${COUNT}"
    else
        LogText "结果：此系统上未找到 dpkg，已跳过检查"
    fi
#
#################################################################################
#
    # Test        : PKGS-7346
    # Description : Check packages which are removed, but still own configuration files, cron jobs etc
    # Notes       : Cleanup: for pkg in $(dpkg -l | ${GREPBINARY} "^rc" | ${CUTBINARY} -d' ' -f3); do aptitude purge ${pkg}; done
    if [ -x ${ROOTDIR}usr/bin/dpkg ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7346 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "搜索系统中未彻底清除的软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "检查：运行 dpkg -l 查询未彻底清除的软件包"
        SPACKAGES=$(${ROOTDIR}usr/bin/dpkg -l 2>/dev/null | ${GREPBINARY} "^rc" | ${CUTBINARY} -d ' ' -f3 | sort)
        if [ -z "${SPACKAGES}" ]; then
            Display --indent 4 --text "- 查询未彻底清除的软件包" --result "${STATUS_NONE}" --color GREEN
            LogText "结果：未发现遗留文件的软件包"
        else
            Display --indent 4 --text "- 查询未彻底清除的软件包" --result "${STATUS_FOUND}" --color YELLOW
            LogText "结果：发现一个或多个软件包仍遗留配置文件、cron 任务等内容"
            LogText "输出："
            for J in ${SPACKAGES}; do
                COUNT=$((COUNT + 1))
                LogText "发现未彻底清除的软件包：${J}"
            done
            ReportSuggestion "${TEST_NO}" "使用 aptitude purge 或 dpkg --purge 清除旧的/已删除的软件包（发现 ${COUNT} 个），以移除旧配置文件、cron 任务和启动脚本。"
        fi
    else
        LogText "结果：此系统上未找到 dpkg，已跳过检查"
    fi
#
#################################################################################
#
    # Test        : PKGS-7348
    # Description : Show unneeded distfiles if present
    # Notes       : Portsclean seems to be gone from the ports, so no suggestion or warning is
    #               issued when it's missing.
    #               Add portmaster --clean-distfiles-all
    Register --test-no PKGS-7348 --os FreeBSD --weight L --network NO --category security --description "检查旧的 distfiles"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -x ${ROOTDIR}usr/local/sbin/portsclean ]; then
            FIND=$(${ROOTDIR}usr/local/sbin/portsclean -n -DD | ${GREPBINARY} 'Delete' | wc -l | ${TRBINARY} -d ' ')
            if [ ${FIND} -eq 0 ]; then
                Display --indent 2 --text "- 检查旧 distfiles" --result "${STATUS_OK}" --color GREEN
                LogText "结果：未发现未使用的 distfiles"
            else
                Display --indent 2 --text "- 检查旧 distfiles" --result "${STATUS_WARNING}" --color YELLOW
                LogText "结果：发现 ${FIND} 个未使用的 distfiles"
                ReportSuggestion "${TEST_NO}" "发现未使用的 distfiles，请使用 portsclean 删除，例如：portsclean -DD。"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7350
    # Description : Use Dandified YUM to gather installed packages
    # Notes       : Possible replacement for YUM in the long term
    if [ -n "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no "PKGS-7350" --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 DNF 检查已安装的软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        Display --indent 4 --text "- 搜索 DNF 软件包管理器" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 DNF 工具（可执行文件：${DNFBINARY}）"
        Report "package_manager[]=dnf"
        Display --indent 6 --text "- 查询 DNF 软件包管理器"

        PACKAGE_AUDIT_TOOL_FOUND=1
        PACKAGE_AUDIT_TOOL="dnf"
        SPACKAGES=$(${DNFBINARY} -q list installed 2> /dev/null | ${AWKBINARY} '{ if ($1!="Installed" && $1!="Last") {print $1","$2 }}')
        for PKG in ${SPACKAGES}; do
            COUNT=$((COUNT + 1))
            PACKAGE_NAME=$(echo ${PKG} | ${CUTBINARY} -d ',' -f1)
            PACKAGE_VERSION=$(echo ${PKG} | ${CUTBINARY} -d ',' -f2)
            LogText "发现软件包：${PACKAGE_NAME}（版本：${PACKAGE_VERSION}）"
            INSTALLED_PACKAGES="${INSTALLED_PACKAGES}|${PACKAGE_NAME},${PACKAGE_VERSION}"
        done
        Report "installed_packages=${COUNT}"
    fi
#
#################################################################################
#
    # Test        : PKGS-7352
    # Description : Use Dandified YUM to detect security updates
    if [ -n "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no "PKGS-7352" --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 DNF 检查安全更新"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check for security updates
        LogText "操作：检查 updateinfo 中的安全更新"
        FIND=$(${DNFBINARY} -q updateinfo list sec 2> /dev/null | ${AWKBINARY} '{ if ($2=="security") { print $3 }}')
        if [ -n "${FIND}" ]; then
            VULNERABLE_PACKAGES_FOUND=1
            LogText "结果：发现存在漏洞的软件包，需要升级系统。"
            for PKG in ${FIND}; do
                Report "vulnerable_package[]=${PKG}"
                LogText "存在漏洞的软件包：${PKG}"
                # Decrease hardening points for every found vulnerable package
                AddHP 1 2
            done
            ReportWarning "${TEST_NO}" "发现一个或多个存在漏洞的软件包。请运行：dnf upgrade"
            Display --indent 2 --text "- 使用 DNF 查找存在漏洞的软件包" --result "${STATUS_WARNING}" --color RED
        else
            LogText "结果：未发现安全更新"
            Display --indent 2 --text "- 使用 DNF 查找存在漏洞的软件包" --result "${STATUS_NONE}" --color GREEN
            AddHP 5 5
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7354
    # Description : Perform integrity tests for package database
    if [ -n "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no "PKGS-7354" --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查软件包数据库完整性"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if repoquery plugin is available
        FIND=$(${DNFBINARY} 2>&1 | ${GREPBINARY} "^repoquery")
        if [ -n "${FIND}" ]; then
            LogText "操作：检查软件包数据库完整性"
            FIND=$(${DNFBINARY} -q repoquery --duplicated)
            if [ -n "${FIND}" ]; then
                LogText "结果：repoquery --duplicated 返回异常结果"
                ReportSuggestion "${TEST_NO}" "检查命令输出：dnf repoquery --duplicated"
            fi
            FIND=$(${DNFBINARY} -q repoquery --unsatisfied)
            if [ -n "${FIND}" ]; then
                LogText "结果：repoquery --unsatisfied 返回异常结果"
                ReportSuggestion "${TEST_NO}" "检查命令输出：dnf repoquery --unsatisfied"
            fi
        else
            LogText "结果：未安装 repoquery 插件。"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7366
    # Description : Checking if debsecan is installed and enabled on Debian systems
    if [ -n "${DEBSECANBINARY}" ] && ( [ "${LINUX_VERSION}" = "Debian" ] || [ "${LINUX_VERSION_LIKE}" = "Debian" ] ); then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no "PKGS-7366" --preqs-met ${PREQS_MET} --os Linux --weight L --network NO --category security --description "检查 debsecan 工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${DEBSECANBINARY}" ]; then
            LogText "结果：已安装 debsecan 工具"
            Display --indent 4 --text "- debsecan 工具" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
            PACKAGE_AUDIT_TOOL_FOUND=1
            PACKAGE_AUDIT_TOOL="debsecan"
            FIND=$(${FINDBINARY} ${ROOTDIR}etc/cron* -name debsecan)
            if [ -n "${FIND}" ]; then
                LogText "结果：已为 debsecan 配置 cron 任务"
                Display --indent 6 --text "- debsecan cron 任务" --result "${STATUS_FOUND}" --color GREEN
                AddHP 3 3
            else
                LogText "结果：未为 debsecan 配置 cron 任务"
                Display --indent 4 --text "- debsecan cron 任务" --result "${STATUS_NOT_FOUND}" --color YELLOW
                AddHP 1 3
                ReportSuggestion "${TEST_NO}" "检查 debsecan 的 cron 任务并确保已启用"
            fi
        else
            LogText "结果：未安装 debsecan。"
            Display --indent 4 --text "- debsecan 工具" --result "${STATUS_NOT_FOUND}" --color YELLOW
            AddHP 0 2
            ReportSuggestion "${TEST_NO}" "安装 debsecan 以检查已安装软件包中的漏洞。"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7370
    # Description : Checking debsums installation status and presence in cron job
    # Note        : Run this only when it is a DPKG based system
    if [ -n "${DPKGBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no "PKGS-7370" --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 debsums 工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${DEBSUMSBINARY}" ]; then
            LogText "结果：已安装 debsums 工具"
            Display --indent 4 --text "- debsums 工具" --result "${STATUS_FOUND}" --color GREEN
            AddHP 1 1
            # Check in /etc/cron.hourly, daily, weekly, monthly etc
            COUNT=$(find /etc/cron* -name debsums | wc -l)
            if [ ${COUNT} -gt 0 ]; then
                CRON_CHECK=""
                if [ -f ${ROOTDIR}etc/default/debsums ]; then
                    CRON_CHECK=$(${GREPBINARY} CRON_CHECK /etc/default/debsums|${AWKBINARY} -F "=" '{print $2}')
                fi
                if [ "${CRON_CHECK}" = "daily" ] || [ "${CRON_CHECK}" = "weekly" ] || [ "${CRON_CHECK}" = "monthly" ]; then
                    LogText "结果：已为 debsums 配置 cron 任务。"
                    Display --indent 6 --text "- debsums 的 cron 任务" --result "${STATUS_FOUND}" --color GREEN
                    AddHP 3 3
                else
                    LogText "结果：未为 debsums 配置 cron 任务。"
                    Display --indent 6 --text "- debsums 的 cron 任务" --result "${STATUS_NOT_FOUND}" --color YELLOW
                    AddHP 1 3
                    ReportSuggestion "${TEST_NO}" "检查 debsums 配置，并通过 cron 任务定期执行检查（默认文件中的 CRON_CHECK）。"
                fi
            else
                LogText "结果：未为 debsums 配置 cron 任务。"
                Display --indent 6 --text "- debsums 的 cron 任务" --result "${STATUS_NOT_FOUND}" --color YELLOW
                AddHP 1 3
                ReportSuggestion "${TEST_NO}" "检查 debsums 配置，并通过 cron 任务定期执行检查。"
            fi
        else
            LogText "结果：未安装 debsums 工具。"
            AddHP 0 2
            ReportSuggestion "${TEST_NO}" "安装 debsums，以使用已知可信数据库验证软件包。"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7378
    # Description : Query FreeBSD portmaster for available port upgrades
    if [ -x ${ROOTDIR}usr/local/sbin/portmaster ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7378 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 portmaster 查询 port 升级"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "检查：查询 portmaster 的可用升级"
        UPACKAGES=$(${ROOTDIR}usr/local/sbin/portmaster -L | ${GREPBINARY} "version available" | ${AWKBINARY} '{ print $5 }')
        for PKG in ${UPACKAGES}; do
            COUNT=$((COUNT + 1))
            LogText "有可用升级（新版本）：${PKG}"
            Report "upgrade_available[]=${PKG}"
        done
        Report "upgrade_available_count=${COUNT}"
        if [ ${COUNT} -eq 0 ]; then
            LogText "结果：未发现更新"
            Display --indent 2 --text "- 使用 portmaster 检查更新" --result "${STATUS_NONE}" --color GREEN
        else
            LogText "结果：发现 ${COUNT} 个更新"
            Display --indent 2 --text "- 使用 portmaster 检查更新" --result "${STATUS_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7380
    # Description : Check for vulnerable NetBSD packages (with pkg_admin)
    Register --test-no PKGS-7380 --os NetBSD --weight L --network NO --category security --description "检查存在漏洞的 NetBSD 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -x ${ROOTDIR}usr/sbin/pkg_admin ]; then
            PACKAGE_AUDIT_TOOL_FOUND=1
            PACKAGE_AUDIT_TOOL="pkg_admin audit"
            if [ -f ${ROOTDIR}var/db/pkg/pkg-vulnerabilities ]; then
                FIND=$(${ROOTDIR}usr/sbin/pkg_admin audit)
                if [ -z "${FIND}" ]; then
                    LogText "结果：pkg_admin audit 检查结果正常"
                    Display --indent 2 --text "- 使用 pkg_admin audit 检查漏洞软件包" --result "${STATUS_NONE}" --color GREEN
                    AddHP 10 10
                else
                    Display --indent 2 --text "- 使用 pkg_admin audit 检查漏洞软件包" --result "${STATUS_WARNING}" --color RED
                    LogText "结果：pkg_admin audit 发现一个或多个已安装软件包存在漏洞。"
                    ReportWarning "${TEST_NO}" "发现一个或多个存在漏洞的软件包。"
                    LogText "存在漏洞的软件包/版本列表："
                    for I in $(${ROOTDIR}usr/sbin/pkg_admin audit | ${AWKBINARY} '{ print $2 }' | ${SORTBINARY} -u); do
                        VULNERABLE_PACKAGES_FOUND=1
                        Report "vulnerable_package[]=${I}"
                        LogText "存在漏洞的软件包：${I}"
                        # Decrease hardening points for every found vulnerable package
                        AddHP 1 2
                    done
                fi
            else
                ReportSuggestion "${TEST_NO}" "使用 pkg_admin fetch-pkg-vulnerabilities 获取漏洞数据库"
                AddHP 0 2
            fi
        else
            Display --indent 2 --text "- 未安装 pkg_admin audit" --result "${STATUS_NOT_FOUND}" --color WHITE
            LogText "结果：未安装 pkg_admin audit，跳过此漏洞检查。"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7381
    # Description : Check for vulnerable FreeBSD packages (with pkg)
    # Notes       : Related vulnerability file is /var/db/pkg/vuln.xml
    # TODO        : Run this in any jail
    if [ -n "${PKG_BINARY}" ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="pkg 工具不可用"; fi
    Register --test-no PKGS-7381 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "使用 pkg 检查存在漏洞的 FreeBSD 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        PACKAGE_AUDIT_TOOL_FOUND=1
        PACKAGE_AUDIT_TOOL="pkg audit"
        if [ -f ${ROOTDIR}var/db/pkg/vuln.xml ]; then
            # Query pkg audit, with optional refresh of vulnerability data (-F)
            if [ ${REFRESH_REPOSITORIES} -eq 1 ]; then
                FIND=$(${PKG_BINARY} audit -F -q 2> /dev/null)
            else
                FIND=$(${PKG_BINARY} audit -q 2> /dev/null)
            fi
            if [ $? -eq 0 ]; then
                LogText "结果：pkg audit 检查结果正常"
                Display --indent 2 --text "- 使用 pkg audit 检查漏洞软件包" --result "${STATUS_NONE}" --color GREEN
                AddHP 10 10
            elif [ $? -eq 1 ]; then
                if [ -n "${FIND}" ]; then
                    VULNERABLE_PACKAGES_FOUND=1
                    Display --indent 2 --text "- 使用 pkg audit 检查漏洞软件包" --result "${STATUS_FOUND}" --color YELLOW
                    for ITEM in ${FIND}; do
                        COUNT=$((COUNT + 1))
                        Report "vulnerable_package[]=${ITEM}"
                        LogText "漏洞包：${ITEM}"
                        AddHP 1 2
                    done
                    ReportWarning "${TEST_NO}" "发现存在漏洞的软件包" "${COUNT} 个存在漏洞的软件包" "text:运行 pkg audit"
                else
                    LogText "结果：退出码大于零，但没有输出"
                fi
            else
                LogText "结果：退出码为 $?"
                ReportException "${TEST_NO}" "pkg audit 返回未知退出码，请在 ${PROJECT_SOURCE} 提交问题"
            fi
        else
            LogText "结果：未找到漏洞数据库"
            ReportWarning "${TEST_NO}" "没有可用的漏洞数据库" "pkg audit" "text:运行 pkg audit -F"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7382
    # Description : Check for vulnerable FreeBSD packages
    # Notes       : Newer machines should use pkg audit instead of portaudit
    if [ -x ${ROOTDIR}usr/local/sbin/portaudit ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7382 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 portaudit 检查存在漏洞的 FreeBSD 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        PACKAGE_AUDIT_TOOL_FOUND=1
        FIND=$(${ROOTDIR}usr/local/sbin/portaudit | ${GREPBINARY} 'problem(s) in your installed packages found' | ${GREPBINARY} -v '0 problem(s) in your installed packages found')
        if [ -z "${FIND}" ]; then
            LogText "结果：Portaudit 检查结果正常"
            Display --indent 2 --text "- 使用 portaudit 检查漏洞软件包" --result "${STATUS_NONE}" --color GREEN
            AddHP 10 10
        else
            Display --indent 2 --text "- 使用 portaudit 检查漏洞" --result "${STATUS_WARNING}" --color RED
            LogText "结果：Portaudit 发现一个或多个已安装软件包存在漏洞。"
            ReportWarning "${TEST_NO}" "发现一个或多个存在漏洞的软件包。"
            ReportSuggestion "${TEST_NO}" "使用 portupgrade 或其他工具更新系统"
            LogText "存在漏洞的软件包/版本列表："
            for PKG in $(${ROOTDIR}usr/local/sbin/portaudit | ${GREPBINARY} "Affected package" | ${CUTBINARY} -d ' ' -f3 | ${SORTBINARY} -u); do
                VULNERABLE_PACKAGES_FOUND=1
                Report "vulnerable_package[]=${PKG}"
                LogText "存在漏洞的软件包：${PKG}"
                # Decrease hardening points for every found vulnerable package
                AddHP 1 2
            done
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7383
    # Description : Check for YUM package Update management
    # Notes       : Skip if DNF is used as package manager
    if [ -n "${YUMBINARY}" -a -z "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7383 --preqs-met ${PREQS_MET} --os Linux --weight M --network NO --category security --description "检查 YUM 软件包更新管理"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：YUM 软件包更新管理"
        FIND=$(${YUMBINARY} repolist 2>/dev/null | ${GREPBINARY} repolist | ${SEDBINARY} 's/[[:blank:]]//g' | ${SEDBINARY} 's/[,.]//g' | ${AWKBINARY} -F ":" '{print $2}' | ${GREPBINARY} -E "^[0-9]+$")
        if [ -z "${FIND}" -o "${FIND}" = "0" ]; then
            LogText "结果：YUM 软件包更新管理检查失败"
            Display --indent 2 --text "- YUM 软件包管理一致性" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "YUM 未正确配置或未在此平台注册（未找到仓库列表）"
        else
            LogText "结果：YUM 软件仓库可用（${FIND}）"
            Display --indent 2 --text "- YUM 软件包管理一致性" --result "${STATUS_OK}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7384
    # Description : Search for YUM utils package
    if [ -n "${YUMBINARY}" -a -z "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7384 --preqs-met ${PREQS_MET} --os Linux --weight L --network NO --category security --description "检查 YUM utils 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        # package-cleanup tool can be found in different locations
        if [ -x ${ROOTDIR}bin/package-cleanup -o -x ${ROOTDIR}usr/bin/package-cleanup ]; then
            LogText "结果：发现 YUM utils 软件包（package-cleanup）"
            # Check for duplicates
            LogText "检查：检查重复软件包"
            FIND=$(package-cleanup -q --dupes > /dev/null; echo $?)
            if [ "${FIND}" = "0" ]; then
                LogText "结果：未发现重复软件包"
                Display --indent 2 --text "- 检查软件包数据库中的重复项" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果：发现一个或多个重复软件包"
                Display --indent 2 --text "- 检查软件包数据库中的重复项" --result "${STATUS_WARNING}" --color RED
                ReportWarning "${TEST_NO}" "发现一个或多个重复安装的软件包"
                ReportSuggestion "${TEST_NO}" "运行 package-cleanup 解决重复软件包问题"
            fi

            # Check for package database problems
            LogText "检查：检查软件包数据库问题"
            FIND=$(package-cleanup --problems > /dev/null; echo $?)
            if [ "${FIND}" = "0" ]; then
                LogText "结果：未发现软件包数据库问题"
                Display --indent 2 --text "- 检查软件包数据库问题" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果：软件包数据库中发现一个或多个问题"
                Display --indent 2 --text "- 检查软件包数据库问题" --result "${STATUS_WARNING}" --color RED
                ReportWarning "${TEST_NO}" "软件包数据库中发现一个或多个问题"
                ReportSuggestion "${TEST_NO}" "运行 package-cleanup 解决软件包问题"
            fi
        else
            Display --indent 2 --text "- 未安装 yum-utils 软件包" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "结果：未找到 YUM utils 软件包"
            ReportSuggestion "${TEST_NO}" "安装 yum-utils 软件包，以更好地检查软件包数据库一致性"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7386
    # Description : Search for YUM security package
    # Notes       : This test does not apply to CentOS and clones, as --security is not available
    #             : RHEL 7: plugin default installed
    #             : RHEL 6: yum-security-plugin (plugin)
    #             : RHEL 5: yum-security (plugin)
    if [ -x ${ROOTDIR}usr/bin/yum -a -z "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7386 --preqs-met ${PREQS_MET} --os Linux --weight L --network NO --category security --description "检查 YUM security 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        DO_TEST=0
        LogText "检查：确认是否安装 yum-security 软件包"

        # Check for built-in --security option
        if [ ${DO_TEST} -eq 0 ]; then
            FileExists ${ROOTDIR}usr/share/yum-cli/cli.py
            if [ ${FILE_FOUND} -eq 1 ]; then
                if SearchItem "\-\-security" "${ROOTDIR}usr/share/yum-cli/cli.py"; then
                    DO_TEST=1
                    LogText "结果：发现 yum 内置的 security 支持"
                else
                    LogText "结果：在 ${ROOTDIR}usr/share/yum-cli/cli.py 中未找到 --security"
                fi
            fi
        fi

        if [ ${DO_TEST} -eq 0 ]; then
            FileExists ${ROOTDIR}etc/yum/pluginconf.d/security.conf
            if [ ${FILE_FOUND} -eq 1 ]; then
                if SearchItem "^enabled=1$" "${ROOTDIR}etc/yum/pluginconf.d/security.conf"; then
                    DO_TEST=1
                    LogText "结果：发现已启用的插件"
                else
                    LogText "结果：${ROOTDIR}etc/yum/pluginconf.d/security.conf 中的插件未启用"
                fi
            fi
        fi

        # Check if it's installed as package (this is old style)
        if [ ${DO_TEST} -eq 0 ]; then
            FIND=$(rpm -q yum-security yum-plugin-security | ${GREPBINARY} -v "not installed")
            if [ -n "${FIND}" ]; then
                LogText "结果：发现 yum-plugin-security 软件包"
                DO_TEST=1
            fi
        fi

        # If we have the module of yum active, continue testing
        if [ ${DO_TEST} -eq 1 ]; then
            PACKAGE_AUDIT_TOOL_FOUND=1
            PACKAGE_AUDIT_TOOL="yum-security"
            LogText "检查：检查存在漏洞的软件包"
            FIND2=$(${ROOTDIR}usr/bin/yum list-sec security | ${AWKBINARY} '{ if($2=="security" || $2~"Sec") print $3","$5 }')
            if [ -z "${FIND2}" ]; then
                LogText "结果：未发现存在漏洞的软件包"
                Display --indent 2 --text "- 检查缺失的安全软件包" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果：发现存在漏洞的软件包"
                Display --indent 2 --text "- 检查缺失的安全软件包" --result "${STATUS_WARNING}" --color RED
                for I in ${FIND2}; do
                    VULNERABLE_PACKAGES_FOUND=1
                    Report "vulnerable_package[]=${I}"
                    LogText "存在漏洞的软件包：${I}"
                    AddHP 1 2
                done
                ReportWarning "${TEST_NO}" "发现一个或多个存在漏洞的软件包。"
            fi
        else
            LogText "结果：未找到 yum-security 软件包"
            Display --indent 2 --text "- 检查缺失的安全软件包" --result "${STATUS_SKIPPED}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "尽可能安装 yum-plugin-security，以便更容易维护安全更新（yum install yum-plugin-security）"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7387
    # Description : Search for YUM GPG check
    if [ -x ${ROOTDIR}usr/bin/yum -a -z "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7387 --preqs-met ${PREQS_MET} --os Linux --weight L --network NO --category security --description "检查 YUM 软件仓库的 GPG 签名"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${PYTHONBINARY}" ]; then
            LogText "检查：检查已启用的软件仓库"
            REPOS=$(${PYTHONBINARY} -c 'import yum ; yb = yum.YumBase() ; yb.conf ; print [(r.id + "=" + str(r.gpgcheck)) for r in yb.repos.listEnabled()]' | ${GREPBINARY} "^\[" | ${TRBINARY} -d '[] ' | ${TRBINARY} -d "'" | ${SEDBINARY} 's/,/ /g')
            if [ -z "${REPOS}" ]; then LogText "结果：未发现软件仓库"; fi
            for I in ${REPOS}; do
                REPO=$(echo ${I} | ${AWKBINARY} -F= '{print $1}')
                GPGSIGNED=$(echo ${I} | ${AWKBINARY} -F= '{print $2}')
                if [ "${GPGSIGNED}" = "False" ]; then
                    LogText "结果：软件仓库 ${REPO} 未签名"
                    Report "software_repository_unsigned[]=${REPO}"
                    AddHP 3 4
                elif [ "${GPGSIGNED}" = "True" ]; then
                    LogText "结果：软件仓库 ${REPO} 已签名"
                    AddHP 4 4
                else
                    LogText "结果：软件仓库状态未知（数据：${I}）"
                fi
            done
        fi
        FOUND=0
        FileExists ${ROOTDIR}etc/yum.conf
        if [ ${FILE_FOUND} -eq 1 ]; then
            if SearchItem "^gpgenabled\s*=\s*1$" "${ROOTDIR}etc/yum.conf"; then FOUND=1; fi
            if SearchItem "^gpgcheck\s*=\s*1$" "${ROOTDIR}etc/yum.conf"; then FOUND=1; fi
            if [ ${FOUND} -eq 1 ]; then
                LogText "结果：已启用 GPG 检查"
                Display --indent 2 --text "- 检查 GPG 验证（yum.conf）" --result "${STATUS_OK}" --color GREEN
                AddHP 3 3
            else
                Display --indent 2 --text "- 检查 GPG 验证（yum.conf）" --result "${STATUS_DISABLED}" --color RED
                ReportWarning "${TEST_NO}" "yum.conf 中未找到 GPG 签名选项"
                AddHP 2 3
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7388
    # Description : Check security repository in Debian/Ubuntu apt sources.list file
    PREQS_MET="NO"
    if [ -f ${ROOTDIR}etc/apt/sources.list -a -d ${ROOTDIR}etc/apt/sources.list.d ]; then
        case "${LINUX_VERSION}" in
            "Debian" | "Linux Mint" | "Ubuntu" | "Pop!_OS")
                # Todo: PureOS (not rolling) has security repositories
                # Todo: Debian sid does not have a security repository.
                PREQS_MET="YES"
            ;;
            *)
                LogText "跳过检查：虽然存在 sources.list 或 sources.list.d，但此操作系统版本很可能没有专用安全仓库"
            ;;
        esac
    fi
    Register --test-no PKGS-7388 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 apt sources.list 中的安全软件仓库"
    if [ $SKIPTEST -eq 0 ]; then
        FOUND=0
        if [ ${OPTION_DEBIAN_SKIP_SECURITY_REPOSITORY} -eq 0 ]; then
            if [ -f ${ROOTDIR}etc/apt/sources.list ]; then
                LogText "在 /etc/apt/sources.list 中搜索 security.debian.org、security.ubuntu.com 或其他安全仓库"
                FIND=$(${GREPBINARY} -E "security.debian.org|security.ubuntu.com|security/? " ${ROOTDIR}etc/apt/sources.list | ${GREPBINARY} -v '#' | ${SEDBINARY} 's/ /!space!/g')
                if [ -n "${FIND}" ]; then
                    FOUND=1
                    Display --indent 2 --text "- 检查 sources.list 中的安全仓库" --result "${STATUS_OK}" --color GREEN
                    LogText "结果：在 ${ROOTDIR}etc/apt/sources.list 中发现安全仓库"
                    for REPO in ${FIND}; do
                        REPO=$(echo ${REPO} | ${SEDBINARY} 's/!space!/ /g')
                        LogText "输出： ${REPO}"
                    done
                fi
            fi
            if [ -d /etc/apt/sources.list.d ]; then
                LogText "在 /etc/apt/sources.list.d 目录中搜索 security.debian.org、security.ubuntu.com 或其他安全仓库"
                FIND=$(${GREPBINARY} -E -r "security.debian.org|security.ubuntu.com|security/? " /etc/apt/sources.list.d | ${GREPBINARY} -v '#' | ${SEDBINARY} 's/ /!space!/g')
                if [ -n "${FIND}" ]; then
                    FOUND=1
                    Display --indent 2 --text "- 检查 sources.list.d 中的安全仓库" --result "${STATUS_OK}" --color GREEN
                    LogText "结果：在 /etc/apt/sources.list.d 的一个或多个文件中发现安全仓库"
                    for REPO in ${FIND}; do
                        REPO=$(echo ${REPO} | ${SEDBINARY} 's/!space!/ /g')
                        LogText "输出： ${REPO}"
                    done
                fi
            fi
            if [ ${FOUND} -eq 1 ]; then
                LogText "结果：发现安全软件仓库"
                AddHP 3 3
            else
                Display --indent 2 --text "- 检查 sources.list 中的安全仓库 or directory" --result "${STATUS_WARNING}" --color RED
                ReportWarning "${TEST_NO}" "在 /etc/apt/sources.list 或 sources.list.d 目录中未找到安全仓库"
                AddHP 0 3
            fi
        else
            LogText "已跳过：配置为忽略安全软件仓库检查"
        fi
        unset FIND FOUND REPO
    fi
#
#################################################################################
#
    # Test        : PKGS-7390
    # Description : Check Ubuntu database consistency
    if ([ "${LINUX_VERSION}" = "Debian" ] || [ "${LINUX_VERSION}" = "Ubuntu" ] ||
           [ "${LINUX_VERSION_LIKE}" = "Debian" ] ||  [ "${LINUX_VERSION_LIKE}" = "Ubuntu" ]) && [ -x "${ROOTDIR}usr/bin/apt-get" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi

    Register --test-no PKGS-7390 --os Linux --preqs-met ${PREQS_MET} --root-only YES --weight L --network NO --category security --description "检查 Ubuntu 软件包数据库一致性"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：运行 apt-get check 检查软件包数据库一致性"
        FIND=$(${ROOTDIR}usr/bin/apt-get -q=2 check 2> /dev/null; echo $?)
        if [ "${FIND}" = "0" ]; then
            Display --indent 2 --text "- 检查 APT 软件包数据库" --result "${STATUS_OK}" --color GREEN
            LogText "结果：软件包数据库看起来一致。"
        else
            LogText "结果：软件包数据库很可能不一致"
            Display --indent 2 --text "- 检查 APT 软件包数据库" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "apt-get check 返回了非成功退出码。"
            ReportSuggestion "${TEST_NO}" "运行 apt-get 手动检查软件包数据库一致性。"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7392
    # Description : Check Debian/Ubuntu vulnerable packages
    # Note        : Skip for zypper-based systems
    if [ -x ${ROOTDIR}usr/bin/apt-get -a -z "${ZYPPERBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7392 --os Linux --preqs-met ${PREQS_MET} --root-only YES --weight L --network YES --category security --description "检查 Debian/Ubuntu 安全更新"
    if [ ${SKIPTEST} -eq 0 ]; then
        VULNERABLE_PACKAGES_FOUND=0
        SCAN_PERFORMED=0
        # If apt-get is installed, then it's a reasonable option for a Package Audit tool
        # If apt-check exists, it will be preferred and will overwrite the PACKAGE_AUDIT_TOOL setting
        PACKAGE_AUDIT_TOOL="apt-get"
        PACKAGE_AUDIT_TOOL_FOUND=1
        # Update the repository, outdated repositories don't give much information
        if [ ${REFRESH_REPOSITORIES} -eq 1 ]; then
            LogText "操作：使用 apt-get 更新软件仓库"
            ${ROOTDIR}usr/bin/apt-get -q=2 update
            LogText "结果：apt-get 执行完成"
        else
            LogText "结果：配置已禁用仓库更新，当前使用的软件仓库信息可能已过期"
        fi
        LogText "检查：确认 ${ROOTDIR}usr/lib/update-notifier/apt-check 是否存在"
        if [ -x ${ROOTDIR}usr/lib/update-notifier/apt-check ]; then
            PACKAGE_AUDIT_TOOL="apt-check"
            LogText "结果：发现 ${ROOTDIR}usr/lib/update-notifier/apt-check"
            LogText "检查：确认可用更新中是否包含安全更新"
            # apt-check binary is a script and translated. Do not search for normal text strings, but use numbered output only
            # We search for the lines that start with a number, as on Ubuntu 24.04 an error can happen:
            # Warning: W:Unable to read /var/lib/ubuntu-advantage/apt-esm/etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
            FIND=$(${ROOTDIR}usr/lib/update-notifier/apt-check 2>&1 | ${GREPBINARY} '^[0-9]' | ${AWKBINARY} -F\; '{ print $2 }')
            # Check if we get the proper line back and amount of security patches available
            if [ -z "${FIND}" ]; then
                LogText "结果：未找到安全更新结果行"
                ReportSuggestion "${TEST_NO}" "检查系统是否为最新状态；安全更新检查 apt-check 返回了异常结果"
                ReportException "${TEST_NO}:1" "apt-check 未返回任何结果"
            else
                if [ "${FIND}" = "0" ]; then
                    LogText "结果：apt-check 未发现存在漏洞的软件包"
                    SCAN_PERFORMED=1
                else
                    VULNERABLE_PACKAGES_FOUND=1
                    SCAN_PERFORMED=1
                    LogText "结果：apt-check 发现 ${FIND} 个安全更新"
                    AddHP 0 25
                fi
            fi
        else
            LogText "结果：未找到 apt-check（update-notifier-common）"
        fi

        # Trying also with apt-get directly (does not always work, as updates are distributed on both -security and -updates)
        # Show packages which would be upgraded and match 'security' in repository name
        FIND=$(${ROOTDIR}usr/bin/apt-get --dry-run --show-upgraded upgrade 2> /dev/null | ${GREPBINARY} '-security' | ${GREPBINARY} "^Inst" | ${CUTBINARY} -d ' ' -f2 | ${SORTBINARY} -u)
        if [ -n "${FIND}" ]; then
            VULNERABLE_PACKAGES_FOUND=1
            SCAN_PERFORMED=1
            LogText "结果：apt-get 在 -security 渠道中发现存在漏洞的软件包"
            PACKAGE_AUDIT_TOOL="apt-get"
            PACKAGE_AUDIT_TOOL_FOUND=1
            for PKG in ${FIND}; do
                LogText "发现存在漏洞的软件包：${PKG}"
                Report "vulnerable_package[]=${PKG}"
            done
        fi
        if [ ${SCAN_PERFORMED} -eq 1 ]; then
            if [ ${VULNERABLE_PACKAGES_FOUND} -eq 1 ]; then
                ReportWarning "${TEST_NO}" "发现一个或多个存在漏洞的软件包。"
                ReportSuggestion "${TEST_NO}" "使用 apt-get update、apt-get upgrade、apt-get dist-upgrade 和/或 unattended-upgrades 更新系统"
                Display --indent 2 --text "- 检查存在漏洞的软件包" --result "${STATUS_WARNING}" --color RED
            else
                Display --indent 2 --text "- 检查存在漏洞的软件包" --result "${STATUS_OK}" --color GREEN
                LogText "结果：未发现存在漏洞的软件包"
            fi
        else
            Display --indent 2 --text "- 检查存在漏洞的软件包 (apt-get only)" --result "${STATUS_DONE}" --color GREEN
            LogText "结果：检查未完整执行（缺少 apt-check 输出）"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7393
    # Description : Check Gentoo vulnerable packages
    if [ -x ${ROOTDIR}usr/bin/emerge-webrsync ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PKGS-7393 --preqs-met ${PREQS_MET} --weight L --network YES --category security --description "检查存在漏洞的 Gentoo 软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        VULNERABLE_PACKAGES_FOUND=0
        SCAN_PERFORMED=0
        # Update portage.
        # Multiple ways to do this.  Some require extra packages to be installed,
        # others require potential firewall ports to be open, outbound.  This is the
        # "most friendly" way.
        if [ ${REFRESH_REPOSITORIES} -eq 1 ]; then
            LogText "操作：使用 emerge-webrsync 更新 Portage"
            ${ROOTDIR}usr/bin/emerge-webrsync --quiet 2> /dev/null
            LogText "结果：emerge-webrsync 执行完成"
        else
            LogText "结果：仓库更新已禁用，当前仓库信息可能已过期"
        fi
        LogText "检查：确认 ${ROOTDIR}usr/bin/glsa-check 是否存在"
        if [ -x ${ROOTDIR}usr/bin/glsa-check ]; then
            PACKAGE_AUDIT_TOOL_FOUND=1
            PACKAGE_AUDIT_TOOL="glsa-check"
            LogText "结果：发现 ${ROOTDIR}usr/bin/glsa-check"
            LogText "检查：确认是否存在有漏洞的软件包"
            # glsa-check reports the GLSA date/ID string, not the vulnerable package.
            FIND=$(${ROOTDIR}usr/bin/glsa-check -t all 2>&1 | ${GREPBINARY} -v "This system is affected by the following GLSAs:" | ${GREPBINARY} -v "This system is not affected by any of the listed GLSAs" | ${WCBINARY} -l)
            if [ -z "${FIND}" ]; then
                LogText "结果：返回值异常；如果未发现漏洞软件包，wc 应返回 0。"
                LogText "说明：检查系统是否为最新状态；glsa-check 返回了异常结果"
                ReportException "${TEST_NO}:1" "glsa-check 未返回结果，情况异常"
            else
                if [ "${FIND}" = "0" ]; then
                    LogText "结果：glsa-check 未发现存在漏洞的软件包"
                    Display --indent 2 --text "- 检查存在漏洞的软件包 (glsa-check)" --result "${STATUS_OK}" --color GREEN
                else
                    VULNERABLE_PACKAGES_FOUND=1
                    Display --indent 2 --text "- 检查存在漏洞的软件包 (glsa-check)" --result "${STATUS_FOUND}" --color RED
                    LogText "结果：glsa-check 发现 ${FIND} 个安全更新"
                    ReportWarning "${TEST_NO}" "glsa-check 发现 ${FIND} 个安全更新。"
                    LogText "说明：运行 glsa-check -t all 查看识别出的 GLSA。"
                    AddHP 0 25
                fi
            fi
        else
            LogText "结果：未找到 glsa-check 工具"
            ReportSuggestion "${TEST_NO}" "使用 Emerge 安装 gentoolkit 软件包，其中包含 glsa-check，可执行额外的安全检查。"
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7394
    # Description : Check Ubuntu upgradeable packages
    if ([ "${LINUX_VERSION}" = "Debian" ] || [ "${LINUX_VERSION}" = "Ubuntu" ] ||
           [ "${LINUX_VERSION_LIKE}" = "Debian" ] ||  [ "${LINUX_VERSION_LIKE}" = "Ubuntu" ]) && [ -x "${ROOTDIR}usr/bin/apt-get" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi

    Register --test-no PKGS-7394 --os Linux --preqs-met ${PREQS_MET} --weight L --network YES --category security --description "检查 Ubuntu 更新"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 ${ROOTDIR}usr/bin/apt-show-versions"
        if [ -x ${ROOTDIR}usr/bin/apt-show-versions ]; then
            LogText "结果：发现 ${ROOTDIR}usr/bin/apt-show-versions"
            LogText "检查：使用 apt-show-versions 查询可升级的软件包"
            FIND=$(${ROOTDIR}usr/bin/apt-show-versions -u | ${SEDBINARY} 's/ /!space!/g')
            if [ -z "${FIND}" ]; then
                LogText "结果：未发现可升级的软件包"
                Display --indent 2 --text "- 检查可升级的软件包" --result "${STATUS_NONE}" --color GREEN
                AddHP 3 3
            else
                LogText "结果：发现一个或多个可升级的软件包"
                Display --indent 2 --text "- 检查可升级的软件包" --result "${STATUS_FOUND}" --color YELLOW
                # output: program/repository upgradeable from version X to Y
                for ITEM in ${FIND}; do
                    ITEM=$(echo ${ITEM} | ${SEDBINARY} 's/!space!/ /g')
                    LogText "${ITEM}"
                done
            fi
        else
            LogText "结果：未找到 ${ROOTDIR}usr/bin/apt-show-versions"
            Display --indent 2 --text "- 检查可升级的软件包" --result "${STATUS_SKIPPED}" --color WHITE
            ReportSuggestion "${TEST_NO}" "安装 apt-show-versions 软件包以进行补丁管理"
        fi
    fi

#
#################################################################################
#
    # Test        : PKGS-7395
    # Description : Check Alpine upgradeable packages
    if [ "${LINUX_VERSION}" = "Alpine Linux" ]  && [ -x "${ROOTDIR}sbin/apk" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi

    Register --test-no PKGS-7395 --os Linux --preqs-met ${PREQS_MET} --weight L --network YES --category security --description "检查 Alpine 更新"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ ${REFRESH_REPOSITORIES} -eq 1 ]; then
            LogText "操作：使用 apk 更新软件仓库"
            ${ROOTDIR}sbin/apk update
            LogText "结果：apk 执行完成"
        else
            LogText "结果：配置已禁用仓库更新，当前使用的软件仓库信息可能已过期"
        fi
        LogText "检查：使用 apk version -l 查询可升级的软件包"
        FIND=$(${ROOTDIR}sbin/apk version -l '<' | ${GREPBINARY} '<' | ${SEDBINARY} 's/\s\+<\s/</g')
        if [ -z "${FIND}" ]; then
            LogText "结果：未发现可升级的软件包"
            Display --indent 2 --text "- 检查可升级的软件包" --result "${STATUS_NONE}" --color GREEN
            AddHP 3 3
        else
            LogText "结果：发现一个或多个可升级的软件包"
            Display --indent 2 --text "- 检查可升级的软件包" --result "${STATUS_FOUND}" --color YELLOW
            for ITEM in ${FIND}; do
                ITEM=$(echo ${ITEM} | ${SEDBINARY}  -r -e 's/([a-z,A-Z,0-9,_,-,.]{1,250})-([a-z,A-Z,0-9,.]+-r[a-z,A-Z,0-9]+)<([a-z,A-Z,0-9,-,.]+)/\1 from \2 to \3/')
                LogText "${ITEM}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : PKGS-7398
    # Description : Check package audit tool
    Register --test-no PKGS-7398 --weight L --network YES --category security --description "检查软件包审计工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索软件包审计工具"
        if [ ${PACKAGE_AUDIT_TOOL_FOUND} -eq 0 ]; then
            Display --indent 2 --text "- 检查软件包审计工具" --result "${STATUS_NONE}" --color RED
            ReportSuggestion "${TEST_NO}" "安装软件包审计工具，以检测存在漏洞的软件包"
            LogText "结果：未找到软件包审计工具"
        else
            Display --indent 2 --text "- 检查软件包审计工具" --result "${STATUS_INSTALLED}" --color GREEN
            Display --indent 4 --text "发现：${PACKAGE_AUDIT_TOOL}"
            LogText "结果：发现软件包审计工具：${PACKAGE_AUDIT_TOOL}"
        fi
    fi
#
#################################################################################
#
    # Description : HP-UX packages
    # Notes       : swlist -l fileset (|${GREPBINARY} patch) / print_manifest
#
#################################################################################
#
    # Description : AIX patches
    # Notes       : ${ROOTDIR}usr/sbin/instfix -c -i | ${CUTBINARY} -d":" -f1
#
#################################################################################
#
    # Test        : PKGS-7410
    # Description : Count number of installed kernel packages
    Register --test-no PKGS-7410 --weight L --network NO --category security --description "统计已安装的内核软件包"
    if [ ${SKIPTEST} -eq 0 ]; then
        KERNELS=0
        TESTED=0
        LogText "检查：统计已安装的内核软件包数量"

        if [ "${DPKGBINARY}" ]; then
            TESTED=1
            KERNEL_PKG_NAMES="linux-image-[0-9]|raspberrypi-kernel|pve-kernel-[0-9]|linux-odroid-5422"
            KERNELS=$(${DPKGBINARY} -l 2> /dev/null | ${GREPBINARY} -E "${KERNEL_PKG_NAMES}" | ${GREPBINARY} -v ^rc | ${WCBINARY} -l)
            if [ ${KERNELS} -eq 0 ]; then
                LogText "结果：dpkg -l 输出中未发现内核软件包，情况异常"
            elif [ ${KERNELS} -gt 5 ]; then
                LogText "结果：系统中发现超过 5 个内核软件包，可能未定期清理"
                ReportSuggestion "${TEST_NO}" "删除不需要的内核软件包" "${KERNELS} 个内核" "text:检查 dpkg -l 输出，并使用 apt autoremove 清理"
            else
                LogText "结果：系统中发现 ${KERNELS} 个内核软件包，数量正常"
            fi
        fi
        if [ "${RPMBINARY}" ]; then
            TESTED=1
            KERNELS=$(${RPMBINARY} -q kernel 2> /dev/null | ${WCBINARY} -l)
            if [ ${KERNELS} -eq 0 ]; then
                LogText "结果：rpm -q kernel 输出中未发现内核软件包，情况异常"
            elif [ ${KERNELS} -gt 5 ]; then
                LogText "结果：系统中发现超过 5 个内核软件包，可能未定期清理"
                ReportSuggestion "${TEST_NO}" "使用 package-cleanup --old-kernels 删除不需要的内核软件包"
            else
                LogText "结果：系统中发现 ${KERNELS} 个内核软件包，数量正常"
            fi
        fi

        if [ "${ZYPPERBINARY}" ]; then
            TESTED=1
            KERNELS=$(${ZYPPERBINARY} --non-interactive -n se --type package --match-exact --installed-only "kernel-default" 2> /dev/null | ${GREPBINARY} "kernel-default" | ${WCBINARY} -l)
            if [ ${KERNELS} -eq 0 ]; then
                LogText "结果：zypper 输出中未发现内核软件包，情况异常。"
                ReportException "${TEST_NO}" "软件包管理器未找到内核软件包，系统可能使用了不同的内核软件包名称。"
            elif [ ${KERNELS} -gt 3 ]; then
                LogText "结果：系统中发现超过 5 个内核软件包，可能未定期清理"
                ReportSuggestion "${TEST_NO}" "删除不需要的内核软件包"
            else
                LogText "结果：系统中发现 ${KERNELS} 个内核软件包，数量正常"
            fi
        fi

        if [ ${KERNELS} -eq 0 -a ${TESTED} -eq 1 ]; then
            # Only report exception if there are kernels actually there. For example, LXC use the kernel of host system
            case "${OS}" in
                "Linux")
                    case "${CONTAINER_TYPE}" in
                        "LXC")
                            LogText "信息：LXC 与宿主机共享内核，因此跳过后续检查"
                        ;;
                        *)
                            if [ -d "${ROOTDIR}boot" ]; then
                                if [ -z "$(${FINDBINARY} /boot -maxdepth 1 -type f -name 'vmlinuz*' -print -quit)" ]; then
                                    ReportException "${TEST_NO}" "软件包管理器未找到内核软件包"
                                fi
                            fi
                        ;;
                    esac
                ;;
                *)
                    ReportException "${TEST_NO}" "软件包管理器未找到内核软件包"
                ;;
            esac
        fi

        Report "installed_kernel_packages=${KERNELS}"
    fi
#
#################################################################################
#
    # Test        : PKGS-7420
    # Description : Detect toolkit to automatically download and apply upgrades
    Register --test-no PKGS-7420 --weight L --network NO --category security --description "检测自动下载并安装更新的工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        UNATTENDED_UPGRADES_TOOLKIT=0
        UNATTENDED_UPGRADES_TOOL=""
        UNATTENDED_UPGRADES_OPTION_AVAILABLE=0

        case "${OS}" in
            "Linux")
                for DIST in CentOS Debian Fedora RHEL Ubuntu; do
                    if [ "${LINUX_VERSION}" = "${DIST}" ] || [ "${LINUX_VERSION_LIKE}" = "${DIST}" ]; then
                        UNATTENDED_UPGRADES_OPTION_AVAILABLE=1
                    fi
                done

                if [ ${UNATTENDED_UPGRADES_OPTION_AVAILABLE} -eq 1 ]; then
                    # Test available tools for Linux
                    if [ -f "${ROOTDIR}bin/auter" ]; then
                        UNATTENDED_UPGRADES_TOOL="auter"
                        UNATTENDED_UPGRADES_TOOLKIT=1
                        LogText "结果：发现 ${UNATTENDED_UPGRADES_TOOL}"
                        Report "unattended_upgrade_tool[]=${UNATTENDED_UPGRADES_TOOL}"
                    fi
                    if [ -f "${ROOTDIR}sbin/yum-cron" ]; then
                        UNATTENDED_UPGRADES_TOOL="yum-cron"
                        UNATTENDED_UPGRADES_TOOLKIT=1
                        LogText "结果：发现 ${UNATTENDED_UPGRADES_TOOL}"
                        Report "unattended_upgrade_tool[]=${UNATTENDED_UPGRADES_TOOL}"
                    fi
                    if [ -f "${ROOTDIR}usr/bin/dnf-automatic" ]; then
                        UNATTENDED_UPGRADES_TOOL="dnf-automatic"
                        UNATTENDED_UPGRADES_TOOLKIT=1
                        LogText "结果：发现 ${UNATTENDED_UPGRADES_TOOL}"
                        Report "unattended_upgrade_tool[]=${UNATTENDED_UPGRADES_TOOL}"
                    fi
                    if [ -f "${ROOTDIR}usr/bin/unattended-upgrade" ]; then
                        UNATTENDED_UPGRADES_TOOL="unattended-upgrade"
                        UNATTENDED_UPGRADES_TOOLKIT=1
                        LogText "结果：发现 ${UNATTENDED_UPGRADES_TOOL}"
                        Report "unattended_upgrade_tool[]=${UNATTENDED_UPGRADES_TOOL}"
                    fi
                fi
            ;;
        esac

        if [ ${UNATTENDED_UPGRADES_OPTION_AVAILABLE} -eq 1 ]; then
            if [ ${UNATTENDED_UPGRADES_TOOLKIT} -eq 1 ]; then
                AddHP 5 5
                Display --indent 2 --text "- 自动更新工具（${UNATTENDED_UPGRADES_TOOL}）" --result "${STATUS_FOUND}" --color GREEN
            else
                AddHP 1 5
                Display --indent 2 --text "- 自动更新工具" --result "${STATUS_NOT_FOUND}" --color YELLOW
                LogText "结果：未发现自动更新工具"
                ReportSuggestion "${TEST_NO}" "建议使用工具自动安装更新"
            fi
        fi

        Report "unattended_upgrade_option_available=${UNATTENDED_UPGRADES_OPTION_AVAILABLE}"
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
