#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Home directories
#
#################################################################################
#
    InsertSection "${SECTION_HOME_DIRECTORIES}"
#
#################################################################################
#
    # Ignore some top level directories (not the sub directories below)
    IGNORE_HOME_DIRS="/bin /boot /cdrom /dev /etc /home /lib /lib64 /media /mnt
                      /opt /proc /sbin /selinux /srv /sys /tmp /usr /var"
#
#################################################################################
#
    # Test        : HOME-9302
    # Description : Create list with home directories
    Register --test-no HOME-9302 --weight L --network NO --category security --description "创建用户主目录列表"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Read sixth field of /etc/passwd
        LogText "检查：查询 ${ROOTDIR}etc/passwd 以获取用户主目录"
        FIND=$(${AWKBINARY} -F: '{ if ($1 !~ "#") print $6 }' ${ROOTDIR}etc/passwd | ${SORTBINARY} -u)
        for I in ${FIND}; do
            if [ -d ${I} ]; then
                LogText "结果：发现用户主目录 ${I}（目录存在）"
                Report "home_directory[]=${I}"
            else
                LogText "结果：发现用户主目录 ${I}（目录不存在）"
            fi
        done
    fi
#
#################################################################################
#
    # Test        : HOME-9304
    # Description : Check if users' home directories permissions are 750 or more restrictive
    Register --test-no HOME-9304 --weight L --network NO --category security --description "检查用户主目录权限是否为 750 或更严格"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if users' home directories permissions are 750 or more restrictive
        FOUND=0
        USERDATA=$(${GREPBINARY} -E -v '^(daemon|git|halt|root|shutdown|sync)' ${ROOTDIR}etc/passwd | ${AWKBINARY} -F: '($7 !~ "/(false|nologin)$") { print }')
        while read -r LINE; do
            USER=$(echo ${LINE} | ${CUTBINARY} -d: -f1)
            DIR=$(echo ${LINE} | ${CUTBINARY} -d: -f6)
            LogText "检查：用户 ${USER} 的目录 '${DIR}'"
            if [ -d "${DIR}" ]; then
                WRITE_GROUP_PERM=$(${LSBINARY} -ld ${DIR} | ${CUTBINARY} -f1 -d" " | ${CUTBINARY} -c6)
                OTHER_PERMS=$(${LSBINARY} -ld ${DIR} | ${CUTBINARY} -f1 -d" " | ${CUTBINARY} -c8-10)
                if [ ! ${WRITE_GROUP_PERM} = "-" -o ! ${OTHER_PERMS} = "---" ]; then
                    LogText "结果：用户 ${USER} 的主目录 ${DIR} 权限不够严格，应为 750 或更严格。可执行：chmod 750 ${DIR}"
                    FOUND=1
                else
                    LogText "结果：用户 ${USER} 的主目录 ${DIR} 权限正常"
                fi
            fi
        done << EOF
${USERDATA}
EOF

        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 用户主目录权限" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "请检查用户主目录权限，部分目录的权限可能不够严格。"
        else
            Display --indent 2 --text "- 用户主目录权限" --result "${STATUS_OK}" --color GREEN
            LogText "结果：正常，所有用户主目录权限均为 750 或更严格"
        fi
    fi
#
#################################################################################
#
    # Test        : HOME-9306
    # Description : Check if users own their home directories
    Register --test-no HOME-9306 --weight L --network NO --category security --description "检查用户是否拥有各自的主目录"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if users own their home directories
        FOUND=0
        USERDATA=$(${GREPBINARY} -E -v '^(daemon|git|halt|root|shutdown|sync)' ${ROOTDIR}etc/passwd | ${AWKBINARY} -F: '($7 !~ "/(false|nologin)$") { print }')
        while read -r LINE; do
            USER=$(echo ${LINE} | ${CUTBINARY} -d: -f1)
            DIR=$(echo ${LINE} | ${CUTBINARY} -d: -f6)
            LogText "检查：用户 ${USER} 的目录 '${DIR}'"
            if [ -d "${DIR}" ]; then
                OWNER=$(ls -ld ${DIR} | awk -F" " '{ print $3 }')
                if [ ! "${OWNER}" = "${USER}" ]; then
                    LogText "结果：用户 ${USER} 的主目录 ${DIR} 当前属于 ${OWNER}。可执行：chown ${USER} ${DIR}"
                    FOUND=1
                else
                    LogText "结果：用户 ${USER} 的主目录 ${DIR} 所有权正确"
                fi
            fi
        done << EOF
${USERDATA}
EOF

        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 用户主目录所有权" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "请检查用户主目录所有权，部分目录的所有者可能不正确。"
        else
            Display --indent 2 --text "- 用户主目录所有权" --result "${STATUS_OK}" --color GREEN
            LogText "结果：正常，所有用户都拥有各自的主目录"
        fi
    fi
#
#################################################################################
#
    # Test        : HOME-9310
    # Description : Check for suspicious shell history files
    Register --test-no HOME-9310 --weight L --network NO --category security --description "检查可疑的 Shell 历史记录文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${HOMEDIRS}" ]; then
            if [ "${OS}" = "Solaris" ]; then
                # Solaris doesn't support -maxdepth
                FIND=$(${FINDBINARY} ${HOMEDIRS} -name ".*history" ! -type f -print)
            else
                FIND=$(${FINDBINARY} ${HOMEDIRS} -maxdepth 1 -name ".*history" ! -type f -print)
            fi
            if [ -z "${FIND}" ]; then
                Display --indent 2 --text "- 正在检查 Shell 历史记录文件" --result "${STATUS_OK}" --color GREEN
                LogText "结果：正常，历史记录均为普通文件。"
            else
                Display --indent 2 --text "- 正在检查 Shell 历史记录文件" --result "${STATUS_WARNING}" --color RED
                LogText "结果：以下历史记录的文件类型可能不正确："
                LogText "输出：${FIND}"
                LogText "说明：上述路径可能被重定向，以绕过历史记录，应进一步调查"
                ReportWarning "${TEST_NO}" "发现文件类型不正确的 Shell 历史记录文件"
            fi
            LogText "备注：历史记录通常应为普通文件，符号链接或其他文件类型值得警惕。"
        else
            Display --indent 2 --text "- 正在检查 Shell 历史记录文件" --result "${STATUS_SKIPPED}" --color WHITE
            LogText "结果：用户主目录列表为空，已跳过此检查"
        fi
    fi
#
#################################################################################
#
    # Test        : HOME-9314
    # Description : Check if non local paths are found in PATH, which can be a risk, but also bad for performance
    #               (like searching on a filer, instead of local disk)
    #Register --test-no HOME-9314 --weight L --network NO --category security --description "Create list with home directories"
#
#################################################################################
#
    # Test        : HOME-9350
    # Description : Scan home directories for specific files, used in different tests later
    # Notes       : For performance reasons we combine the scanning of different files, so inode caching is used
    #               as much as possible for every find command
    # Profile opt : ignore-home-dir (multiple lines allowed), ignores home directory
    if [ -n "${REPORTFILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HOME-9350 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "收集用户主目录信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        IGNORE_HOME_DIRS=$(${GREPBINARY} "^ignore-home-dir=" ${REPORTFILE} | ${AWKBINARY} -F= '{ print $2 }')
        if [ -z "${IGNORE_HOME_DIRS}" ]; then
            LogText "结果：IGNORE_HOME_DIRS 为空，没有排除任何路径"
        else
            LogText "输出：${IGNORE_HOME_DIRS}"
        fi
    fi
#
#################################################################################
#

    WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
