#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Kernel
#
#################################################################################
#
    InsertSection "${SECTION_KERNEL}"
#
#################################################################################
#
    CPU_PAE=0
    CPU_NX=0
    LINUXCONFIGFILE=""
    LINUXCONFIGFILE_ZIPPED=0
    LIMITS_DIRECTORY="${ROOTDIR}etc/security/limits.d"
    APT_ARCHIVE_DIRECTORY="${ROOTDIR}var/cache/apt/archives"
#
#################################################################################
#
    # Test        : KRNL-5622
    # Description : Check default run level on Linux machines
    Register --test-no KRNL-5622 --os Linux --weight L --network NO --category security --description "确定 Linux 默认运行级别"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Checking if we can find the systemd default target
        LogText "测试：检查 systemd default.target"
        if [ $( [ ! -z ${SYSTEMCTLBINARY} ] && ${SYSTEMCTLBINARY} get-default) ]; then
            FIND=$(${SYSTEMCTLBINARY} get-default)
            FIND2=$(${ECHOCMD} ${FIND} | ${EGREPBINARY} "runlevel5|graphical")
            if HasData "${FIND2}"; then
                LogText "结果：在 runlevel5/graphical 上找到匹配项"
                Display --indent 2 --text "- 检查默认运行级别" --result "runlevel 5" --color GREEN
                Report "linux_default_runlevel=5"
            else
                LogText "结果：未找到匹配的运行级别，默认使用运行级别 3"
                Display --indent 2 --text "- 检查默认运行级别" --result "runlevel 3" --color GREEN
                Report "linux_default_runlevel=3"
            fi
        else
            LogText "结果：未找到 systemd，尝试检查 inittab"
            LogText "测试：检查 ${ROOTDIR}etc/inittab"
            if [ -f ${ROOTDIR}etc/inittab ]; then
                LogText "结果：找到文件 ${ROOTDIR}etc/inittab"
                LogText "测试：检查默认 Linux 运行级别"
                FIND=$(${AWKBINARY} -F: '/^id/ { print $2; }' ${ROOTDIR}etc/inittab | head -n 1)
                if IsEmpty "${FIND}"; then
                    Display --indent 2 --text "- 检查默认运行级别" --result "${STATUS_UNKNOWN}" --color YELLOW
                    LogText "结果：无法从 ${ROOTDIR}etc/inittab 确定默认运行级别"
                else
                    Display --indent 2 --text "- 检查默认运行级别" --result "${FIND}" --color GREEN
                    LogText "发现默认运行级别 '${FIND}'"
                    Report "linux_default_runlevel=${FIND}"
                fi
            else
                LogText "结果：找不到文件 ${ROOTDIR}etc/inittab"
                if [ "${LINUX_VERSION}" = "Debian" ] || [ "${LINUX_VERSION}" = "Ubuntu" ] || [ "${LINUX_VERSION_LIKE}" = "Debian" ] || [ "${LINUX_VERSION_LIKE}" = "Ubuntu" ]; then
                    LogText "检查：在 Debian 系统上使用 who -r 检查运行级别"
                    FIND=$(who -r | ${AWKBINARY} '{ if ($1=="run-level") { print $2 } }')
                    if HasData "${FIND}"; then
                        LogText "Result: 发现默认运行级别 '${FIND}'"
                        Report "linux_default_runlevel=${FIND}"
                        Display --indent 2 --text "- 检查默认运行级别" --result "RUNLEVEL ${FIND}" --color GREEN
                    else
                        LogText "结果：无法通过 who -r 确定默认运行级别"
                        Display --indent 2 --text "- 检查默认运行级别" --result "${STATUS_UNKNOWN}" --color YELLOW
                    fi
                fi
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5677
    # Description : Check CPU options and support (PAE, No eXecute, eXecute Disable)
    # More info   : pae and nx bit are both visible on AMD and Intel CPU's if supported

    Register --test-no KRNL-5677 --platform "x86_64 amd64" --os "Linux NetBSD" --weight L --network NO --category security --description "检查 CPU 选项和支持"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 检查 CPU 支持 (NX/PAE)"
        LogText "测试：检查/proc/cpuinfo"
        if [ -f /proc/cpuinfo ]; then
            LogText "结果：找到/proc/cpuinfo"
            LogText "测试：检查 CPU 选项 (XD/NX/PAE)"
            FIND_PAE_NX=$(${GREPBINARY} " pae " /proc/cpuinfo | ${GREPBINARY} " nx ")
            FIND_PAE=$(${GREPBINARY} " pae " /proc/cpuinfo)
            FIND_NX=$(${GREPBINARY} " nx " /proc/cpuinfo)
            FOUND=0
            if HasData "${FIND_PAE_NX}"; then
                LogText "PAE：是"
                LogText "NX：是"
                CPU_PAE=1
                CPU_NX=1
                LogText "结果：PAE 或未找到 eXecute 选项"
                Report "cpu_pae=1"
                Report "cpu_nx=1"
                FOUND=1
            else
                if HasData "${FIND_PAE}" && IsEmpty "${FIND_NX}"; then
                    Report "cpu_pae=1"
                    LogText "结果：找到PAE"
                    CPU_PAE=1
                    FOUND=1
                else
                    if HasData "${FIND_NX}" && IsEmpty "${FIND_PAE}"; then
                        Report "cpu_nx=1"
                        LogText "结果：发现No eXecute"
                        CPU_NX=1
                        FOUND=1
                    else
                        LogText "结果：发现没有启用 CPU 选项（PAE 或 NX 位）"
                    fi
                fi
            fi
            if [ ${FOUND} -eq 1 ]; then
                Display --indent 4 --text "CPU 支持：支持 PAE 和/或 NoeXecute" --result "${STATUS_FOUND}" --color GREEN
            else
                Display --indent 4 --text "CPU 支持： 不支持 PAE 或 NoeXecute" --result "${STATUS_NONE}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "尽可能使用启用 PAE 的内核以获得本机 No eXecute/eXecute Disable 支持"
            fi
        else
            Display --indent 4 --text "CPU 支持：无 /proc/cpuinfo" --result "${STATUS_SKIPPED}" --color YELLOW
            LogText "结果：未找到 /proc/cpuinfo"
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5680
    # Description : Check if installed kernel has PAE support
    # Dependency  : KRNL-5677
    # More info   : RedHat/CentOS/Fedora uses the package name 'kernel-PAE'
#
#################################################################################
#
    # Test        : KRNL-5695
    # Description : Determining Linux kernel version and release number
    Register --test-no KRNL-5695 --os Linux --weight L --network NO --category security --description "确定 Linux 内核版本和发行号"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Kernel number (and suffix)
        LINUX_KERNEL_RELEASE=$(uname -r)
        Report "linux_kernel_release=${LINUX_KERNEL_RELEASE}"
        LogText "结果：找到内核版本${LINUX_KERNEL_RELEASE}"
        # Type and build date
        LINUX_KERNEL_VERSION=$(uname -v)
        Report "linux_kernel_version=${LINUX_KERNEL_VERSION}"
        LogText "结果：找到内核版本${LINUX_KERNEL_VERSION}"
        Display --indent 2 --text "- 检查内核版本和发布" --result "${STATUS_DONE}" --color GREEN
    fi
#
#################################################################################
#
    # Test        : KRNL-5723
    # Description : Check if Linux is build as a monolithic kernel or not
    Register --test-no KRNL-5723 --os Linux --weight L --network NO --category security --description "确定 Linux 内核是否是单片内核"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${LSMODBINARY}" -a -f /proc/modules ]; then
            LogText "测试：检查内核是整体的还是模块化的"
            # Checking if any modules are loaded
            FIND=$(${LSMODBINARY} | ${GREPBINARY} -v "^Module" | wc -l | ${TRBINARY} -s ' ' | ${TRBINARY} -d ' ')
            Display --indent 2 --text "- 检查内核类型" --result "${STATUS_DONE}" --color GREEN
            MONOLITHIC_KERNEL_TESTED=1
            if [ "${FIND}" = "0" ]; then
                LogText "结果：找到整体内核"
                Report "linux_kernel_type=monolithic"
                MONOLITHIC_KERNEL=1
            else
                LogText "结果：找到模块化内核"
                Report "linux_kernel_type=modular"
                MONOLITHIC_KERNEL=0
            fi
        else
            LogText "已跳过检查：未找到 lsmod 程序或无法打开 /proc/modules"
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5726
    # Description : Checking Linux loaded kernel modules
    Register --test-no KRNL-5726 --os Linux --weight L --network NO --category security --description "检查 Linux 加载的内核模块"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${LSMODBINARY}" -a -f /proc/modules ]; then
            FIND=$(${LSMODBINARY} | ${AWKBINARY} '{ if ($1!="Module") print $1 }' | sort)
            Display --indent 2 --text "- 检查加载的内核模块" --result "${STATUS_DONE}" --color GREEN
            if HasData "${FIND}"; then
                LogText "根据 lsmod 加载模块："
                COUNT=0
                for ITEM in ${FIND}; do
                    LogText "加载模块：${ITEM}"
                    Report "loaded_kernel_module[]=${ITEM}"
                    COUNT=$((COUNT + 1))
                done
                Display --indent 6 --text "找到 ${COUNT} 有源模块"
            else
                LogText "结果：未找到加载的模块"
                LogText "注意：未发现已加载的内核模块，可能是 lsmod 损坏或格式异常，也可能使用了自定义单体内核"
            fi
        else
            LogText "已跳过检查：未找到 lsmod 程序或无法打开 /proc/modules"
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5728
    # Description : Checking for available Linux kernel configuration file in /boot
    Register --test-no KRNL-5728 --os Linux --weight L --network NO --category security --description "检查 Linux 内核配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        CHECKFILE="${ROOTDIR}boot/config-$(uname -r)"
        CHECKFILE_ZIPPED="${ROOTDIR}proc/config.gz"
        if [ -f ${CHECKFILE} ]; then
            LINUXCONFIGFILE="${CHECKFILE}"
            LogText "结果：找到配置（${LINUXCONFIGFILE}）"
            Display --indent 2 --text "- 检查Linux内核配置文件" --result "${STATUS_FOUND}" --color GREEN
        elif [ -f ${CHECKFILE_ZIPPED} ]; then
            LINUXCONFIGFILE="${CHECKFILE_ZIPPED}"
            LINUXCONFIGFILE_ZIPPED=1
            LogText "结果：找到配置：${ROOTDIR}proc/config.gz（压缩）"
            Display --indent 2 --text "- 检查Linux内核配置文件" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：在${ROOTDIR}boot中找不到Linux内核配置文件"
            Display --indent 2 --text "- 检查Linux内核配置文件" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
        if HasData "${LINUXCONFIGFILE}"; then
            Report "linux_config_file=${LINUXCONFIGFILE}"
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5730
    # Description : Checking default I/O kernel scheduler
    # Notes       : This test could be extended with testing some of the specific devices like disks
    #               cat /sys/block/sda/queue/scheduler
    PREQS_MET="NO"
    if HasData "${LINUXCONFIGFILE}"; then
        if [ -f ${LINUXCONFIGFILE} ]; then PREQS_MET="YES"; fi
    fi
    Register --test-no KRNL-5730 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查磁盘 I/O 内核调度程序"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ ${LINUXCONFIGFILE_ZIPPED} -eq 1 ]; then GREPTOOL="${ZGREPBINARY}"; else GREPTOOL="${GREPBINARY}"; fi
        if [ -n "${GREPTOOL}" ]; then
            LogText "测试：检查默认的 I/O 内核调度程序"
            LINUX_KERNEL_IOSCHED=$(${GREPTOOL} "CONFIG_DEFAULT_IOSCHED" ${LINUXCONFIGFILE} | ${AWKBINARY} -F= '{ print $2 }' | ${SEDBINARY} s/\"//g)
            if [ -n "${LINUX_KERNEL_IOSCHED}" ]; then
                LogText "结果：发现 I/O 调度器 '${LINUX_KERNEL_IOSCHED}'"
                Display --indent 2 --text "- 检查默认的 I/O 内核调度程序" --result "${STATUS_FOUND}" --color GREEN
                Report "linux_kernel_io_scheduler[]=${LINUX_KERNEL_IOSCHED}"
            else
                LogText "结果：未找到默认的 I/O 内核调度程序"
                Display --indent 2 --text "- 检查默认的 I/O 内核调度程序" --result "${STATUS_NOT_FOUND}" --color WHITE
            fi
        else
            ReportException "${TEST_NO}" "找不到有效的 ${GREPBINARY} 工具来搜索内核设置"
        fi
   fi
#
#################################################################################
#
    # Test        : KRNL-5745
    # Description : Checking FreeBSD loaded kernel modules
    Register --test-no KRNL-5745 --os FreeBSD --weight L --network NO --category security --description "检查 FreeBSD 加载的内核模块"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 检查活动内核模块"
        LogText "测试：活动内核模块 (KLD)"
        LogText "说明：查看所有活动的内核模块（包括内核）"
        LogText "测试：检查模块"
        if [ -f /sbin/kldstat ]; then
            FIND=$(kldstat | ${GREPBINARY} -v 'Name' | ${TRBINARY} -s ' ' | ${CUTBINARY} -d ' ' -f6)
            if [ $? -eq 0 ]; then
                LogText "根据 kldstat 加载的模块："
                COUNT=0
                for ITEM in ${FIND}; do
                    LogText "加载模块：${ITEM}"
                    Report "loaded_kernel_module[]=${ITEM}"
                    COUNT=$((COUNT + 1))
                done
                Display --indent 4 --text "找到 ${COUNT} 内核模块" --result "${STATUS_DONE}" --color GREEN
            else
                Display --indent 4 --text "测试失败" --result "${STATUS_WARNING}" --color RED
                LogText "结果：执行 kldstat 时出现问题"
            fi
        else
            LogText "结果：没有结果，找不到 /sbin/kldstat"
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5831
    # Description : Checking DragonFly loaded kernel modules
    Register --test-no KRNL-5831 --os DragonFly --weight L --network NO --category security --description "检查 DragonFly 加载的内核模块"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 检查活动内核模块"
        LogText "测试：活动内核模块 (KLD)"
        LogText "说明：查看所有活动的内核模块（包括内核）"
        LogText "测试：检查模块"
        if [ -x /sbin/kldstat ]; then
            FIND=$(/sbin/kldstat | ${GREPBINARY} -v 'Name' | ${TRBINARY} -s ' ' | ${CUTBINARY} -d ' ' -f6)
            if [ $? -eq 0 ]; then
                LogText "根据 kldstat 加载的模块："
                COUNT=0
                for ITEM in ${FIND}; do
                    LogText "加载模块：${ITEM}"
                    Report "loaded_kernel_module[]=${ITEM}"
                    COUNT=$((COUNT + 1))
                done
                Display --indent 4 --text "找到 ${COUNT} 内核模块" --result "${STATUS_DONE}" --color GREEN
            else
                Display --indent 4 --text "测试失败" --result "${STATUS_WARNING}" --color RED
                LogText "结果：执行 kldstat 时出现问题"
            fi
        else
            echo "[ ${WHITE}SKIPPED${NORMAL} ]"
            LogText "结果：没有结果，找不到 /sbin/kldstat"
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5770
    # Description : Checking Solaris load modules
    Register --test-no KRNL-5770 --os Solaris --weight L --network NO --category security --description "检查活动的内核模块"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索加载的内核模块"
        FIND=$(/usr/sbin/modinfo -c -w | ${GREPBINARY} -v "UNLOADED" | ${GREPBINARY} LOADED | ${AWKBINARY} '{ print $3 }' | sort)
        if HasData "${FIND}"; then
            for ITEM in ${FIND}; do
                LogText "找到模块：${ITEM}"
                Report "loaded_kernel_module[]=${ITEM}"
            done
            Display --indent 2 --text "- 检查 Solaris 活动内核模块" --result "${STATUS_DONE}" --color GREEN
        else
            LogText "结果：无输出"
            Display --indent 2 --text "- 检查 Solaris 活动内核模块" --result "${STATUS_UNKNOWN}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5788
    # Description : Checking availability new kernel
    if [ "${LINUX_VERSION}" = "Debian" ] || [ "${LINUX_VERSION}" = "Ubuntu" ] || [ "${LINUX_VERSION_LIKE}" = "Debian" ] || [ "${LINUX_VERSION_LIKE}" = "Ubuntu" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi
    Register --test-no KRNL-5788 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查新 Linux 内核的可用性"
    if [ ${SKIPTEST} -eq 0 ]; then
        FINDKERNEL=""
        HAS_VMLINUZ=0
        LogText "检查：搜索 apt-cache，以确定是否有更新的内核"
        if [ -x ${ROOTDIR}usr/bin/apt-cache ]; then
            LogText "结果：找到${ROOTDIR}usr/bin/apt-cache"
            LogText "测试：检查 ${ROOTDIR}vmlinuz 或 ${ROOTDIR}boot/vmlinuz 是否存在"
            if [ -f ${ROOTDIR}vmlinuz -o -f ${ROOTDIR}boot/vmlinuz ]; then
                HAS_VMLINUZ=1
                if [ -f ${ROOTDIR}vmlinuz ]; then
                    FINDVMLINUZ="${ROOTDIR}vmlinuz"
                else
                    FINDVMLINUZ="${ROOTDIR}boot/vmlinuz"
                fi
                LogText "结果：找到${FINDVMLINUZ}"
                LogText "测试：检查 ${FINDVMLINUZ} 的读取链接位置"
                FINDKERNFILE=$(readlink -f ${FINDVMLINUZ})
                LogText "输出：readlink报告的文件${FINDKERNFILE}"
                LogText "测试：使用 dpkg -S 的输出检查相关包"
                FINDKERNEL=$(dpkg -S ${FINDKERNFILE} 2> /dev/null | ${AWKBINARY} -F : '{print $1}')
                LogText "输出： dpkg -S 报告包 ${FINDKERNEL}"
            elif [ -e ${ROOTDIR}dev/grsec ]; then
                FINDKERNEL="linux-image-$(uname -r)"
                LogText "结果：由于 grsecurity，${ROOTDIR}vmlinuz 缺失；假定内核为 ${FINDKERNEL}"
            elif [ -e ${ROOTDIR}etc/rpi-issue ]; then
                FINDKERNEL="raspberrypi-kernel"
                LogText "结果：由于 Raspbian，${ROOTDIR}vmlinuz 丢失"
            elif $(${GREPBINARY} -E -q 'do_symlinks.*=.*No' ${ROOTDIR}etc/kernel-img.conf); then
                FINDKERNEL="linux-image-$(uname -r)"
                LogText "结果：由于 /etc/kernel-img.conf 项 do_symlinks = No，${ROOTDIR}vmlinuz 缺失"
            else
                LogText "此系统缺少 ${ROOTDIR}vmlinuz 或 ${ROOTDIR}boot/vmlinuz。无法检查内核是否是最新的。"
                ReportSuggestion "${TEST_NO}" "确定此 Debian/Ubuntu 系统上缺少 ${ROOTDIR}vmlinuz 或 ${ROOTDIR}boot/vmlinuz 的原因。" "/vmlinuz or /boot/vmlinuz"
            fi

            if IsEmpty "${FINDKERNEL}"; then
                LogText "结果：无法检查内核更新状态，因为内核未知"
            else
                LogText "结果：发现内核 '${FINDKERNEL}'，将用于后续检查"
                LogText "测试：使用 apt-cache policy 确定是否有可用更新"
                FINDINSTALLED=$(apt-cache policy ${FINDKERNEL} | ${GREPBINARY} -E 'Installed' | ${CUTBINARY} -d ':' -f2 | ${TRBINARY} -d ' ')
                FINDCANDIDATE=$(apt-cache policy ${FINDKERNEL} | ${GREPBINARY} -E 'Candidate' | ${CUTBINARY} -d ':' -f2 | ${TRBINARY} -d ' ')
                LogText "安装的内核：${FINDINSTALLED}"
                LogText "候选内核：${FINDCANDIDATE}"
                if IsEmpty "${FINDINSTALLED}"; then
                    Display --indent 2 --text "- 检查可用的内核更新" --result "${STATUS_UNKNOWN}" --color YELLOW
                    LogText "结果：发生异常，apt-cache policy 没有输出"
                    if [ ${HAS_VMLINUZ} -eq 1 ]; then
                        ReportException "${TEST_NO}:01" "找到 vmlinuz (${FINDVMLINUZ})，但无法使用 apt-cache policy 确定已安装的内核"
                        ReportSuggestion "${TEST_NO}" "检查 apt-cache policy 的输出以确定其输出为何为空"
                    fi
                    LogText "结果：apt-cache policy 未返回已安装的内核版本"
                else
                    if [ "${FINDINSTALLED}" = "${FINDCANDIDATE}" ]; then
                        if [ -e /dev/grsec ]; then
                            Display --indent 2 --text "- 检查可用的内核更新" --result GRSEC --color GREEN
                            LogText "结果：已安装 Grsecurity，无法确定是否有更新的内核"
                            ReportManual "Manually check to confirm you're using a recent kernel and grsecurity patch"
                        else
                            Display --indent 2 --text "- 检查可用的内核更新" --result "${STATUS_OK}" --color GREEN
                            LogText "结果：没有可用的内核更新"
                        fi
                    else
                        Display --indent 2 --text "- 检查可用的内核更新" --result "有可用更新" --color YELLOW
                        LogText "结果：根据 'apt-cache policy'，有可用的内核更新。"
                        ReportSuggestion "${TEST_NO}" "确定可用内核更新的优先级"
                    fi
                fi
            fi
        else
            LogText "结果：找不到 ${ROOTDIR}usr/bin/apt-cache，跳过其他检查。"
        fi
        unset FINDCANDIDATE FINDINSTALLED FINDKERNEL HAS_VMLINUZ
    fi
#
#################################################################################
#
    # Test        : KRNL-5820
    # Description : Checking core dumps configuration (Linux)
    Register --test-no KRNL-5820 --os Linux --weight L --network NO --category security --description "检查核心转储配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 检查核心转储配置"
        LogText "测试：检查 systemd 是否存在"
        # systemd option
        if [ $HAS_SYSTEMD -eq 1 ]; then
            LogText "结果：systemd 出现在该系统上"
            LogText "检查：确认 ${ROOTDIR}etc/systemd/coredump.conf 和 ${ROOTDIR}etc/systemd/coredump.conf.d/*.conf 中是否禁用了核心转储"
            # check likely main config file for systemd: ${ROOTDIR}etc/systemd/coredump.conf for ProcessSizeMax=0 and Storage=none
            SYSD_CORED_BASE_PROCSIZEMAX_NR_DISABLED=$(${GREPBINARY} -v "^ *#" ${ROOTDIR}etc/systemd/coredump.conf 2> /dev/null | ${SEDBINARY} 's/^ *//g' | ${GREPBINARY} -i "^ProcessSizeMax=" | ${CUTBINARY} -d'=' -f2 | ${SEDBINARY} 's/ .*$//g ; s/\([A-Z][a-z]*\)*$//g' | ${GREPBINARY} "^0 *$" | ${WCBINARY} -l)
            SYSD_CORED_BASE_PROCSIZEMAX_NR_ENABLED=$(${GREPBINARY} -v "^ *#" ${ROOTDIR}etc/systemd/coredump.conf 2> /dev/null | ${SEDBINARY} 's/^ *//g' | ${GREPBINARY} -i "^ProcessSizeMax=" | ${CUTBINARY} -d'=' -f2 | ${SEDBINARY} 's/ .*$//g ; s/\([A-Z][a-z]*\)*$//g' | ${GREPBINARY} -v "^0 *$" | ${WCBINARY} -l)
            SYSD_CORED_BASE_STORAGE_FOUND=$(${GREPBINARY} -v "^ *#" ${ROOTDIR}etc/systemd/coredump.conf 2> /dev/null | ${SEDBINARY} 's/^ *//g' | ${GREPBINARY} -i "^Storage=" | ${CUTBINARY} -d'=' -f2 | ${SEDBINARY} 's/ .*$//g')
            SYSD_CORED_BASE_STORAGE_NR_ENABLED=$(${ECHOCMD} "${SYSD_CORED_BASE_STORAGE_FOUND}" | ${SEDBINARY} 's/none//g' | ${WCBINARY} | ${AWKBINARY} '{print $2}')
            SYSD_CORED_BASE_STORAGE_NR_DISABLED=$(${ECHOCMD} "${SYSD_CORED_BASE_STORAGE_FOUND}" | ${GREPBINARY} -o "none" | ${WCBINARY} | ${AWKBINARY} '{print $2}')
            # check conf files in possibly existing coredump.conf.d folders
            # using find instead of grep -r to stay POSIX compliant. On AIX and HPUX grep -r is not available.
            # while there could be multiple files overwriting each other, we are checking the number of occurrences
            SYSD_CORED_SUB_PROCSIZEMAX_NR_DISABLED=$(${FINDBINARY} -L /etc/systemd/coredump.conf.d/ /run/systemd/coredump.conf.d/ /usr/lib/systemd/coredump.conf.d/ -type f -iname "*.conf" -exec ${SEDBINARY} 's/^ *//g' {} \; 2> /dev/null | ${GREPBINARY} -i "^ProcessSizeMax=" | ${CUTBINARY} -d'=' -f2 | ${SEDBINARY} 's/ .*$//g ; s/\([A-Z][a-z]*\)*$//g' | ${GREPBINARY} "^0 *$" | ${WCBINARY} -l)
            SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED=$(${FINDBINARY} -L /etc/systemd/coredump.conf.d/ /run/systemd/coredump.conf.d/ /usr/lib/systemd/coredump.conf.d/ -type f -iname "*.conf" -exec ${SEDBINARY} 's/^ *//g' {} \; 2> /dev/null | ${GREPBINARY} -i "^ProcessSizeMax=" | ${CUTBINARY} -d'=' -f2 | ${SEDBINARY} 's/ .*$//g ; s/\([A-Z][a-z]*\)*$//g' | ${GREPBINARY} -v "^0 *$" | ${WCBINARY} -l)
            SYSD_CORED_SUB_STORAGE_FOUND=$(${FINDBINARY} -L /etc/systemd/coredump.conf.d/ /run/systemd/coredump.conf.d/ /usr/lib/systemd/coredump.conf.d/ -type f -iname "*.conf" -exec ${SEDBINARY} 's/^ *//g' {} \; 2> /dev/null | ${GREPBINARY} -i "^Storage=" | ${CUTBINARY} -d'=' -f2 | ${SEDBINARY} 's/ .*$//g')
            SYSD_CORED_SUB_STORAGE_NR_ENABLED=$(${ECHOCMD} "${SYSD_CORED_SUB_STORAGE_FOUND}" | ${SEDBINARY} 's/none//g' | ${WCBINARY} | ${AWKBINARY} '{print $2}')
            SYSD_CORED_SUB_STORAGE_NR_DISABLED=$(${ECHOCMD} "${SYSD_CORED_SUB_STORAGE_FOUND}" | ${GREPBINARY} -o "none" | ${WCBINARY} | ${AWKBINARY} '{print $2}')
            if ( [ ${SYSD_CORED_BASE_PROCSIZEMAX_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_BASE_STORAGE_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -eq 0 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -eq 0 ] ) || \
               ( [ ${SYSD_CORED_BASE_PROCSIZEMAX_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -eq 0 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -eq 0 ] ) || \
               ( [ ${SYSD_CORED_BASE_STORAGE_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -eq 0 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -eq 0 ] ) || \
               ( [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -eq 0 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -eq 0 ] ); then
                LogText "结果：systemd 配置文件中的 'ProcessSizeMax=0' 和 'Storage=none' 已禁用核心转储"
                AddHP 1 1
                TMP_COLOR="GREEN"
                if [ ${SYSD_CORED_BASE_PROCSIZEMAX_NR_DISABLED} -gt 1 ] || [ ${SYSD_CORED_BASE_STORAGE_NR_DISABLED} -gt 1 ] || [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_DISABLED} -gt 1 ] || [ ${SYSD_CORED_SUB_STORAGE_NR_DISABLED} -gt 1 ]; then
                    LogText "结果：systemd 配置文件中多次设置了 'ProcessSizeMax=0' 和 'Storage=none'，请检查配置！"
                    ReportSuggestion "${TEST_NO}" "检查 systemd 配置中是否有重复的核心转储设置条目"
                    TMP_COLOR="YELLOW"
                fi
                Display --indent 4 --text "- systemd conf 文件中的配置" --result "${STATUS_DISABLED}" --color "${TMP_COLOR}"
            elif [ ${SYSD_CORED_BASE_PROCSIZEMAX_NR_DISABLED} -ge 1 ] && [ ${SYSD_CORED_BASE_STORAGE_NR_DISABLED} -ge 1 ] && ( [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -ge 1 ] || [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -ge 1 ] ); then
                LogText "结果：${ROOTDIR}etc/systemd/coredump.conf 中设置了 'ProcessSizeMax=0' 和 'Storage=none'，但被子目录中的配置文件覆盖"
                ReportSuggestion "${TEST_NO}" "检查 systemd 配置以覆盖核心转储设置"
                Display --indent 4 --text "- systemd conf 文件中的配置" --result "${STATUS_ENABLED}" --color YELLOW
                AddHP 0 1
            elif ( [ ${SYSD_CORED_BASE_PROCSIZEMAX_NR_ENABLED} -ge 1 ] && [ ${SYSD_CORED_BASE_STORAGE_NR_ENABLED} -ge 1 ] ) || \
                 ( [ ${SYSD_CORED_BASE_PROCSIZEMAX_NR_ENABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -ge 1 ] ) || \
                 ( [ ${SYSD_CORED_BASE_STORAGE_NR_ENABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -ge 1 ] ) || \
                 ( [ ${SYSD_CORED_SUB_PROCSIZEMAX_NR_ENABLED} -ge 1 ] && [ ${SYSD_CORED_SUB_STORAGE_NR_ENABLED} -ge 1 ] ); then
                LogText "结果：在 systemd 配置文件中显式启用核心转储"
                ReportSuggestion "${TEST_NO}" "如非必要，建议在 ${ROOTDIR}etc/systemd/coredump.conf 中明确禁用核心转储（'ProcessSizeMax=0'、'Storage=none'）"
                Display --indent 4 --text "- systemd conf 文件中的配置" --result "${STATUS_ENABLED}" --color RED
                AddHP 0 1
            else
                LogText "结果：systemd 配置中未禁用核心转储，未找到 'ProcessSizeMax=0' 和 'Storage=none' 设置"
                Display --indent 4 --text "- systemd conf 文件中的配置" --result "${STATUS_DEFAULT}" --color WHITE
                AddHP 0 1
            fi
        fi
        # Profile option
        LogText "测试：检查存在 ${ROOTDIR}etc/profile"
        if [ -f "${ROOTDIR}etc/profile" ]; then
            LogText "检查：确认 ${ROOTDIR}etc/profile 或 ${ROOTDIR}etc/profile.d/*.sh 中是否存在 'ulimit -c 0'"
            # use tail -1 in the following commands to get the last entry, which is the one that counts (in case of profile.d/ probably counts)
            ULIMIT_C_VALUE="$(${GREPBINARY} "ulimit -H\?c " ${ROOTDIR}etc/profile 2> /dev/null | ${SEDBINARY} 's/^ *//g' | ${GREPBINARY} -v "^#" | ${TAILBINARY} -1 | ${CUTBINARY} -d' ' -f3 | ${SEDBINARY} 's/ .*$//g ; s/\([A-Z][a-z]*\)*$//g')"
            ULIMIT_C_VALUE_SUB="$(${FINDBINARY} -L ${ROOTDIR}etc/profile.d -name "*.sh" -type f -exec ${CAT_BINARY} {} \; 2> /dev/null | ${GREPBINARY} "ulimit -H\?c " | ${SEDBINARY} 's/^ *//g' | ${GREPBINARY} -v "^#" | ${TAILBINARY} -1 | ${CUTBINARY} -d' ' -f3 | ${SEDBINARY} 's/ .*$//g ; s/\([A-Z][a-z]*\)*$//g')"
            if ( [ -n "${ULIMIT_C_VALUE_SUB}" ] && [ "${ULIMIT_C_VALUE_SUB}" = "0" ] ) || ( [ -n "${ULIMIT_C_VALUE}" ] && [ -z "${ULIMIT_C_VALUE_SUB}" ] && [ "${ULIMIT_C_VALUE}" = "0" ] ); then
                LogText "结果：${ROOTDIR}etc/profile 或 ${ROOTDIR}etc/profile.d/*.sh 中的 'ulimit -c 0' 已禁用核心转储"
                Display --indent 4 --text "- 在etc/profile中配置" --result "${STATUS_DISABLED}" --color GREEN
                AddHP 1 1
            elif [ -z "${ULIMIT_C_VALUE_SUB}" ] && [ -z "${ULIMIT_C_VALUE}" ]; then
                LogText "结果：${ROOTDIR}etc/profile 或 ${ROOTDIR}etc/profile.d/*.sh 中未禁用核心转储，未找到 'ulimit -c 0' 设置"
                Display --indent 4 --text "- ${ROOTDIR}etc/profile 中的配置" --result "${STATUS_DEFAULT}" --color WHITE
                AddHP 0 1
            elif ( [ -n "${ULIMIT_C_VALUE_SUB}" ] && ( [ "${ULIMIT_C_VALUE_SUB}" = "unlimited" ] || [ "${ULIMIT_C_VALUE_SUB}" != "0" ] ) ) || ( [ -n "${ULIMIT_C_VALUE}" ] && [ -z "${ULIMIT_C_VALUE_SUB}" ] && ( [ "${ULIMIT_C_VALUE}" = "unlimited" ] || [ "${ULIMIT_C_VALUE}" != "0" ] ) ); then
                LogText "结果：${ROOTDIR}etc/profile 或 ${ROOTDIR}etc/profile.d/*.sh 中启用了核心转储，'ulimit -c' 配置值高于 0"
                Display --indent 4 --text "- ${ROOTDIR}etc/profile 中的配置" --result "${STATUS_ENABLED}" --color RED
                AddHP 0 1
            else
                LogText "结果：错误——检查 ${ROOTDIR}etc/profile 和 ${ROOTDIR}etc/profile.d/*.sh 配置文件时得到异常结果，请在 GitHub 报告！"
                Display --indent 4 --text "- ${ROOTDIR}etc/profile 中的配置" --result "${STATUS_ERROR}" --color YELLOW
            fi
        fi

        # Limits options
        for DIR in "/" "/usr/"; do
            LogText "测试：检查存在 ${DIR}etc/security/limits.conf"
            if [ -f "${DIR}etc/security/limits.conf" ]; then
                LogText "结果：文件 ${DIR}etc/security/limits.conf 存在"
                LogText "检查：确认 ${DIR}etc/security/limits.conf 和 ${LIMITS_DIRECTORY}/* 中是否禁用了核心转储"
                # using find instead of grep -r to stay POSIX compliant. On AIX and HPUX grep -r is not available.
                FIND1=$(${FINDBINARY} -L "${DIR}etc/security/limits.conf" "${LIMITS_DIRECTORY}" -type f -exec ${CAT_BINARY} {} \; 2> /dev/null | ${GREPBINARY} -v "^$" | ${AWKBINARY} '{ if ($1=="*" && $2=="soft" && $3=="core" && $4=="0") { print "soft core disabled" } else if ($1=="*" && $2=="soft" && $3=="core" && $4!="0") { print "soft core enabled" } }' | ${TAILBINARY} -1)
                FIND2=$(${FINDBINARY} -L "${DIR}etc/security/limits.conf" "${LIMITS_DIRECTORY}" -type f -exec ${CAT_BINARY} {} \; 2> /dev/null | ${GREPBINARY} -v "^$" | ${AWKBINARY} '{ if ($1=="*" && $2=="hard" && $3=="core" && $4=="0") { print "hard core disabled" } else if ($1=="*" && $2=="hard" && $3=="core" && $4!="0") { print "hard core enabled" } }' | ${TAILBINARY} -1)
                FIND3=$(${FINDBINARY} -L "${DIR}etc/security/limits.conf" "${LIMITS_DIRECTORY}" -type f -exec ${CAT_BINARY} {} \; 2> /dev/null | ${GREPBINARY} -v "^$" | ${AWKBINARY} '{ if ($1=="*" && $2=="-" && $3=="core" && $4=="0") { print "core dumps disabled" } else if ($1=="*" && $2=="-" && $3=="core" && $4!="0") { print "core dumps enabled" } }' | ${TAILBINARY} -1)

                # When "* - core [value]" is used, then this sets both soft and core. In that case we set the values, as they the type 'hard' and 'soft' will not be present in the configuration file.
                if [ "${FIND3}" = "core dumps disabled" ]; then
                    FIND1="soft core disabled"
                    FIND2="hard core disabled"
                elif [ "${FIND3}" = "core dumps enabled" ]; then
                    FIND1="soft core enabled"
                    FIND2="hard core enabled"
                fi

                IS_SOFTCORE_DISABLED="$(if [ "${FIND1}" = "soft core disabled" ]; then ${ECHOCMD} DISABLED; elif [ "${FIND1}" = "soft core enabled" ]; then ${ECHOCMD} ENABLED; else ${ECHOCMD} ${STATUS_DEFAULT}; fi)"
                IS_HARDCORE_DISABLED="$(if [ "${FIND2}" = "hard core disabled" ]; then ${ECHOCMD} DISABLED; elif [ "${FIND2}" = "hard core enabled" ]; then ${ECHOCMD} ENABLED; else ${ECHOCMD} ${STATUS_DEFAULT}; fi)"

                if [ "${FIND2}" = "hard core disabled" ]; then
                    LogText "结果：核心转储被硬禁用"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'hard' 配置" --result "${IS_HARDCORE_DISABLED}" --color "GREEN"
                    if [ "${FIND1}" = "soft core disabled" ]; then
                        Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'soft' 配置" --result "${IS_SOFTCORE_DISABLED}" --color "GREEN"
                    else
                        Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'soft' 配置（隐式）" --result "${STATUS_DISABLED}" --color "GREEN"
                    fi
                    AddHP 3 3
                elif [ "${FIND1}" = "soft core enabled" ] && [ "${FIND2}" = "hard core enabled" ]; then
                    LogText "结果：启用核心转储（软和硬）"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'hard' 配置" --result "${STATUS_ENABLED}" --color "RED"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'soft' 配置" --result "${STATUS_ENABLED}" --color "RED"
                    ReportSuggestion "${TEST_NO}" "如非必要，建议在 /etc/security/limits.conf 中明确禁用核心转储"
                    AddHP 0 3
                elif [ "${FIND1}" = "soft core disabled" ]; then
                    LogText "结果：已对 'soft' 禁用核心转储（'hard'=${IS_HARDCORE_DISABLED}）"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'hard' 配置" --result "${IS_HARDCORE_DISABLED}" --color "$(if [ "${IS_HARDCORE_DISABLED}" = "ENABLED" ]; then ${ECHOCMD} RED; elif [ "${IS_HARDCORE_DISABLED}" = "DISABLED" ]; then ${ECHOCMD} GREEN; else ${ECHOCMD} WHITE; fi)"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'soft' 配置" --result "${IS_SOFTCORE_DISABLED}" --color "GREEN"
                    AddHP 2 3
                elif [ "${FIND1}" = "soft core enabled" ] || [ "${FIND2}" = "hard core enabled" ]; then
                    LogText "结果：核心转储部分启用（'hard'=${IS_HARDCORE_DISABLED}，'soft'=${IS_SOFTCORE_DISABLED}）"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'hard' 配置" --result "${IS_HARDCORE_DISABLED}" --color "$(if [ "${IS_HARDCORE_DISABLED}" = "ENABLED" ]; then ${ECHOCMD} RED; elif [ "${IS_HARDCORE_DISABLED}" = "DISABLED" ]; then ${ECHOCMD} GREEN; else ${ECHOCMD} WHITE; fi)"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'soft' 配置" --result "${IS_SOFTCORE_DISABLED}" --color "$(if [ "${IS_SOFTCORE_DISABLED}" = "ENABLED" ]; then ${ECHOCMD} RED; elif [ "${IS_SOFTCORE_DISABLED}" = "DISABLED" ]; then ${ECHOCMD} GREEN; else ${ECHOCMD} WHITE; fi)"
                    AddHP 0 3
                else
                    LogText "结果：核心转储未显式禁用"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'hard' 配置" --result "${IS_HARDCORE_DISABLED}" --color "WHITE"
                    Display --indent 4 --text "- ${DIR}etc/security/limits.conf 中的 'soft' 配置" --result "${IS_HARDCORE_DISABLED}" --color "WHITE"
                    ReportSuggestion "${TEST_NO}" "如非必要，建议在 ${DIR}etc/security/limits.conf 中明确禁用核心转储"
                    AddHP 1 3
                fi
            else
                LogText "结果：文件 ${DIR}etc/security/limits.conf 不存在，跳过该文件的检查"
            fi
        done

        # Sysctl option
        LogText "测试：检查 fs.suid_dumpable 的 sysctl 值"
        FIND=$(${SYSCTLBINARY} fs.suid_dumpable 2> /dev/null | ${AWKBINARY} '{ if ($1=="fs.suid_dumpable") { print $3 } }')
        if [ -z "${FIND}" ]; then
            LogText "结果：未找到 sysctl 键 fs.suid_dumpable"
        else
            LogText "结果：找到值 ${FIND}"
        fi
        if [ "${FIND}" = "2" ]; then
            LogText "结果：程序可以生成核心转储，但仅 root 可读取（值 2，用于带文件保护的调试）"
            Display --indent 4 --text "- 检查 setuid 核心转储配置" --result "${STATUS_PROTECTED}" --color WHITE
            AddHP 1 1
        elif [ "${FIND}" = "1" ]; then
            LogText "结果：所有程序都可以生成核心转储（值 1，用于调试）"
            Display --indent 2 --text "- 检查 setuid 核心转储配置" --result "${STATUS_DEBUG}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "确定是否所有二进制文件都需要能够核心转储"
            AddHP 0 1
        else
            # 0 - (default) - traditional behaviour. Any process which has changed privilege levels or is execute only will not be dumped
            # https://www.kernel.org/doc/Documentation/sysctl/fs.txt
            LogText "结果：发现默认选项（0），仅执行程序或权限级别发生变化的程序无法生成核心转储"
            Display --indent 4 --text "- 检查 setuid 核心转储配置" --result "${STATUS_DISABLED}" --color GREEN
            AddHP 1 1
        fi
    fi
#
#################################################################################
#
    # Test        : KRNL-5830
    # Description : Check if system needs a reboot (Linux only)
    Register --test-no KRNL-5830 --os Linux --weight L --network NO --category security --description "检查系统是否在最新安装的内核上运行"
    if [ ${SKIPTEST} -eq 0 ]; then
        REBOOT_NEEDED=2
        for FILE in "${ROOTDIR}var/run/reboot-required.pkgs" "${ROOTDIR}var/run/needs_restarting"
        do
            LogText "测试：检查存在 ${FILE}"
            if [ -f ${FILE} ]; then
                LogText "结果：文件 ${FILE} 存在"
                FIND=$(${WCBINARY} -l < ${FILE})
                if [ "${FIND}" = "0" ]; then
                    LogText "结果：无需重新启动（文件为空）"
                    REBOOT_NEEDED=0
                    break
                else
                    PKGSCOUNT=$(${WCBINARY} -l < ${FILE})
                    LogText "结果：需要重启，涉及 ${PKGSCOUNT} 个软件包"
                    for I in ${FIND}; do
                        LogText "封装：${I}"
                    done
                    REBOOT_NEEDED=1
                    break
                fi
            else
                LogText "结果：未找到文件 ${FILE}"
            fi
        done

        # Check if /boot exists
        if [ -d "${ROOTDIR}boot" ]; then
            LogText "结果：/boot 存在，将继续执行更多检查"
            FIND=$(${LSBINARY} ${ROOTDIR}boot/* 2> /dev/null)
            if [ -n "${FIND}" ]; then
                if [ -f ${ROOTDIR}boot/vmlinuz -a ! -L ${ROOTDIR}boot/vmlinuz ]; then
                    LogText "结果：找到 /boot/vmlinuz（未符号链接）"
                    NEXTLINE=0
                    FINDVERSION=""
                    for I in $(file ${ROOTDIR}boot/vmlinuz-linux); do
                        if [ ${NEXTLINE} -eq 1 ]; then
                            FINDVERSION="${I}"
                            break
                        else
                            # Searching for the Linux kernel after the keyword 'version'
                            if [ "${I}" = "version" ]; then NEXTLINE=1; fi
                        fi
                    done
                    if [ -n "${FINDVERSION}" ]; then
                        CURRENT_KERNEL=$(uname -r)
                        if [ ! "${CURRENT_KERNEL}" = "${FINDVERSION}" ]; then
                            LogText "结果：当前内核与已加载内核不同，需要重启"
                            REBOOT_NEEDED=1
                        fi
                    else
                        ReportException "${TEST_NO}:1" "无法确定磁盘上的内核版本，需要调试数据"
                    fi
                elif [ -f ${ROOTDIR}boot/vmlinuz-linux ] || [ -f ${ROOTDIR}boot/vmlinuz-linux-lts ] || [ -f "$(${LSBINARY} -t ${ROOTDIR}boot/vm[l0-9]* 2> /dev/null | ${HEADBINARY} -1)" ]; then
                    if [ -f ${ROOTDIR}boot/vmlinuz ]; then
                          LogText "结果：找到${ROOTDIR}boot/vmlinuz"
                          FOUND_VMLINUZ=${ROOTDIR}boot/vmlinuz
                    elif [ -f ${ROOTDIR}boot/vmlinuz-linux ]; then
                        LogText "结果：找到${ROOTDIR}boot/vmlinuz-linux"
                        FOUND_VMLINUZ=${ROOTDIR}boot/vmlinuz-linux
                    elif [ -f ${ROOTDIR}boot/vmlinuz-linux-lts ]; then
                        LogText "结果：找到${ROOTDIR}boot/vmlinuz-linux-lts"
                        FOUND_VMLINUZ=${ROOTDIR}boot/vmlinuz-linux-lts
                    elif [ -f ${ROOTDIR}boot/vmlinuz-lts ]; then
                        LogText "结果：找到${ROOTDIR}boot/vmlinuz-lts"
                        FOUND_VMLINUZ=${ROOTDIR}boot/vmlinuz-lts
                    else
                        # Match on items like /boot/vm5.3.7 or /boot/vmlinuz-5.3.7-1-default. Sort based on versions (-v) and then find the last item
                        # Note: ignore a rescue kernel (e.g. CentOS)
                        FOUND_VMLINUZ=$(${LSBINARY} -v ${ROOTDIR}boot/vm[l0-9]* 2> /dev/null | ${GREPBINARY} -v '\-rescue-' | ${TAILBINARY} -1)
                        LogText "结果：找到${FOUND_VMLINUZ}"
                    fi

                    VERSION_ON_DISK=""
                    if [ -L "${FOUND_VMLINUZ}" ]; then
                        LogText "结果：发现符号链接，正在获取目标路径"
                        FOUND_VMLINUZ=$(readlink "${FOUND_VMLINUZ}")
                        LogText "结果：目标文件为 ${FOUND_VMLINUZ}"
                        VERSION_ON_DISK=$(echo ${FOUND_VMLINUZ} | ${SEDBINARY} 's#^/boot/##' | ${SEDBINARY} 's/^vmlinuz-//')
                        LogText "结果：从文件名推导出的版本为 '${VERSION_ON_DISK}'"
                    elif [ -f "${FOUND_VMLINUZ}" ]; then
                        VERSION_ON_DISK=$(echo ${FOUND_VMLINUZ} | ${SEDBINARY} 's#^/boot/##' | ${SEDBINARY} 's/^vmlinuz-//' | ${SEDBINARY} '$s/-\?\(linux\)\?-\?\(lts\)\?//')
                        LogText "结果：从文件名推导出的版本为 '${VERSION_ON_DISK}'"

                    fi

                    # Data check: perform reset if we found a version but looks incomplete
                    # Example: Arch Linux will return only 'linux' as its version after it discovered /boot/vmlinuz-linux
                    case ${VERSION_ON_DISK} in
                        "linux" | "linux-lts")
                            LogText "结果：重置版本（${VERSION_ON_DISK}），因为它看起来不完整"
                            VERSION_ON_DISK=""
                        ;;
                    esac

                    # If we did not find the version yet, see if we can extract it from the magic data that 'file' returns
                    if [ -z "${VERSION_ON_DISK}" ]; then
                        LogText "测试：检查磁盘上的内核版本"
                        NEXTLINE=0
                        VERSION_ON_DISK=""
                        for I in $(file ${FOUND_VMLINUZ}); do
                            if [ ${NEXTLINE} -eq 1 ]; then
                                VERSION_ON_DISK="${I}"
                                break
                            else
                                # Searching for the Linux kernel after the keyword 'version'
                                if [ "${I}" = "version" ]; then NEXTLINE=1; fi
                            fi
                        done
                    fi

                    # Last check if we finally got a version or not
                    if [ -z "${VERSION_ON_DISK}" ]; then
                        LogText "结果：在磁盘上找不到版本"
                        ReportException "${TEST_NO}:4" "找不到内核版本"
                    else
                        LogText "结果：找到版本${VERSION_ON_DISK}"
                        ACTIVE_KERNEL=$(uname -r)
                        LogText "结果：活动内核版本 ${ACTIVE_KERNEL}"
                        if [ "${VERSION_ON_DISK}" = "${ACTIVE_KERNEL}" ]; then
                            REBOOT_NEEDED=0
                            LogText "结果：活动内核与磁盘上的版本相同，无需重启"
                        else
                            REBOOT_NEEDED=1
                            LogText "结果：活动内核与磁盘上的版本不同，需要重启"
                        fi
                    fi
                else
                    if [ -L ${ROOTDIR}boot/vmlinuz ]; then
                        LogText "结果：发现 ${ROOTDIR}boot/vmlinuz 是符号链接，跳过该文件"
                    else
                        LogText "结果：磁盘上没有 ${ROOTDIR}boot/vmlinuz，尝试查找 ${ROOTDIR}boot/vmlinuz*"
                    fi
                    # Extra current kernel version and replace dashes to allow numeric ${SORTBINARY} later on
                    MYKERNEL=$(${UNAMEBINARY} -r | ${SEDBINARY} 's/\.[a-z].*.//g' | ${SEDBINARY} 's/-[a-z].*.//g' | ${SEDBINARY} 's/-/./g')
                    LogText "结果：使用 ${MYKERNEL} 作为我的内核版本（已删除）"
                    FIND=$(ls ${ROOTDIR}boot/vmlinuz* 2> /dev/null)
                    if [ -n "${FIND}" ]; then
                        for ITEM in ${FIND}; do
                            LogText "结果：找到${ITEM}"
                        done
                        # Display kernels, extract version numbers and ${SORTBINARY} them numeric per column (up to 6 numbers)
                        # Ignore rescue images. Remove generic. and huge. for Slackware machines
                        # TODO: see if this can be simplified using ls -v sorting
                        LogText "行动：检查相关内核"
                        KERNELS=$(${LSBINARY} /boot/vmlinuz* | ${GREPBINARY} -v rescue | ${SEDBINARY} 's/vmlinuz-//' | ${SEDBINARY} 's/generic.//' | ${SEDBINARY} 's/huge.//' | ${SEDBINARY} 's/\.[a-z].*.//g' | ${SEDBINARY} 's/-[a-z].*.//g' | ${SEDBINARY} 's./boot/..' | ${SEDBINARY} 's/-/./g' | ${SORTBINARY} -n -k1,1 -k2,2 -k3,3 -k4,4 -k5,5 -k6,6 -t \.)
                        KERNELS_ONE_LINE=$(${ECHOCMD} ${KERNELS} | ${TRBINARY} '\n' ' ')
                        LogText "输出：${KERNELS_ONE_LINE}"
                    elif [ ! "$(ls ${ROOTDIR}boot/kernel* 2> /dev/null)" = "" ]; then
                        LogText "输出：在 ${ROOTDIR}boot 中找到内核文件"
                        # Display kernels, extract version numbers and ${SORTBINARY} them numeric per column (up to 6 numbers)
                        # Examples:
                        # /boot/kernel-genkernel-x86_64-3.14.14-gentoo
                        KERNELS=$(${LSBINARY} ${ROOTDIR}boot/kernel* | ${AWKBINARY} -F- '{ if ($2=="genkernel") { print $4 }}' | ${GREPBINARY} "^[0-9]" | ${SORTBINARY} -n -k1,1 -k2,2 -k3,3 -k4,4 -k5,5 -k6,6 -t \.)
                        if [ -n "${KERNELS}" ]; then LogText "输出：${KERNELS}"; fi
                    else
                        ReportException "${TEST_NO}:2" "在 /boot 中找不到任何 vmlinuz 或内核文件，情况异常"
                    fi
                    if [ -n "${KERNELS}" ]; then
                        FOUND_KERNEL=0
                        for I in ${KERNELS}; do
                            # Check if we already found a kernel and it is not equal to what we run (e.g. double versions may exist)
                            if [ ${FOUND_KERNEL} -eq 1 -a ! "${MYKERNEL}" = "${I}" ]; then
                                LogText "结果：发现内核 (${I}) 晚于活动内核 (${MYKERNEL})"
                                REBOOT_NEEDED=1
                            fi
                            if [ "${MYKERNEL}" = "${I}" ]; then
                                FOUND_KERNEL=1
                                LogText "结果：找到 ${I}（= 活动内核）"
                            else
                                LogText "结果：找到${I}"
                            fi
                        done
                        # Check if we at least found the kernel on disk
                        if [ ${FOUND_KERNEL} -eq 0 ]; then
                            ReportException "${TEST_NO}:3" "在磁盘上找不到当前运行的内核，情况异常"
                        else
                            # If we are not sure yet reboot it needed, but we found running kernel as last one on disk, we run latest kernel
                            if [ ${REBOOT_NEEDED} -eq 2 ]; then
                                LogText "结果：磁盘上当前运行的内核是最后一个条目，看起来已是最新版本"
                                REBOOT_NEEDED=0
                            fi
                        fi
                    fi
                fi
            # No files in /boot
            else
                LogText "结果：/boot 中没有文件，跳过此检查"
            fi
        else
            LogText "结果：/boot 不存在或没有读取文件的权限"
        fi

        # Attempt to check for Raspbian if reboot is needed
        # This check searches for apt package "raspberrypi-kernel-[package-date]", trys to extract the date of packaging from the filename
        # and compares that date with the currently running kernel's build date (uname -v).
        # Of course there can be a time difference between kernel build and kernel packaging, therefore a time difference of
        # 3 days is accepted and it is assumed with only 3 days apart, this must be the same kernel version.
        if [ ${REBOOT_NEEDED} -eq 2 ] && [ -d "${APT_ARCHIVE_DIRECTORY}" ]; then
            LogText "结果：发现目录 ${APT_ARCHIVE_DIRECTORY}，假定这是基于 Debian 的发行版"
            LogText "检查：尝试在 ${APT_ARCHIVE_DIRECTORY} 中找到 raspberrypi-kernel 文件并从文件名中提取包日期"

            FOUND_KERNEL_DATE=$(${FINDBINARY} ${APT_ARCHIVE_DIRECTORY} -name "raspberrypi-kernel*" -printf "%T@ %Tc %p\n" 2> /dev/null \
            | ${SORTBINARY} -nr | ${HEADBINARY} -1 | ${GREPBINARY} -o "raspberrypi-kernel.*deb" | ${GREPBINARY} -E -o "\.[0-9]+" | ${SEDBINARY} 's/\.//g')

            if [ -n "${FOUND_KERNEL_DATE}" ]; then
                FOUND_KERNEL_IN_SECONDS=$(date -d "${FOUND_KERNEL_DATE}" "+%s" 2> /dev/null)
            else
                LogText "结果：没有可提取的软件包日期，跳过此检查"
            fi

            if [ -n "${FOUND_KERNEL_IN_SECONDS}" ] && [ ${FOUND_KERNEL_IN_SECONDS} -gt 1 ]; then
                LogText "结果：收到包裹日期：${FOUND_KERNEL_DATE}（= ${FOUND_KERNEL_IN_SECONDS} 秒）"
                UNAME_OUTPUT="$(${UNAMEBINARY} -v 2> /dev/null)"
            else
                LogText "结果：无法提取软件包日期的秒数，跳过此检查"
            fi

            if [ -n "${UNAME_OUTPUT}" ]; then
                LogText "结果：从 'uname -v' 获取到输出"
                LogText "检查：尝试从 'uname -v' 输出中提取内核构建日期"
                next=""
                for part in ${UNAME_OUTPUT}; do
                    if [ -z "$next" ]; then
                        if [ "${part}" = "Mon" ] || [ "${part}" = "Tue" ] || [ "${part}" = "Wed" ] || [ "${part}" = "Thu" ] || [ "${part}" = "Fri" ] || [ "${part}" = "Sat" ] || [ "${part}" = "Sun" ]; then
                            next="month"
                        fi
                    elif [ "$next" = "month" ]; then
                        if [ $(${ECHOCMD} "${part}" | ${GREPBINARY} -E -c "[A-Z][a-z]") -ge 1 ]; then
                            UNAME_DATE_MONTH="${part}"
                            next="day"
                        fi
                    elif [ "${next}" = "day" ]; then
                        if [ $(${ECHOCMD} ${part} | ${GREPBINARY} -E -c "[0-9][0-9]") -ge 1 ]; then
                            UNAME_DATE_DAY="${part}"
                            next="time"
                        fi
                    elif [ "${next}" = "time" ]; then
                        if [ $(${ECHOCMD} ${part} | ${GREPBINARY} -E -c ":[0-9][0-9]:") -ge 1 ]; then
                            next="year"
                        fi
                    elif [ "${next}" = "year" ]; then
                        if [ $(${ECHOCMD} ${part} | ${GREPBINARY} -E -c "[0-9][0-9]") -ge 1 ]; then
                            UNAME_DATE_YEAR="${part}"
                            break
                        fi
                    fi
                done
                if [ -n "${UNAME_DATE_MONTH}" ] && [ -n "${UNAME_DATE_DAY}" ] && [ -n "${UNAME_DATE_YEAR}" ]; then
                    LogText "结果：提取的内核构建日期为：${UNAME_DATE_DAY} ${UNAME_DATE_MONTH} ${UNAME_DATE_YEAR}"
                    UNAME_DATE_IN_SECONDS=$(date -d "${UNAME_DATE_DAY} ${UNAME_DATE_MONTH} ${UNAME_DATE_YEAR}" "+%s" 2> /dev/null)
                    LogText "检查：将内核构建日期（以秒为单位）（${UNAME_DATE_IN_SECONDS}s）与包日期（以秒为单位）（${FOUND_KERNEL_IN_SECONDS}s）进行比较"
                    if [ -n "${UNAME_DATE_IN_SECONDS}" ] && [ ${FOUND_KERNEL_IN_SECONDS} -ge ${UNAME_DATE_IN_SECONDS} ]; then
                        LogText "结果：软件包创建日期早于运行中的内核，因此此检查应有效。"
                        LogText "检查包创建日期和内核构建日期是否相差不超过 3 天。"

                        SECONDS_APART=$(( ${FOUND_KERNEL_IN_SECONDS} - ${UNAME_DATE_IN_SECONDS} ))
                        if [ ${SECONDS_APART} -ge 60 ]; then
                            MINUTES_APART=$(( ${SECONDS_APART} / 60 ))
                            if [ ${MINUTES_APART} -ge 60 ]; then
                                DAYS_APART=$(( ${MINUTES_APART} / 60 ))
                                if [ ${DAYS_APART} -ge 24 ]; then DAYS_APART=$(( ${DAYS_APART} / 24 )); else DAYS_APART=0; fi
                            else
                                DAYS_APART=0
                            fi
                        else
                            DAYS_APART=0
                        fi
                        # assuming kernels are packaged definitely within 3 days. ACCEPTED_TIME_DIFF needs a value in seconds
                        ACCEPTED_TIME_DIFF=$((3 * 24 * 60 * 60))
                        if [ ${FOUND_KERNEL_IN_SECONDS} -le $((${UNAME_DATE_IN_SECONDS} + ${ACCEPTED_TIME_DIFF})) ]; then
                            LogText "结果：包创建日期和内核构建日期仅相隔 ${DAYS_APART} 天。"
                            LogText "结果：假设不需要重新启动。"
                            REBOOT_NEEDED=0
                        else
                            LogText "结果：包创建日期和内核构建日期相隔 ${DAYS_APART} 天。"
                            LogText "结果：假设需要重新启动。"
                            REBOOT_NEEDED=1
                        fi
                    else
                        LogText "结果：软件包创建日期早于运行中的内核，情况异常，此检查可能无效，正在跳过……"
                    fi
                else
                    LogText "结果：无法从 'uname -v' 输出中提取日、月和年"
                fi
            else
                LogText "结果：未从 'uname -v' 获取输出，跳过检查。"
            fi

        else
            LogText "结果：/var/cache/apt/archives/ 不存在"
        fi

        # Display discovered status
        if [ ${REBOOT_NEEDED} -eq 0 ]; then
            Display --indent 2 --text "- 检查是否需要重新启动" --result "${STATUS_NO}" --color GREEN
            AddHP 5 5
        elif [ ${REBOOT_NEEDED} -eq 1 ]; then
            Display --indent 2 --text "- 检查是否需要重新启动" --result "${STATUS_YES}" --color RED
            ReportWarning "${TEST_NO}" "很可能需要重新启动系统" "" "text:重新启动"
            AddHP 0 5
        else
            Display --indent 2 --text "- 检查是否需要重新启动" --result "${STATUS_UNKNOWN}" --color YELLOW
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

# EOF
