#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Squid
#
#################################################################################
#
    SQUID_DAEMON_CONFIG_LOCS="${ROOTDIR}etc ${ROOTDIR}etc/squid ${ROOTDIR}etc/squid3 ${ROOTDIR}usr/local/etc/squid ${ROOTDIR}usr/local/squid/etc"
    SQUID_DAEMON_CONFIG=""
    SQUID_DAEMON_UNSAFE_PORTS_LIST="22 23 25"
    SQUID_DAEMON_RUNNING=0
#
#################################################################################
#
    InsertSection "${SECTION_SQUID_SUPPORT}"
#
#################################################################################
#
    # Test        : SQD-3602
    # Description : Check for a running Squid daemon
    # Notes       : Search for squid(3) with a space, to avoid SquidGuard and other
    #               programs.
    Register --test-no SQD-3602 --weight L --network NO --category security --description "检查正在运行的 Squid 守护进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 Squid 守护进程"
        FOUND=0
        # Check running processes
        FIND=$(${PSBINARY} ax | ${GREPBINARY} -E "(squid|squid3) " | ${GREPBINARY} -v "grep")
        if [ -n "${FIND}" ]; then
            SQUID_DAEMON_RUNNING=1
            LogText "结果：Squid 守护进程正在运行"
            Display --indent 2 --text "- 正在检查运行中的 Squid 守护进程" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未发现正在运行的 Squid 守护进程"
            Display --indent 2 --text "- 正在检查运行中的 Squid 守护进程" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : SQD-3604
    # Description : Determine Squid daemon configuration file location
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3604 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 守护进程配置文件位置"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 squid.conf 或 squid3.conf 文件"
        for I in ${SQUID_DAEMON_CONFIG_LOCS}; do
            # Checking squid.conf
            if [ -f "${I}/squid.conf" ]; then
                LogText "结果：${I}/squid.conf 存在"
                SQUID_DAEMON_CONFIG="${I}/squid.conf"
            fi
            # Checking squid3.conf
            if [ -f "${I}/squid3.conf" ]; then
                LogText "结果：${I}/squid3.conf 存在"
                SQUID_DAEMON_CONFIG="${I}/squid3.conf"
            fi
        done
        if [ -z "${SQUID_DAEMON_CONFIG}" ]; then
            LogText "结果：未找到 Squid 配置文件"
            Display --indent 4 --text "- 搜索 Squid 配置文件" --result "${STATUS_NOT_FOUND}" --color YELLOW
        else
            LogText "结果：使用最后找到的配置文件：${SQUID_DAEMON_CONFIG}"
            Display --indent 4 --text "- 搜索 Squid 配置" --result "${STATUS_FOUND}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : SQD-3606
    # Description : Check Squid version
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3606 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 版本"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${SQUIDBINARY}" ]; then
            LogText "结果：发现 Squid 可执行文件（${SQUIDBINARY}）"
            # Skip check if a setuid/setgid bit is found
            FIND=$(${FINDBINARY} ${SQUIDBINARY} \( -perm 4000 -o -perm 2000 \) -print)
            if [ -z "${FIND}" ]; then
                FIND2=$(${SQUIDBINARY} -v | ${AWKBINARY} '{ if ($3=="Version") { print $4 } }')
                Display --indent 4 --text "- 正在检查 Squid 版本" --result "${STATUS_FOUND}" --color GREEN
                SQUID_VERSION="${FIND2}"
            else
                LogText "结果：出于安全原因跳过检查，因为设置了 setuid/setgid 位"
                Display --indent 4 --text "- 正在检查 Squid 版本" --result "${STATUS_SKIPPED}" --color RED
            fi
        else
            LogText "结果：未找到 Squid 可执行文件"
        fi
    fi
#
#################################################################################
#
    # Test        : SQD-3610
    # Description : Check Squid configuration options
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3610 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "收集 Squid 配置选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：${SQUID_DAEMON_CONFIG} 中所有明确定义的选项"
        FIND=$(${GREPBINARY} -v "^#" ${SQUID_DAEMON_CONFIG} | ${GREPBINARY} -v "^$" | ${AWKBINARY} '{gsub("\t"," ");print}' | ${SEDBINARY} 's/ /!space!/g')
        for I in ${FIND}; do
            I=$(echo ${I} | ${SEDBINARY} 's/!space!/ /g')
            LogText "发现 Squid 选项：${I}"
            Report "squid_option=${I}"
        done
        Display --indent 4 --text "- 正在检查已定义的 Squid 选项" --result "${STATUS_DONE}" --color GREEN
    fi
#
#################################################################################
#
    # Test        : SQD-3613
    # Description : Check Squid configuration file permissions
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3613 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 文件权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：${SQUID_DAEMON_CONFIG} 的文件权限"
        FIND=$(find -L ${SQUID_DAEMON_CONFIG} -type f -a \( -perm -004 -o -perm -002 -o -perm -001 \))
        if [ -n "${FIND}" ]; then
            LogText "结果：文件 ${SQUID_DAEMON_CONFIG} 可被所有用户读取、写入或执行，可能泄露信息或密码"
            Display --indent 4 --text "- 正在检查 Squid 配置文件权限" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "检查 ${SQUID_DAEMON_CONFIG} 的文件权限并限制访问"
            ReportWarning "${TEST_NO}" "${SQUID_DAEMON_CONFIG} 的文件权限限制不足"
            AddHP 0 2
        else
            LogText "结果：文件 ${SQUID_DAEMON_CONFIG} 的权限设置正确"
            Display --indent 4 --text "- 正在检查 Squid 配置文件权限" --result "${STATUS_OK}" --color GREEN
            AddHP 2 2
        fi
    fi
#
#################################################################################
#
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then
        Display --indent 4 --text "- 正在检查 Squid 访问控制"
    fi
#
#################################################################################
#
    # Test        : SQD-3614
    # Description : Check Squid authentication
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3614 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 身份验证方法"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：auth_param 选项中的身份验证方法"
        FIND=$(${GREPBINARY} "^auth_param" ${SQUID_DAEMON_CONFIG} | ${AWKBINARY} '{ print $2 }')
        if [ -z "${FIND}" ]; then
            LogText "未找到 auth_param 选项，代理访问可能为匿名访问或基于其他方式（例如 ACL）"
            Display --indent 6 --text "- 正在检查 Squid 身份验证方法" --result "${STATUS_NONE}" --color YELLOW
        else
            Display --indent 6 --text "- 正在检查 Squid 身份验证方法" --result "${STATUS_FOUND}" --color GREEN
            for I in ${FIND}; do
                LogText "结果：发现身份验证方法 ${I}"
                Report "squid_auth_method=${I}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : SQD-3616
    # Description : Check external Squid authentication
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3616 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 外部身份验证"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：external_acl_类型 选项中的外部身份验证辅助程序"
        FIND=$(${GREPBINARY} "^external_acl_type" ${SQUID_DAEMON_CONFIG})
        if [ -z "${FIND}" ]; then
            LogText "未找到 external_acl_类型"
            Display --indent 6 --text "- 正在检查 Squid 外部身份验证方法" --result "${STATUS_NONE}" --color YELLOW
        else
            Display --indent 6 --text "- 正在检查 Squid 外部身份验证方法" --result "${STATUS_FOUND}" --color GREEN
            for I in ${FIND}; do
                LogText "结果：发现外部身份验证辅助程序"
                LogText "输出：${FIND}"
                #Report "squid_external_acl_type=TRUE"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : SQD-3620
    # Description : Check ACLs
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a ! "${SQUID_DAEMON_CONFIG}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3620 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 访问控制列表"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "检查：ACL"
        FIND=$(${GREPBINARY} "^acl " ${SQUID_DAEMON_CONFIG} | ${SEDBINARY} 's/ /!space!/g')
        if [ "${FIND}" = "" ]; then
            LogText "结果：未发现 ACL"
            Display --indent 6 --text "- 正在检查访问控制列表" --result "${STATUS_NONE}" --color RED
        else
            for ITEM in ${FIND}; do
                COUNT=$((COUNT + 1))
                ITEM=$(echo ${ITEM} | ${SEDBINARY} 's/!space!/ /g')
                LogText "发现 ACL：${ITEM}"
                #Report "squid_acl=${ITEM}" # TODO
            done
            LogText "结果：发现 ${COUNT} 个 ACL"
            Display --indent 6 --text "- 正在检查访问控制列表" --result "发现 ${COUNT} 个 ACL" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : SQD-3624
    # Description : Check insecure ports in Safe_ports list
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a ! "${SQUID_DAEMON_CONFIG}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3624 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 安全端口"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：ACL Safe_端口 的 http_access 选项"
        FIND=$(${GREPBINARY} "^http_access" ${SQUID_DAEMON_CONFIG} | ${GREPBINARY} "Safe_ports")
        if IsEmpty "${FIND}"; then
            LogText "结果：未发现 Safe_端口"
            Display --indent 6 --text "- 正在检查 ACL 'Safe_ports' 的 http_access 选项" --result "${STATUS_NOT_FOUND}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "检查 Squid 是否已配置为仅允许访问安全端口"
        else
            LogText "结果：正在检查 ACL 安全端口"
            FIND2=$(${GREPBINARY} "^acl Safe_ports port" ${SQUID_DAEMON_CONFIG} | ${AWKBINARY} '{ print $4 }')
            if IsEmpty "${FIND2}"; then
                Display --indent 6 --text "- 正在检查 ACL 'Safe_ports' 端口" --result "未发现" --color YELLOW
                ReportSuggestion "${TEST_NO}" "检查 Squid 是否已配置允许出站流量使用的端口（Safe_端口）"
                AddHP 0 1
            else
                LogText "结果：发现 Safe_端口"
                for ITEM in ${FIND}; do
                    LogText "发现安全端口：${ITEM}"
                done
                Display --indent 6 --text "- 正在检查 ACL 'Safe_ports' 端口" --result "${STATUS_FOUND}" --color GREEN
                AddHP 1 1
            fi

            for ITEM in ${SQUID_DAEMON_UNSAFE_PORTS_LIST}; do
                LogText "检查：Safe_端口 列表中的端口 ${ITEM}"
                FIND2=$(${GREPBINARY} -w "^acl Safe_ports port ${ITEM}" ${SQUID_DAEMON_CONFIG})
                if IsEmpty "${FIND2}"; then
                    Display --indent 6 --text "- 正在检查 ACL 'Safe_ports'（端口 ${ITEM}）" --result "${STATUS_NOT_FOUND}" --color GREEN
                    AddHP 1 1
                else
                    Display --indent 6 --text "- 正在检查 ACL 'Safe_ports'（端口 ${ITEM}）" --result "${STATUS_FOUND}" --color RED
                    ReportWarning "${TEST_NO}" "Squid 配置可能允许通过已配置的 Safe_端口 ${ITEM} 中继流量"
                    AddHP 0 1
                fi
            done
        fi
    fi
#
#################################################################################
#
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then
        Display --indent 4 --text "- 正在检查 Squid 拒绝服务防护调优选项"
    fi
#
#################################################################################
#
    # Test        : SQD-3630 [T]
    # Description : Check reply_body_max_size value
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3630 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid reply_body_max_size 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：reply_body_max_size 选项"
        FIND=$(${GREPBINARY} "^reply_body_max_size " ${SQUID_DAEMON_CONFIG} | ${SEDBINARY} 's/ /!space!/g')
        if IsEmpty "${FIND}"; then
            LogText "结果：未配置 reply_body_max_size 选项"
            Display --indent 6 --text "- 正在检查选项：reply_body_max_size" --result "${STATUS_NONE}" --color RED
            AddHP 1 2
            ReportSuggestion "${TEST_NO}" "配置 Squid 的 reply_body_max_size 选项，以限制响应内容的最大大小。"
        else
            LogText "结果：已配置 reply_body_max_size 选项"
            LogText "输出：${FIND}"
            Display --indent 6 --text "- 正在检查选项：reply_body_max_size" --result "${STATUS_FOUND}" --color GREEN
            AddHP 2 2
        fi
    fi
#
#################################################################################
#
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then
        Display --indent 4 --text "- 正在检查 Squid 常规选项"
    fi
#
#################################################################################
#
    # Test        : SQD-3680
    # Description : Check httpd_suppress_version_string
    if [ ${SQUID_DAEMON_RUNNING} -eq 1 -a -n "${SQUID_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SQD-3680 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Squid 版本信息隐藏设置"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${GREPBINARY} "^httpd_suppress_version_string " ${SQUID_DAEMON_CONFIG} | ${GREPBINARY} " on")
        if [ -z "${FIND}" ]; then
            LogText "结果：未配置 httpd_suppress_版本_字符串 选项"
            Display --indent 6 --text "- 正在检查选项：httpd_suppress_版本_字符串" --result "${STATUS_NOT_FOUND}" --color YELLOW
            AddHP 1 2
            ReportSuggestion "${TEST_NO}" "将 Squid 的 httpd_suppress_版本_字符串 选项配置为 在，以隐藏版本信息。"
        else
            LogText "结果：已配置 httpd_suppress_版本_字符串 选项"
            LogText "输出：${FIND}"
            Display --indent 6 --text "- 正在检查选项：httpd_suppress_版本_字符串" --result "${STATUS_FOUND}" --color GREEN
            AddHP 2 2
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

# EOF
