#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
#  USB Devices
#
#################################################################################
#
    InsertSection "${SECTION_USB_DEVICES}"
#
#################################################################################
#
    USBGUARD_FOUND=0
    USBGUARD_CONFIG=""
    USBGUARD_RULES=""
    USBGUARD_RESTORE_POLICY=""
    USBGUARD_CONTROLLER_POLICY=""
    USBGUARD_DEVICE_POLICY=""
    USBGUARD_INSERTED_POLICY=""
    USBGUARD_DEFAULT_POLICY=""
    USBGUARD_RULES_ALLOW=0
    USBGUARD_RULES_BLOCK=0
    USBGUARD_RULES_REJECT=0
#
#################################################################################
#
    # Test to determine if USBGuard is installed.  If it is, we will limit
    # suggestions from other tests.
    if [ -n "${USBGUARDBINARY}" ]; then
        USBGUARD_FOUND=1
    fi
#
#################################################################################
#
    # Test        : USB-1000 (was STRG-1840)
    # Description : Check for disabled USB storage
    Register --test-no USB-1000 --os Linux --weight L --network NO --category security --description "检查是否禁用 USB 存储"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查：/etc/modprobe.d 目录和 /etc/modprobe.conf 配置文件中的 USB 存储驱动"
        if [ -d /etc/modprobe.d ]; then
            FIND=$(${LSBINARY} ${ROOTDIR}etc/modprobe.d/* 2> /dev/null)
            if [ -n "${FIND}" ]; then
                FIND=$(${GREPBINARY} -E -r "install usb[-_]storage /bin/(false|true)" ${ROOTDIR}etc/modprobe.d/* | ${GREPBINARY} -v "#")
                FIND2=$(${GREPBINARY} -E -r "^blacklist usb[-_]storage" ${ROOTDIR}etc/modprobe.d/*)
                if [ -n "${FIND}" -o -n "${FIND2}" ]; then
                    FOUND=1
                    LogText "结果：发现 usb-storage 驱动已被禁用（列入黑名单）"
                fi
            else
                LogText "结果：发现 /etc/modprobe.d 目录，但其中没有文件，这种情况较少见"
            fi
        fi
        if [ -f ${ROOTDIR}etc/modprobe.conf ]; then
            FIND=$(${GREPBINARY} -E "install usb[-_]storage /bin/(false|true)" ${ROOTDIR}etc/modprobe.conf | ${GREPBINARY} "usb-storage" | ${GREPBINARY} -v "#")
            if [ -n "${FIND}" ]; then
                FOUND=1
                LogText "结果：发现 usb-storage 驱动已被禁用"
            fi
        fi
        if [ ${FOUND} -eq 0 ]; then
            LogText "结果：usb-storage 驱动未被明确禁用"
            Display --indent 2 --text "- 正在检查 usb-storage 驱动（modprobe 配置）" --result "${STATUS_NOT_DISABLED}" --color WHITE
            if [ "${USBGUARD_FOUND}" -eq "0" ]; then
                ReportSuggestion "${TEST_NO}" "不使用 USB 存储等驱动时将其禁用，以防止未经授权的存储设备接入或数据被窃取"
            fi
            AddHP 2 3
        else
            LogText "结果：usb-storage 驱动已禁用"
            Display --indent 2 --text "- 正在检查 usb-storage 驱动（modprobe 配置）" --result "${STATUS_DISABLED}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : USB-2000 (was STRG-1842)
    # Description : Check USB authorizations
    Register --test-no USB-2000 --os Linux --weight L --network NO --category security --description "检查 USB 授权状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        USBDEVICESPATH="${ROOTDIR}sys/bus/usb/devices"
        LogText "检查：USB 设备路径是否存在（${USBDEVICESPATH}）"
        if [ -d "${USBDEVICESPATH}" ]; then

            LogText "检查：USB 设备连接系统时的授权状态"
            for device in $(find ${USBDEVICESPATH} -name "usb*" -type l -print); do
                if [ -e "${device}/authorized" -o -e "${device}/authorized_default" ]; then
                    if [ "$(cat "${device}/authorized_default")" = "1" ]; then
                        FOUND=1
                        LogText "检查：${device} 默认获得授权（authorized_default=1）"
                        Report "usb_authorized_default_device[]=${device}"
                    fi
                    if [ "$(cat "${device}/authorized")" = "1" ]; then
                        FOUND=1
                        LogText "检查：${device} 当前已授权（authorized=1）"
                        Report "usb_authorized_device[]=${device}"
                    fi
                else
                    LogText "检查：未发现 authorized 或 authorized_default 文件，假定 ${device} 默认获得授权"
                    Report "usb_authorized_default_device[]=${device}"
                    FOUND=1
                fi
            done

            if [ ${FOUND} -eq 1 ]; then
                LogText "结果：部分 USB 设备默认或临时获准连接系统"
                Display --indent 2 --text "- 正在检查 USB 设备授权" --result "${STATUS_ENABLED}" --color YELLOW
                # TODO: create documentation and enable the suggestion
                #if [ ${USBGUARD_FOUND} -eq 0 ]; then
                #   ReportSuggestion "${TEST_NO}" "Disable USB devices authorization, to prevent unauthorized storage or data theft"
                #fi
                AddHP 0 3
            else
                LogText "结果：没有 USB 设备默认或临时获准连接系统"
                Display --indent 2 --text "- 正在检查 USB 设备授权" --result "${STATUS_DISABLED}" --color GREEN
                AddHP 3 3
            fi
        else
            LogText "结果：设备路径不存在"
        fi
    fi

#
#################################################################################
#
    # Test        : USB-3000
    # Description : Perform USBGuard check
    Register --test-no USB-3000  --os Linux --weight L --network NO --category security --description "检查是否安装 USBGuard"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ ${USBGUARD_FOUND} -eq 1 ]; then
            LogText "结果：已安装 USBGuard（${USBGUARDBINARY}）"
            Display --indent 2 --text "- 正在检查 USBGuard" --result "${STATUS_FOUND}" --color GREEN
            AddHP 1 1

            LogText "正在检查 USBGuard 配置文件"
            if [ -f ${ROOTDIR}etc/usbguard/usbguard-daemon.conf ]; then
                USBGUARD_CONFIG="${ROOTDIR}etc/usbguard/usbguard-daemon.conf"
            else
                USBGUARD_CONFIG=""
            fi

            if [ -n "${USBGUARD_CONFIG}" ]; then
                LogText "结果：发现 USBGuard 配置（${USBGUARD_CONFIG}）"
                Display --indent 4 --text "- 配置" --result "${STATUS_FOUND}" --color GREEN
                AddHP 1 1

                LogText "正在检查 USBGuard 控制器设备状态恢复设置（RestoreControllerDeviceState）"
                USBGUARD_RESTORE_POLICY=$(${AWKBINARY} -F '=' -v OPT="RestoreControllerDeviceState" 'index($0, OPT) == 1 {print $2}' ${USBGUARD_CONFIG})
                if [ -n "${USBGUARD_RESTORE_POLICY}" ]; then
                    LogText "结果：RestoreControllerDeviceState = ${USBGUARD_RESTORE_POLICY}"
                    case "${USBGUARD_RESTORE_POLICY}" in
                        "true")
                            Display --indent 6 --text "- 恢复控制器设备状态" --result "${USBGUARD_RESTORE_POLICY}" --color YELLOW
                            LogText " 建议将 RestoreControllerDeviceState 改为 \\"false\\""
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Consider hardening USBGuard configuration" "RestoreControllerDeviceState (${USBGUARD_RESTORE_POLICY} --> false)"
                            AddHP 0 1
                            ;;
                        "false")
                            Display --indent 6 --text "- 恢复控制器设备状态" --result "${USBGUARD_RESTORE_POLICY}" --color GREEN
                            AddHP 1 1
                            ;;
                        *)
                            LogText "结果：RestoreControllerDeviceState 配置无效"
                            Display --indent 6 --text "- 恢复控制器设备状态" --result "无效" --color RED
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Fix USBGuard configuration" "RestoreControllerDeviceState invalid \"${USBGUARD_RESTORE_POLICY}\""
                            AddHP 0 1
                            ;;
                    esac

                else
                    LogText "结果：未找到 RestoreControllerDeviceState"
                    Display --indent 6 --text "- 恢复控制器设备状态" --result "未找到" --color WHITE
                    AddHP 0 1
                fi

                LogText "正在检查守护进程启动前已连接控制器的 USBGuard 规则（PresentControllerPolicy）"
                USBGUARD_CONTROLLER_POLICY=$(${AWKBINARY} -F '=' -v OPT="PresentControllerPolicy" 'index($0, OPT) == 1 {print $2}' ${USBGUARD_CONFIG})
                if [ -n "${USBGUARD_CONTROLLER_POLICY}" ]; then
                    LogText "结果：PresentControllerPolicy = ${USBGUARD_CONTROLLER_POLICY}"
                    case "${USBGUARD_CONTROLLER_POLICY}" in
                        "allow" | "keep")
                            Display --indent 6 --text "- 守护进程启动前已连接控制器的规则" --result "${USBGUARD_CONTROLLER_POLICY}" --color YELLOW
                            LogText " 建议将 PresentControllerPolicy 改为 \\"apply-policy\\"、\\"block\\" 或 \\"reject\\""
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Consider hardening USBGuard configuration" "PresentControllerPolicy (${USBGUARD_CONTROLLER_POLICY} --> (apply-policy|block|reject)"
                            AddHP 0 1
                            ;;
                        "apply-policy" | "block" | "reject")
                            Display --indent 6 --text "- 守护进程启动前已连接控制器的规则" --result "${USBGUARD_CONTROLLER_POLICY}" --color GREEN
                            AddHP 1 1
                            ;;
                        *)
                            LogText "结果：PresentControllerPolicy 配置无效"
                            Display --indent 6 --text "- 守护进程启动前已连接控制器的规则" --result "无效" --color RED
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Fix USBGuard configuration" "PresentControllerPolicy invalid \"${USBGUARD_CONTROLLER_POLICY}\""
                            AddHP 0 1
                            ;;
                    esac
                else
                    LogText "结果：未找到 PresentControllerPolicy"
                    Display --indent 6 --text "- 守护进程启动前已连接控制器的规则" --result "未找到" --color WHITE
                    AddHP 0 1
                fi

                LogText "正在检查守护进程启动前已连接设备的 USBGuard 规则（PresentDevicePolicy）"
                USBGUARD_DEVICE_POLICY=$(${AWKBINARY} -F '=' -v OPT="PresentDevicePolicy" 'index($0, OPT) == 1 {print $2}' ${USBGUARD_CONFIG})
                if [ -n "${USBGUARD_DEVICE_POLICY}" ]; then
                    LogText "结果：PresentDevicePolicy = ${USBGUARD_DEVICE_POLICY}"
                    case "${USBGUARD_DEVICE_POLICY}" in
                        "allow" | "keep")
                            Display --indent 6 --text "- 守护进程启动前已连接设备的规则" --result "${USBGUARD_DEVICE_POLICY}" --color YELLOW
                            LogText " 建议将 PresentDevicePolicy 改为 \\"apply-policy\\"、\\"block\\" 或 \\"reject\\""
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Consider hardening USBGuard configuration" "PresentDevicePolicy (${USBGUARD_DEVICE_POLICY} --> (apply-policy|block|reject)"
                            AddHP 0 1
                            ;;
                        "apply-policy" | "block" | "reject")
                            Display --indent 6 --text "- 守护进程启动前已连接设备的规则" --result "${USBGUARD_DEVICE_POLICY}" --color GREEN
                            AddHP 1 1
                            ;;
                        *)
                            LogText "结果：PresentDevicePolicy 配置无效"
                            Display --indent 6 --text "- 守护进程启动前已连接设备的规则" --result "无效" --color RED
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Fix USBGuard configuration" "PresentDevicePolicy invalid \"${USBGUARD_DEVICE_POLICY}\""
                            AddHP 0 1
                            ;;
                    esac
                else
                    LogText "结果：未找到 PresentDevicePolicy"
                    Display --indent 6 --text "- 守护进程启动前已连接设备的规则" --result "未找到" --color WHITE
                    AddHP 0 1
                fi

                LogText "正在检查守护进程启动后插入设备的 USBGuard 规则（InsertedDevicePolicy）"
                USBGUARD_INSERTED_POLICY=$(${AWKBINARY} -F '=' -v OPT="InsertedDevicePolicy" 'index($0, OPT) == 1 {print $2}' ${USBGUARD_CONFIG})
                if [ -n "${USBGUARD_INSERTED_POLICY}" ]; then
                    LogText "结果：InsertedDevicePolicy = ${USBGUARD_INSERTED_POLICY}"
                    case "${USBGUARD_INSERTED_POLICY}" in
                        "allow" | "keep")
                            Display --indent 6 --text "- 守护进程启动后插入设备的规则" --result "${USBGUARD_INSERTED_POLICY}" --color YELLOW
                            LogText " 建议将 InsertedDevicePolicy 改为 \\"apply-policy\\"、\\"block\\" 或 \\"reject\\""
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Consider hardening USBGuard configuration" "InsertedDevicePolicy (${USBGUARD_INSERTED_POLICY} --> (apply-policy|block|reject)"
                            AddHP 0 1
                            ;;
                        "apply-policy" | "block" | "reject")
                            Display --indent 6 --text "- 守护进程启动后插入设备的规则" --result "${USBGUARD_INSERTED_POLICY}" --color GREEN
                            AddHP 1 1
                            ;;
                        *)
                            LogText "结果：InsertedDevicePolicy 配置无效"
                            Display --indent 6 --text "- 守护进程启动后插入设备的规则" --result "无效" --color RED
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Fix USBGuard configuration" "InsertedDevicePolicy invalid \"${USBGUARD_INSERTED_POLICY}\""
                            AddHP 0 1
                            ;;
                    esac
                else
                    LogText "结果：未找到 InsertedDevicePolicy"
                    Display --indent 6 --text "- 守护进程启动后插入设备的规则" --result "未找到" --color WHITE
                    AddHP 0 1
                fi

                LogText "正在检查 RuleFile 中未列出设备的 USBGuard 规则（ImplicitPolicyTarget）"
                USBGUARD_DEFAULT_POLICY=$(${AWKBINARY} -F '=' -v OPT="ImplicitPolicyTarget" 'index($0, OPT) == 1 {print $2}' ${USBGUARD_CONFIG})
                if [ -n "${USBGUARD_DEFAULT_POLICY}" ]; then
                    LogText "结果：ImplicitPolicyTarget = ${USBGUARD_DEFAULT_POLICY}"
                    case "${USBGUARD_DEFAULT_POLICY}" in
                        "allow")
                            Display --indent 6 --text "- RuleFile 中未列出设备的规则" --result "${USBGUARD_DEFAULT_POLICY}" --color YELLOW
                            LogText " 建议将 ImplicitPolicyTarget 改为 \\"block\\" 或 \\"reject\\""
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Consider hardening USBGuard configuration" "ImplicitPolicyTarget (${USBGUARD_DEFAULT_POLICY} --> (block|reject)"
                            AddHP 0 1
                            ;;
                        "block"|"reject")
                            Display --indent 6 --text "- RuleFile 中未列出设备的规则" --result "${USBGUARD_DEFAULT_POLICY}" --color GREEN
                            AddHP 1 1
                            ;;
                        *)
                            LogText "结果：ImplicitPolicyTarget 配置无效"
                            Display --indent 6 --text "- RuleFile 中未列出设备的规则" --result "无效" --color RED
                            # TODO: assign TEST_NO, create documentation, and enable the suggestion
                            # ReportSuggestion "${TEST_NO}" "Fix USBGuard configuration" "ImplicitPolicyTarget invalid \"${USBGUARD_DEFAULT_POLICY}\""
                            AddHP 0 1
                            ;;
                    esac
                else
                    LogText "结果：未找到 ImplicitPolicyTarget"
                    Display --indent 4 --text "- RuleFile 中未列出设备的规则" --result "未找到" --color WHITE
                    AddHP 0 1
                fi

                LogText "正在检查 RuleFile"
                USBGUARD_RULES=$(${AWKBINARY} -F '=' -v OPT="RuleFile" 'index($0, OPT) == 1 {print $2}' ${USBGUARD_CONFIG})
                if [ -n "${USBGUARD_RULES}" ] && [ -f "${USBGUARD_RULES}" ]; then
                    LogText "结果：发现 RuleFile（${USBGUARD_RULES}）"
                    Display --indent 4 --text "- RuleFile" --result "${STATUS_FOUND}" --color GREEN
                    AddHP 1 1

                    USBGUARD_RULES_ALLOW=$(${GREPBINARY} -E -c "^allow" ${USBGUARD_RULES})
                    Display --indent 6 --text "- 允许的控制器和设备" --result "${USBGUARD_RULES_ALLOW}" --color WHITE
                    USBGUARD_RULES_BLOCK=$(${GREPBINARY} -E -c "^block" ${USBGUARD_RULES})
                    Display --indent 6 --text "- 阻止的控制器和设备" --result "${USBGUARD_RULES_BLOCK}" --color WHITE
                    USBGUARD_RULES_REJECT=$(${GREPBINARY} -E -c "^reject" ${USBGUARD_RULES})
                    Display --indent 6 --text "- 拒绝的控制器和设备" --result "${USBGUARD_RULES_REJECT}" --color WHITE
                else
                    LogText "结果：未找到 RuleFile（安装初始策略的方法请参阅 man usbguard）"
                    Display --indent 4 --text "- RuleFile" --result "${STATUS_NOT_FOUND}" --color RED
                    # To-Be-Added: assign TEST_NO, create documentation, and enable the suggestion
                    #ReportSuggestion "${TEST_NO}" "Install USBGuard RuleFile" "\"man usbguard\" for instructions to install initial policies"
                    AddHP 0 1
                fi

            else
                Display --indent 4 --text "- 配置" --result "${STATUS_NOT_FOUND}" --color WHITE
                LogText "结果：未找到配置"
                # To-Be-Added: assign TEST_NO, create documentation, and enable the suggestion
                #ReportSuggestion "${TEST_NO}" "USBGuard configuration file not found, consider reinstalling"
                AddHP 0 7
            fi
        else
            LogText "结果：未找到 USBGuard"
            Display --indent 2 --text "- 正在检查 USBGuard" --result "${STATUS_NOT_FOUND}" --color WHITE
            # To-Be-Added: assign TEST_NO, create documentation, and enable the suggestion
            #ReportSuggestion "${TEST_NO}" "Install USBGuard to allow for fine-grained control of USB authorization"
            AddHP 0 8
        fi

    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
