#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
    InsertSection "${SECTION_HARDENING}"

    # COMPILER_INSTALLED is initialized before
    HARDEN_COMPILERS_NEEDED=0
#
#################################################################################
#
    # Test        : HRDN-7220
    # Description : Check for installed compilers
    # Notes       : No suggestion for hardening compilers, as HRDN-7222 will take care of that
    Register --test-no HRDN-7220 --weight L --network NO --category security --description "检查是否安装了一个或多个编译器"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：系统中是否存在一个或多个编译器"
        if [ ${COMPILER_INSTALLED} -eq 0 ]; then
            LogText "结果：未发现编译器"
            Display --indent 4 --text "- 已安装的编译器" --result "${STATUS_NOT_FOUND}" --color GREEN
            AddHP 3 3
        else
            LogText "结果：发现已安装的编译器；请查看日志文件开头列出的编译器，或使用 ${GREPBINARY} 过滤 'compiler'"
            Display --indent 4 --text "- 已安装的编译器" --result "${STATUS_FOUND}" --color RED
            AddHP 1 3
        fi
    fi
#
#################################################################################
#
    # Test        : HRDN-7222
    # Description : Check for permissions of installed compilers
    Register --test-no HRDN-7222 --weight L --network NO --category security --description "检查编译器权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：系统中是否存在一个或多个编译器"
        HARDEN_COMPILERS_NEEDED=0
        if [ ${COMPILER_INSTALLED} -eq 0 ]; then
            LogText "结果：未发现编译器"
        else
            # TODO - c89 c99 cpp ld
            TEST_BINARIES="${ASBINARY} ${CCBINARY} ${CLANGBINARY} ${GCCBINARY}"
            for ITEM in ${TEST_BINARIES}; do
                FILE="${ITEM}"
                LogText "检查：文件 ${ITEM} 的权限"
                ShowSymlinkPath ${ITEM}
                if [ -n "${SYMLINK}" ]; then
                    FILE="${SYMLINK}"
                fi

                if IsWorldExecutable ${FILE}; then
                    LogText "可执行文件：发现 ${FILE}（所有用户均可执行）"
                    Report "compiler_world_executable[]=${FILE}"
                    AddHP 2 3
                    HARDEN_COMPILERS_NEEDED=1
                else
                    AddHP 3 3
                fi
            done

            # Report suggestion is one or more compilers can be better hardened
            if [ ${HARDEN_COMPILERS_NEEDED} -eq 1 ]; then
                LogText "结果：至少一个编译器可以通过仅允许 root 或指定组执行来进一步加固"
                ReportSuggestion "${TEST_NO}" "加固编译器，例如仅允许 root 用户访问"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : HRDN-7230
    # Description : Check for installed malware scanners
    Register --test-no HRDN-7230 --weight L --network NO --category security --description "检查恶意软件扫描器"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：是否安装了恶意软件扫描器"
        if [ ${MALWARE_SCANNER_INSTALLED} -eq 1 ]; then
            LogText "结果：发现至少一个恶意软件扫描器"
            Display --indent 4 --text "- 已安装的恶意软件扫描器" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        else
            LogText "结果：未发现恶意软件扫描器"
            if [ "${MACHINE_ROLE}" = "personal" ]; then
                Display --indent 4 --text "- 已安装的恶意软件扫描器" --result "${STATUS_NOT_FOUND}" --color YELLOW
            else
                Display --indent 4 --text "- 已安装的恶意软件扫描器" --result "${STATUS_NOT_FOUND}" --color RED
            fi
            ReportSuggestion "${TEST_NO}" "安装至少一个恶意软件扫描器并定期扫描文件系统，以加强系统安全" "-" "安装 rkhunter、chkrootkit、OSSEC 或 Wazuh 等工具"
            AddHP 1 3
            LogText "结果：未发现恶意软件扫描器"
        fi
    fi
#
#################################################################################
#
    # Test        : HRDN-7231
    # Description : Check for registered non-native binary formats
    Register --test-no HRDN-7231  --os Linux --weight L --network NO --category security --description "检查已注册的非原生二进制格式"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：已注册的非原生二进制格式"
        NFORMATS=0
        if [ -d /proc/sys/fs/binfmt_misc ]; then
            NFORMATS=$(${FINDBINARY} /proc/sys/fs/binfmt_misc -type f -not -name register -not -name status | ${WCBINARY} -l)
        fi
        if [ ${NFORMATS} -eq 0 ]; then
            LogText "结果：未发现非原生二进制格式"
            Display --indent 4 --text "- 非原生二进制格式" --result "${STATUS_NOT_FOUND}" --color GREEN
        else
            FORMATS=$(${FINDBINARY} /proc/sys/fs/binfmt_misc -type f -not -name register -not -name status -printf '%f ')
            LogText "结果：发现 ${NFORMATS} 个已注册的非原生二进制格式：${FORMATS}"
            Display --indent 4 --text "- 非原生二进制格式" --result "${STATUS_FOUND}" --color RED
        fi
    fi
#
#################################################################################
#
#    LogText "--------------------------------------------------------------------"
#    LogText "| System part                        | Preferred value | Actual value | Points |"
#    LogText "| [!] Compiler installed               |              0  | [${COMPILER_INSTALLED}]     | x  |"
#    LogText "| [V] Malware scanner installed        |              1  | [x]     | x  |"
#    LogText "| [V] Packet filter enabled            |              1  | [x]     | x  |"
#    LogText "--------------------------------------------------------------------"
#    LogText "| [!]: Hardening possible,  [V]: Hardening performed,  [ ]: Unknown "
#    LogText "--------------------------------------------------------------------"
#
#################################################################################
#

Report "compiler_installed=${COMPILER_INSTALLED}"
WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
