#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
    APPARMORFOUND=0                     # Set default for test MACF-6208
    MAC_FRAMEWORK_ACTIVE=0              # Default no MAC framework active
    RBAC_FRAMEWORK_ACTIVE=0             # Default no RBAC framework active
    SELINUXFOUND=0
    TOMOYOFOUND=0

    InsertSection "${SECTION_SECURITY_FRAMEWORKS}"
#
#################################################################################
#
    # Test        : MACF-6204
    # Description : Check if AppArmor is installed
    Register --test-no MACF-6204 --weight L --network NO --category security --description "检查 AppArmor presence"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -z "${AASTATUSBINARY}" ]; then
            APPARMORFOUND=0
            LogText "结果： aa-status 程序 未找到, AppArmor 不 已安装"
            Display --indent 2 --text "- 检查 presence AppArmor" --result "${STATUS_NOT_FOUND}" --color WHITE
        else
            APPARMORFOUND=1
            LogText "结果：发现 aa-status 程序，已安装 AppArmor"
            Display --indent 2 --text "- 检查 presence AppArmor" --result "${STATUS_FOUND}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : MACF-6208
    # Description : Check AppArmor active status
    if [ ${APPARMORFOUND} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MACF-6208 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 如果 AppArmor 是 已启用"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${AASTATUSBINARY}" ]; then
            CAN_READ_FILE=0
            FILE="/sys/kernel/security/apparmor/profiles"
            if [ -f ${FILE} ]; then
                FIND=$(${CAT_BINARY} ${FILE} 2> /dev/null)
                if [ $? -eq 0 ]; then CAN_READ_FILE=1; fi
            else
                LogText "文件 ${FILE} 不存在"
            fi
            if [ ${CAN_READ_FILE} -eq 1 ]; then
                LogText "结果： 文件 ${FILE} 是 可用 和 可读"
                # Checking AppArmor status
                # 0 if apparmor is enabled and policy is loaded.
                # 1 if apparmor is not enabled/loaded.
                # 2 if apparmor is enabled but no policy is loaded.
                # 3 if control files are not available
                # 4 if apparmor status can't be read
                FIND=$(${AASTATUSBINARY} 2>&1 > /dev/null)
                if [ $? -eq 0 ]; then
                    MAC_FRAMEWORK_ACTIVE=1
                    LogText "结果： AppArmor 是 已启用 和 一个 策略 是 已加载"
                    Display --indent 4 --text "- 检查 AppArmor 状态" --result "${STATUS_ENABLED}" --color GREEN
                    Report "apparmor_enabled=1"
                    Report "apparmor_policy_loaded=1"
                    AddHP 3 3
                    # ignore kernel threads (Parent PID = 2 [kthreadd])
                    NUNCONFINED=$(${PSBINARY} -N --ppid 2 -o label | ${GREPBINARY} '^unconfined' | ${WCBINARY} -l)
                    Display --indent 8 --text "发现 ${NUNCONFINED} unconfined 进程"
                    for PROCESS in $(${PSBINARY} -N --ppid 2 -o label:1,pid,comm | ${GREPBINARY} '^unconfined' | ${TRBINARY} ' ' ':'); do
                        LogText "结果： Unconfined 进程： ${PROCESS}"
                    done
                elif [ $? -eq 4 ]; then
                    LogText "结果：无法确定状态，很可能是权限不足"
                    Display --indent 4 --text "- 检查 AppArmor 状态" --result "${STATUS_UNKNOWN}" --color RED
                elif [ $? -eq 3 ]; then
                    LogText "结果： 可以 不 检查 控制 文件"
                    Display --indent 4 --text "- 检查 AppArmor 状态" --result "${STATUS_UNKNOWN}" --color RED
                elif [ $? -eq 2 ]; then
                    LogText "结果：AppArmor 已启用，但未加载策略"
                    ReportSuggestion "${TEST_NO}" "加载 AppArmor 策略"
                    Display --indent 4 --text "- 检查 AppArmor 状态" --result "NON-ACTIVE" --color GREEN
                    Report "apparmor_enabled=1"
                    Report "apparmor_policy_loaded=0"
                    AddHP 0 3
                elif [ $? -eq 1 ]; then
                    LogText "结果： AppArmor 是 已禁用"
                    Display --indent 4 --text "- 检查 AppArmor 状态" --result "${STATUS_DISABLED}" --color YELLOW
                    Report "apparmor_enabled=0"
                    AddHP 0 3
                else
                    Display --indent 4 --text "- 检查 AppArmor 状态" --result "${STATUS_UNKNOWN}" --color RED
                    ReportException "${TEST_NO}:1" "无效 或 未知 AppArmor 状态 检测到"
                fi
            else
                LogText "结果： 无法找到 或 读取 ${FILE}"
                Display --indent 4 --text "- 检查 AppArmor 状态" --result "${STATUS_UNKNOWN}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "检查 输出 的 aa-status" "${FILE}" "text：运行 aa-status"
            fi
        else
            LogText "结果： 没有 aa-status 程序 可用"
        fi
    fi
#
#################################################################################
#
    # Test        : MACF-6232
    # Description : Check SELINUX for installation
    Register --test-no MACF-6232 --weight L --network NO --category security --description "检查 SELINUX presence"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 如果 we 有 sestatus 程序"
        if [ -n "${SESTATUSBINARY}" ]; then
            LogText "结果： 发现 sestatus 程序 (${SESTATUSBINARY})"
            Display --indent 2 --text "- 检查 presence SELinux" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果： sestatus 程序 未找到"
            Display --indent 2 --text "- 检查 presence SELinux" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : MACF-6234
    # Description : Check SELINUX status
    if HasData "${SESTATUSBINARY}"; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MACF-6234 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 SELINUX 状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Status: Enabled/Disabled
        FIND=$(${SESTATUSBINARY} | ${GREPBINARY} "^SELinux status" | ${AWKBINARY} '{ print $3 }')
        if [ "${FIND}" = "enabled" ]; then
            MAC_FRAMEWORK_ACTIVE=1
            LogText "结果： SELinux 框架 是 已启用"
            Report "selinux_status=1"
            SELINUXFOUND=1
            Display --indent 4 --text "- 检查 SELinux 状态" --result "${STATUS_ENABLED}" --color GREEN
            FIND=$(${SESTATUSBINARY} | ${GREPBINARY} "^Current mode" | ${AWKBINARY} '{ print $3 }')
            Report "selinux_mode=${FIND}"
            FIND2=$(${SESTATUSBINARY} | ${GREPBINARY} "^Mode from config file" | ${AWKBINARY} '{ print $5 }')
            LogText "结果： 当前 SELinux 模式 是 ${FIND}"
            LogText "结果： 模式 已配置 在 config 文件 是 ${FIND2}"
            if [ "${FIND}" = "${FIND2}" ]; then
                LogText "结果： 当前 SELinux 模式 是 相同 作为 在 config 文件."
                Display --indent 6 --text "- 检查 当前 模式 和 config 文件" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果： 当前 SELinux 模式 (${FIND}) 是 NOT 相同 作为 在 config 文件 (${FIND2})."
                ReportWarning "${TEST_NO}" "当前 SELinux 模式与配置文件不同（当前：${FIND}，配置文件：${FIND2}）"
                Display --indent 6 --text "- 检查 当前 模式 和 config 文件" --result "${STATUS_WARNING}" --color RED
            fi
            Display --indent 8 --text "当前 SELinux 模式： ${FIND}"
            if [ -n "${SEMANAGEBINARY}" ]; then
                PERMISSIVE=$(${SEMANAGEBINARY} permissive --list --noheading | ${TRBINARY} '\n' ' ')
                NPERMISSIVE=$(${SEMANAGEBINARY} permissive --list --noheading | ${WCBINARY} -l)
                Display --indent 8 --text "发现 ${NPERMISSIVE} permissive SELinux object types"
                LogText "Permissive SELinux object types： ${PERMISSIVE}"
            else
                LogText "结果：未找到 semanage 程序，无法分析宽容域"
            fi
            UNCONFINED=$(${PSBINARY} -eo label,pid,command | ${GREPBINARY} '[u]nconfined_t' | ${TRBINARY} '\n' ' ')
            INITRC=$(${PSBINARY} -eo label,pid,command | ${GREPBINARY} '[i]nitrc_t' | ${TRBINARY} '\n' ' ')
            NUNCONFINED=$(${PSBINARY} -eo label | ${GREPBINARY} '[u]nconfined_t' | ${WCBINARY} -l)
            NINITRC=$(${PSBINARY} -eo label | ${GREPBINARY} '[i]nitrc_t' | ${WCBINARY} -l)
            Display --indent 8 --text "发现 ${NUNCONFINED} unconfined 和 ${NINITRC} initrc_t 进程"
            LogText "Unconfined 进程： ${UNCONFINED}"
            LogText "进程 使用 initrc_t 类型： ${INITRC}"
        else
            LogText "结果： SELinux 框架 是 已禁用"
            Display --indent 4 --text "- 检查 SELinux 状态" --result "${STATUS_DISABLED}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : MACF-6240
    # Description : Check if the tomoyo-init binary is available on the system
    Register --test-no MACF-6240 --weight L --network NO --category security --description "检查 TOMOYO Linux presence"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查： 检查 如果 we 有 tomoyo-init 程序"
        if [ -z "${TOMOYOINITBINARY}" ]; then
            TOMOYOFOUND=0
            LogText "结果： tomoyo-init 程序 未找到"
            Display --indent 2 --text "- 检查 presence TOMOYO Linux" --result "${STATUS_NOT_FOUND}" --color WHITE
        else
            TOMOYOFOUND=1
            LogText "结果： tomoyo-init 程序 发现"
            Display --indent 2 --text "- 检查 presence TOMOYO Linux" --result "${STATUS_FOUND}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : MACF-6242
    # Description : Check TOMOYO Linux status
    if [ ${TOMOYOFOUND} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MACF-6242 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 TOMOYO Linux 状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        FILE="/sys/kernel/security/tomoyo/stat"
        if [ -f ${FILE} ]; then
            MAC_FRAMEWORK_ACTIVE=1
            LogText "结果： TOMOYO Linux 是 已启用"
            Display --indent 4 --text "- 检查 TOMOYO Linux 状态" --result "${STATUS_ENABLED}" --color GREEN
            Report "tomoyo_enabled=1"
            if [ ! -z ${TOMOYOPSTREEBINARY} ]; then
                NUNCONFINED=$(${TOMOYOPSTREEBINARY} | ${GREPBINARY} -v '^  3 ' | ${WCBINARY} -l)
                Display --indent 8 --text "发现 ${NUNCONFINED} unconfined (不 配置文件 3) 进程"
                for PROCESS in $(${TOMOYOPSTREEBINARY} | ${GREPBINARY} -v '^  3 ' | ${SEDBINARY} -e 's/+-//g' -e 's/^ *//g' -e 's/ \+/:/g' | ${SORTBINARY}); do
                    LogText "结果： Unconfined 进程： ${PROCESS}"
                done
            fi
            AddHP 3 3
        else
            LogText "结果： TOMOYO Linux 是 已禁用"
            Display --indent 4 --text "- 检查 TOMOYO Linux 状态" --result "${STATUS_DISABLED}" --color YELLOW
            Report "tomoyo_enabled=0"
            AddHP 0 3
        fi
    fi
#
#################################################################################
#
    # Test        : RBAC-6272
    # Description : Check if grsecurity is installed
    # Notes       : We already checked grsecurity in osdetection
    Register --test-no RBAC-6272 --weight L --network NO --category security --description "检查 grsecurity presence"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check Linux kernel configuration
        if [ -n "${LINUXCONFIGFILE}" -a -f "${LINUXCONFIGFILE}" ]; then
            FIND=$(${GREPBINARY} ^CONFIG_GRKERNSEC=y ${LINUXCONFIGFILE})
            if [ ! "${FIND}" = "" ]; then
                LogText "结果： grsecurity 可用 (在 内核 config)"
                GRSEC_FOUND=1
            else
                LogText "结果： 没有 grsecurity 发现 在 内核 config"
            fi
        fi
        if [ ${GRSEC_FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 检查 presence grsecurity" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        else
            Display --indent 2 --text "- 检查 presence grsecurity" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
        if HasData "${GRADMBINARY}"; then
            FIND=$(${GRADMBINARY} --status 2>/dev/null)
            if [ "${FIND}" = "The RBAC system is currently enabled." ]; then
                MAC_FRAMEWORK_ACTIVE=1
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : MACF-6290
    # Description : Check if at least one MAC framework is implemented
    Register --test-no MACF-6290 --weight L --network NO --category security --description "检查 用于 已实现 MAC 框架"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ ${MAC_FRAMEWORK_ACTIVE} -eq 1 ]; then
            Display --indent 2 --text "- 检查 用于 已实现 MAC 框架" --result "${STATUS_OK}" --color GREEN
            AddHP 3 3
            LogText "结果： 发现 已实现 MAC 框架"
        else
            Display --indent 2 --text "- 检查 用于 已实现 MAC 框架" --result "${STATUS_NONE}" --color YELLOW
            AddHP 2 3
            LogText "结果： 发现 没有 已实现 MAC 框架"
        fi
     fi
#
#################################################################################
#

Report "framework_grsecurity=${GRSEC_FOUND}"
Report "framework_selinux=${SELINUXFOUND}"

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
