#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# E-mail and messaging
#
#################################################################################
#
    InsertSection "${SECTION_EMAIL_AND_MESSAGING}"
#
#################################################################################
#
    DOVECOT_RUNNING=0
    EXIM_RUNNING=0
    EXIM_TYPE=""
    IMAP_DAEMON=""
    OPENSMTPD_RUNNING=0
    POP3_DAEMON=""
    POSTFIX_RUNNING=0
    QMAIL_RUNNING=0
    SENDMAIL_RUNNING=0
    SMTP_DAEMON=""
#
#################################################################################
#
    # Test        : MAIL-8802
    # Description : Check Exim process status
    Register --test-no MAIL-8802 --weight L --network NO --category security --description "检查Exim状态"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查Exim状态"
        if IsRunning "exim4" || IsRunning "exim"; then
            LogText "结果：发现运行Exim进程"
            Display --indent 2 --text "- Exim 状态" --result "${STATUS_RUNNING}" --color GREEN
            EXIM_RUNNING=1
            SMTP_DAEMON="exim"
            Report "smtp_daemon[]=exim"
        else
            LogText "结果：未找到正在运行的 Exim 进程"
            if IsVerbose; then Display --indent 2 --text "- Exim 状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8804
    # Description : Exim configuration options
    if [ ${EXIM_RUNNING} -eq 1 -a ! "${EXIMBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MAIL-8804 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "Exim 配置选项"
    if [ ${SKIPTEST} -eq 0 -a ${EXIM_RUNNING} -eq 1 ]; then
        LogText "测试：Exim配置选项"

        EXIM_ROUTERS=$(${EXIMBINARY} -bP router_list)

        unset FIND FIND2 FIND3 FIND4

        # Local Only
        FIND=$(echo "${EXIM_ROUTERS}" | ${GREPBINARY} -E '^nonlocal')
        # Internet Host
        FIND2=$(echo "${EXIM_ROUTERS}" | ${GREPBINARY} -E '^dnslookup_relay_to_domains')
        # Smarthost or Satellite
        FIND3=$(echo "${EXIM_ROUTERS}" | ${GREPBINARY} -E '^smarthost')

        if [ -n "${FIND}" ]; then
            EXIM_TYPE="LOCAL ONLY"
        elif [ -n "${FIND2}" ]; then
            EXIM_TYPE="INTERNET HOST"
        elif [ -n "${FIND3}" ]; then
            FIND4=$(echo "${EXIM_ROUTERS}" | ${GREPBINARY} -E '^hub_user_smarthost')
            if [ -n "${FIND4}" ]; then
                EXIM_TYPE="SATELLITE"
            else
                EXIM_TYPE="SMARTHOST"
            fi
        fi

        if [ -n "${EXIM_TYPE}" ]; then
            LogText "结果：Exim 类型 - ${EXIM_TYPE}"
            Display --indent 4 --text "- 类型" --result "${EXIM_TYPE}" --color GREEN
        else
            LogText "结果：Exim 类型 - 未配置"
            Display --indent 4 --text "- 类型" --result "${STATUS_NOT_CONFIGURED}" --color WHITE
        fi

        if [ "${EXIM_TYPE}" = "INTERNET HOST" -o "${EXIM_TYPE}" = "SMARTHOST" ]; then
            LogText "测试：Exim 公共接口"
            EXIM_IP=$(${EXIMBINARY} -bP local_interfaces | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/\s*<\s*\;\?//' -e 's/\s*::0\s*\;\?//' -e 's/\s*127.0.0.1\s*\;\?//' -e 's/^\s*//' -e 's/\s*$//')
            if [ -n "${EXIM_IP}" ]; then
                LogText "结果：${EXIM_IP}"
                Display --indent 4 --text "- 公共接口" --result "${EXIM_IP}" --color GREEN
            else
                LogText "结果：无"
                Display --indent 4 --text "- 公共接口" --result "NONE" --color WHITE
            fi

            LogText "测试： Exim TLS 状态"
            EXIM_TLS=$(${EXIMBINARY} -bP tls_advertise_hosts | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
            if [ -n "${EXIM_TLS}" ]; then
                LogText "结果：启用"
                Display --indent 4 --text "- TLS" --result "${STATUS_ENABLED}" --color GREEN
            else
                LogText "结果：未启用"
                Display --indent 4 --text "- TLS" --result "${STATUS_DISABLED}" --color WHITE
            fi
        fi

        if [ -n "${EXIM_TYPE}" -a "${EXIM_TYPE}" != "LOCAL ONLY" ]; then
            LogText "测试：Exim 证书和私钥"

            case "${EXIM_TYPE}" in
                "INTERNET HOST" | "SMARTHOST" )
                    EXIM_CERTIFICATE=$(${EXIMBINARY} -bP tls_certificate | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    EXIM_PRIVATEKEY=$(${EXIMBINARY} -bP tls_privatekey | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    ;;
                "SATELLITE" )
                    EXIM_CERTIFICATE=$(${EXIMBINARY} -bP transport remote_smtp_smarthost | ${GREPBINARY} tls_certificate | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    EXIM_PRIVATEKEY=$(${EXIMBINARY} -bP transport remote_smtp_smarthost | ${GREPBINARY} tls_privatekey | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    ;;
            esac

            if [ -n "${EXIM_CERTIFICATE}" ]; then
                LogText "结果：${EXIM_CERTIFICATE}"
                if [ -f "${EXIM_CERTIFICATE}" ]; then
                    Display --indent 4 --text "- 证书" --result "${STATUS_FOUND}" --color GREEN
                    LogText "结果：找到证书"
                else
                    Display --indent 4 --text "- 证书" --result "${STATUS_NOT_FOUND}" --color YELLOW
                    LogText "结果：未找到证书"
                fi
            else
                LogText "结果：证书未设置"
                Display --indent 4 --text "- 证书" --result "${STATUS_NOT_CONFIGURED}" --color WHITE
            fi

            if [ -n "${EXIM_PRIVATEKEY}" ]; then
                LogText "结果：${EXIM_PRIVATEKEY}"
                if [ -f "${EXIM_PRIVATEKEY}" ]; then
                    LogText "结果：找到私钥"
                    Display --indent 4 --text "- 私钥" --result "${STATUS_FOUND}" --color GREEN
                else
                    Display --indent 4 --text "- 私钥" --result "${STATUS_NOT_FOUND}" --color YELLOW
                    LogText "结果：未找到私钥"
                fi
            else
                LogText "结果：私钥未设置"
                Display --indent 4 --text "- 私钥" --result "${STATUS_NOT_CONFIGURED}" --color WHITE
            fi

            LogText "测试：Exim 验证证书"

            case "${EXIM_TYPE}" in
                "INTERNET HOST" | "SMARTHOST" )
                    EXIM_CERTIFICATES=$(${EXIMBINARY} -bP tls_verify_certificate | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    ;;
                "SATELLITE" )
                    EXIM_CERTIFICATES=$(${EXIMBINARY} -bP transport remote_smtp_smarthost | ${GREPBINARY} tls_verify_certificate | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    ;;
            esac

            case "${EXIM_CERTIFICATES}" in
                "")
                    # This condition results in a RED warning because it should never be hit
                    LogText "结果：验证证书未设置"
                    Display --indent 4 --text "- 验证证书未设置" --result "${STATUS_WARNING}" --color RED
                    ;;
                "system")
                    # This is the default setting and should be the most common
                    LogText "结果：验证证书设置为系统默认值"
                    Display --indent 4 --text "- 验证证书" --result "DEFAULT" --color WHITE
                    ;;
                *)
                    # This condition should only be hit when it has been set to a custom value
                    LogText "结果：验证证书设置为 \\"${EXIM_CERTIFICATES}\\""
                    Display --indent 4 --text "- 验证证书" --result "CUSTOM" --color GREEN
                    ;;
            esac


            case "${EXIM_TYPE}" in
                "INTERNET HOST" | "SMARTHOST" )
                    EXIM_VERIFY_HOSTS=$(${EXIMBINARY} -bP tls_verify_hosts | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    EXIM_TRY_VERIFY_HOSTS=$(${EXIMBINARY} -bP tls_try_verify_hosts | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    ;;
                "SATELLITE" )
                    EXIM_VERIFY_HOSTS=$(${EXIMBINARY} -bP transport remote_smtp_smarthost | ${GREPBINARY} tls_verify_hosts | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    EXIM_TRY_VERIFY_HOSTS=$(${EXIMBINARY} -bP transport remote_smtp_smarthost | ${GREPBINARY} tls_try_verify_hosts | ${CUTBINARY} -d '=' -f2 | ${SEDBINARY} -e 's/^\s*//' -e 's/\s*$//')
                    ;;
            esac

            LogText "测试：Exim 尝试验证主机"
            if [ -n "${EXIM_TRY_VERIFY_HOSTS}" ]; then
                LogText "结果：尝试验证主机已启用"
                case "${EXIM_TYPE}" in
                    "INTERNET HOST" )
                        Display --indent 4 --text "- 尝试验证主机" --result "${STATUS_ENABLED}" --color GREEN
                        ;;
                    "SATELLITE" | "SMARTHOST" )
                        Display --indent 4 --text "- 尝试验证主机" --result "${STATUS_ENABLED}" --color YELLOW
                        ;;
                esac
            else
                LogText "结果：尝试验证主机未启用"
                Display --indent 4 --text "- 尝试验证主机" --result "${STATUS_DISABLED}" --color WHITE
            fi

            LogText "测试：Exim 验证主机"
            if [ -n "${EXIM_VERIFY_HOSTS}" ]; then
                LogText "结果：验证主机已启用"
                case "${EXIM_TYPE}" in
                    "INTERNET HOST" )
                        Display --indent 4 --text "- 验证主机" --result "${STATUS_ENABLED}" --color YELLOW
                        ;;
                    "SATELLITE" | "SMARTHOST" )
                        Display --indent 4 --text "- 验证主机" --result "${STATUS_ENABLED}" --color GREEN
                        ;;
                esac
            else
                LogText "结果：验证主机未启用"
                Display --indent 4 --text "- 验证主机" --result "${STATUS_DISABLED}" --color WHITE
            fi
        fi
    fi

#
#################################################################################
#
    # Test        : MAIL-8814
    # Description : Check Postfix process
    # Notes       : qmgr and pickup run under postfix uid, without full path to binary
    Register --test-no MAIL-8814 --weight L --network NO --category security --description "检查postfix进程状态"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查Postfix状态"
        # Some other processes also use master, therefore it should include both master and postfix
        FIND1=$(${PSBINARY} ax | ${GREPBINARY} "master" | ${GREPBINARY} "postfix" | ${GREPBINARY} -v "grep")
        if [ -n "${FIND1}" ]; then
            LogText "结果：发现运行Postfix进程"
            Display --indent 2 --text "- Postfix 状态" --result "${STATUS_RUNNING}" --color GREEN
            POSTFIX_RUNNING=1
            SMTP_DAEMON="postfix"
            Report "smtp_daemon[]=postfix"
        else
            LogText "结果：未找到正在运行的 Postfix 进程"
            if IsVerbose; then Display --indent 2 --text "- Postfix 状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8816
    # Description : Check Postfix configuration
    if [ ${POSTFIX_RUNNING} -eq 1 -a ! "${POSTFIXBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MAIL-8816 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查Postfix配置"
    if [ ${SKIPTEST} -eq 0  ]; then
        Display --indent 4 --text "- Postfix配置" --result "${STATUS_FOUND}" --color GREEN
        POSTFIX_CONFIGDIR=$(${POSTCONFBINARY} 2> /dev/null | ${GREPBINARY} '^config_directory' | ${AWKBINARY} '{ print $3 }')
        POSTFIX_CONFIGFILE="${POSTFIX_CONFIGDIR}/main.cf"
        LogText "Postfix配置目录：${POSTFIX_CONFIGDIR}"
        LogText "Postfix 配置文件：${POSTFIX_CONFIGFILE}"
    fi
#
#################################################################################
#
    # Test        : MAIL-8817
    # Description : Check Postfix configuration for error
    if [ ${POSTFIX_RUNNING} -eq 1 -a ! "${POSTFIXBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MAIL-8817 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查Postfix配置错误"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：使用postconf查看Postfix配置是否有错误"
        FIND=$(${POSTCONFBINARY} 2>&1 | ${GREPBINARY} "warning:")
        if [ -n "${FIND}" ]; then
            Report "postfix_config_error=1"
            Display --indent 6 --text "- Postfix 配置错误" --result "${STATUS_WARNING}" --color RED
            LogText "结果：在 Postfix 配置中发现错误或警告。建议手动检查。"
            ReportSuggestion "${TEST_NO}" "发现 Postfix 配置错误" "${POSTFIX_CONFIGFILE}" "text:运行 postconf > /dev/null"
        else
            LogText "结果：Postfix 配置看起来一切正常"
            if IsVerbose; then Display --indent 6 --text "- Postfix 配置错误" --result "${STATUS_OK}" --color GREEN; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8818
    # Description : Check Postfix configuration
    if [ ${POSTFIX_RUNNING} -eq 1 -a ! "${POSTFIXBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MAIL-8818 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Postfix 配置：横幅"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查 Postfix 横幅"
        FIND1=$(${POSTCONFBINARY} 2> /dev/null | ${GREPBINARY} '^smtpd_banner' | ${GREPBINARY} 'postfix')
        FIND2=$(${POSTCONFBINARY} 2> /dev/null | ${GREPBINARY} '^smtpd_banner' | ${GREPBINARY} '$mail_name')
        FIND3=$(${POSTCONFBINARY} 2> /dev/null | ${GREPBINARY} '^mail_name' | ${GREPBINARY} -i 'postfix')
        FIND4=$(${POSTCONFBINARY} 2> /dev/null | ${GREPBINARY} '^smtpd_banner' | ${GREPBINARY} -i "${OS}")
        if [ -n "${LINUX_VERSION}" ]; then
            FIND5=$(${POSTCONFBINARY} 2> /dev/null | ${GREPBINARY} '^smtpd_banner' | ${GREPBINARY} -i "${LINUX_VERSION}")
        fi
        SHOWWARNING=0

        if [ -n "${FIND1}" ]; then
            SHOWWARNING=1
            Report "banner_software_disclosure[]=${FIND1}"
        elif [ -n "${FIND2}" -a -n "${FIND3}" ]; then
            SHOWWARNING=1
            Report "banner_software_disclosure[]=${FIND2}"
        elif [ -n "${FIND4}" ]; then
            SHOWWARNING=1
            Report "banner_os_disclosure[]=${FIND4}"
        elif [ -n "${FIND5}" ]; then
            SHOWWARNING=1
            Report "banner_os_disclosure[]=${FIND5}"
        fi

        if [ ${SHOWWARNING} -eq 1 ]; then
            Display --indent 6 --text "- Postfix 横幅" --result "${STATUS_WARNING}" --color RED
            LogText "结果：SMTP 横幅中发现操作系统或 mail_name，或者 mail_name 包含 'Postfix'。"
            ReportWarning "${TEST_NO}" "在SMTP横幅（OS或软件名称）中发现一些信息泄露"
            ReportSuggestion "${TEST_NO}" "建议您从 postfix 配置中隐藏 mail_name（选项：smtpd_banner）。使用 postconf -e or 更改您的 main.cf 文件 (${POSTFIX_CONFIGFILE})"
        else
            if IsVerbose; then Display --indent 6 --text "- Postfix 横幅" --result "${STATUS_OK}" --color GREEN; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8820
    Register --test-no MAIL-8820 --weight L --network NO --category security --description "Postfix配置扫描"
    if [ ${SKIPTEST} -eq 0  ]; then
        if [ "$(postconf -h inet_interfaces 2> /dev/null)" = "all" ]; then
            if ! SkipAtomicTest "${TEST_NO}:disable_vrfy_command"; then
                if [ "$(postconf -h disable_vrfy_command 2> /dev/null)" = "no" ]; then
                    ReportSuggestion "${TEST_NO}:disable_vrfy_command" "禁用 'VRFY' 命令" "disable_vrfy_command=no" "text:运行 postconf -e disable_vrfy_command=yes 修改该值"
                fi
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8838
    # Description : Check Dovecot process
    Register --test-no MAIL-8838 --weight L --network NO --category security --description "检查鸽舍进程"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查鸽舍状态"
        if IsRunning "dovecot"; then
            LogText "结果：发现正在运行的 dovecot 进程"
            Display --indent 2 --text "- 鸽舍状态" --result "${STATUS_RUNNING}" --color GREEN
            DOVECOT_RUNNING=1
            IMAP_DAEMON="dovecot"
            POP3_DAEMON="dovecot"
            Report "pop3_daemon[]=dovecot"
            Report "imap_daemon[]=dovecot"
        else
            LogText "结果：未找到鸽舍"
            if IsVerbose; then Display --indent 2 --text "- 鸽舍状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8860
    # Description : Check Qmail process status
    Register --test-no MAIL-8860 --weight L --network NO --category security --description "检查Qmail状态"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查Qmail状态"
        if IsRunning "qmail-smtpd"; then
            LogText "结果：发现正在运行Qmail进程"
            Display --indent 2 --text "- Qmail状态" --result "${STATUS_RUNNING}" --color GREEN
            QMAIL_RUNNING=1
            SMTP_DAEMON="qmail"
            Report "smtp_daemon[]=qmail"
        else
            LogText "结果：未找到正在运行的 Qmail 进程"
            if IsVerbose; then Display --indent 2 --text "- Qmail状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8880
    # Description : Check Sendmail process status
    Register --test-no MAIL-8880 --weight L --network NO --category security --description "检查 Sendmail 状态"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查sendmail状态"
        if IsRunning "sendmail"; then
            LogText "结果：发现正在运行Sendmail进程"
            Display --indent 2 --text "- 发送邮件状态" --result "${STATUS_RUNNING}" --color GREEN
            SENDMAIL_RUNNING=1
            SMTP_DAEMON="sendmail"
            Report "smtp_daemon[]=sendmail"
        else
            LogText "结果：未找到正在运行的 Sendmail 进程"
            if IsVerbose; then Display --indent 2 --text "- 发送邮件状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : MAIL-8920
    # Description : Check OpenSMTPD process status
    if [ -n "${SMTPCTLBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no MAIL-8920 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查OpenSMTPD状态"
    if [ ${SKIPTEST} -eq 0  ]; then
        LogText "测试：检查 smtpd 状态"
        FIND=$(${PSBINARY} ax | ${GREPBINARY} -E "(/smtpd|smtpd: \[priv\]|smtpd: smtp)" | ${GREPBINARY} -v "grep")
        if [ ! "${FIND}" = "" ]; then
            LogText "结果：发现正在运行 smtpd 进程"
            Display --indent 2 --text "- OpenSMTPD 状态" --result "${STATUS_RUNNING}" --color GREEN
            OPENSMTPD_RUNNING=1
            Report "smtp_daemon[]=opensmtpd"
        else
            LogText "结果：找不到 smtpd"
            if IsVerbose; then Display --indent 2 --text "- OpenSMTPD 状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#

Report "imap_daemon=${IMAP_DAEMON}"
Report "pop3_daemon=${POP3_DAEMON}"
Report "smtp_daemon=${SMTP_DAEMON}"


WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
