#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Databases
#
#################################################################################
#
    # Paths to DATADIR
    sMYSQLDBPATHS="${ROOTDIR}var/lib/mysql"
    # Paths to my.cnf
    sMYCNFLOCS="${ROOTDIR}etc/mysql/my.cnf ${ROOTDIR}usr/etc/my.cnf"
    REDIS_CONFIGURATION_FILES=""
    REDIS_CONFIGURATION_FOUND=0

    MYSQL_RUNNING=0
    DATABASE_ENGINE_RUNNING=0
    MONGODB_RUNNING=0
    POSTGRESQL_RUNNING=0
    ORACLE_RUNNING=0
    DB2_RUNNING=0
    REDIS_RUNNING=0
#
#################################################################################
#
    InsertSection "${SECTION_DATABASES}"

    # Test        : DBS-1804
    # Description : Check if MySQL is being used
    Register --test-no DBS-1804 --weight L --network NO --category security --description "检查活动的 MySQL 进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${PSBINARY} ax | ${GREPBINARY} -E "mariadb|mysqld|mysqld_safe" | ${GREPBINARY} -v "grep")
        if [ -z "${FIND}" ]; then
            if [ ${DEBUG} -eq 1 ]; then Display --indent 2 --text "- MySQL 进程状态" --result "${STATUS_NOT_FOUND}" --color WHITE --debug; fi
            LogText "结果：MySQL 进程未运行"
        else
            Display --indent 2 --text "- MySQL 进程状态" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：MySQL 正在运行"
            MYSQL_RUNNING=1
            DATABASE_ENGINE_RUNNING=1
            Report "mysql_running=${MYSQL_RUNNING}"
        fi
    fi
#
#################################################################################
#
    # Test        : DBS-1808
    # Description : Check MySQL data directory
    #Register --test-no DBS-1808 --weight L --network NO --category security --description "Checking MySQL data directory"
    #if [ ${SKIPTEST} -eq 0 ]; then
    #fi
#
#################################################################################
#
    # Test        : DBS-1812
    # Description : Check data directory permissions
    #Register --test-no DBS-1812 --weight L --network NO --category security --description "Checking MySQL data directory permissions"
    #if [ ${SKIPTEST} -eq 0 ]; then
    #fi
#
#################################################################################
#
    # Test        : DBS-1816
    # Description : Check empty MySQL root password
    # Notes       : Only perform test when MySQL is running and client is available
    if [ -n "${MYSQLCLIENTBINARY}" -a ${MYSQL_RUNNING} -eq 1 ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="未安装 MySQL 或 MySQL 未运行"; fi
    Register --test-no DBS-1816 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "检查 MySQL root 密码"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：尝试不使用密码登录本地 MySQL 服务器"

        # "-u root --password=" avoids ~/.my.cnf authentication settings
        # "plugin = 'mysql_native_password' AND authentication_string = ''" avoids false positives when secure plugins are used
        FIND=$(${MYSQLCLIENTBINARY} --default-auth=mysql_native_password  --no-defaults -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user WHERE user = 'root' AND plugin = 'mysql_native_password' AND authentication_string = ''" mysql > /dev/null 2>&1; echo $?)
        if [ "${FIND}" = "0" ]; then
           LogText "结果：登录成功，MySQL root 账户未设置密码！"
           ReportWarning "${TEST_NO}" "MySQL root 账户未设置密码"
           Display --indent 4 --text "- 正在检查 MySQL root 空密码" --result "${STATUS_WARNING}" --color RED
           AddHP 0 5
        else
            LogText "结果：登录失败，说明 MySQL root 账户已设置密码"
            if IsVerbose; then Display --indent 4 --text "- 检查 MySQL root 密码" --result "${STATUS_OK}" --color GREEN; fi
            AddHP 2 2
        fi
    else
        LogText "检查已跳过：MySQL 守护进程未运行或没有可用的 MySQL 客户端"
    fi
#
#################################################################################
#
    # Test        : DBS-1818
    # Description : Check MongoDB status
    Register --test-no DBS-1818 --weight L --network NO --category security --description "检查 MongoDB 服务器状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        if IsRunning "mongod"; then
            MONGODB_RUNNING=1
            DATABASE_ENGINE_RUNNING=1
            Report "mongodb_running=1"
            Display --indent 2 --text "- MongoDB 状态" --result "${STATUS_FOUND}" --color GREEN
        fi
    fi

    # Test        : DBS-1820
    # Description : Check empty MongoDB authorization
    # Notes       : Authentication can be set via command line or configuration file
    Register --test-no DBS-1820 --weight L --network NO --category security --description "检查 MongoDB 授权配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        MONGODB_AUTHORIZATION_ENABLED=0
        if [ ${MONGODB_RUNNING} -eq 1 ]; then

            MONGO_CONF_FILES="${ROOTDIR}etc/mongod.conf ${ROOTDIR}etc/mongodb.conf"
            for FILE in ${MONGO_CONF_FILES}; do
                if [ -f ${FILE} ]; then
                    LogText "结果：发现 MongoDB 配置文件（${FILE}）"
                    # YAML with quotes
                    if [ ${MONGODB_AUTHORIZATION_ENABLED} -eq 0 ]; then
                        LogText "检查：确定新版 YAML 格式中的授权设置"
                        AUTH_IN_CONFIG=$(${GREPBINARY} "authorization: \"enabled\"" ${FILE} | ${GREPBINARY} -E -v "(^#|#auth)")
                        if HasData "${AUTH_IN_CONFIG}"; then
                            LogText "结果：正常，配置文件中已启用授权选项（带引号的 YAML 格式）"
                            MONGODB_AUTHORIZATION_ENABLED=1
                        fi
                    fi
                    # YAML without quotes
                    if [ ${MONGODB_AUTHORIZATION_ENABLED} -eq 0 ]; then
                        AUTH_IN_CONFIG=$(${GREPBINARY} "authorization: enabled" ${FILE} | ${GREPBINARY} -E -v "(^#|#auth)")
                        if HasData "${AUTH_IN_CONFIG}"; then
                            LogText "结果：正常，配置文件中已启用授权选项（不带引号的 YAML 格式）"
                            MONGODB_AUTHORIZATION_ENABLED=1
                        fi
                    fi
                    # Old style
                    if [ ${MONGODB_AUTHORIZATION_ENABLED} -eq 0 ]; then
                        LogText "结果：未在配置文件中发现已启用的授权选项（YAML 格式）"
                        LogText "检查：正在配置文件中搜索旧式配置（auth = true）"
                        AUTH_IN_CONFIG=$(${GREPBINARY} "auth = true" ${FILE} | ${GREPBINARY} -v "noauth" | ${GREPBINARY} -E -v "(^#|#auth)")
                        if IsEmpty "${AUTH_IN_CONFIG}"; then
                            LogText "结果：配置文件中未找到 auth = true"
                        else
                            LogText "结果：正常，配置文件中已启用授权选项（旧格式）"
                            MONGODB_AUTHORIZATION_ENABLED=1
                        fi
                    fi
                else
                    LogText "结果：未找到配置文件 ${FILE}"
                fi
            done

            # Now check authorization on the command line
            if [ ${MONGODB_AUTHORIZATION_ENABLED} -eq 0 ]; then
                if HasData "${PGREPBINARY}"; then
                    AUTH_ON_CMDLINE=$(for I in $(${PGREPBINARY} mongo); do cat /proc/${I}/cmdline | xargs -0 echo | ${GREPBINARY} -E "\-\-auth( |$)"; done)
                    if [ -n "${AUTH_ON_CMDLINE}" ]; then LogText "结果：发现已通过 mongod 参数启用授权"; MONGODB_AUTHORIZATION_ENABLED=1; fi
                else
                    LogText "结果：pgrep 不可用，跳过这部分检查"
                fi
            fi
            if [ ${MONGODB_AUTHORIZATION_ENABLED} -eq 0 ]; then
                LogText "结果：参数或配置文件中均未启用授权"
                Report "mongodb_authorization_disabled=1"
                ReportWarning "${TEST_NO}" "MongoDB 实例允许任何用户访问数据库"
                Display --indent 4 --text "- 正在检查 MongoDB 授权" --result "${STATUS_DISABLED}" --color RED
            else
                if IsVerbose; then Display --indent 4 --text "- 正在检查 MongoDB 授权" --result "${STATUS_ENABLED}" --color GREEN; fi
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : DBS-1826
    # Description : Check if PostgreSQL is being used
    Register --test-no DBS-1826 --weight L --network NO --category security --description "检查活动的 PostgreSQL 进程"
    for PROCES in postgres postmaster
    do
    if [ ${SKIPTEST} -eq 0 ]; then
        if IsRunning "${PROCES}"; then
            Display --indent 2 --text "- PostgreSQL 进程状态" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：PostgreSQL 正在运行"
            POSTGRESQL_RUNNING=1
            DATABASE_ENGINE_RUNNING=1
            Report "postgresql_running=${POSTGRESQL_RUNNING}"
        else
            if [ ${DEBUG} -eq 1 ]; then Display --indent 2 --text "- PostgreSQL 进程状态" --result "${STATUS_NOT_FOUND}" --color WHITE --debug; fi
            LogText "结果：PostgreSQL 进程 ${PROCES} 未运行"
        fi
    fi
    done
#
#################################################################################
#
    # Test        : DBS-1828
    # Description : Test PostgreSQL configuration file(s)
    #
    # Authentication:
    # /var/lib/pgsql/data/pg_hba.conf
    #
    # Configuration
    # Arch            /var/lib/postgres/data/postgresql.conf
    # CentOS/Fedora   /var/lib/pgsql/data/postgresql.conf
    # Ubuntu          /etc/postgresql/x.y/main/postgresql.conf
    # FreeBSD         /var/db/postgres/data[0-9][0-9]/postgresql.conf

    if [ "${POSTGRESQL_RUNNING}" -eq 1 ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="未安装 PostgreSQL 或 PostgreSQL 未运行"; fi

    Register --test-no DBS-1828 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PostgreSQL 配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND_PATHS=$(${LSBINARY} -d ${ROOTDIR}usr/local/pgsql/data* 2> /dev/null)
        FIND_PATHS="${FIND_PATHS} ${ROOTDIR}etc/postgres ${ROOTDIR}etc/postgresql ${ROOTDIR}var/lib/postgres/data ${ROOTDIR}usr/local/pgsql/data ${ROOTDIR}var/lib/pgsql/data ${ROOTDIR}var/db/postgres/data[0-9][0-9]"
        CONFIG_FILES=$(${FINDBINARY} -L ${FIND_PATHS} -type f -name "*.conf" -print0 2> /dev/null | ${TRBINARY} -cd '[:print:]\0' | ${TRBINARY} -d '\n' | ${TRBINARY} '\0' '\n' | xargs -I'{}' sh -c 'test -r "{}" && echo "{}"' | ${SEDBINARY} "s/ /:space:/g")
        for CF in ${CONFIG_FILES}; do
            Report "postgresql_config_file[]=${CF}"
            LogText "发现配置文件（${CF}）"
            if IsWorldReadable ${CF}; then
                LogText "结果：配置文件 ${CF} 可被所有用户读取，可能泄露敏感信息！"
                ReportWarning "${TEST_NO}" "PostgreSQL 配置文件 ${CF} 可被所有用户读取，可能泄露敏感信息" "${CF}" "使用 chmod 600 修改文件权限"
            else
                LogText "结果：配置文件 ${CF} 不可被所有用户读取，状态正常"
            fi
        done
    fi
#
#################################################################################
#
    # Test        : DBS-1840
    # Description : Check if Oracle is being used
    # Notes       : tnslsnr: Oracle listener
    #               pmon: process monitor
    #               smon: system monitor
    #               dbwr: database writer
    #               lgwr: log writer
    #               arch: archiver (optional)
    #               ckpt: checkpoint (optional)
    #               reco: recovery (optional)
    Register --test-no DBS-1840 --weight L --network NO --category security --description "检查活动的 Oracle 进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${PSBINARY} ax | ${GREPBINARY} -E "ora_pmon|ora_smon|tnslsnr" | ${GREPBINARY} -v "grep")
        if [ -z "${FIND}" ]; then
            if [ ${DEBUG} -eq 1 ]; then Display --indent 2 --text "- Oracle 进程状态" --result "${STATUS_NOT_FOUND}" --color WHITE --debug; fi
            LogText "结果：Oracle 进程未运行"
        else
            Display --indent 2 --text "- Oracle 进程状态" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：Oracle 正在运行"
            ORACLE_RUNNING=1
            DATABASE_ENGINE_RUNNING=1
            Report "oracle_running=${ORACLE_RUNNING}"
        fi
    fi
#
#################################################################################
#
    # Test        : DBS-1842
    # Description : Check Oracle home paths from oratab
    #Register --test-no DBS-1842 --weight L --network NO --category security --description "Checking Oracle home paths"
    #if [ ${SKIPTEST} -eq 0 ]; then
    # if [ -f /etc/oratab ]; then
    #  FIND=$(${GREPBINARY} -v "#" /etc/oratab | ${AWKBINARY} -F: "{ print $2 }")
    # fi
    #fi
#
#################################################################################
#
    # Test        : DBS-1860
    # Description : Checks if a DB2 instance is currently running
    Register --test-no DBS-1860 --weight L --network NO --category security --description "检查活动的 DB2 实例"
    if [ ${SKIPTEST} -eq 0 ]; then
        if IsRunning db2sysc; then
            Display --indent 2 --text "- DB2 实例运行状态" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：至少有一个 DB2 实例正在运行"
            DB2_RUNNING=1
            DATABASE_ENGINE_RUNNING=1
            Report "db2_running=${DB2_RUNNING}"
        else
            if [ ${DEBUG} -eq 1 ]; then Display --indent 2 --text "- DB2 实例运行状态" --result "${STATUS_NOT_FOUND}" --color WHITE --debug; fi
            LogText "结果：没有正在运行的 DB2 实例"
        fi
    fi
#
#################################################################################
#
    # Test        : DBS-1880
    # Description : Determine if redis is running
    Register --test-no DBS-1880 --weight L --network NO --category security --description "检查活动的 Redis 服务器"
    if [ ${SKIPTEST} -eq 0 ]; then
        if IsRunning redis-server; then
            Display --indent 2 --text "- Redis（服务器）状态" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：Redis 正在运行"
            REDIS_RUNNING=1
            DATABASE_ENGINE_RUNNING=1
            Report "redis_server_running=${REDIS_RUNNING}"
        else
            if [ ${DEBUG} -eq 1 ]; then Display --indent 2 --text "- Redis（服务器）状态" --result "${STATUS_NOT_FOUND}" --color WHITE --debug; fi
            LogText "结果：没有正在运行的 Redis 进程"
        fi
    fi
#
#################################################################################
#
    # Test        : DBS-1882
    # Description : Determine Redis configuration
    if [ ${REDIS_RUNNING} -eq 1 ]; then PREQS_METS="YES"; else PREQS_MET="NO"; SKIPREASON="Redis 未运行"; fi
    Register --test-no DBS-1882 --weight L --network NO --preqs-met "${PREQS_MET}" --skip-reason "${SKIPREASON}" --category security --description "Redis 配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        PATHS="${ROOTDIR}etc/redis ${ROOTDIR}usr/local/etc ${ROOTDIR}usr/local/etc/redis ${ROOTDIR}usr/local/redis/etc"
        if [ ${QNAP_DEVICE} -eq 1 ]; then
            PATHS="${PATHS} ${ROOTDIR}share/CACHEDEV1_DATA/.qpkg/QKVM/usr/etc/redis.conf"
        fi
        if [ -d "${ROOTDIR}snap" ]; then
          for SNAP_PATH in $(${FINDBINARY} ${ROOTDIR}snap -name 'redis.conf' -type f | ${SEDBINARY} 's/redis.conf$//g'); do
            PATHS="${PATHS} ${SNAP_PATH}"
          done
        fi

        ALLFILES=$(${LSBINARY} ${ROOTDIR}etc/redis.conf 2> /dev/null)
        FOUND=0
        for DIR in ${PATHS}; do
            LogText "操作：扫描目录 ${DIR} 中的 Redis 配置文件"
            FILES=$(${LSBINARY} ${DIR}/*.conf 2> /dev/null)
            if [ -n "${FILES}" ]; then
                ALLFILES="${ALLFILES} ${FILES}"
            else
                LogText "结果：此目录中未找到配置文件"
            fi
        done
        for CONFFILE in ${ALLFILES}; do
            if FileIsReadable ${CONFFILE}; then
                LogText "操作：检查 ${CONFFILE} 是否为 Sentinel 配置文件"
                # Exclude Sentinel configuration file
                FIND=$(${GREPBINARY} "^sentinel " ${CONFFILE})
                if [ -n "${FIND}" ]; then
                    LogText "结果：该文件是 Sentinel 配置文件，跳过"
                else
                    LogText "结果：该文件不是 Sentinel 配置文件，继续检查是否为 Redis 配置文件"
                    FIND=$(${GREPBINARY} "Redis" ${CONFFILE})
                    if [ -n "${FIND}" ]; then
                        REDIS_CONFIGURATION_FILES="${REDIS_CONFIGURATION_FILES} ${CONFFILE}"
                        REDIS_CONFIGURATION_FOUND=1
                        LogText "结果：发现 Redis 配置文件（${CONFFILE}）"
                    else
                        LogText "结果：该文件不像 Redis 配置文件（${CONFFILE}）"
                    fi
                fi
            else
                LogText "无法读取该文件，跳过"
            fi
        done
        # Sort the list of discovered configuration files so we can make them unique
        REDIS_CONFIGURATION_FILES=$(echo ${REDIS_CONFIGURATION_FILES} | ${SEDBINARY} 's/^ //' | ${TRBINARY} ' ' '\n' | ${SORTBINARY} -u | ${TRBINARY} '\n' ' ')
        for FILE in ${REDIS_CONFIGURATION_FILES}; do
            if IsWorldReadable ${FILE}; then
                LogText "结果：配置文件 ${FILE} 可被所有用户读取，可能泄露敏感信息！"
                ReportWarning "${TEST_NO}" "Redis 配置文件 ${FILE} 可被所有用户读取，可能泄露敏感信息" "${FILE}" "使用 chmod 640 修改文件权限"
            else
                LogText "结果：配置文件 ${FILE} 不可被所有用户读取，状态正常"
            fi
        done
        if [ ${REDIS_CONFIGURATION_FOUND} -eq 0 ]; then ReportException "${TEST_NO}" "发现 Redis，但未找到配置文件；如知道其在系统中的位置，请提交反馈。"; fi
    fi
#
#################################################################################
#
    # Test        : DBS-1884
    # Description : Determine Redis configuration option: requirepass
    if [ ${REDIS_RUNNING} -eq 1 -a ${REDIS_CONFIGURATION_FOUND} -eq 1 ]; then PREQS_METS="YES"; else PREQS_MET="NO"; SKIPREASON="Redis 未运行或未找到配置文件"; fi
    Register --test-no DBS-1884 --weight L --network NO --preqs-met "${PREQS_MET}" --skip-reason "${SKIPREASON}" --category security --description "Redis：检查 requirepass 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        for FILE in ${REDIS_CONFIGURATION_FILES}; do
            if FileIsReadable ${FILE}; then
                if SearchItem "^requirepass" "${FILE}" "--sensitive"; then
                    LogText "结果：发现已配置 'requirepass'"
                    AddHP 3 3
                    Display --indent 4 --text "- Redis（已配置 requirepass）" --result "${STATUS_FOUND}" --color GREEN
                    Report "redis_requirepass=1"
                else
                    AddHP 0 3
                    Display --indent 4 --text "- Redis（已配置 requirepass）" --result "${STATUS_NOT_FOUND}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "为 Redis 配置 'requirepass' 设置" "${FILE}" "text:在 ${FILE} 中配置 'requirepass' 设置"
                    Report "redis_requirepass=0"
                fi
            else
                LogText "结果：无法读取配置文件，跳过检查"
            fi
        done
    fi
#
#################################################################################
#
    # Test        : DBS-1886
    # Description : Determine Redis configuration option: rename-command CONFIG
    if [ ${REDIS_RUNNING} -eq 1 -a ${REDIS_CONFIGURATION_FOUND} -eq 1 ]; then PREQS_METS="YES"; else PREQS_MET="NO"; SKIPREASON="Redis 未运行或未找到配置"; fi
    Register --test-no DBS-1886 --weight L --network NO --preqs-met "${PREQS_MET}" --skip-reason "${SKIPREASON}" --category security --description "Redis：检查 rename-command CONFIG 设置"
    if [ ${SKIPTEST} -eq 0 ]; then
        for FILE in ${REDIS_CONFIGURATION_FILES}; do
            if FileIsReadable ${FILE}; then
                if SearchItem "^rename-command CONFIG" "${FILE}" "--sensitive"; then
                    LogText "结果：发现已配置 'rename-command CONFIG'"
                    AddHP 3 3
                    Display --indent 4 --text "- Redis（CONFIG 命令已重命名）" --result "${STATUS_FOUND}" --color GREEN
                    Report "redis_rename_command_config=1"
                else
                    AddHP 0 3
                    Display --indent 4 --text "- Redis（CONFIG 命令已重命名）" --result "${STATUS_NOT_FOUND}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "为 Redis 使用 'rename-command CONFIG' 设置" "${FILE}" "text:在 ${FILE} 中配置 'rename-command CONFIG'"
                    Report "redis_rename_command_config=0"
                fi
            else
                LogText "结果：无法读取配置文件，跳过检查"
            fi
        done
    fi
#
#################################################################################
#
    # Test        : DBS-1888
    # Description : Determine Redis configuration option: bind on localhost
    if [ ${REDIS_RUNNING} -eq 1 -a ${REDIS_CONFIGURATION_FOUND} -eq 1 ]; then PREQS_METS="YES"; else PREQS_MET="NO"; SKIPREASON="Redis 未运行或未找到配置"; fi
    Register --test-no DBS-1888 --weight L --network NO --preqs-met "${PREQS_MET}" --skip-reason "${SKIPREASON}" --category security --description "Redis：检查是否绑定到本地主机"
    if [ ${SKIPTEST} -eq 0 ]; then
        for FILE in ${REDIS_CONFIGURATION_FILES}; do
            if FileIsReadable ${FILE}; then
                if SearchItem "^bind (localhost|127\.)" "${FILE}" "--sensitive"; then
                    LogText "结果：发现已配置绑定到本地主机"
                    AddHP 3 3
                    Display --indent 4 --text "- Redis（绑定到本地主机）" --result "${STATUS_FOUND}" --color GREEN
                    Report "redis_bind_localhost=1"
                else
                    AddHP 0 3
                    Display --indent 4 --text "- Redis（绑定到本地主机）" --result "${STATUS_NOT_FOUND}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "使用 'bind' 设置让 Redis 实例仅监听本地主机" "${FILE}" "text:在 ${FILE} 中配置 'bind localhost'"
                    Report "redis_bind_localhost=0"
                fi
            else
                LogText "结果：无法读取配置文件，跳过检查"
            fi
        done
    fi
#
#################################################################################
#
    if [ ${DATABASE_ENGINE_RUNNING} -eq 0 ]; then
        Display --indent 4 --text "未发现数据库引擎"
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
