#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Shells
#
#################################################################################
#
    IDLE_TIMEOUT=0
    InsertSection "${SECTION_SHELLS}"
#
#################################################################################
#
    # bash
    # Files (interactive login shells):     /etc/profile $HOME/.bash_profile
    #                                       $HOME/.bash_login $HOME/.profile
    # Files (interactive non-login shells): $HOME/.bash_rc
    #
    # csh/tcsh
    # Files: /etc/csh.cshrc /etc/csh.login
    #
    # zsh
    # Files: /etc/zshenv /etc/zsh/zshenv $HOME/.zshenv /etc/zprofile
    #        /etc/zsh/zprofile $HOME/.zprofile /etc/zshrc /etc/zsh/zshrc
    #        $ZDOTDIR/.zshrc /etc/zlogin /etc/zsh/zlogin

    SHELL_LOGIN_FILES="${ROOTDIR}etc/csh.cshrc ${ROOTDIR}etc/csh.login ${ROOTDIR}etc/zshenv ${ROOTDIR}etc/zsh/zshenv
                       ${ROOTDIR}etc/zprofile ${ROOTDIR}etc/zsh/zprofile ${ROOTDIR}etc/zshrc ${ROOTDIR}etc/zsh/zshrc
                       ${ROOTDIR}etc/zlogin ${ROOTDIR}etc/zsh/zlogin"
#
#################################################################################
#

    # Test        : SHLL-6202
    # Description : check all console TTYs in which root user can enter single user mode without password
    Register --test-no SHLL-6202 --os FreeBSD --weight L --network NO --category security --description "检查控制台 TTY 安全设置"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：控制台 TTY"
        FIND=$(${GREPBINARY} -E '^console' ${ROOTDIR}etc/ttys | ${GREPBINARY} -v 'insecure')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 正在检查控制台 TTY" --result "${STATUS_OK}" --color GREEN
            LogText "结果：控制台已防止用户在无密码情况下进入单用户模式。"
        else
            Display --indent 2 --text "- 正在检查控制台 TTY" --result "${STATUS_WARNING}" --color RED
            LogText "结果：在 ${ROOTDIR}etc/ttys 中发现不安全的控制台设置，允许无密码进入单用户模式！"
            LogText "${ROOTDIR}etc/ttys 输出："
            LogText "${FIND}"
            ReportWarning "${TEST_NO}" "在 ${ROOTDIR}etc/ttys 中发现未受保护的控制台"
            LogText "可能的处理方法：将控制台行从 'secure' 改为 'insecure'。"
        fi
    fi
#
#################################################################################
#
    # Test        : SHLL-6211
    # Description : Determine available shell according /etc/shells
    Register --test-no SHLL-6211 --weight L --network NO --category security --description "检查可用且有效的 Shell"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 ${ROOTDIR}etc/shells"
        if [ -f ${ROOTDIR}etc/shells ]; then
            LogText "结果：发现 ${ROOTDIR}etc/shells 文件"
            LogText "检查：从 ${ROOTDIR}etc/shells 读取可用 Shell"
            SSHELLS=$(${GREPBINARY} "^/" ${ROOTDIR}etc/shells)
            CSSHELLS=0; CSSHELLS_ALL=0
            Display --indent 2 --text "- 正在检查 ${ROOTDIR}etc/shells 中的 Shell"
            for I in ${SSHELLS}; do
                CSSHELLS_ALL=$((CSSHELLS_ALL + 1))
                Report "available_shell[]=${I}"
                # TODO add check for symlinked shells
                if [ -f ${I} ]; then
                    LogText "发现已安装的 Shell：${I}"
                    CSSHELLS=$((CSSHELLS + 1))
                else
                    LogText "Shell ${I} 未安装，可能是占位项或不存在的 Shell。"
                fi
            done
            Display --indent 4 --text "结果：共发现 ${CSSHELLS_ALL} 个 Shell（有效 Shell：${CSSHELLS} 个）。"
        else
            LogText "结果：未找到 ${ROOTDIR}etc/shells，已跳过检查"
        fi
    fi
#
#################################################################################
#
    # Test        : SHLL-6220
    # Description : Check for idle session killing tools or settings
    Register --test-no SHLL-6220 --weight L --network NO --category security --description "检查空闲会话自动终止工具或设置"
    if [ ${SKIPTEST} -eq 0 ]; then

        IDLE_TIMEOUT_METHOD=""
        IDLE_TIMEOUT_READONLY=""

        LogText "检查：搜索 Shell 会话超时工具或设置"
        if IsRunning "timeoutd"; then
            IDLE_TIMEOUT=1
            LogText "结果：发现用于终止空闲会话的 timeoutd 进程"
            IDLE_TIMEOUT_METHOD="timeout-daemon"
        fi
        if IsRunning "autolog"; then
            IDLE_TIMEOUT=1
            LogText "结果：发现用于终止空闲会话的 autolog 进程"
            Report "session_timeout_method[]=autolog"
            IDLE_TIMEOUT_METHOD="autolog"
        fi

        if [ -f ${ROOTDIR}etc/profile ]; then
            # Determine if we can find a TMOUT value
            FIND=$(${GREPBINARY} 'TMOUT=' ${ROOTDIR}etc/profile | ${TRBINARY} -d ' ' | ${TRBINARY} -d '\t' | ${GREPBINARY} -v "^#" | ${SEDBINARY} 's/export//' | ${SEDBINARY} 's/#.*//' | ${AWKBINARY} -F= '{ print $2 }')
            # Determine if the value is exported (with export, readonly, or typeset)
            FIND2=$(${GREPBINARY} '\(export\|readonly\|typeset -r\)[ \t]*TMOUT' ${ROOTDIR}etc/profile | ${GREPBINARY} -v "^#" | ${SEDBINARY} 's/#.*//' | ${AWKBINARY} '{ print $1 }')
            if [ -n "${FIND}" ]; then
                N=0; IDLE_TIMEOUT=1
                for I in ${FIND}; do
                    LogText "输出：${I}"
                    Report "session_timeout_value[]=${I}"
                    N=$((N + 1))
                done
                if [ ${N} -eq 1 ]; then
                    LogText "结果：在 ${ROOTDIR}etc/profile 中发现已配置的 TMOUT 值"
                else
                    LogText "结果：在 ${ROOTDIR}etc/profile 中发现多个 TMOUT 值"
                fi
                IDLE_TIMEOUT_METHOD="profile"
            else
                LogText "结果：在 ${ROOTDIR}etc/profile 中未找到 TMOUT 设置"
            fi

            if [ -n "${FIND2}" ]; then
                N=0;
                for I in ${FIND2}; do
                    LogText "输出：${I}"
                    if [ "${I}" = "readonly" -o "${I}" = "typeset" ]; then
                        N=$((N + 1))
                    fi
                done
                if [ ${N} -gt 0 ]; then
                    LogText "结果：在 ${ROOTDIR}etc/profile 中发现只读设置（readonly 或 typeset -r）"
                    IDLE_TIMEOUT_READONLY=1
                else
                    LogText "结果：在 ${ROOTDIR}etc/profile 中未发现只读设置（readonly 或 typeset -r）"
                    IDLE_TIMEOUT_READONLY=0
                fi
            else
                LogText "结果：在 ${ROOTDIR}etc/profile 中未找到 export、readonly 或 typeset -r"
            fi
        else
            LogText "结果：本系统没有 ${ROOTDIR}etc/profile 文件，已跳过该项检查"
        fi

        if [ -d ${ROOTDIR}etc/profile.d ]; then
            FIND=$(${LSBINARY} ${ROOTDIR}etc/profile.d/*.sh 2> /dev/null)
            if [ -n "${FIND}" ]; then
                # Determine if we can find a TMOUT value
                FIND=$(${FINDBINARY} -L ${ROOTDIR}etc/profile.d -name "*.sh" -type f -exec cat {} \; 2> /dev/null | ${GREPBINARY} 'TMOUT=' | ${TRBINARY} -d ' ' | ${TRBINARY} -d '\t' | ${GREPBINARY} -v "^#" | ${SEDBINARY} 's/export//' | ${SEDBINARY} 's/#.*//' | ${AWKBINARY} -F= '{ print $2 }')
                # Determine if the value is exported (with export, readonly, or typeset)
                FIND2=$(${FINDBINARY} -L ${ROOTDIR}etc/profile.d -name "*.sh" -type f -exec cat {} \; 2> /dev/null | ${GREPBINARY} '\(export\|readonly\|typeset -r\)[ \t]*TMOUT' | ${GREPBINARY} -v "^#" | ${SEDBINARY} 's/#.*//' | ${AWKBINARY} '{ print $1 }')
                if [ -n "${FIND}" ]; then
                    N=0; IDLE_TIMEOUT=1
                    for I in ${FIND}; do
                        LogText "输出：${I}"
                        Report "session_timeout_value[]=${I}"
                        N=$((N + 1))
                    done
                    if [ ${N} -eq 1 ]; then
                        LogText "结果：在 ${ROOTDIR}etc/profile.d 目录中的文件里发现一个 TMOUT 值"
                    else
                        LogText "结果：在 ${ROOTDIR}etc/profile.d 目录中的文件里发现多个 TMOUT 值"
                    fi
                    IDLE_TIMEOUT_METHOD="profile.d"
                else
                    LogText "结果：在 ${ROOTDIR}etc/profile.d/*.sh 中未找到 TMOUT 设置"
                fi
                # Check for readonly
                if [ -n "${FIND2}" ]; then
                    N=0;
                    for I in ${FIND2}; do
                        LogText "输出：${I}"
                        if [ "${I}" = "readonly" -o "${I}" = "typeset" ]; then
                            N=$((N + 1))
                        fi
                    done
                    if [ ${N} -gt 0 ]; then
                        LogText "结果：在 ${ROOTDIR}etc/profile 中发现只读设置（readonly 或 typeset -r）"
                        IDLE_TIMEOUT_READONLY=1
                    else
                        LogText "结果：在 ${ROOTDIR}etc/profile 中未发现只读设置（readonly 或 typeset -r）"
                        IDLE_TIMEOUT_READONLY=0
                    fi
                else
                    LogText "结果：在 ${ROOTDIR}etc/profile 中未找到 export、readonly 或 typeset -r"
                fi
            fi
        else
            LogText "结果：本系统没有 ${ROOTDIR}etc/profile.d 目录，已跳过该项检查"
        fi

        if [ -n "${IDLE_TIMEOUT_METHOD}" ]; then
            Report "session_timeout_method[]=${IDLE_TIMEOUT_METHOD}"
        fi
        if [ -n "${IDLE_TIMEOUT_READONLY}" ]; then
            Report "session_timeout_set_readonly=${IDLE_TIMEOUT_READONLY}"
        fi

        if [ ${IDLE_TIMEOUT} -eq 1 ]; then
            Display --indent 4 --text "- 会话超时设置/工具" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        else
            Display --indent 4 --text "- 会话超时设置/工具" --result "${STATUS_NONE}" --color YELLOW
            AddHP 1 3
        fi
    fi
#
#################################################################################
#
    # Test        : SHLL-6230
    # Description : Check for umask values in shell configurations
    SHELL_CONFIG_FILES="${ROOTDIR}etc/bashrc ${ROOTDIR}etc/bash.bashrc ${ROOTDIR}etc/bash.bashrc.local ${ROOTDIR}etc/csh.cshrc ${ROOTDIR}etc/profile"
    Register --test-no SHLL-6230 --weight H --network NO --category security --description "检查 Shell 配置中的 umask 值"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        Display --indent 2 --text "- 正在检查默认 umask 值"
        for FILE in ${SHELL_CONFIG_FILES}; do
            HARDENING_POSSIBLE=0
            FIND=""
            if [ -f ${FILE} ]; then
                LogText "结果：文件 ${FILE} 存在"
                FOUND=1
                FIND=$(${GREPBINARY} umask ${FILE} | ${SEDBINARY} 's/^[ \t]*//g' | ${SEDBINARY} 's/#.*$//' | ${GREPBINARY} -v "^$" | ${AWKBINARY} '{ print $2 }')
                if IsEmpty "${FIND}"; then
                    LogText "结果：在 ${FILE} 中未找到 umask 配置"
                    Display --indent 4 --text "- 正在检查 ${FILE} 中的默认 umask" --result "${STATUS_NONE}" --color YELLOW
                else
                    for UMASKVALUE in ${FIND}; do
                        LogText "结果：在 ${FILE} 中发现 umask ${UMASKVALUE}"
                        case ${UMASKVALUE} in
                            027|0027|077|0077)
                                    LogText "结果：umask ${UMASKVALUE} 属于适当加固的值"
                            ;;
                            *)
                                    LogText "结果：umask ${UMASKVALUE} 仍可进一步加固"
                                    HARDENING_POSSIBLE=1
                            ;;
                        esac
                    done
                    if [ ${HARDENING_POSSIBLE} -eq 0 ]; then
                        Display --indent 4 --text "- 正在检查 ${FILE} 中的默认 umask" --result "${STATUS_OK}" --color GREEN
                        AddHP 3 3
                    else
                        Display --indent 4 --text "- 正在检查 ${FILE} 中的默认 umask" --result "${STATUS_WEAK}" --color YELLOW
                        AddHP 1 3
                    fi
                fi
            else
                LogText "结果：未找到文件 ${FILE}"
            fi
        done
    fi
#
#################################################################################
#

Report "session_timeout_enabled=${IDLE_TIMEOUT}"

#
#################################################################################
#

WaitForKeyPress

# EOF
