#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# NFS
#
#################################################################################
#
    InsertSection "NFS"
#
#################################################################################
#
    NFS_DAEMON_RUNNING=0
    NFS_EXPORTS_EMPTY=0
#
#################################################################################
#
    # Test        : STRG-1902
    # Description : Check rpcinfo
    if [ -n "${RPCINFOBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no STRG-1902 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 rpcinfo 注册的程序"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：rpcinfo 注册的程序"
        FIND=$(${RPCINFOBINARY} -p 2> /dev/null | ${TRBINARY} -s ' ' ',')
        for I in ${FIND}; do
            LogText "rpcinfo: ${I}"
        done
        Display --indent 2 --text "- 查询 RPC 注册程序" --result "${STATUS_DONE}" --color GREEN
    fi
#
#################################################################################
#
    # Test        : STRG-1904
    # Description : Check nfs versions in rpcinfo
    if [ -n "${RPCINFOBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no STRG-1904 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 NFS RPC 信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：NFS 注册版本"
        FIND=$(${RPCINFOBINARY} -p 2> /dev/null | ${AWKBINARY} '{ if ($5=="nfs") { print $2 } }' | uniq | sort)
        for I in ${FIND}; do
            LogText "发现版本：${I}"
        done
        Display --indent 2 --text "- 查询 NFS 版本" --result "${STATUS_DONE}" --color GREEN
    fi
#
#################################################################################
#
    # Test        : STRG-1906
    # Description : Check nfs protocols (TCP/UDP) and port in rpcinfo
    if [ -n "${RPCINFOBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no STRG-1906 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 NFS RPC 信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：NFS 注册协议"
        FIND=$(${RPCINFOBINARY} -p 2> /dev/null | ${AWKBINARY} '{ if ($5=="nfs") { print $3 } }' | uniq | sort)
        for I in ${FIND}; do
            LogText "发现协议：${I}"
        done
        if [ -z "${FIND}" ]; then
            LogText "输出：未发现 NFS 协议"
        fi

        # Check port number
        LogText "检查：NFS 注册端口"
        FIND=$(${RPCINFOBINARY} -p 2> /dev/null | ${AWKBINARY} '{ if ($5=="nfs") { print $3 } }' | uniq | sort)
        for I in ${FIND}; do
            LogText "发现端口：${I}"
        done
        if [ -z "${FIND}" ]; then
            LogText "输出：未发现 NFS 端口号"
        fi
        Display --indent 2 --text "- 查询 NFS 协议" --result "${STATUS_DONE}" --color GREEN
    fi
#
#################################################################################
#
    # Test        : STRG-1920
    # Description : Check for running NFS daemons
    Register --test-no STRG-1920 --weight L --network NO --category security --description "检查 NFS 守护进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：正在运行的 NFS 守护进程"
        FIND=$(${PSBINARY} ax | ${GREPBINARY} "nfsd" | ${GREPBINARY} -v "grep")
        if [ -z "${FIND}" ]; then
            LogText "输出：NFS 守护进程未运行"
            Display --indent 2 --text "- 检查运行中的 NFS 守护进程" --result "${STATUS_NOT_FOUND}" --color WHITE
        else
            LogText "输出：NFS 守护进程正在运行"
            Display --indent 2 --text "- 检查运行中的 NFS 守护进程" --result "${STATUS_FOUND}" --color GREEN
            NFS_DAEMON_RUNNING=1
        fi
    fi
#
#################################################################################
#
    # Test        : STRG-1924
    # Description : Check missing nfs in rpcinfo while NFS is running
    #Register --test-no STRG-1924 --weight L --network NO --category security --description "Checking NFS daemon"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : STRG-1926
    # Description : Check NFS exports
    if [ ${NFS_DAEMON_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no STRG-1926 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 NFS 导出配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：/etc/exports"
        if [ -f ${ROOTDIR}etc/exports ]; then
            LogText "结果：${ROOTDIR}etc/exports 存在"
            FIND=$(${GREPBINARY} -v "^$" ${ROOTDIR}etc/exports | ${GREPBINARY} -v "^#" | ${SEDBINARY} 's/ /!space!/g')
            if [ -n "${FIND}" ]; then
                for I in ${FIND}; do
                    I=$(echo ${I} | ${SEDBINARY} 's/!space!/ /g')
                    LogText "发现配置行：${I}"
                done
            else
                LogText "结果：${ROOTDIR}etc/exports 中没有导出的文件系统"
                NFS_EXPORTS_EMPTY=1
            fi
            Display --indent 4 --text "- 正在检查 ${ROOTDIR}etc/exports" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：文件 /etc/exports 不存在"
            Display --indent 4 --text "- 正在检查 ${ROOTDIR}etc/exports" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : STRG-1928
    # Description : Check for empty exports file while NFS is running
    if [ ${NFS_DAEMON_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no STRG-1928 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查空的 /etc/exports"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ ${NFS_EXPORTS_EMPTY} -eq 1 ]; then
            Display --indent 6 --text "- 正在检查空的 /etc/exports" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "结果：${ROOTDIR}etc/exports 似乎没有导出的文件系统"
            ReportSuggestion "${TEST_NO}" "NFS 守护进程正在运行，但 /etc/exports 中没有导出的文件系统；请确认本系统是否需要运行 NFS"
        fi
    fi
#
#################################################################################
#
    # Test        : STRG-1930
    # Description : Check client access to nfs share
    if [ ${NFS_DAEMON_RUNNING} -eq 1 -a ${NFS_EXPORTS_EMPTY} -eq 0 -a ! "${SHOWMOUNTBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no STRG-1930 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查客户端对 NFS 共享的访问"
    if [ ${SKIPTEST} -eq 0 ]; then
        sFIND=$(${SHOWMOUNTBINARY} -e | ${AWKBINARY} '{ print $2 }' | ${SEDBINARY} '1d' | ${GREPBINARY} "\*")
        if [ -n "${sFIND}" ]; then
            LogText "结果：所有客户端都可以访问 /etc/exports 中的 NFS 共享"
            Display --indent 4 --text "- 正在检查 NFS 客户端访问" --result "所有客户端" --color YELLOW
            ReportSuggestion "${TEST_NO}" "在 /etc/exports 中明确指定允许访问 NFS 共享的客户端"
            AddHP 2 3
        else
            LogText "结果：只有部分客户端可以访问 NFS 共享"
            Display --indent 4 --text "- 正在检查 NFS 客户端访问" --result "${STATUS_OK}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
