#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Software: PHP
#
#################################################################################
#
    # Variables
    PHPVERSION=""

    InsertSection "PHP"

    # Possible locations of php.ini
    PHPINILOCS="${ROOTDIR}etc/php.ini ${ROOTDIR}etc/php.ini.default \
                ${ROOTDIR}etc/php/php.ini \
                ${ROOTDIR}etc/php7.0/php.ini \
                ${ROOTDIR}etc/php7.1/php.ini \
                ${ROOTDIR}etc/php7.2/php.ini \
                ${ROOTDIR}etc/php7.3/php.ini \
                ${ROOTDIR}etc/php7.4/php.ini \
                ${ROOTDIR}etc/php8.0/php.ini \
                ${ROOTDIR}etc/php8.1/php.ini \
                ${ROOTDIR}etc/php8.2/php.ini \
                ${ROOTDIR}etc/php8.3/php.ini \
                ${ROOTDIR}etc/php8.4/php.ini \
                ${ROOTDIR}etc/php/apache2-php7.0/php.ini \
                ${ROOTDIR}etc/php/apache2-php7.1/php.ini \
                ${ROOTDIR}etc/php/apache2-php7.2/php.ini \
                ${ROOTDIR}etc/php/apache2-php7.3/php.ini \
                ${ROOTDIR}etc/php/apache2-php7.4/php.ini \
                ${ROOTDIR}etc/php/apache2-php8.0/php.ini \
                ${ROOTDIR}etc/php/apache2-php8.1/php.ini \
                ${ROOTDIR}etc/php/apache2-php8.2/php.ini \
                ${ROOTDIR}etc/php/apache2-php8.3/php.ini \
                ${ROOTDIR}etc/php/apache2-php8.4/php.ini \
                ${ROOTDIR}etc/php/cgi-php7.0/php.ini \
                ${ROOTDIR}etc/php/cgi-php7.1/php.ini \
                ${ROOTDIR}etc/php/cgi-php7.2/php.ini \
                ${ROOTDIR}etc/php/cgi-php7.3/php.ini \
                ${ROOTDIR}etc/php/cgi-php7.4/php.ini \
                ${ROOTDIR}etc/php/cli-php5.5/php.ini \
                ${ROOTDIR}etc/php/cli-php5.6/php.ini \
                ${ROOTDIR}etc/php/cli-php7.0/php.ini \
                ${ROOTDIR}etc/php/cli-php7.1/php.ini \
                ${ROOTDIR}etc/php/cli-php7.2/php.ini \
                ${ROOTDIR}etc/php/cli-php7.3/php.ini \
                ${ROOTDIR}etc/php/cli-php7.4/php.ini \
                ${ROOTDIR}etc/php/cli-php8.0/php.ini \
                ${ROOTDIR}etc/php/cli-php8.1/php.ini \
                ${ROOTDIR}etc/php/cli-php8.2/php.ini \
                ${ROOTDIR}etc/php/cli-php8.3/php.ini \
                ${ROOTDIR}etc/php/cli-php8.4/php.ini \
                ${ROOTDIR}etc/php/embed-php7.0/php.ini \
                ${ROOTDIR}etc/php/embed-php7.1/php.ini \
                ${ROOTDIR}etc/php/embed-php7.2/php.ini \
                ${ROOTDIR}etc/php/embed-php7.3/php.ini \
                ${ROOTDIR}etc/php/embed-php7.4/php.ini \
                ${ROOTDIR}etc/php/embed-php8.0/php.ini \
                ${ROOTDIR}etc/php/embed-php8.1/php.ini \
                ${ROOTDIR}etc/php/embed-php8.2/php.ini \
                ${ROOTDIR}etc/php/embed-php8.3/php.ini \
                ${ROOTDIR}etc/php/embed-php8.4/php.ini \
                ${ROOTDIR}etc/php/fpm-php7.0/php.ini \
                ${ROOTDIR}etc/php/fpm-php7.1/php.ini \
                ${ROOTDIR}etc/php/fpm-php7.2/php.ini \
                ${ROOTDIR}etc/php/fpm-php7.3/php.ini \
                ${ROOTDIR}etc/php/fpm-php7.4/php.ini \
                ${ROOTDIR}etc/php/fpm-php8.0/php.ini \
                ${ROOTDIR}etc/php/fpm-php8.1/php.ini \
                ${ROOTDIR}etc/php/fpm-php8.2/php.ini \
                ${ROOTDIR}etc/php/7.0/apache2/php.ini \
                ${ROOTDIR}etc/php/7.1/apache2/php.ini \
                ${ROOTDIR}etc/php/7.2/apache2/php.ini \
                ${ROOTDIR}etc/php/7.3/apache2/php.ini \
                ${ROOTDIR}etc/php/7.4/apache2/php.ini \
                ${ROOTDIR}etc/php/8.0/apache2/php.ini \
                ${ROOTDIR}etc/php/8.1/apache2/php.ini \
                ${ROOTDIR}etc/php/8.2/apache2/php.ini \
                ${ROOTDIR}etc/php/8.3/apache2/php.ini \
                ${ROOTDIR}etc/php/8.4/apache2/php.ini \
                ${ROOTDIR}etc/php/7.0/cli/php.ini \
                ${ROOTDIR}etc/php/7.0/fpm/php.ini \
                ${ROOTDIR}etc/php/7.1/cli/php.ini \
                ${ROOTDIR}etc/php/7.1/fpm/php.ini \
                ${ROOTDIR}etc/php/7.2/cli/php.ini \
                ${ROOTDIR}etc/php/7.2/fpm/php.ini \
                ${ROOTDIR}etc/php/7.3/cli/php.ini \
                ${ROOTDIR}etc/php/7.3/fpm/php.ini \
                ${ROOTDIR}etc/php/7.4/cli/php.ini \
                ${ROOTDIR}etc/php/7.4/fpm/php.ini \
                ${ROOTDIR}etc/php/8.0/cli/php.ini \
                ${ROOTDIR}etc/php/8.0/fpm/php.ini \
                ${ROOTDIR}etc/php/8.1/cli/php.ini \
                ${ROOTDIR}etc/php/8.1/fpm/php.ini \
                ${ROOTDIR}etc/php/8.2/cli/php.ini \
                ${ROOTDIR}etc/php/8.2/fpm/php.ini \
                ${ROOTDIR}etc/php/8.3/cli/php.ini \
                ${ROOTDIR}etc/php/8.3/fpm/php.ini \
                ${ROOTDIR}etc/php/8.4/cli/php.ini \
                ${ROOTDIR}etc/php/8.4/fpm/php.ini \
                ${ROOTDIR}opt/alt/php70/etc/php.ini \
                ${ROOTDIR}opt/alt/php71/etc/php.ini \
                ${ROOTDIR}opt/alt/php72/etc/php.ini \
                ${ROOTDIR}opt/alt/php73/etc/php.ini \
                ${ROOTDIR}opt/alt/php74/etc/php.ini \
                ${ROOTDIR}opt/alt/php80/etc/php.ini \
                ${ROOTDIR}opt/alt/php81/etc/php.ini \
                ${ROOTDIR}opt/alt/php82/etc/php.ini \
                ${ROOTDIR}opt/alt/php83/etc/php.ini \
                ${ROOTDIR}opt/alt/php84/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php70/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php71/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php72/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php73/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php74/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php80/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php81/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php82/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php83/root/etc/php.ini \
                ${ROOTDIR}opt/cpanel/ea-php84/root/etc/php.ini \
                ${ROOTDIR}private/etc/php.ini \
                ${ROOTDIR}var/www/conf/php.ini \
                ${ROOTDIR}usr/local/etc/php.ini \
                ${ROOTDIR}usr/local/lib/php.ini \
                ${ROOTDIR}usr/local/php70/lib/php.ini \
                ${ROOTDIR}usr/local/php71/lib/php.ini \
                ${ROOTDIR}usr/local/php72/lib/php.ini \
                ${ROOTDIR}usr/local/php73/lib/php.ini \
                ${ROOTDIR}usr/local/php74/lib/php.ini \
                ${ROOTDIR}usr/local/php80/lib/php.ini \
                ${ROOTDIR}usr/local/php81/lib/php.ini \
                ${ROOTDIR}usr/local/php82/lib/php.ini \
                ${ROOTDIR}usr/local/php83/lib/php.ini \
                ${ROOTDIR}usr/local/php84/lib/php.ini \
                ${ROOTDIR}usr/local/zend/etc/php.ini \
                ${ROOTDIR}usr/pkg/etc/php.ini \
                ${ROOTDIR}etc/opt/remi/php56/php.ini \
                ${ROOTDIR}etc/opt/remi/php70/php.ini \
                ${ROOTDIR}etc/opt/remi/php71/php.ini \
                ${ROOTDIR}etc/opt/remi/php72/php.ini \
                ${ROOTDIR}etc/opt/remi/php73/php.ini \
                ${ROOTDIR}etc/opt/remi/php74/php.ini \
                ${ROOTDIR}etc/opt/remi/php80/php.ini \
                ${ROOTDIR}etc/opt/remi/php81/php.ini \
                ${ROOTDIR}etc/opt/remi/php82/php.ini\
                ${ROOTDIR}etc/opt/remi/php83/php.ini \
                ${ROOTDIR}etc/opt/remi/php84/php.ini"

    PHPINIDIRS="${ROOTDIR}etc/php/7.0/cli/conf.d \
                ${ROOTDIR}etc/php/7.1/cli/conf.d \
                ${ROOTDIR}etc/php/7.2/cli/conf.d \
                ${ROOTDIR}etc/php/7.3/cli/conf.d \
                ${ROOTDIR}etc/php/7.4/cli/conf.d \
                ${ROOTDIR}etc/php/7.0/fpm/conf.d \
                ${ROOTDIR}etc/php/7.1/fpm/conf.d \
                ${ROOTDIR}etc/php/7.2/fpm/conf.d \
                ${ROOTDIR}etc/php/7.3/fpm/conf.d \
                ${ROOTDIR}etc/php/7.4/fpm/conf.d \
                ${ROOTDIR}etc/php/8.0/fpm/conf.d \
                ${ROOTDIR}etc/php/8.1/fpm/conf.d \
                ${ROOTDIR}etc/php/8.2/fpm/conf.d \
                ${ROOTDIR}etc/php/8.3/fpm/conf.d \
                ${ROOTDIR}etc/php/8.4/fpm/conf.d \
                ${ROOTDIR}etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php70/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php71/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php72/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php73/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php74/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php80/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php81/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php82/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php83/root/etc/php.d \
                ${ROOTDIR}opt/cpanel/ea-php84/root/etc/php.d \
                ${ROOTDIR}opt/alt/php70/etc/php.d.all \
                ${ROOTDIR}opt/alt/php71/etc/php.d.all \
                ${ROOTDIR}opt/alt/php72/etc/php.d.all \
                ${ROOTDIR}opt/alt/php73/etc/php.d.all \
                ${ROOTDIR}opt/alt/php74/etc/php.d.all \
                ${ROOTDIR}opt/alt/php80/etc/php.d.all \
                ${ROOTDIR}opt/alt/php81/etc/php.d.all \
                ${ROOTDIR}opt/alt/php82/etc/php.d.all \
                ${ROOTDIR}opt/alt/php83/etc/php.d.all \
                ${ROOTDIR}opt/alt/php84/etc/php.d.all \
                ${ROOTDIR}usr/local/lib/php.conf.d \
                ${ROOTDIR}usr/local/php70/lib/php.conf.d \
                ${ROOTDIR}usr/local/php71/lib/php.conf.d \
                ${ROOTDIR}usr/local/php72/lib/php.conf.d \
                ${ROOTDIR}usr/local/php73/lib/php.conf.d \
                ${ROOTDIR}usr/local/php74/lib/php.conf.d \
                ${ROOTDIR}usr/local/php80/lib/php.conf.d \
                ${ROOTDIR}usr/local/php81/lib/php.conf.d \
                ${ROOTDIR}usr/local/php82/lib/php.conf.d \
                ${ROOTDIR}usr/local/php83/lib/php.conf.d \
                ${ROOTDIR}usr/local/php84/lib/php.conf.d"
                
    PHPINIDIRS="${PHPINIDIRS} \
                ${ROOTDIR}etc/php-7.0 \
                ${ROOTDIR}etc/php-7.1 \
                ${ROOTDIR}etc/php-7.2 \
                ${ROOTDIR}etc/php-7.3 \
                ${ROOTDIR}etc/php-7.4 \
                ${ROOTDIR}etc/php-8.0 \
                ${ROOTDIR}etc/php-8.1 \
                ${ROOTDIR}etc/php-8.2 \
                ${ROOTDIR}etc/php-8.3 \
                ${ROOTDIR}etc/php-8.4"
#
#################################################################################
#
    # Test        : PHP-2211
    # Description : Check php.ini presence
    Register --test-no PHP-2211 --weight L --network NO --category security --description "检查 php.ini 是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查是否存在 php.ini"
        PHPINIFILE=""
        PHPINI_ALLFILES=""
        for FILE in ${PHPINILOCS}; do
            LogText "测试：检查存在 ${FILE}"
            if [ -f ${FILE} ]; then
                PHPINIFILE="${FILE}"
                LogText "结果：找到 php.ini 文件 (${PHPINIFILE})"
                LogText "注意：将文件添加到 php.ini 数组"
                PHPINI_ALLFILES="${PHPINI_ALLFILES} ${PHPINIFILE}"
            else
                LogText "结果：未找到文件 ${FILE}"
            fi
        done

        # Check all known locations
        for DIR in ${PHPINIDIRS}; do
            FIND=$(ls ${DIR}/*.ini 2> /dev/null)
            if [ -z "${FIND}" ]; then
                LogText "结果：未找到 ${DIR} 的文件"
            else
                LogText "结果：在位置 ${DIR} 中发现文件，正在检查"
                for FILE in ${FIND}; do
                    if [ -f ${FILE} ]; then
                        LogText "结果：文件 ${FILE} 存在，加入 php.ini 数组"
                        PHPINI_ALLFILES="${PHPINI_ALLFILES} ${FILE}"
                    fi
                done
            fi
        done

        if [ -n "${PHPINIFILE}" ]; then
            Display --indent 2 --text "- 检查PHP" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：使用单个文件 ${PHPINIFILE} 进行主要 php.ini 测试"
            LogText "结果：使用php.ini阵列${PHPINI_ALLFILES}进行进一步测试"
        else
            Display --indent 2 --text "- 检查PHP" --result "${STATUS_NOT_FOUND}" --color WHITE
            LogText "结果：未找到 php.ini 文件"
        fi
        unset DIR FILE FIND
    fi
#
#################################################################################
#
    # Test        : PHP-2320
    # Description : Check php disable functions option
    if [ -n "${PHPINI_ALLFILES}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PHP-2320 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查PHP禁用的功能"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for I in ${PHPINI_ALLFILES}; do
            LogText "测试：检查文件 ${I} 中的 PHP 功能强化禁用_functions 或 suhosin.executor.func.blacklist"
            FIND=$(${GREPBINARY} "^disable_functions.*=" ${I})
            if [ -z "${FIND}" ]; then
                LogText "结果：${I}：找不到disabled_functions"
            else
                LogText "结果：${I}：找到disabled_functions"
                FOUND=1
            fi

            FIND=$(${GREPBINARY} "^suhosin.executor.func.blacklist=" ${I})
            if [ -z "${FIND}" ]; then
                LogText "结果：${I}：未找到suhosin.executor.func.blacklist"
            else
                LogText "结果：${I}：找到suhosin.executor.func.blacklist"
                FOUND=1
            fi
        done
        if [ ${FOUND} -eq 0 ]; then
            LogText "结果：所有 PHP 函数都可以执行"
            Display --indent 4 --text "- 检查PHP禁用的功能" --result "${STATUS_NONE}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "通过禁用有风险的功能来强化 PHP"
            LogText "建议评估或禁用的函数： chown, diskfreespace, disk_free_space, disk_total_space, dl, exec, escapeshellarg, escapeshellcmd, fileinode, highlight_file, max_execution_time, passthru, pclose, phpinfo, popen, proc_close, proc_open, proc_get_status, proc_nice, proc_open, proc_terminate, set_time_limit, shell_exec, show_source, system)"
            AddHP 0 1
        else
            LogText "结果：一项或多项 PHP 功能被禁用/列入黑名单"
            Display --indent 4 --text "- 检查PHP禁用的功能" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : PHP-2368
    # Description : Check php register_globals option
    # Notes       : Don't test for it if PHP version is 5.4.0 or later (it has been removed)
    if [ -n "${PHPINIFILE}" -a -n "${PHPVERSION}" -a -n "${GREPBINARY}" ]; then
        if [ -f "${PHPINIFILE}" ]; then
            FIND=$(echo ${PHPVERSION} | ${GREPBINARY} -E "^(4.|5.[0-3])")
            if [ -z "${FIND}" ]; then
                PREQS_MET="NO"; Debug "Found most likely PHP version 5.4.0 or higher (${PHPVERSION}) which does not use register_globals"
            else
                PREQS_MET="YES"; Debug "Found PHP version 4 or up to 5.3 (${FIND}) which we are going to scan"
            fi
        else
            Debug "File php.ini (${PHPINIFILE}) not found"
        fi
    else
        PREQS_MET="NO"
        Debug "Skipping test: php.ini not found, or PHP version empty"
        Debug "php.ini: ${PHPINIFILE}"
        Debug "version: ${PHPVERSION}"
    fi
    Register --test-no PHP-2368 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PHP register_globals 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 PHP register_globals 选项"
        FIND=$(${GREPBINARY} -E -i 'register_globals.*(on|yes|1)' ${PHPINIFILE} | ${GREPBINARY} -v '^;')
        if [ -n "${FIND}" ]; then
            Display --indent 4 --text "- 检查 register_globals 选项" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "PHP 的 register_globals 选项已开启，可能存在变量值被覆盖的风险"
            ReportSuggestion "${TEST_NO}" "将 register_globals 行更改为： register_globals = Off"
            LogText "结果：register_globals 选项已开启，可能存在变量值被覆盖的风险。"
            AddHP 1 2
        else
            Display --indent 4 --text "- 检查 register_globals 选项" --result "${STATUS_OK}" --color GREEN
            LogText "结果：未找到 'register_globals'，它很可能处于禁用状态（0、no 或 off），这是当前默认且较安全的值。"
            ReportManual ${TEST_NO}:01
            AddHP 2 2
        fi
    fi
#
#################################################################################
#
    # Test        : PHP-2372
    # Description : Check PHP expose_php option
    # Background  : When this option is turned on, PHP will show its version number in the HTTP headers
    # Notes       : TODO - Extend test to check all PHP files
    if [ -n "${PHPINI_ALLFILES}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PHP-2372 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PHP expose_php 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for FILE in ${PHPINI_ALLFILES}; do
            # Don't look at this setting in cli configuration
            case "${FILE}" in
                */cli/*)
                    continue
                    ;;
            esac
            LogText "测试：检查文件${FILE}"
            FIND=$(${GREPBINARY} -E -i 'expose_php.*(on|yes|1)' ${FILE} | ${GREPBINARY} -v '^;')
            if HasData "${FIND}"; then
                LogText "结果：在 expose_php 设置上找到可能的匹配项"
                LogText "数据：${FIND}"
                FOUND=1
            fi
        done

        if [ ${FOUND} -eq 1 ]; then
            Display --indent 4 --text "- 检查 expose_php 选项" --result "${STATUS_ON}" --color RED
            ReportSuggestion "${TEST_NO}" "关闭PHP信息暴露" "expose_php = 关" "-"
            Report "Result: expose_php option is turned on, which can expose useful information for an attacker"
            AddHP 1 3
        else
            Display --indent 4 --text "- 检查 expose_php 选项" --result "${STATUS_OFF}" --color GREEN
            LogText "结果：发现 'expose_php' 处于禁用状态（0、no 或 off）"
            AddHP 2 2
        fi
    fi
#
#################################################################################
#
    # Test        : PHP-2374
    # Description : Check PHP enable_dl option
    # Notes       : Extend test to check all PHP files
    if [ -n "${PHPINIFILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PHP-2374 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PHP enable_dl 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 PHP enable_dl 选项"
        FIND=$(${GREPBINARY} -E -i 'enable_dl.*(on|yes|1)' ${PHPINIFILE} | ${GREPBINARY} -v '^;')
        if [ -n "${FIND}" ]; then
            Display --indent 4 --text "- 检查 enable_dl 选项" --result "${STATUS_ON}" --color YELLOW
            Report "Result: enable_dl option is turned on, which can be used to enable more modules dynamically and circumventing security controls"
            ReportSuggestion "${TEST_NO}" "将 enable_dl 行改为 enable_dl = Off，以禁用动态加载新模块"
            AddHP 0 1
        else
            Display --indent 4 --text "- 检查 enable_dl 选项" --result "${STATUS_OFF}" --color GREEN
            LogText "结果：发现 'enable_dl' 处于禁用状态（未配置、0、no 或 off）"
            AddHP 2 2
        fi
    fi
#
#################################################################################
#
    # Test        : PHP-2376
    # Description : Check PHP allow_url_fopen option
    # Notes       : Extend test to check all PHP files YYY
    if [ -n "${PHPINIFILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PHP-2376 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PHP allow_url_fopen 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 PHP allow_url_fopen 选项"
        FIND=$(${GREPBINARY} -E -i 'allow_url_fopen.*(off|no|0)' ${PHPINIFILE} | ${GREPBINARY} -v '^;')
        if [ -z "${FIND}" ]; then
            Display --indent 4 --text "- 检查 allow_url_fopen 选项" --result "${STATUS_ON}" --color YELLOW
            LogText "结果：allow_url_fopen 选项已开启，可通过 PHP 下载内容，存在安全风险"
            ReportSuggestion "${TEST_NO}" "将 allow_url_fopen 行改为 allow_url_fopen = Off，以禁用通过 PHP 下载内容"
            AddHP 0 1
        else
            Display --indent 4 --text "- 检查 allow_url_fopen 选项" --result "${STATUS_OFF}" --color GREEN
            LogText "结果：发现 'allow_url_fopen' 处于禁用状态（0、no 或 off）"
            AddHP 2 2
        fi
        # TODO Check through all files
    fi
#
#################################################################################
#
    # Test        : PHP-2378
    # Description : Check PHP allow_url_include option
    # Notes       : Extend test to check all PHP files YYY
    if [ -n "${PHPINIFILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PHP-2378 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PHP allow_url_include 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 PHP allow_url_include 选项"
        FIND=$(${GREPBINARY} -E -i 'allow_url_include.*(off|no|0)' ${PHPINIFILE} | ${GREPBINARY} -v '^;')
        if [ -z "${FIND}" ]; then
            Display --indent 4 --text "- 检查 allow_url_include 选项" --result "${STATUS_ON}" --color YELLOW
            Report "Result: allow_url_include option is turned on, which can be used for downloads via PHP and is a risk"
            ReportSuggestion "${TEST_NO}" "将 allow_url_include 行改为 allow_url_include = Off，以禁用通过 PHP 包含远程内容"
            AddHP 0 1
        else
            Display --indent 4 --text "- 检查 allow_url_include 选项" --result "${STATUS_OFF}" --color GREEN
            LogText "结果：发现 'allow_url_include' 处于禁用状态（0、no 或 off）"
            AddHP 2 2
        fi
    fi
#
#################################################################################
#
    # - test disabled for time being, as newer suhosin7 work is not stable enough -
    # Test        : PHP-2379
    # Description : Check PHP suhosin extension status
    #if [ -n "${PHPINI_ALLFILES}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no PHP-2379 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "Check PHP suhosin extension status"

    #if [ ${SKIPTEST} -eq 0 ]; then
    #    FOUND=0
    #    SIMULATION=0
    #    MAJOR_VERSION=$(echo ${PHPVERSION} | ${GREPBINARY} -E "^7")
    #    if [ "${OS}" = "OpenBSD" ]; then
    #        FOUND=1                    # On OpenBSD, Suhosin is hard linked into PHP
    #        SIMULATION=off
    #    else
    #        for I in ${PHPINI_ALLFILES}; do
    #            LogText "Test: Checking for PHP suhosin extension status in file ${I}"
    #            FIND=$(${GREPBINARY} -oP '^extension=.*?suhosin7?.so.*$' ${I})
    #            if [ -z "${FIND}" ]; then
    #                LogText "Result: ${I}: suhosin is not enabled"
    #            else
    #                LogText "Result: ${I}: suhosin is enabled"
    #                FOUND=1
    #            fi

    #            LogText "Test: Check Suhosin simulation mode status"
    #            SIMULATION=$(${GREPBINARY} -oP '^suhosin.simulation.*$' ${I} | ${CUTBINARY} -d= -f2 | ${GREPBINARY} -io 'off' | ${TRBINARY} '[:upper:]' '[:lower:]')
    #            if [ "${SIMULATION}" = "off" ]; then
    #                LogText "Result: ${I}: suhosin simulation mode is not active"
    #            else
    #                LogText "Result: ${I}: suhosin simulation mode is active"
    #            fi
    #        done
    #    fi

    #    # Check Suhosin for PHP 7
    #    if [ -n "${MAJOR_VERSION}" -a ${FOUND} -eq 1 ]; then
    #        LogText "Test: Check Suhosin for PHP 7 is not enabled"
    #        LogText "Result: Suhosin for PHP 7 is in alpha stage and should not be used in production"
    #        ReportSuggestion "${TEST_NO}" "Disable Suhosin for PHP 7"
    #        Display --indent 4 --text "- Checking PHP suhosin extension status" --result "${STATUS_WARNING}" --color RED
    #        Display --indent 6 --text "- Suhosin is enabled for PHP 7" --result "${STATUS_WARNING}" --color RED
    #        AddHP 0 1
    #    elif [ -n "${MAJOR_VERSION}" -a ${FOUND} -eq 0 ]; then
    #        LogText "Test: Check Suhosin for PHP 7 is not enabled"
    #        LogText "Result: Suhosin for PHP 7 is not enabled"
    #        Display --indent 4 --text "- Checking PHP suhosin extension status" --result "${STATUS_OK}" --color GREEN
    #        Display --indent 6 --text "- Suhosin is not enabled for PHP 7" --result "${STATUS_OK}" --color GREEN
    #        AddHP 1 1
    #    else
    #        if [ ${FOUND} -eq 0 ]; then
    #            LogText "Result: Suhosin extension is not enabled"
    #            Display --indent 4 --text "- Checking PHP suhosin extension status" --result "${STATUS_WARNING}" --color RED
    #            ReportSuggestion "${TEST_NO}" "Harden PHP by enabling suhosin extension"
    #            LogText "suhosin extension is not enabled"
    #            AddHP 0 1
    #        else
    #            LogText "Result: Suhosin extension is enabled"
    #            Display --indent 4 --text "- Checking PHP suhosin extension status" --result "${STATUS_OK}" --color GREEN
    #            AddHP 2 2
    #        fi

    #        if [ "${SIMULATION}" = "off" ]; then
    #            LogText "Result: Suhosin simulation mode is not active"
    #            Display --indent 6 --text "- Suhosin simulation mode status" --result "${STATUS_OK}" --color GREEN
    #            AddHP 2 2
    #        else
    #            LogText "Result: Suhosin simulation mode is active"
    #            Display --indent 6 --text "- Suhosin simulation mode status" --result "${STATUS_WARNING}" --color RED
    #            ReportSuggestion "${TEST_NO}" "Harden PHP by deactivating suhosin simulation mode"
    #            LogText "suhosin simulation mode is active"
    #            AddHP 0 1
    #        fi
    #    fi
    #fi
#
#################################################################################
#
    # Test        : PHP-2382
    # Description : Check listen option
    # Background  : https://github.com/CISOfy/lynis/issues/837
    if [ -n "${PHPINI_ALLFILES}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no PHP-2382 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PHP expose_php 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for FILE in ${PHPINI_ALLFILES}; do
            # Don't look at this setting in cli configuration
            case "${FILE}" in
                */cli/*)
                    continue
                    ;;
            esac
            LogText "测试：检查文件${FILE}"
            FIND=$(${GREPBINARY} -E -i "^listen = [0-9]{1,5}$" ${FILE})
            if HasData "${FIND}"; then
                LogText "结果：发现只监听一个端口号"
                LogText "数据：${FIND}"
                LogText "注意：条件允许时，请将访问限制为仅 localhost，避免外部访问"
                FOUND=1
            fi
        done

        if [ ${FOUND} -eq 1 ]; then
            Display --indent 4 --text "- 检查监听选项" --result "${STATUS_SUGGESTION}" --color YELLOW
            #ReportSuggestion "${TEST_NO}" "Limit the listening of FastCGI to just localhost or a local socket" "listen = 127.0.0.1:9000" "-"
            AddHP 1 3
        else
            Display --indent 4 --text "- 检查监听选项" --result "${STATUS_OK}" --color GREEN
            AddHP 2 2
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
