#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# SNMP related tests
#
#################################################################################
#
    SNMP_DAEMON_CONFIG_LOCS="${ROOTDIR}etc/snmp"
    SNMP_DAEMON_CONFIG=""
    SNMP_DAEMON_RUNNING=0
#
#################################################################################
#
    InsertSection "${SECTION_SNMP_SUPPORT}"

    # Test        : SNMP-3302
    # Description : Check for a running SNMP daemon
    Register --test-no SNMP-3302 --weight L --network NO --category security --description "检查正在运行的 SNMP 守护进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 SNMP 守护进程"
        if IsRunning "snmpd"; then
            SNMP_DAEMON_RUNNING=1
            LogText "结果：SNMP 守护进程正在运行"
            Display --indent 2 --text "- 正在检查运行中的 SNMP 守护进程" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未发现正在运行的 SNMP 守护进程"
            Display --indent 2 --text "- 正在检查运行中的 SNMP 守护进程" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : SNMP-3304
    # Description : Determine SNMP daemon configuration file location
    if [ ${SNMP_DAEMON_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SNMP-3304 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 SNMP 守护进程配置文件位置"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 snmpd.conf 文件"
        for I in ${SNMP_DAEMON_CONFIG_LOCS}; do
            if [ -f "${I}/snmpd.conf" ]; then
                LogText "结果：${I}/snmpd.conf 存在"
                SNMP_DAEMON_CONFIG="${I}/snmpd.conf"
            fi
        done
        if [ -z "${SNMP_DAEMON_CONFIG}" ]; then
            LogText "结果：未找到 snmpd 配置文件"
            Display --indent 4 --text "- 正在检查 SNMP 配置" --result "${STATUS_NOT_FOUND}" --color WHITE
        else
            LogText "结果：使用最后找到的配置文件：${SNMP_DAEMON_CONFIG}"
            Display --indent 4 --text "- 正在检查 SNMP 配置" --result "${STATUS_FOUND}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : SNMP-3306
    # Description : Determine SNMP communities
    if [ -n "${SNMP_DAEMON_CONFIG}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SNMP-3306 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 SNMP 团体字符串"
    if [ ${SKIPTEST} -eq 0 ]; then
        WARN=0
        LogText "检查：读取活动的 SNMP 团体字符串"
        FIND=$(${AWKBINARY} '/^com2sec/ { print $4 }' ${SNMP_DAEMON_CONFIG})
        for I in ${FIND}; do
            LogText "输出：${I}"
            if [ "${I}" = "public" -o "${I}" = "private" ]; then
                LogText "结果：发现容易猜测的 SNMP 团体字符串（${I}）"
                WARN=1
                AddHP 1 3
            fi
        done

        # Check status of test
        if [ ${WARN} -eq 0 ]; then
            Display --indent 2 --text "- 正在检查 SNMP 团体字符串" --result "${STATUS_OK}" --color GREEN
            AddHP 2 2
        else
            Display --indent 2 --text "- 正在检查 SNMP 团体字符串" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "发现容易猜测的 SNMP 团体字符串"
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

# EOF
