#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Time
#
#################################################################################
#
    InsertSection "${SECTION_TIME_AND_SYNCHRONIZATION}"
#
#################################################################################
#
    CRON_DIRS="${ROOTDIR}etc/cron.d ${ROOTDIR}etc/cron.hourly ${ROOTDIR}etc/cron.daily ${ROOTDIR}etc/cron.weekly ${ROOTDIR}etc/cron.monthly ${ROOTDIR}var/spool/crontabs"
    CHRONY_CONF_FILE=""
    NTP_DAEMON=""
    NTP_DAEMON_RUNNING=0
    NTP_CONFIG_FOUND=0
    NTP_CONFIG_TYPE_DAEMON=0
    NTP_CONFIG_TYPE_SCHEDULED=0
    NTP_CONFIG_TYPE_EVENTBASED=0
    NTP_CONFIG_TYPE_STARTUP=0
    NTPD_RUNNING=0 # Specific for ntpd
    OPENNTPD_COMMUNICATION=0 # if ntpctl can communicate
    SYSTEMD_NTP_ENABLED=0
#
#################################################################################
#
    # Test        : TIME-3104
    # Description : Check for a running NTP daemon
    if [ -f /sys/hypervisor/type ]; then
        # TODO: Skip NTP tests if we are in a DomU xen instance
        FIND=$(cat /sys/hypervisor/type)
        if [ "${FIND}" = "xen" ]; then PREQS_MET="NO"; else PREQS_MET="YES"; fi
    elif [ -f /sbin/sysctl ] && [ "$(/sbin/sysctl -n security.jail.jailed 2>/dev/null || echo 0)" -eq 1 ]; then
        # Skip NTP tests if we're in a FreeBSD jail
        PREQS_MET="NO"
    else
        PREQS_MET="YES"
    fi
    Register --test-no TIME-3104 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查正在运行的 NTP 守护进程或客户端"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Linux/FreeBSD (ntpdate), OpenBSD (ntpd, rdate), Chrony, systemd-timesyncd
        LogText "检查：搜索正在运行的 NTP 守护进程或可用客户端"
        FOUND=0

        SEARCH_FILES="${ROOTDIR}etc/chrony.conf ${ROOTDIR}etc/chrony/chrony.conf"
        for FILE in ${SEARCH_FILES}; do
            if [ -f ${FILE} ]; then LogText "结果：发现 chrony 配置文件 ${FILE}"; CHRONY_CONF_FILE="${FILE}"; fi
        done
        if [ -n "${CHRONY_CONF_FILE}" ]; then
            if IsRunning "chronyd"; then
                FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="chronyd"
                Display --indent 2 --text "- 发现 NTP 守护进程：chronyd" --result "${STATUS_FOUND}" --color GREEN
            else
                LogText "结果：发现 chrony 配置，但守护进程未运行"
            fi
        else
            LogText "结果：未发现 chrony 配置"
        fi

        # Check time daemon (eg DragonFly BSD)
        if IsRunning "dntpd"; then
            FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="dntpd"
            Display --indent 2 --text "- 发现 NTP 守护进程：dntpd" --result "${STATUS_FOUND}" --color GREEN
        fi

        # Check for OpenNTPD, ntpctl comes with a "regular" install
        if [ -n "${NTPCTLBINARY}" ]; then
            # In contrast to timectl, "synchronised: yes" is not grepped.
            # Reason: openntpd syncs only if large time corrections are not required or -s is passed.
            #         This might be not intended by the administrator (-s is NOT the default!)
            FIND=$(${PSBINARY} ax | ${GREPBINARY} "ntpd: ntp engine" | ${GREPBINARY} -v "grep")
            # Status code 0 is when communication over the socket is successful
            if ${NTPCTLBINARY} -s status > /dev/null 2> /dev/null; then
                FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="openntpd"
                LogText "结果：发现 openntpd（检测方式：ntpctl）"
                OPENNTPD_COMMUNICATION=1
            elif [ -n "${FIND}" ] ; then
                # Reasons for ntpctl to fail might be someone spawned a new process thus overwriting the socket,
                # then ended it, but another openntpd process is still running
                FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="openntpd"
                LogText "结果：发现 openntpd（检测方式：ps）"
            else
                LogText "结果：未发现正在运行的 openntpd，但已安装 ntpctl"
            fi

            if [ "${NTP_DAEMON}" = "openntpd" ]; then
                Display --indent 2 --text "- 发现 NTP 守护进程：OpenNTPD" --result "${STATUS_FOUND}" --color GREEN
            fi
        fi

        # Check running processes (ntpd from ntp.org)
        # As checking by process name is ambiguous (openntpd has the same process name),
        # this check will be skipped if openntpd has been found.
        FIND=$(${PSBINARY} ax | ${GREPBINARY} "ntpd" | ${GREPBINARY} -v "dntpd" | ${GREPBINARY} -v "ntpd: " | ${GREPBINARY} -v "grep")
        if [ "${NTP_DAEMON}" != "openntpd" ] && [  -n "${FIND}" ]; then
            FOUND=1; NTPD_RUNNING=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1
            NTP_DAEMON="ntpd"
            LogText "结果：在进程列表中发现正在运行的 NTP 守护进程"
            Display --indent 2 --text "- 发现 NTP 守护进程：ntpd" --result "${STATUS_FOUND}" --color GREEN
        fi

        # Check time daemon (eg NetBSD)
        if IsRunning "timed"; then
            FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="timed"
            Display --indent 2 --text "- 发现 NTP 守护进程：timed" --result "${STATUS_FOUND}" --color GREEN
        fi

        # Check timedate daemon (systemd)
        FIND=$(${PSBINARY} ax | ${GREPBINARY} "systemd-timesyncd" | ${GREPBINARY} -v "grep")
        if [  -n "${FIND}" ]; then
            FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="systemd-timesyncd"
            Display --indent 2 --text "- 发现 NTP 守护进程：systemd-timesyncd" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：在进程列表中发现正在运行的 systemd-timesyncd"
        fi

        # Check crontab for OpenBSD/FreeBSD
        # Check anacrontab for Linux
        CRONTAB_FILES="/etc/anacrontab /etc/crontab"
        # Regex for matching multiple time synchronisation binaries
        # Partial sanity check for sntp and ntpdig, but this does not consider all corner cases
        CRONTAB_REGEX='ntpdate|rdate|sntp.+-(s|j|--adj)|ntpdig.+-(S|s)'
        for I in ${CRONTAB_FILES}; do
            if [ -f ${I} ]; then
                LogText "检查：在 crontab 文件 ${I} 中搜索 ntpdate、rdate、sntp 或 ntpdig"
                FIND=$(${GREPBINARY} -E "${CRONTAB_REGEX}" ${I} | ${GREPBINARY} -v '^#')
                if [ -n "${FIND}" ]; then
                    FOUND=1; NTP_CONFIG_TYPE_SCHEDULED=1
                    Display --indent 2 --text "- 检查 crontab 文件中的 NTP 客户端（${I}）" --result "${STATUS_FOUND}" --color GREEN
                    LogText "结果：在 crontab 文件 ${I} 中发现 ntpdate、rdate、sntp 或 ntpdig 配置"
                else
                    #Display --indent 2 --text "- 检查 crontab 文件中的 NTP 客户端（${I}）" --result "${STATUS_NOT_FOUND}" --color WHITE
                    LogText "结果：crontab 文件 ${I} 中未发现 ntpdate、rdate、sntp 或 ntpdig 配置"
                fi
            else
                LogText "结果：未找到 crontab 文件 ${I}"
            fi
        done

        # Notes: only test for normal files. File /etc/cron.d/FIFO on solaris is a special file and test may hang
        # Linux systems may have a .placeholder file
        FOUND_IN_CRON=0

        # Check cron jobs
        for I in ${CRON_DIRS}; do
            for J in "${I}"/*; do  # iterate over folders in a safe way
                # Check: regular file, readable and not called .placeholder
                FIND=$(echo "${J}" | ${GREPBINARY} -E '/.placeholder$')
                if [ -f "${J}" ] && [ -r "${J}" ] && [ -z "${FIND}" ]; then
                    LogText "检查：在 ${J} 中搜索 ntpdate、rdate、sntp 或 ntpdig"
                    FIND=$("${GREPBINARY}" -E "${CRONTAB_REGEX}" "${J}" | "${GREPBINARY}" -v "^#")
                    if [ -n "${FIND}" ]; then
                        FOUND=1; FOUND_IN_CRON=1; NTP_CONFIG_TYPE_SCHEDULED=1
                        LogText "结果：在 ${J} 中发现 ntpdate、rdate、sntp 或 ntpdig"
                    fi
                fi
            done
        done

        if [ ${FOUND_IN_CRON} -eq 1 ]; then
            Display --indent 2 --text "- 检查 cron 文件中的 NTP 客户端" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：在 cron 目录中发现 ntpdate 或 rdate"
        else
            LogText "结果：cron 目录中未发现 ntpdate 或 rdate"
        fi

        # Checking if ntpdate is performed by event
        LogText "检查：确认文件 /etc/network/if-up.d/ntpdate 是否存在"
        if [ -f /etc/network/if-up.d/ntpdate ]; then
            LogText "结果：发现网络接口启动时执行的 ntpdate 操作"
            FOUND=1
            NTP_CONFIG_TYPE_EVENTBASED=1
            Display --indent 2 --text "- 检查基于网络事件的 ntpdate（if-up）" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：文件 /etc/network/if-up.d/ntpdate 不存在"
        fi

        # Configuration file for *BSD
        if [ -f /etc/rc.conf ]; then
            LogText "检查：确认 *BSD 是否在启动时启用 ntpdate"
            FIND=$(${GREPBINARY} 'ntpdate_enable="YES"' /etc/rc.conf)
            if [ -n "${FIND}" ]; then
                LogText "结果：rc.conf 中已启用 ntpdate"
                FOUND=1
                NTP_CONFIG_TYPE_STARTUP=1
                # Only show suggestion when ntpdate is enabled, however ntpd is not running
                if [ ${NTP_DAEMON_RUNNING} -eq 0 ]; then
                    ReportSuggestion "${TEST_NO}" "虽然 rc.conf 中已启用 ntpdate，但建议至少每天运行一次，或改用 NTP 守护进程"
                fi
            else
                LogText "结果：rc.conf 中未启用 ntpdate"
            fi
        fi

        if [ ${FOUND} -eq 0 ]; then
            if [ ${ISVIRTUALMACHINE} -eq 1 ]; then
                LogText "结果：虚拟机通常无需在虚拟机内部单独同步时间，因此不显示警告"
            else
                Display --indent 2 --text "- 检查正在运行的 NTP 守护进程或客户端" --result "${STATUS_WARNING}" --color RED
                LogText "结果：未找到 NTP 守护进程或客户端"
                ReportSuggestion "${TEST_NO}" "使用 NTP 守护进程或客户端避免时间问题。"
                AddHP 0 2
            fi
        else
            Display --indent 2 --text "- 检查正在运行的 NTP 守护进程或客户端" --result "${STATUS_OK}" --color GREEN
            LogText "结果：发现时间同步守护进程或客户端。"
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3106
    # Description : Check status of systemd time synchronization
    if [ ${SYSTEMD_NTP_ENABLED} -eq 1 -a -n "${TIMEDATECTL}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3106 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 systemd NTP 时间同步状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：通过 timedatectl 检查时间同步状态"
        FIND=$(${TIMEDATECTL} status | ${GREPBINARY} -E "(NTP|System clock) synchronized: yes")
        if [ -z "${FIND}" ]; then
            LogText "结果：时间未通过 NTP 同步"
            ReportSuggestion "${TEST_NO}" "检查 timedatectl 输出；NTP 同步已启用，但状态显示尚未同步"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3112
    # Description : Check for valid associations from ntpq peers list
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3112 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查活动的 NTP 关联 ID"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：从 ntpq peers 列表中检查 NTP 关联 ID"
        FIND=$(${NTPQBINARY} -p -n | ${GREPBINARY} "No association ID's returned")
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 检查有效的关联 ID" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：发现一个或多个关联 ID"
        else
            Display --indent 2 --text "- 检查有效的关联 ID" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "检查 ntp.conf 中的 NTP 服务器配置以及名称解析服务是否正常。"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3116
    # Description : Check for stratum 16 peers
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3116 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 stratum 值为 16 的对等节点"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "检查：从 ntpq peers 列表中检查 stratum 16 时间源"
        FIND=$(${NTPQBINARY} -p -n | ${AWKBINARY} '{ if ($2!=".POOL." && $3=="16") { print $1 }}')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 检查高 stratum NTP 对等节点" --result "${STATUS_OK}" --color GREEN
            LogText "结果：所有对等节点的 stratum 均低于 16"
        else
            for ITEM in ${FIND}; do
                LogText "发现 stratum 16 对等节点：${ITEM}"
                FIND2=$(${GREPBINARY} -E "^ntp-ignore-stratum-16-peer=${ITEM}" ${PROFILE})
                if IsEmpty "${FIND2}"; then
                    COUNT=$((COUNT + 1))
                    Report "ntp_stratum_16_peer[]=${ITEM}"
                else
                    LogText "输出：配置文件已忽略主机 ${ITEM}"
                fi
            done
            # Check if one or more high stratum time servers are found
            if [ ${COUNT} -eq 0 ]; then
                Display --indent 2 --text "- 检查高 stratum NTP 对等节点" --result "${STATUS_OK}" --color GREEN
                LogText "结果：所有非本地服务器的 stratum 均低于 16，或已在扫描配置中加入白名单"
            else
                Display --indent 2 --text "- 检查高 stratum NTP 对等节点" --result "${STATUS_WARNING}" --color RED
                LogText "结果：发现 ${COUNT} 个高 stratum（16）对等节点"
                ReportSuggestion "${TEST_NO}" "检查 ntpq peers 输出中的 stratum 16 对等节点"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3120
    # Description : Check unreliable peers from peer list
    # Notes       : Items with # are too far away (network distance)
    #               Items with - are not chosen due clustering algorithm
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3120 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查不可靠的 NTP 对等节点"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查不可靠的 NTP 对等节点"
        FIND=$(${NTPQBINARY} -p -n | ${GREPBINARY} -E "^(-|#)" | ${AWKBINARY} '{ print $1 }' | ${SEDBINARY} 's/^-//g')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 检查不可靠的 NTP 对等节点" --result "${STATUS_NONE}" --color GREEN
            LogText "结果：未发现不可靠的对等节点"
        else
            Display --indent 2 --text "- 检查不可靠的 NTP 对等节点" --result "${STATUS_FOUND}" --color YELLOW
            LogText "结果：发现一个或多个不可靠的对等节点（以减号或井号标记）"
            for I in ${FIND}; do
                LogText "不可靠的对等节点：${I}"
                Report "ntp_unreliable_peer[]=${I}"
            done
            ReportSuggestion "${TEST_NO}" "检查 ntpq peers 输出中的不可靠节点，并修正或替换它们"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3124
    # Description : 检查选定的时间源
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3124 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查选定的时间源"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查选定的时间源"
        FIND=$(${NTPQBINARY} -p -n | ${GREPBINARY} '^*' | ${AWKBINARY} '{ if ($4=="l") { print $1 } }')
        FIND2=$(${NTPQBINARY} -p -n | ${GREPBINARY} '^*' | ${AWKBINARY} '{ print $1 }')
        if [ -z "${FIND}" -a -n "${FIND2}" ]; then
            Display --indent 2 --text "- 检查选定的时间源" --result "${STATUS_OK}" --color GREEN
            FIND2=$(echo ${FIND2} | ${SEDBINARY} 's/*//g')
            LogText "结果：发现选定的时间源（值：${FIND2}）"
        else
            Display --indent 2 --text "- 检查选定的时间源" --result "${STATUS_WARNING}" --color RED
            LogText "结果：本地时间源被选为同步源，可能表示没有可用的外部时间源。"
            LogText "本地时间源：${FIND}"
            ReportSuggestion "${TEST_NO}" "检查 ntpq peers 输出中的选定时间源"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3128
    # Description : Check time source candidates
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3128 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查首选时间源"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查首选时间源"
        FIND=$(${NTPQBINARY} -p -n | ${GREPBINARY} '^+' | ${AWKBINARY} '{ print $1 }')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 检查候选时间源" --result "${STATUS_NONE}" --color YELLOW
            LogText "结果：未发现其他候选时间源"
            ReportSuggestion "${TEST_NO}" "检查 ntpq peers 输出中的候选时间源"
        else
            Display --indent 2 --text "- 检查候选时间源" --result "${STATUS_OK}" --color GREEN
            LogText "结果：发现一个或多个可用于时间同步的候选源。"
            for I in ${FIND}; do
                I=$(echo ${I} | ${SEDBINARY} 's/+//g')
                LogText "发现候选时间源：${I}"
            done
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3132
    # Description : Check ntpq falsetickers
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3132 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 NTP 错误时间源（falseticker）"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查首选时间源"
        FIND=$(${NTPQBINARY} -p -n | ${GREPBINARY} -E '^x')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 检查错误时间源（falseticker）" --result "${STATUS_OK}" --color GREEN
            LogText "结果：未发现错误时间源（以 'x' 开头的项目）"
        else
            Display --indent 2 --text "- 检查错误时间源（falseticker）" --result "${STATUS_NONE}" --color YELLOW
            LogText "结果：发现一个或多个错误时间源（以 'x' 开头的项目）"
            for I in ${FIND}; do
                I=$(echo ${I} | ${SEDBINARY} 's/x//g')
                LogText "发现错误时间源：${I}"
                Report "ntp_falseticker[]=${I}"
            done
            ReportSuggestion "${TEST_NO}" "检查 ntpq peers 输出中的错误时间源"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3136
    # Description : Check ntpq reported ntp version (Linux)
    if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3136 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 NTP 协议版本"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 NTP 协议版本（ntpq -c ntpversion）"
        FIND=$(${NTPQBINARY} -c ntpversion | ${AWKBINARY} '{ if ($1=="NTP" && $2=="version" && $5=="is") { print $6 } }')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 检查 NTP 版本" --result "${STATUS_UNKNOWN}" --color YELLOW
            LogText "结果：未发现 NTP 版本"
            ReportSuggestion "${TEST_NO}" "检查 ntpq 输出中的 NTP 协议版本"
        else
            Display --indent 2 --text "- 检查 NTP 版本" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：发现 NTP 版本 ${FIND}"
            Report "ntp_version=${FIND}"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3146
    # Description : Check /etc/default/ntpdate (Linux)
    # Notes       : ntpdate-debian binary
    #if [ ${NTPD_RUNNING} -eq 1 -a -n "${NTPQBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no TIME-3146 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "Check /etc/default/ntpdate"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : TIME-3148
    # Description : Check if TZ variable is set (Linux)
    # Notes       : without TZ variable set, a lot of unneeded calls might be performed.
    Register --test-no TIME-3148 --os Linux --weight L --network NO --category performance --description "检查 TZ 变量"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 TZ 变量"
        FIND="${TZ:=notset}"
        LogText "结果：发现 TZ 变量，值为 ${FIND}"
        if [ "${FIND}" = "notset" ]; then
            Report "tz_variable_empty=1"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3160
    # Description : 检查空的 NTP step-tickers 文件
    # Notes       : Mostly applies to Red Hat and clones
    FILE="${ROOTDIR}etc/ntp/step-tickers"
    if [ "${NTPD_RUNNING}" -eq 1 -a -n "${NTPQBINARY}" -a -f "${FILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no TIME-3160 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查空的 NTP step-tickers 文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        OUTPUT=$(${AWKBINARY} '/^[a-z0-9]/ { print $1 }' ${FILE})
        if [ -z "${OUTPUT}" ]; then
            if [ ${OS_REDHAT_OR_CLONE} -eq 1 -a -f "${FILE}" ]; then
                # On RedHat if step-ticker file exists but is empty, the ntpdate start script uses the servers listed in ntp.conf for the initial time synchronization
                LogText "结果：${FILE} 存在但为空；在 Red Hat 系统上，初始时间同步将使用 ntp.conf 中列出的服务器。"
                Display --indent 2 --text "- 检查 NTP step-tickers 文件" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果：${FILE} 为空，step-tickers 中没有配置 NTP 服务器"
                Display --indent 2 --text "- 检查 NTP step-tickers 文件" --result "空文件" --color YELLOW
                ReportSuggestion "${TEST_NO}" "使用 step-tickers 文件加快时间同步"
            fi
        else
            LogText "结果：${FILE} 不为空，状态正常"
            Display --indent 2 --text "- 检查 NTP step-tickers 文件" --result "${STATUS_OK}" --color GREEN
            sFIND=$(${AWKBINARY} '/^[a-z0-9]/ { print $1 }' ${FILE} | ${GREPBINARY} -E -v "^127." | ${GREPBINARY} -E -v "^::1")
            for I in ${sFIND}; do
                FIND=$(${GREPBINARY} ^${I} ${FILE} | wc -l)
                if [ ${FIND} -gt 0 ]; then
                    LogText "结果：${I} 存在于 ${FILE}"
                else
                    LogText "结果：${I} 不存在于 ${FILE}"
                    FOUND=1
                fi
            done
            if [ ${FOUND} -eq 1 ]; then
                Display --indent 4 --text "- 检查 step-tickers 中的 NTP 服务器条目" --result "部分缺失" --color YELLOW
                ReportSuggestion "${TEST_NO}" "step-tickers 文件中缺少部分时间服务器"
                AddHP 3 4
            else
                Display --indent 4 --text "- 检查 step-tickers 中的 NTP 服务器条目" --result "${STATUS_OK}" --color GREEN
                LogText "结果：所有时间服务器都在 step-tickers 文件中"
                AddHP 4 4
            fi
        fi
        LogText "信息：step-tickers 由 ntpdate 使用，而 ntp.conf 是 ntpd 的配置文件。ntpdate 会在 ntpd 启动前设置时钟，确保时间差在 1000 秒以内。"
        LogText "风险：如果服务器与客户端的时间差超过 1000 秒，NTP 可能无法在启动时运行。"
    fi
#
#################################################################################
#
    # Test        : TIME-3170
    # Description : Check file permissions and ownership of configuration files
    # Notes       : Files should be owned by root, or the user running
    #               Group owner should have only read access
    #               Other should preferably have no access, or read-only at max

    FILE_ARRAY="${ROOTDIR}etc/chrony.conf ${ROOTDIR}usr/pkg/etc/chrony.conf \
        ${ROOTDIR}etc/inet/ntp.conf ${ROOTDIR}etc/ntp.conf ${ROOTDIR}usr/local/etc/ntp.conf\
        ${ROOTDIR}etc/ntpd.conf ${ROOTDIR}etc/openntpd/ntpd.conf ${ROOTDIR}usr/local/etc/ntpd.conf"

    Register --test-no TIME-3170 --weight L --network NO --category security --description "检查时间同步配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        for FILE in ${FILE_ARRAY}; do
            if [ -f ${FILE} ]; then
                LogText "结果：发现 ${FILE}"
                if IsWorldWritable ${FILE}; then
                    ReportWarning "${TEST_NO}" "发现所有用户均可写的配置文件" "${FILE}" ""
                fi
                Report "ntp_config_file[]=${FILE}"
                NTP_CONFIG_FOUND=1
            fi
        done
    fi
#
#################################################################################
#
    # Test        : TIME-3180
    # Description : 检查 ntpctl 是否无法与 OpenNTPD 通信
    if [ "${NTP_DAEMON_RUNNING}" -eq 1 ] && [ -n "${NTPCTLBINARY}" ] && [ "${NTP_DAEMON}" = "openntpd" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi
    Register --test-no TIME-3180 --preqs-met "${PREQS_MET}" --weight L --network NO --category security --description "检查 ntpctl 是否无法与 OpenNTPD 通信"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ "${OPENNTPD_COMMUNICATION}" -eq 0 ]; then
            ReportWarning "${TEST_NO}" "发现 OpenNTPD，但 ntpctl 无法与其通信" "${NTPCTLBINARY} -s 状态" "重启 OpenNTPD"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3181
    # Description : 检查 OpenNTPD 时间同步状态
    if [ "${NTP_DAEMON_RUNNING}" -eq 1 ] && [ -n "${NTPCTLBINARY}" ] && [ "${NTP_DAEMON}" = "openntpd" ] && [ "${OPENNTPD_COMMUNICATION}" -eq 1 ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi

    Register --test-no TIME-3181 --preqs-met "${PREQS_MET}" --weight L --network NO --category security --description "检查 OpenNTPD 时间同步状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${NTPCTLBINARY} -s status | ${GREPBINARY} "clock synced" )
        if [ -z "${FIND}" ]; then
            ReportWarning "${TEST_NO}" "OpenNTPD 未同步系统时间" "${NTPCTLBINARY} -s 状态" "text：手动设置一次时间，或检查网络连接。"
        fi
    fi
#
#################################################################################
#
    # Test        : TIME-3182
    # Description : 检查 OpenNTPD 是否有可用的对等节点

    if [ "${NTP_DAEMON_RUNNING}" -eq 1 ] && [ -n "${NTPCTLBINARY}" ] && [ "${NTP_DAEMON}" = "openntpd" ] && [ "${OPENNTPD_COMMUNICATION}" -eq 1 ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi

    Register --test-no TIME-3182 --preqs-met "${PREQS_MET}" --weight L --network NO --category security --description "检查 OpenNTPD 是否有可用的对等节点"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Format is "xx/yy peers valid, ..."
        FIND=$(${NTPCTLBINARY} -s status | ${GREPBINARY} -E -o '[0-9]+/[0-9]+' | ${CUTBINARY} -d '/' -f 1)
        if [ -z "${FIND}" ] || [ "${FIND}" -eq 0 ]; then
            ReportWarning "${TEST_NO}" "OpenNTPD 没有可用的对等节点" "${NTPCTLBINARY} -s 状态"
        fi
    fi

#
#################################################################################
#

    # Test        : TIME-3185
    # Description : 检查 systemd-timesyncd 时间同步

    if [ "${NTP_DAEMON}" = "systemd-timesyncd" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi


    Register --test-no TIME-3185 --preqs-met "${PREQS_MET}" --weight L --network NO --category "security" --description "检查 systemd-timesyncd 时间同步"
    SYNCHRONIZED_FILE="/run/systemd/timesync/synchronized"
       
    if [ ${SKIPTEST} -eq 0 ]; then
        # On earlier systemd versions (237), '/run/systemd/timesync/synchronized' does not exist, so use '/var/lib/systemd/timesync/clock'
        if [ ! -e "${SYNCHRONIZED_FILE}" ]; then
            SYNCHRONIZED_FILE="/var/lib/systemd/timesync/clock"
        fi
        # DynamicUser=yes moves the clock file to '/var/lib/private/systemd/timesync/clock'
        if [ ! -e "${SYNCHRONIZED_FILE}" ]; then
            SYNCHRONIZED_FILE="/var/lib/private/systemd/timesync/clock"
        fi
        # Fix for debian stretch
        if [ ! -e "${SYNCHRONIZED_FILE}" ]; then
            SYNCHRONIZED_FILE="/var/lib/systemd/clock"
        fi
        if [ -e "${SYNCHRONIZED_FILE}" ]; then
           FIND=$(( $(date +%s) - $(${STATBINARY} -L --format %Y "${SYNCHRONIZED_FILE}") ))
           # Check if last sync was more than 2048 seconds (= the default of systemd) ago
           if [ "${FIND}" -ge 2048 ]; then
               COLOR=RED
               ReportWarning "${TEST_NO}" "systemd-timesyncd 最近没有同步时间。"
           else
               COLOR=GREEN
           fi
           Display --indent 2 --text "- 上次时间同步" --result "${FIND}s" --color "${COLOR}"
           LogText "结果：systemd-timesyncd 在 ${FIND} 秒前完成时间同步。"
        else
           Display --indent 2 --text "- 上次时间同步" --result "${STATUS_NOT_FOUND}" --color RED
           ReportWarning "${TEST_NO}" "systemd-timesyncd 从未成功同步时间"
        fi
    fi
    unset SYNCHRONIZED_FILE

#
#################################################################################
#

    Report "ntp_config_found=${NTP_CONFIG_FOUND}"
    Report "ntp_config_type_daemon=${NTP_CONFIG_TYPE_DAEMON}"
    Report "ntp_config_type_eventbased=${NTP_CONFIG_TYPE_EVENTBASED}"
    Report "ntp_config_type_scheduled=${NTP_CONFIG_TYPE_SCHEDULED}"
    Report "ntp_config_type_startup=${NTP_CONFIG_TYPE_STARTUP}"
    Report "ntp_daemon=${NTP_DAEMON}"
    Report "ntp_daemon_running=${NTP_DAEMON_RUNNING}"
#
#################################################################################
#
    # For VMs check ntpd.conf : tinker panic 0

    # OS        Time daemons  Configuration file
    # --------------------------------------------
    # AIX       xntpd         /etc/ntp.conf
    # HP
    # Linux     ntpd          /etc/ntp.conf
    #           chrony        /etc/chrony.conf
    # OpenBSD   ntpd          /etc/ntpd.conf
    # Solaris   xntpd         /etc/inet/ntp.conf

    WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
