#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# User, Group and authentication tests
#
#################################################################################
#
    LDAP_AUTH_ENABLED=0
    LDAP_PAM_ENABLED=0
    LDAP_CONF_LOCATIONS="${ROOTDIR}etc/ldap.conf ${ROOTDIR}etc/ldap/ldap.conf ${ROOTDIR}etc/openldap/ldap.conf ${ROOTDIR}usr/local/etc/ldap.conf ${ROOTDIR}usr/local/etc/openldap/ldap.conf"
    PAM_FILE_LOCATIONS="${ROOTDIR}usr/lib/aarch64-linux-gnu/security ${ROOTDIR}lib/arm-linux-gnueabihf/security ${ROOTDIR}lib/i386-linux-gnu/security ${ROOTDIR}lib/security ${ROOTDIR}lib/x86_64-linux-gnu/security ${ROOTDIR}lib/powerpc64le-linux-gnu/security ${ROOTDIR}lib64/security ${ROOTDIR}usr/lib /usr/lib/security"
    SUDOERS_LOCATIONS="${ROOTDIR}etc/sudoers ${ROOTDIR}usr/local/etc/sudoers ${ROOTDIR}usr/pkg/etc/sudoers"
    SUDOERS_FILE=""
#
#################################################################################
#
    InsertSection "${SECTION_USERS_GROUPS_AND_AUTHENTICATION}"

    # Test        : AUTH-9204
    # Description : Check users with UID zero (0)
    # Notes       : Ignores :0: in file if match is in NIS related line
    Register --test-no AUTH-9204 --weight L --network NO --category security --description "检查 UID 为 0 的用户"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Search accounts with UID 0
        LogText "检查：搜索 UID 为 0 的账户"
        # Check if device is a QNAP, as the root user is called admin, and not root
        if [ ${QNAP_DEVICE} -eq 1 ]; then
            FIND=$(${GREPBINARY} ':0:' ${ROOTDIR}etc/passwd | ${GREPBINARY} -E -v '^#|^admin:|^(\+:\*)?:0:0:::' | ${CUTBINARY} -d ":" -f1,3 | ${GREPBINARY} ':0')
        else
            FIND=$(${GREPBINARY} ':0:' ${ROOTDIR}etc/passwd | ${GREPBINARY} -E -v '^#|^root:|^(\+:\*)?:0:0:::' | ${CUTBINARY} -d ":" -f1,3 | ${GREPBINARY} ':0')
        fi
        if [ -n "${FIND}" ]; then
            Display --indent 2 --text "- 管理员账户" --result "${STATUS_WARNING}" --color RED
            LogText "结果：发现多个管理员账户"
            ReportWarning "${TEST_NO}" "passwd 文件中发现多个 UID 为 0 的用户"
            for USER in ${FIND}; do
                LogText "管理员账户：${USER}"
                Report "user_with_uid_zero[]=${USER}"
                if [ "${USER}" = "toor" ]; then
                    LogText "BSD 说明：系统默认安装了用户 'toor'。除非为其设置密码并用于"
                    LogText "日常操作或紧急情况，否则通常无需保留，例如 root 用户的 Shell 配置异常。"
                    ReportSuggestion "${TEST_NO}" "如未使用，请通过 vipw 删除 'toor' 用户。"
                fi
            done
        else
            Display --indent 2 --text "- 管理员账户" --result "${STATUS_OK}" --color GREEN
            LogText "结果：除 root 外未发现其他 UID 为 0 的账户。"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9208
    # Description : Check non-unique accounts
    Register --test-no AUTH-9208 --weight L --network NO --category security --description "检查 passwd 文件中的重复账户"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：查找重复账户"
        if  [ "${OS}" = "DragonFly" -o "${OS}" = "FreeBSD" -o "${OS}" = "NetBSD" -o "${OS}" = "OpenBSD" ]; then
            PASSWD_FILE="${ROOTDIR}etc/master.passwd"
          else
            PASSWD_FILE="${ROOTDIR}etc/passwd"
        fi
        # Check password file
        if [ -f ${PASSWD_FILE} ]; then
            FIND=$(${GREPBINARY} -v '^#' ${PASSWD_FILE} | ${CUTBINARY} -d ':' -f3 | ${SORTBINARY} | uniq -d)
            if [ "${FIND}" = "" ]; then
                Display --indent 2 --text "- UID 唯一性" --result "${STATUS_OK}" --color GREEN
                LogText "结果：${PASSWD_FILE} 中的所有账户 UID 均唯一"
            else
                Display --indent 2 --text "- UID 唯一性" --result "${STATUS_WARNING}" --color RED
                LogText "结果：发现多个账户使用相同 UID"
                LogText "输出（重复 UID）：${FIND}"
                ReportWarning "${TEST_NO}" "发现多个账户使用相同 UID"
            fi
          else
            Display --indent 2 --text "- UID 唯一性" --result "${STATUS_SKIPPED}" --color WHITE
            LogText "结果：${PASSWD_FILE} 文件不可用，跳过检查"
        fi
        LogText "说明：重复 UID 可能带来系统风险，也可能是配置错误"
    fi
#
#################################################################################
#
    # Test        : AUTH-9212
    # Description : 检查组文件 with chkgrp tool (ie FreeBSD)
    LogText "前置检查：/usr/sbin/chkgrp"
    if [ -x ${ROOTDIR}usr/sbin/chkgrp ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9212 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查组文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 检查 chkgrp 工具" --result "${STATUS_FOUND}" --color GREEN
        LogText "结果：发现 /usr/sbin/chkgrp，将用它执行后续检查。"
        LogText "检查：验证 /etc/group 文件一致性"
        FIND=$(${ROOTDIR}usr/sbin/chkgrp | ${GREPBINARY} -v 'is fine')
        if [ "${FIND}" = "" ]; then
            Display --indent 4 --text "- 检查 /etc/group 文件一致性" --result "${STATUS_OK}" --color GREEN
            LogText "结果：chkgrp 检查完成，组文件看起来正常。"
          else
            Display --indent 4 --text "- 检查 /etc/group 文件一致性" --result "${STATUS_WARNING}" --color RED
            LogText "结果：chkgrp 发现错误，请手动运行该工具查看详情。"
            LogText "chkgrp 输出：${FIND}"
            ReportWarning "${TEST_NO}" "chkgrp 报告 /etc/group 文件存在不一致"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9216
    # Description : Check /etc/group and shadow group files
    # Notes       : Run grpck to test group files (most likely /etc/group and shadow group files)
    if [ -n "${GRPCKBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9216 --preqs-met ${PREQS_MET} --weight L --network NO --root-only YES --category security --description "检查 group 和 shadow group 文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：分析 grpck 输出"

        case ${OS} in
            "AIX")  FIND=$(${GRPCKBINARY} -n ALL 2> /dev/null ; echo $?) ;;
            "Linux")
                if [ "${LINUX_VERSION}" = "SuSE" ]; then
                    FIND=$(${GRPCKBINARY} -q -r > /dev/null ; echo $?)
                else
                    FIND=$(${GRPCKBINARY} -r 2> /dev/null ; echo $?)
                fi
                ;;
            *)      FIND=$(${GRPCKBINARY} 2> /dev/null ; echo $?) ;;
        esac

        # Check exit-code
        if [ "${FIND}" = "0" ]; then
            Display --indent 2 --text "- 组文件一致性（grpck）" --result "${STATUS_OK}" --color GREEN
            LogText "结果：grpck 未在组文件中发现错误"
        else
            Display --indent 2 --text "- 组文件一致性（grpck）" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "grpck 在一个或多个组文件中发现错误"
        fi
        unset FIND
    fi
#
#################################################################################
#
    # Test        : AUTH-9218
    # Description : 检查无密码账户的登录 Shell
    # Notes       : Results should be checked
    Register --test-no AUTH-9218 --os "DragonFly FreeBSD NetBSD OpenBSD" --root-only YES --weight L --network NO --category security --description "检查无密码账户的登录 Shell"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查：检查登录 Shell"
        if [ -f ${ROOTDIR}etc/master.passwd ]; then
            # Check for all shells, except: (/usr)/sbin/nologin /nonexistent
            FIND=$(${GREPBINARY} "[a-z]:\*:" ${ROOTDIR}etc/master.passwd | ${GREPBINARY} -E -v '^#|/sbin/nologin|/usr/sbin/nologin|/nonexistent' | ${SEDBINARY} 's/ /!space!/g')
            if [ -z "${FIND}" ]; then
                Display --indent 2 --text "- 登录 Shell" --result "${STATUS_OK}" --color GREEN
            else
                Display --indent 2 --text "- 登录 Shell" --result "${STATUS_WARNING}" --color RED
                for LINE in ${FIND}; do
                    LINE=$(echo ${LINE} | ${SEDBINARY} 's/!space!/ /g')
                    SHELL=$(echo ${LINE} | ${AWKBINARY} -F: '{ print $10 }')
                    LogText "输出：${LINE}"
                    if [ -z "${SHELL}" ]; then
                        LogText "结果：该行未发现 Shell"
                    else
                        LogText "结果：发现可能存在风险的 Shell ${SHELL}"
                        if [ -f ${SHELL} ]; then
                            LogText "结果：Shell ${SHELL} 存在"
                            FOUND=1
                        else
                            LogText "结果：Shell ${SHELL} 不存在"
                            ReportSuggestion "${TEST_NO}" "确认该账户是否仍有必要保留，因为 Shell ${SHELL} 不存在"
                        fi
                    fi
                done
                if [ ${FOUND} -eq 1 ]; then
                    ReportWarning "${TEST_NO}" "无密码账户使用了可能存在风险的 Shell"
                fi
            fi
          else
            Display --indent 2 --text "- 登录 Shell" --result "${STATUS_SKIPPED}" --color WHITE
            LogText "结果：未找到 ${ROOTDIR}etc/master.passwd 文件"
        fi
        unset LINE SHELL
    fi
#
#################################################################################
#
    # Test        : AUTH-9222
    # Description : Check unique group IDs
    Register --test-no AUTH-9222 --weight L --network NO --category security --description "检查组 ID 唯一性"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：查找 /etc/group 中重复的组 ID"
        FIND=$(${GREPBINARY} -v '^#' ${ROOTDIR}etc/group | ${GREPBINARY} -v '^$' | ${AWKBINARY} -F: '{ print $3 }' | ${SORTBINARY} | uniq -d)
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 组 ID 唯一性" --result "${STATUS_OK}" --color GREEN
            LogText "结果：所有组 ID 均唯一"
            Report "auth_group_ids_unique=1"
        else
            Display --indent 2 --text "- 组 ID 唯一性" --result "${STATUS_WARNING}" --color RED
            LogText "结果：同一组 ID 出现多次"
            for I in ${FIND}; do
                Report "auth_groups_nonunique[]=${I}"
                LogText "重复组：${I}"
            done
            ReportSuggestion "${TEST_NO}" "检查 /etc/group 文件并修正所有不一致"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9226
    # Description : 检查组名唯一性
    if [ -f ${ROOTDIR}etc/group ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9226 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查组名唯一性"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：查找 ${ROOTDIR}etc/group 中重复的组名"
        FIND=$(${GREPBINARY} -v '^#' ${ROOTDIR}etc/group | ${GREPBINARY} -v '^$' | ${AWKBINARY} -F: '{ print $1 }' | ${SORTBINARY} | uniq -d)
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 组名唯一性" --result "${STATUS_OK}" --color GREEN
            LogText "结果：所有组名均唯一"
            Report "auth_group_names_unique=1"
        else
            Display --indent 2 --text "- 组名唯一性" --result "${STATUS_WARNING}" --color RED
            LogText "结果：同一组名出现多次"
            for I in ${FIND}; do
                Report "auth_groups_nonunique[]=${I}"
                LogText "重复组：${I}"
            done
            ReportSuggestion "${TEST_NO}" "检查 ${ROOTDIR}etc/group 文件并修正所有不一致"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9228
    # Description : 使用 pwck 检查密码文件一致性
    # Notes       : Operating systems include Linux, Solaris
    if [ -x ${ROOTDIR}usr/sbin/pwck ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9228 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "使用 pwck 检查密码文件一致性"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：使用 pwck 检查密码文件一致性"
        TESTED=0
        case ${OS} in
            "Linux")
                FIND=$(${ROOTDIR}usr/sbin/pwck -q -r 2> /dev/null; echo $?)
                TESTED=1
            ;;
            "Solaris" | "HP-UX")
                FIND=$(${ROOTDIR}usr/sbin/pwck 2> /dev/null; echo $?)
                TESTED=1
            ;;
            *)
                LogText "开发信息：发现 ${ROOTDIR}usr/sbin/pwck，但不确定在此操作系统上的调用方式"
                ReportException "${TEST_NO}:1" "发现 ${ROOTDIR}usr/sbin/pwck，但不确定在此操作系统上的调用方式"
            ;;
        esac
        # Only display if this test has been executed
        if [ ${TESTED} -eq 1 -a "${FIND}" = "0" ]; then
            Display --indent 2 --text "- 密码文件一致性" --result "${STATUS_OK}" --color GREEN
            LogText "结果：pwck 未发现问题"
            AddHP 2 2
        else
            Display --indent 2 --text "- 密码文件一致性" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "结果：pwck 在密码文件中发现一个或多个错误或警告。"
            ReportSuggestion "${TEST_NO}" "手动运行 pwck 并修正密码文件中的错误"
            AddHP 0 2
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9229
    # Description : 检查密码散列方法 vs. recommendations in crypt(5)
    # Notes       : Applicable to all Unix-like OS
    #               Requires read access to /etc/shadow (if it exists)

    ParsePasswordEntry() {
        METHOD=$1
        case ${METHOD} in
            1:\* | 1:x | 0: | *:!* | *LOCK*)
                # disabled | shadowed | no password | locked account (can be literal *LOCK* or something like LOCKED)
                ;;
            *:\$5\$*| *:\$6\$*)
                # sha256crypt | sha512crypt: check number of rounds, should be >=5000
                ROUNDS=$(echo "${METHOD}" | sed -n 's/.*rounds=\([0-9]*\)\$.*/\1/gp')
                if [ -z "${ROUNDS}" ]; then
                    echo 'sha256crypt/sha512crypt(default=5000rounds)'
                elif [ "${ROUNDS}" -lt 5000 ]; then
                    echo 'sha256crypt/sha512crypt(<5000rounds)'
                fi
                ;;
            *:\$y\$* | *:\$gy\$* | *:\$2b\$* | *:\$7\$*)
                # yescrypt | gost-yescrypt | bcrypt | scrypt
                ;;
            *:_*)
                echo bsdicrypt
                ;;
            *:\$1\$*)
                echo md5crypt
                ;;
            *:\$3\$*)
                echo NT
                ;;
            *:\$md5*)
                echo SunMD5
                ;;
            *:\$sha1*)
                echo sha1crypt
                ;;
            13:* | 178:*)
                echo bigcrypt/descrypt
                ;;
            *)
                echo "未知密码散列方法 ${METHOD}，请报告至 lynis-dev@cisofy.com"
                ;;
        esac
    }

    Register --test-no AUTH-9229 --root-only YES --weight L --network NO --category security --description "检查密码散列方法"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查密码散列方法"
        SHADOW="";
        if [ -e ${ROOTDIR}etc/shadow ]; then SHADOW="${ROOTDIR}etc/shadow"; fi
        FIND=$(${CAT_BINARY} ${ROOTDIR}etc/passwd ${SHADOW} | ${AWKBINARY} -F : '{print length($2) ":" $2 }' | while read METHOD; do
            ParsePasswordEntry ${METHOD}
        done | ${SORTBINARY} -u | ${TRBINARY} '\n' ' ')
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- 密码散列方法" --result "${STATUS_OK}" --color GREEN
            LogText "结果：未发现较弱的密码散列方法"
            AddHP 2 2
        else
            Display --indent 2 --text "- 密码散列方法" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "结果：发现较弱的密码散列方法：${FIND}"
            ReportSuggestion "${TEST_NO}" "检查 PAM 配置；适用时增加散列轮数，并使旧密码过期以使用新参数重新加密"
            AddHP 0 2
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9230
    # Description : 检查密码散列轮数 in login.defs
    # Notes       : Applicable to all Unix-like OS
    PREQS_MET="NO"
    if [ -f ${ROOTDIR}etc/login.defs ]; then
        PREQS_MET="YES"
    fi
    Register --test-no AUTH-9230 --preqs-met ${PREQS_MET} --root-only NO --weight L --network NO --category security --description "检查密码散列轮数"
    if [ ${SKIPTEST} -eq 0 ]; then
        SHA_CRYPT_MIN_ROUNDS_FIND=$(${GREPBINARY} "^SHA_CRYPT_MIN_ROUNDS" ${ROOTDIR}etc/login.defs | ${AWKBINARY} '{ if ($1=="SHA_CRYPT_MIN_ROUNDS") { print $2 } }')
        SHA_CRYPT_MAX_ROUNDS_FIND=$(${GREPBINARY} "^SHA_CRYPT_MAX_ROUNDS" ${ROOTDIR}etc/login.defs | ${AWKBINARY} '{ if ($1=="SHA_CRYPT_MAX_ROUNDS") { print $2 } }')
        SHA_CRYPT_ROUNDS=0

        if [ -n "${SHA_CRYPT_MIN_ROUNDS_FIND}" -a -n "${SHA_CRYPT_MAX_ROUNDS_FIND}" ]; then
            if [ ${SHA_CRYPT_MIN_ROUNDS_FIND} -lt ${SHA_CRYPT_MAX_ROUNDS_FIND} ]; then
                SHA_CRYPT_ROUNDS=${SHA_CRYPT_MIN_ROUNDS_FIND}
            else
                SHA_CRYPT_ROUNDS=${SHA_CRYPT_MAX_ROUNDS_FIND}
            fi
        elif [ -z "${SHA_CRYPT_MIN_ROUNDS_FIND}" -a -n "${SHA_CRYPT_MAX_ROUNDS_FIND}" ]; then
            SHA_CRYPT_ROUNDS=${SHA_CRYPT_MAX_ROUNDS_FIND}
        elif [ -n "${SHA_CRYPT_MIN_ROUNDS_FIND}" -a -z "${SHA_CRYPT_MAX_ROUNDS_FIND}" ]; then
            SHA_CRYPT_ROUNDS=${SHA_CRYPT_MIN_ROUNDS_FIND}
        else
            SHA_CRYPT_ROUNDS=0
        fi

        LogText "检查：${ROOTDIR}etc/login.defs 中的 SHA_CRYPT_{MIN,MAX}_ROUNDS 选项"
        if [ ${SHA_CRYPT_ROUNDS} -eq 0 ]; then
            LogText "结果：未配置密码散列轮数"
            Display --indent 2 --text "- 检查密码散列轮数" --result "${STATUS_DISABLED}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "在 /etc/login.defs 中配置密码散列轮数"
            AddHP 0 2
        fi

        if [ -n "${SHA_CRYPT_ROUNDS}" ] && [ ${SHA_CRYPT_ROUNDS} -gt 0 ]; then
            if [ ${SHA_CRYPT_ROUNDS} -lt 5000 ]; then
                LogText "结果：密码散列轮数过低：${SHA_CRYPT_ROUNDS}"
                Display --indent 2 --text "- 密码散列轮数（最小值）"  --result "${STATUS_SUGGESTION}" --color YELLOW
                AddHP 1 2
            else
                LogText "结果：密码散列轮数为 ${SHA_CRYPT_ROUNDS}"
                Display --indent 2 --text "- 密码散列轮数（最小值）" --result CONFIGURED --color GREEN
                AddHP 2 2
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9234
    # Description : 查询用户账户
    # Notes       : AIX: 100+
    #               HPUX: 100+
    #               macOS doesn't have any user info in /etc/passwd, users are managed with opendirectoryd)
    #               OpenBSD/NetBSD: 1000-60000, excluding 32767 (default)
    #               Arch Linux / CentOS / Ubuntu: 1000+
    Register --test-no AUTH-9234 --weight L --network NO --category security --description "查询用户账户"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：从密码数据库（例如 /etc/passwd）读取系统用户，包括 root"
        FIND=""

        case ${OS} in
            "AIX")
                LogText "AIX 真实用户输出（ID 为 0 或不小于 100）："
                FIND=$(${AWKBINARY} -F: '($3 >= 100 && $3 != 65534) || ($3 == 0) { print $1","$3 }' /etc/passwd)
            ;;

            "FreeBSD")
                LogText "FreeBSD 真实用户输出（ID 为 0 或不小于 1000，但不包括 65534）："
                FIND=$(${AWKBINARY} -F: '($3 >= 1000 && $3 != 65534) || ($3 == 0) { print $1","$3 }' /etc/passwd)
            ;;

            "Linux")
                UID_MIN=""
                if [ -f ${ROOTDIR}etc/login.defs ]; then
                    UID_MIN=$(${GREPBINARY} "^UID_MIN" /etc/login.defs | ${AWKBINARY} '{print $2}')
                    LogText "结果：发现配置的最小用户 ID：${UID_MIN}"
                fi
                if [ "${UID_MIN}" = "" ]; then UID_MIN="1000"; fi
                LogText "Linux 真实用户输出（ID 为 0 或不小于 ${UID_MIN}，但不包括 65534）："
                FIND=$(${AWKBINARY} -v UID_MIN="${UID_MIN}" -F: '($3 >= UID_MIN && $3 != 65534) || ($3 == 0) { print $1","$3 }' /etc/passwd)
            ;;

            "macOS")
                LogText "使用 dscacheutil 获取 macOS 真实用户（ID 为 0 或 500–599）"
                FIND_USERS=$(dscacheutil -q user | ${GREPBINARY} -A 3 -B 2 -e "^uid: 5[0-9][0-9]" | ${GREPBINARY} "^name: " | ${AWKBINARY} '{print $2}')
                if [ -n "${FIND_USERS}" ]; then
                    for FUSERNAME in ${FIND_USERS}; do
                        FDETAILS=$(dscacheutil -q user -a name ${FUSERNAME} | ${GREPBINARY} "^uid: " | ${AWKBINARY} '{print $2}')
                        FIND="${FUSERNAME},${FDETAILS} ${FIND}"
                    done
                else
                    FIND=""
                fi
            ;;

            "NetBSD"|"OpenBSD")
                if [ -f ${ROOTDIR}etc/usermgmt.conf ]; then
                    UID_RANGE=$(${GREPBINARY} "^range" ${ROOTDIR}etc/usermgmt.conf | ${AWKBINARY} '{ sub(/\.\./, "-", $2); print $2 }')
                fi
                if [ -n "${UID_RANGE}" ]; then
                    LogText "结果：发现配置的用户 ID 范围：${UID_RANGE}"
                    UID_MIN=$(echo $UID_RANGE | ${AWKBINARY} -F- '{ print $1 }')
                    UID_MAX=$(echo $UID_RANGE | ${AWKBINARY} -F- '{ print $2 }')
                else
                    UID_MIN=1000
                    UID_MAX=60000
                    LogText "结果：未配置用户 ID 范围，使用默认值 ${UID_MIN}-${UID_MAX}"
                fi
                LogText "${OS} 真实用户输出（ID 为 0 或 ${UID_MIN}-${UID_MAX}，但不包括 32767）："
                FIND=$(${AWKBINARY} -v UID_MIN="${UID_MIN}" -v UID_MAX="${UID_MAX}" -F: '($3 >= UID_MIN && $3 <= UID_MAX && $3 != 32767) || ($3 == 0) { print $1","$3 }' /etc/passwd)
            ;;

            "Solaris")
                LogText "Solaris 真实用户输出（ID 为 0 或不小于 100，但不包括 60001/65534）："
                FIND=$(${AWKBINARY} -F: '($3 >= 100 && $3 != 60001 && $3 != 65534) || ($3 == 0) { print $1","$3 }' /etc/passwd)
            ;;

            *)
                # Want to help improving Lynis? Determine what user IDs belong to normal user accounts
                ReportException "${TEST_NO}:1" "无法确定用户账户"
            ;;
        esac

        # Check if we got any output
        if [ -z "${FIND}" ]; then
            Display --indent 4 --text "结果：未发现用户或结果未知"
            LogText "结果：跳过系统用户查询"
            Display --indent 2 --text "- 查询系统用户（非守护进程账户）" --result "${STATUS_UNKNOWN}" --color YELLOW
        else
            Display --indent 2 --text "- 查询系统用户（非守护进程账户）" --result "${STATUS_DONE}" --color GREEN
            for I in ${FIND}; do
                if [ -n "${I}" ]; then
                    LogText "真实用户：${I}"
                    Report "real_user[]=${I}"
                fi
            done
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9240
    # Description : 查询 NIS+ 身份验证支持
    Register --test-no AUTH-9240 --weight L --network NO --category security --description "查询 NIS+ 身份验证支持"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f /etc/nsswitch.conf ]; then
            FIND=$(${GREPBINARY} -E "^passwd" /etc/nsswitch.conf | ${GREPBINARY} -E "compat|nisplus")
            if [ -z "${FIND}" ]; then
                LogText "结果：未启用 NIS+ 身份验证"
                Display --indent 2 --text "- NIS+ 身份验证支持" --result "${STATUS_NOT_ENABLED}" --color WHITE
            else
                FIND2=$(${GREPBINARY} -E "^passwd_compat" ${ROOTDIR}etc/nsswitch.conf | ${GREPBINARY} "nisplus")
                FIND3=$(${GREPBINARY} -E "^passwd" ${ROOTDIR}etc/nsswitch.conf | ${GREPBINARY} "nisplus")
                if [ -n "${FIND2}" -o -n "${FIND3}" ]; then
                    LogText "结果：已启用 NIS+ 身份验证"
                    Display --indent 2 --text "- NIS+ 身份验证支持" --result "${STATUS_ENABLED}" --color GREEN
                else
                    LogText "结果：未启用 NIS+ 身份验证"
                    Display --indent 2 --text "- NIS+ 身份验证支持" --result "${STATUS_NOT_ENABLED}" --color WHITE
                fi
            fi
          else
            LogText "结果：未找到 /etc/nsswitch.conf"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9242
    # Description : 查询 NIS 身份验证支持
    Register --test-no AUTH-9242 --weight L --network NO --category security --description "查询 NIS 身份验证支持"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f /etc/nsswitch.conf ]; then
            FIND=$(${GREPBINARY} -E "^passwd" /etc/nsswitch.conf | ${GREPBINARY} -E "compat|nis" | ${GREPBINARY} -v "nisplus")
            if [ -z "${FIND}" ]; then
                LogText "结果：未启用 NIS 身份验证"
                Display --indent 2 --text "- NIS 身份验证支持" --result "${STATUS_NOT_ENABLED}" --color WHITE
            else
                FIND2=$(${GREPBINARY} -E "^passwd_compat" /etc/nsswitch.conf | ${GREPBINARY} "nis" | ${GREPBINARY} -v "nisplus")
                FIND3=$(${GREPBINARY} -E "^passwd" /etc/nsswitch.conf | ${GREPBINARY} "nis" | ${GREPBINARY} -v "nisplus")
                if [ -n "${FIND2}" -o -n "${FIND3}" ]; then
                    LogText "结果：已启用 NIS 身份验证"
                    Display --indent 2 --text "- NIS 身份验证支持" --result "${STATUS_ENABLED}" --color GREEN
                else
                    LogText "结果：未启用 NIS 身份验证"
                    Display --indent 2 --text "- NIS 身份验证支持" --result "${STATUS_NOT_ENABLED}" --color WHITE
                fi
            fi
        else
            LogText "结果：未找到 /etc/nsswitch.conf"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9250
    # Description : Check for sudoers file
    Register --test-no AUTH-9250 --weight L --network NO --category security --description "检查 sudoers 文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for I in ${SUDOERS_LOCATIONS}; do
            LogText "检查：确认 ${I} 是否存在"
            if [ -f ${I} ]; then
                FOUND=1
                SUDOERS_FILE="${I}"
                LogText "结果：发现文件（${SUDOERS_FILE}）"
            else
                LogText "结果：未找到文件 ${I}"
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
            LogText "结果：发现 sudoers 文件（${SUDOERS_FILE}）"
            Display --indent 2 --text "- Sudoers 文件" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未找到 sudoers 文件"
            Display --indent 2 --text "- Sudoers 文件" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9252
    # Description : 检查 sudo 配置文件的所有者和权限
    if [ -n "${SUDOERS_FILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9252 --preqs-met ${PREQS_MET} --weight L --network NO --root-only YES --category security --description "检查 sudo 配置文件的所有者和权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        SUDO_CONFIG_FILES="${SUDOERS_FILE}"
        SUDOERS_D="${SUDOERS_FILE}.d"
        if [ -d "${SUDOERS_D}" ]; then
            LogText "检查：检查附加配置目录（${SUDOERS_D}）"
            FIND=$(${LSBINARY} -ld ${SUDOERS_D} | ${CUTBINARY} -c 2-10)
            FIND2=$(${LSBINARY} -lnd ${SUDOERS_D} | ${AWKBINARY} '{print $3$4}')
            LogText "结果：目录权限为 ${FIND}，所有者 UID/GID 为 ${FIND2}"
            case "${FIND}" in
                rwx[r-][w-][x-]--- )
                    LogText "结果：目录 ${SUDOERS_D} 权限正常"
                    if [ "${FIND2}" = "00" ]; then
                        LogText "结果：目录 ${SUDOERS_D} 所有者正常"
                        Display --indent 4 --text "- 目录权限：${SUDOERS_D}" --result "${STATUS_OK}" --color GREEN
                    else
                        LogText "结果：目录 ${SUDOERS_D} 的所有者可能不安全"
                        Display --indent 4 --text "- 目录权限：${SUDOERS_D}" --result "${STATUS_WARNING}" --color RED
                    fi
                    ;;
                * )
                    LogText "结果：目录 ${SUDOERS_D} 的权限可能不安全"
                    if [ "${FIND2}" = "00" ]; then
                        LogText "结果：目录 ${SUDOERS_D} 所有者正常"
                    else
                        LogText "结果：目录 ${SUDOERS_D} 的所有者可能不安全"
                    fi
                    Display --indent 4 --text "- 目录权限：${SUDOERS_D}" --result "${STATUS_WARNING}" --color RED
                    ;;
            esac
            SUDO_CONFIG_FILES="${SUDO_CONFIG_FILES} $(${FINDBINARY} -L ${SUDOERS_D} -type f -print)"
        fi
        for f in ${SUDO_CONFIG_FILES}; do
            LogText "检查：检查文件（${f}）"
            FIND=$(${LSBINARY} -l ${f} | ${CUTBINARY} -c 2-10)
            FIND2=$(${LSBINARY} -ln ${f} | ${AWKBINARY} '{print $3$4}')
            LogText "结果：文件权限为 ${FIND}，所有者 UID/GID 为 ${FIND2}"
            case "${FIND}" in
                r[w-]-[r-][w-]---- )
                    LogText "结果：文件 ${f} 权限正常"
                    if [ "${FIND2}" = "00" ]; then
                        LogText "结果：文件 ${f} 所有者正常"
                        Display --indent 4 --text "- 权限：${f}" --result "${STATUS_OK}" --color GREEN
                    else
                        LogText "结果：文件 ${f} 的所有者可能不安全"
                        Display --indent 4 --text "- 权限：${f}" --result "${STATUS_WARNING}" --color RED
                    fi
                    ;;
                * )
                    LogText "结果：文件 ${f} 的权限可能不安全"
                    if [ "${FIND2}" = "00" ]; then
                        LogText "结果：文件 ${f} 所有者正常"
                    else
                        LogText "结果：文件 ${f} 的所有者可能不安全"
                    fi
                    Display --indent 4 --text "- 权限：${f}" --result "${STATUS_WARNING}" --color RED
                    ;;
            esac
        done
    fi
#
#################################################################################
#
    # Test        : AUTH-9254
    # Description : Solaris test to check passwordless accounts
    Register --test-no AUTH-9254 --os Solaris --weight L --network NO --root-only YES --category security --description "检查 Solaris 无密码账户"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(logins -p | ${AWKBINARY} '{ print $1 }')
        if [ -z "${FIND}" ]; then
            LogText "结果：未发现无密码账户"
            Display --indent 2 --text "- Solaris 无密码账户" --result "${STATUS_OK}" --color GREEN
        else
            for I in ${FIND}; do
                ReportWarning "${TEST_NO}" "发现无密码账户（${I}）"
            done
            Display --indent 2 --text "- Solaris 无密码账户" --result "${STATUS_WARNING}" --color RED
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9262
    # Description : Search for PAM password strength testing libraries
    Register --test-no AUTH-9262 --weight L --network NO --category security --description "检查 PAM 密码强度检测工具"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        FOUND_CRACKLIB=0
        FOUND_PASSWDQC=0
        FOUND_PWQUALITY=0

        # Cracklib
        LogText "搜索 PAM 密码检测模块（cracklib、passwdqc、pwquality）"
        for I in ${PAM_FILE_LOCATIONS}; do

            if [ -f ${I}/pam_cracklib.so ]; then
                FOUND_CRACKLIB=1
                FOUND=1
                LogText "结果：在 ${I} 中发现 pam_cracklib.so（PAM cracklib 模块）"
            fi

            if [ -f ${I}/pam_passwdqc.so ]; then
                FOUND_PASSWDQC=1
                FOUND=1
                LogText "结果：在 ${I} 中发现 pam_passwdqc.so（PAM 密码质量控制模块）"
            fi

            if [ -f ${I}/pam_pwquality.so ]; then
                FOUND_PWQUALITY=1
                FOUND=1
                LogText "结果：在 ${I} 中发现 pam_pwquality.so（PAM 密码质量控制模块）"
            fi
        done

        # Cracklib
        if [ ${FOUND_CRACKLIB} -eq 1 ]; then
            LogText "结果：发现 pam_cracklib.so"
            Report "pam_cracklib=1"
        else
            LogText "结果：未发现 pam_cracklib.so（PAM cracklib 模块）"
        fi

        # Password quality control
        if [ ${FOUND_PASSWDQC} -eq 1 ]; then
            LogText "结果：发现 pam_passwdqc.so"
            Report "pam_passwdqc=1"
        else
            LogText "结果：未发现 pam_passwdqc.so（PAM 密码质量控制模块）"
        fi

        # pwquality module
        if [ ${FOUND_PWQUALITY} -eq 1 ]; then
            LogText "结果：发现 pam_pwquality.so"
            Report "pam_pwquality=1"
        else
            LogText "结果：未发现 pam_pwquality.so（PAM 密码质量控制模块）"
        fi

        if [ ${FOUND} -eq 0 ]; then
            Display --indent 2 --text "- PAM 密码强度工具" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "结果：未发现用于密码强度检测的 PAM 模块"
            ReportSuggestion "${TEST_NO}" "安装用于密码强度检测的 PAM 模块，例如 pam_cracklib、pam_passwdqc 或 libpam-passwdqc"
            AddHP 0 3
        else
            Display --indent 2 --text "- PAM 密码强度工具" --result "${STATUS_OK}" --color GREEN
            LogText "结果：至少发现一个用于密码强度检测的 PAM 模块"
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9264
    # Description : Scan /etc/pam.conf file
    Register --test-no AUTH-9264 --weight L --network NO --category security --description "检查 pam.conf 是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 /etc/pam.conf 文件"
        if [ -f ${ROOTDIR}etc/pam.conf ]; then
            LogText "结果：文件 ${ROOTDIR}etc/pam.conf 存在"
            Display --indent 2 --text "- PAM 配置文件（pam.conf）" --result "${STATUS_FOUND}" --color GREEN
            LogText "检查：搜索 PAM 配置文件"
            FIND=$(${GREPBINARY} -E -v "^#" ${ROOTDIR}etc/pam.conf | ${GREPBINARY} -E -v "^$" | ${SEDBINARY} 's/[[:space:]]/ /g' | ${SEDBINARY} 's/  / /g' | ${SEDBINARY} 's/ /:space:/g')
            if [ -z "${FIND}" ]; then
                LogText "结果：文件未定义配置选项（为空，或仅包含注释和空行）"
            else
                LogText "结果：发现一行或多行配置"
                for LINE in ${FIND}; do
                    LINE=$(echo ${LINE} | ${SEDBINARY} 's/:space:/ /g')
                    LogText "发现配置行：${LINE}"
                done
            fi
        else
            LogText "结果：未找到 /etc/pam.conf 文件"
            Display --indent 2 --text "- PAM 配置文件（pam.conf）" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9266
    # Description : Searching available PAM configurations (/etc/pam.d)
    Register --test-no AUTH-9266 --weight L --network NO --category security --description "检查 pam.d 文件是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查目录 ${ROOTDIR}etc/pam.d"
        if [ -d ${ROOTDIR}etc/pam.d ]; then
            LogText "结果：目录 /etc/pam.d 存在"
            Display --indent 2 --text "- PAM 配置文件（pam.d）" --result "${STATUS_FOUND}" --color GREEN
            LogText "检查：搜索 PAM 配置文件"
            FIND=$(${FINDBINARY} -L ${ROOTDIR}etc/pam.d \! -name "*.pam-old" -type f -print | sort)
            for FILE in ${FIND}; do
                LogText "发现文件：${FILE}"
            done
        else
            LogText "结果：未找到目录 /etc/pam.d"
            Display --indent 2 --text "- PAM 配置文件（pam.d）" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9268
    # Description : Searching available PAM files
    # Notes       : PAM is used on AIX, FreeBSD, Linux, HPUX, NetBSD, Solaris
    OS_USES_PAM="AIX DragonFly FreeBSD Linux HPUX NetBSD Solaris"
    Register --test-no AUTH-9268 --os "${OS_USES_PAM}" --weight L --network NO --category security --description "检查 pam.d 文件是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查：搜索 PAM 模块"
        for DIR in ${PAM_FILE_LOCATIONS}; do
            LogText "检查：检查 ${DIR}"
            if [ -d ${DIR} -a ! -L ${DIR} ]; then
                LogText "结果：目录 ${DIR} 存在"
                # Search in the specified directory
                if [ "${OS}" = "AIX" -o "${OS}" = "Solaris" ]; then
                    # AIX/Solaris does not support -maxdepth
                    FIND=$(find ${DIR} -type f -name "pam_*.so" -print | sort)
                else
                    FIND=$(find ${DIR} -maxdepth 1 -type f -name "pam_*.so" -print | sort)
                fi
                if [ -n "${FIND}" ]; then FOUND=1; fi
                for FILE in ${FIND}; do
                    LogText "发现文件：${FILE}"
                    Report "pam_module[]=${FILE}"
                done
            else
                LogText "结果：目录 ${DIR} 不存在，或是指向其他目录的符号链接"
            fi
        done
        # Check if we found at least one module
        if [ ${FOUND} -eq 0 ]; then
            Display --indent 2 --text "- PAM 模块" --result "${STATUS_NOT_FOUND}" --color WHITE
            LogText "结果：未发现 PAM 模块"
        else
            Display --indent 2 --text "- PAM 模块" --result "${STATUS_FOUND}" --color GREEN
        fi
        unset DIR FILE FIND
    fi
#
#################################################################################
#
    # Test        : AUTH-9278
    # Description : Search LDAP support in PAM files
    Register --test-no AUTH-9278 --weight L --network NO --category security --description "检查 PAM 文件中的 LDAP 支持"
    if [ ${SKIPTEST} -eq 0 ]; then
        AUTH_FILES="${ROOTDIR}etc/pam.d/common-auth ${ROOTDIR}etc/pam.d/system-auth"
        for FILE in ${AUTH_FILES}; do
            LogText "检查：确认 ${FILE} 是否存在"
            if [ -f ${FILE} ]; then
                LogText "结果：文件 ${FILE} 存在"
                LogText "检查：确认 LDAP 模块是否存在"
                FIND=$(${GREPBINARY} "^auth.*ldap" ${FILE})
                if [ -n "${FIND}" ]; then
                    LogText "结果：LDAP 模块存在"
                    LogText "输出：${FIND}"
                    LDAP_AUTH_ENABLED=1
                    LDAP_PAM_ENABLED=1
                else
                    LogText "结果：未找到 LDAP 模块"
                fi
            else
                LogText "结果：未找到文件 ${FILE}，跳过检查"
            fi
        done

        if [ ${LDAP_PAM_ENABLED} -eq 1 ]; then
            Display --indent 2 --text "- PAM 中的 LDAP 模块" --result "${STATUS_FOUND}" --color GREEN
        else
            Display --indent 2 --text "- PAM 中的 LDAP 模块" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9282, AUTH-9283, and AUTH-9284
    # Note        : Every Linux based operating system seem to have different passwd
    #               options, so we have to check the version first.
    if [ "${OS}" = "Linux" ]; then
        if [ "${OS_REDHAT_OR_CLONE}" -eq 0 ]; then
            case ${LINUX_VERSION} in
                "SuSE")
                    PREQS_MET="YES"
                    FIND_P=$(passwd -a -S 2> /dev/null | ${AWKBINARY} '{ if ($2=="P" && $5=="99999") print $1 }')
                    FIND2=$(passwd -a -S 2> /dev/null | ${AWKBINARY} '{ if ($2=="NP") print $1 }')
                    FIND3=$(passwd -a -S 2> /dev/null | ${AWKBINARY} '{ if ($2=="L") print $1 }' | sort | uniq)
                    ;;
                *)
                    PREQS_MET="YES"
                    FIND_P=$(passwd --all --status 2> /dev/null | ${AWKBINARY} '{ if ($2=="P" && $5=="99999") print $1 }')
                    FIND2=$(passwd --all --status 2> /dev/null | ${AWKBINARY} '{ if ($2=="NP") print $1 }')
                    FIND3=$(passwd --all --status 2> /dev/null | ${AWKBINARY} '{ if ($2=="L") print $1 }' | sort | uniq)
                    ;;
            esac
        elif [ "${OS_REDHAT_OR_CLONE}" -eq 1 ]; then
            PREQS_MET="YES"
            FIND_P=$(for I in $(${AWKBINARY} -F: '{print $1}' "${ROOTDIR}etc/passwd") ; do passwd -S "$I" | ${AWKBINARY} '{ if ($2=="PS" && $5=="99999") print $1 }' ; done)
            FIND2=$(for I in $(${AWKBINARY} -F: '{print $1}' "${ROOTDIR}etc/passwd") ; do passwd -S "$I" | ${AWKBINARY} '{ if ($2=="NP") print $1 }' ; done)
            FIND3=$(for I in $(${AWKBINARY} -F: '{print $1}' "${ROOTDIR}etc/passwd") ; do passwd -S "$I" | ${AWKBINARY} '{ if ($2=="L" || $2=="LK") print $1 }' | sort | uniq ; done)
        else
            LogText "结果：此 Linux 版本不执行该检查"
            ReportManual "AUTH-9282:01"
            PREQS_MET="NO"
            FIND_P=""
            FIND2=""
            FIND3=""
        fi
    else
        PREQS_MET="NO"
    fi

    # Test        : AUTH-9282
    # Description : Search password protected accounts without expire (Linux)
    Register --test-no AUTH-9282 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查没有过期日期的密码保护账户"
    if [ "${SKIPTEST}" -eq 0 ]; then
        LogText "检查：检查 Linux 版本和密码过期日期状态"
        if [ -z "${FIND_P}" ]; then
            LogText "结果：所有账户似乎都设置了过期日期"
            Display --indent 2 --text "- 未设置过期日期的账户" --result "${STATUS_OK}" --color GREEN
        else
            LogText "结果：发现一个或多个未设置过期日期的账户"
            for I in ${FIND_P}; do
                LogText "未设置过期日期的账户：${I}"
            done
            Display --indent 2 --text "- 未设置过期日期的账户" --result "${STATUS_SUGGESTION}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "尽可能为所有密码保护账户设置过期日期"
        fi
    fi

    # Test        : AUTH-9283
    # Description : Search passwordless accounts
    # Notes       : requires FIND2 variable
    Register --test-no AUTH-9283 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查无密码账户"
    if [ "${SKIPTEST}" -eq 0 ]; then
        LogText "检查：检查无密码账户"
        if [ -z "${FIND2}" ]; then
            LogText "结果：所有账户似乎都设置了密码"
            Display --indent 2 --text "- 无密码账户" --result "${STATUS_OK}" --color GREEN
        else
            LogText "结果：发现一个或多个无密码账户"
            for I in ${FIND2}; do
                LogText "无密码账户：${I}"
                Report "account_without_password[]=${I}"
            done
            Display --indent 2 --text "- 无密码账户" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "发现无密码账户"
        fi
    fi

    # Test        : AUTH-9284
    # Description : 检查 /etc/passwd 中被锁定的用户账户
    # Notes       : requires FIND3 variable
    Register --test-no AUTH-9284 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 /etc/passwd 中被锁定的用户账户"
    if [ "${SKIPTEST}" -eq 0 ]; then
        LogText "检查：检查被锁定的账户"
        NON_SYSTEM_ACCOUNTS=$(${AWKBINARY} -F : '$3 > 999 && $3 != 65534 {print $1}' ${ROOTDIR}etc/passwd | ${SORTBINARY} | ${UNIQBINARY})
        LOCKED_NON_SYSTEM_ACCOUNTS=0
        for account in ${FIND3}; do
            if echo "${NON_SYSTEM_ACCOUNTS}" | ${GREPBINARY} -w "${account}" > /dev/null ; then
                LOCKED_NON_SYSTEM_ACCOUNTS=$((LOCKED_NON_SYSTEM_ACCOUNTS + 1))
            fi
        done
        if [ ${LOCKED_NON_SYSTEM_ACCOUNTS} -eq 0 ]; then
            LogText "结果：所有账户似乎均未锁定"
            Display --indent 2 --text "- 被锁定的账户" --result "${STATUS_OK}" --color GREEN
        else
            LogText "结果：发现一个或多个被锁定的账户"
            for account in ${FIND3}; do
                if echo "${NON_SYSTEM_ACCOUNTS}" | ${GREPBINARY} -w "${account}" > /dev/null ; then
                    LogText "被锁定的账户：${account}"
                    Report "locked_account[]=${account}"
                fi
            done
            Display --indent 2 --text "- 被锁定的账户" --result "${STATUS_FOUND}" --color RED
            ReportSuggestion "${TEST_NO}" "检查被锁定的账户，并考虑删除不再需要的账户"
        fi
        unset account LOCKED_NON_SYSTEM_ACCOUNTS NON_SYSTEM_ACCOUNTS
    fi

    unset FIND1 FIND2 FIND3
#
#################################################################################
#
    # Test        : AUTH-9286
    # Description : Check user password aging
    # Notes       : MIN = minimum age, avoid rotation of passwords too quickly
    #             : MAX = maximum age, ensure regular change of passwords
    PREQS_MET="NO"
    if [ -f ${ROOTDIR}etc/login.defs ]; then
        PREQS_MET="YES"
        # Future TODO: check if PAM overrule these settings
    fi
    Register --test-no AUTH-9286 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查用户密码有效期"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：${ROOTDIR}etc/login.defs 中的 PASS_MIN_DAYS 选项"
        FIND=$(${GREPBINARY} "^PASS_MIN_DAYS" ${ROOTDIR}etc/login.defs | ${AWKBINARY} '{ if ($1=="PASS_MIN_DAYS") { print $2 } }')
        if [ -z "${FIND}" -o "${FIND}" = "0" ]; then
            LogText "结果：未配置密码最短使用期限"
            Display --indent 2 --text "- 检查用户密码有效期 (minimum)" --result "${STATUS_DISABLED}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "在 /etc/login.defs 中配置密码最短使用期限"
            AddHP 0 1
        else
            LogText "结果：密码至少需要使用 ${FIND} 天"
            PASSWORD_MINIMUM_DAYS=${FIND}
            Display --indent 2 --text "- 用户密码有效期（最小值）" --result CONFIGURED --color GREEN
            AddHP 3 3
        fi

        LogText "检查：${ROOTDIR}etc/login.defs 中的 PASS_MAX_DAYS 选项 "
        FIND=$(${GREPBINARY} "^PASS_MAX_DAYS" ${ROOTDIR}etc/login.defs | ${AWKBINARY} '{ if ($1=="PASS_MAX_DAYS") { print $2 } }')
        if [ -z "${FIND}" -o "${FIND}" = "99999" ]; then
            LogText "结果：未配置密码有效期限制"
            Display --indent 2 --text "- 用户密码有效期（最大值）" --result "${STATUS_DISABLED}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "在 /etc/login.defs 中配置密码最长使用期限"
            AddHP 0 1
        else
            LogText "结果：密码最长使用期限为 ${FIND} 天"
            PASSWORD_MAXIMUM_DAYS=${FIND}
            Display --indent 2 --text "- 用户密码有效期（最大值）" --result CONFIGURED --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9288
    # Description : Determine which accounts have an expired password
    # Notes       : This test might not work (yet) on all platforms
    if [ -f ${ROOTDIR}etc/shadow ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9288 --preqs-met ${PREQS_MET} --weight L --network NO --root-only YES --category security --description "检查已过期密码"
    if [ ${SKIPTEST} -eq 0 ]; then
        if FileIsReadable ${ROOTDIR}etc/shadow; then

            if [ "${OS}" = "Solaris" ]; then
                NOW=$(nawk 'BEGIN{print srand()}')
            else
                NOW=$(date "+%s")
            fi

            DAYS_SINCE_EPOCH=$((NOW / 86400))
            LogText "数据：自 Unix 纪元以来的天数为 ${DAYS_SINCE_EPOCH}"
            LogText "检查：收集密码已过期的账户（最后修改日期加最长有效期）"
            # Skip fields with a !, *, or x, or !* (field $3 is last changed, $5 is maximum changed)
            FIND=$(${GREPBINARY} -E -v ":[\!\*x]([\*\!])?:" /etc/shadow | ${AWKBINARY} -v today=${DAYS_SINCE_EPOCH} -F: '{ if (($5!="") && (today>$3+$5)) { print $1 }}')
            if [ -n "${FIND}" ]; then
                for ACCOUNT in ${FIND}; do
                    LogText "结果：用户 ${ACCOUNT} 的密码已过期"
                    Report "account_password_expired[]=${ACCOUNT}"
                done
                AddHP 0 10
                Display --indent 2 --text "- 检查已过期密码" --result "${STATUS_FOUND}" --color RED
                ReportSuggestion "${TEST_NO}" "删除不再使用的账户"
            else
                LogText "结果：良好，未发现已过期密码"
                Display --indent 2 --text "- 检查已过期密码" --result "${STATUS_OK}" --color GREEN
                AddHP 10 10
            fi
        else
            Display --indent 2 --text "- 检查已过期密码" --result "${STATUS_SKIPPED}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9304
    # Description : Check if single user mode login is properly configured in Solaris
    # Notes       : sulogin should be called from svm script (Solaris <10) in /etc/rcS.d
    Register --test-no AUTH-9304 --os Solaris --weight L --network NO --category security --description "检查单用户模式登录配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if file exists (Solaris 10 does not have this file by default)
        if [ -f ${ROOTDIR}etc/default/sulogin ]; then
            LogText "结果：文件 ${ROOTDIR}etc/default/sulogin 存在"
            LogText "检查：确认是否存在 PASSREQ=NO"
            FIND=$(${GREPBINARY} "^PASSREQ=NO" ${ROOTDIR}etc/default/sulogin)
            if [ -z "${FIND}" ]; then
                LogText "结果：该选项不存在，或已配置为单用户模式登录时要求密码"
                Display --indent 2 --text "- 检查 Solaris /etc/default/sulogin 文件" --result "${STATUS_OK}" --color GREEN
                AddHP 1 1
            else
                LogText "结果：该选项存在，单用户模式登录无需密码"
                Display --indent 2 --text "- 检查 Solaris /etc/default/sulogin 文件" --result "${STATUS_WARNING}" --color RED
                ReportWarning "${TEST_NO}" "单用户模式登录无需密码"
                AddHP 0 1
            fi
        else
            LogText "结果：文件 /etc/default/sulogin 不存在"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9306
    # Description : Check if authentication is needed to boot the system
    # Notes       : :d_boot_authenticate: is a good option for production machines to
    #               avoid unauthorized booting of systems. Option :d_boot_authentication@:
    #               disabled a required login.
    Register --test-no AUTH-9306 --os HP-UX --weight L --network NO --category security --description "检查单用户启动身份验证"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if file exists
        LogText "检查：搜索 /tcb/files/auth/system/default"
        if [ -f ${ROOTDIR}tcb/files/auth/system/default ]; then
            LogText "结果：文件 ${ROOTDIR}tcb/files/auth/system/default 存在"
            LogText "检查：确认是否存在 :d_boot_authenticate@:"
            FIND=$(${GREPBINARY} "^:d_boot_authenticate@" /tcb/files/auth/system/default)
            if [ -z "${FIND}" ]; then
                LogText "结果：未设置该选项，启动时需要密码"
                Display --indent 2 --text "- 检查 HP-UX 启动身份验证" --result "${STATUS_OK}" --color GREEN
                AddHP 1 1
            else
                LogText "结果：该选项存在，单用户模式登录无需密码"
                Display --indent 2 --text "- 检查 HP-UX 启动身份验证" --result "${STATUS_SUGGESTION}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "为系统启动设置密码"
                AddHP 0 1
            fi
        else
            LogText "结果：文件 ${ROOTDIR}tcb/files/auth/system/default 不存在"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9308
    # Description : Check single user mode login for Linux
    Register --test-no AUTH-9308 --os Linux --weight L --network NO --category security --description "检查单用户模式登录配置"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        TEST_PERFORMED=0

        if [ ${HAS_SYSTEMD} -eq 0 ]; then
            # Check inittab
            LogText "检查：搜索 ${ROOTDIR}etc/inittab"
            if [ -f ${ROOTDIR}etc/inittab ]; then
                TEST_PERFORMED=1
                LogText "结果：文件 ${ROOTDIR}etc/inittab 存在"
                LogText "检查：确认单用户模式是否使用 sulogin"
                FIND=$(${GREPBINARY} -E "^[a-zA-Z0-9~]+:S:(respawn|wait):/sbin/sulogin" /etc/inittab)
                FIND2=$(${GREPBINARY} -E "^su:S:(respawn|wait):/sbin/sulogin" /etc/inittab)
                if [ -n "${FIND}" -o -n "${FIND2}" ]; then
                    FOUND=1
                    LogText "结果：发现 sulogin，单用户模式受到保护"
                fi
            else
                LogText "结果：文件 ${ROOTDIR}etc/inittab 不存在"
            fi

            # Check init
            LogText "检查：搜索 ${ROOTDIR}etc/sysconfig/init"
            if [ -f ${ROOTDIR}etc/sysconfig/init ]; then
                TEST_PERFORMED=1
                LogText "结果：文件 ${ROOTDIR}etc/sysconfig/init 存在"
                LogText "检查：确认单用户模式是否使用 sulogin"
                FIND=$(${GREPBINARY} "^SINGLE=/sbin/sulogin" ${ROOTDIR}etc/sysconfig/init)
                if [ -n "${FIND}" ]; then
                    FOUND=1
                    LogText "结果：发现 sulogin，单用户模式受到保护"
                fi
            else
                LogText "结果：文件 ${ROOTDIR}etc/sysconfig/init 不存在"
            fi
        fi

        # Systemd support
        SYSTEMD_DIRECTORY="/lib/systemd/system"
        if [ -d ${SYSTEMD_DIRECTORY} ]; then
            FILES="console-shell.service emergency.service rescue.service"
            LogText "检查：开始检查多个 systemd 目标"
            for I in ${FILES}; do
                FILE="${SYSTEMD_DIRECTORY}/${I}"
                LogText "检查：确认目标 ${I} 是否可用（${FILE}）"
                if [ -f ${FILE} ]; then
                    # Mark test as performed only when at least 1 target exists (e.g. Ubuntu 14.04 has limited systemd support)
                    TEST_PERFORMED=1
                    LogText "结果：发现目标 ${I}"
                    FIND=$(${GREPBINARY} -E "^ExecStart=" ${FILE} | ${GREPBINARY} "sulogin")
                    if [ "${FIND}" = "" ]; then
                        LogText "结果：未发现 sulogin 配置，可能存在未经身份验证进入单用户模式的风险"
                    else
                        LogText "结果：发现 sulogin，可有效保护单用户模式"
                        FOUND=1
                    fi
                else
                    LogText "结果：未找到目标 ${I}"
                fi
            done
        fi

        if [ ${TEST_PERFORMED} -eq 1 ]; then
            if [ ${FOUND} -eq 0 ]; then
                LogText "结果：未设置该选项，单用户模式启动无需密码"
                Display --indent 2 --text "- 检查 Linux 单用户模式身份验证" --result "${STATUS_WARNING}" --color RED
                ReportWarning "${TEST_NO}" "单用户模式未设置密码"
                ReportSuggestion "${TEST_NO}" "为单用户模式设置密码，以降低物理访问攻击面"
                AddHP 0 2
            else
                LogText "结果：已设置该选项，单用户模式启动需要密码"
                Display --indent 2 --text "- 检查 Linux 单用户模式身份验证" --result "${STATUS_OK}" --color GREEN
                AddHP 2 2
            fi
        else
            LogText "结果：未执行任何检查"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9328
    # Description : Check default umask in common files
    # Notes:        This test should be moved later to shells section
    # /etc/login.defs
    # pam_umask
    Register --test-no AUTH-9328 --weight L --network NO --category security --description "默认 umask 值"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "- 确定默认 umask"
        GOOD_UMASK=0
        WEAK_UMASK=0

        # /etc/profile.d
        LogText "检查：检查 ${ROOTDIR}etc/profile.d 目录"
        if [ -d ${ROOTDIR}etc/profile.d ]; then
            FOUND=0
            FIND=$(ls ${ROOTDIR}etc/profile.d/* 2> /dev/null)
            if [ -n "${FIND}" ]; then
                LogText "结果：发现 /etc/profile.d，且其中包含一个或多个文件"
                for FILE in ${FIND}; do
                    HAS_MASK=$(${GREPBINARY} umask ${FILE} 2> /dev/null | ${SEDBINARY} 's/^[ \t]*//' | ${GREPBINARY} -v "^#" | ${AWKBINARY} '{ print $2 }')
                    for MASK in ${HAS_MASK}; do
                        if [ "${MASK}" = "077" -o "${MASK}" = "027" -o "${MASK}" = "0077" -o "${MASK}" = "0027" ]; then
                            LogText "结果：文件 ${FILE} 设置了较严格的 umask '${MASK}'"
                            GOOD_UMASK=1
                        else
                            LogText "结果：文件 ${FILE} 设置了较宽松的 umask '${MASK}'"
                            WEAK_UMASK=1
                        fi
                    done
                done
            else
                LogText "结果：发现 /etc/profile.d，但其中没有文件"
            fi
        else
            LogText "结果：未找到 /etc/profile.d"
        fi

        # Test /etc/profile (only if we didn't find a good umask in profile.d)
        LogText "检查：检查 /etc/profile"
        if [ -f /etc/profile -a ${GOOD_UMASK} -eq 0 ]; then
            LogText "结果：文件 /etc/profile 存在"
            LogText "检查：检查 /etc/profile 中的 umask 值"
            FIND=$(${GREPBINARY} "umask" /etc/profile | ${SEDBINARY} 's/^[ \t]*//' | ${GREPBINARY} -v "^#" | ${AWKBINARY} '{ print $2 }')
            FIND2=$(${GREPBINARY} "umask" /etc/profile | ${SEDBINARY} 's/^[ \t]*//' | ${GREPBINARY} -v "^#" | ${AWKBINARY} '{ print $2 }' | wc -l)
            FOUND_UMASK=0
            if [ "${FIND2}" = "0" ]; then
                LogText "结果：未在 /etc/profile 中发现 umask"
            elif [ "${FIND2}" = "1" ]; then
                LogText "结果：发现带前导空格的 umask 配置"
                FOUND_UMASK=1
                if [ ! "${FIND}" = "077" -a ! "${FIND}" = "027" -a ! "${FIND}" = "0077" -a ! "${FIND}" = "0027" ]; then
                    LogText "结果：发现 umask ${FIND}，可以设置得更严格"
                    WEAK_UMASK=1
                else
                    LogText "结果：发现 umask ${FIND}，设置正常"
                    GOOD_UMASK=1
                fi
              # Found more than 1 umask value in profile
            else
                LogText "结果：/etc/profile 中配置了多个 umask 值"
                FOUND_UMASK=1
                for I in ${FIND}; do
                    if [ ! "${I}" = "077" -a ! "${I}" = "027" -a ! "${I}" = "0077" -a ! "${I}" = "0027" ]; then
                        LogText "结果：umask ${I} 可以设置得更严格"
                        WEAK_UMASK=1
                        AddHP 1 2
                    else
                        LogText "结果：发现 umask ${I}，设置正常"
                        AddHP 2 2
                    fi
                done
            fi

            if [ ${FOUND_UMASK} -eq 1 ]; then
                if [ ${WEAK_UMASK} -eq 0 ]; then
                    Display --indent 4 --text "- umask (/etc/profile and /etc/profile.d)" --result "${STATUS_OK}" --color GREEN
                    AddHP 2 2
                elif [ ${GOOD_UMASK} -eq 1 -a ${WEAK_UMASK} -eq 1 ]; then
                    Display --indent 4 --text "- umask (/etc/profile and /etc/profile.d)" --result "${STATUS_SUGGESTION}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "发现部分 umask 可以设置得更严格（例如 027）"
                    AddHP 1 2
                else
                    Display --indent 4 --text "- umask (/etc/profile and /etc/profile.d)" --result "${STATUS_SUGGESTION}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "可以将 /etc/profile 或 /etc/profile.d/custom.sh 中的默认 umask 设置得更严格（例如 027）"
                    AddHP 0 2
                fi
              else
                # Some operating systems don't have a default umask defined in /etc/profile (Debian)
                LogText "结果：未发现 umask，请确认这是否符合预期"
                Display --indent 4 --text "- umask (/etc/profile)" --result "${STATUS_NOT_FOUND}" --color YELLOW
            fi
        fi

        # /etc/passwd
        LogText "检查：检查 /etc/passwd 中的 umask 条目（pam_umask）"
        if [ -f /etc/passwd ]; then
            LogText "结果：文件 /etc/passwd 存在"
            LogText "检查：检查 /etc/passwd 中的 umask 值"
            FIND=$(${GREPBINARY} "umask=" /etc/passwd)
            if [ "${FIND}" = "" ]; then
                ReportManual "AUTH-9328:03"
            fi
          else
            LogText "结果：文件 /etc/passwd 不存在"
        fi

        # /etc/login.defs
        LogText "检查：检查 /etc/login.defs"
        if [ -f /etc/login.defs ]; then
            LogText "结果：文件 /etc/login.defs 存在"
            LogText "检查：检查 /etc/login.defs 中的 umask 值"
            FIND=$(${GREPBINARY} "^UMASK" /etc/login.defs | ${AWKBINARY} '{ print $2 }')
            if [ "${FIND}" = "" ]; then
                LogText "结果：未配置 umask 值，通常会使用默认值 022"
                Display --indent 4 --text "- umask (/etc/login.defs)" --result "${STATUS_SUGGESTION}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "未在 /etc/login.defs 中找到默认 umask；通常默认为 022，可以改为更严格的 027"
                AddHP 1 2
            elif [ "${FIND}" = "077" -o "${FIND}" = "027" -o "${FIND}" = "0077" -o "${FIND}" = "0027" ]; then
                LogText "结果：umask 为 ${FIND}，设置正常"
                Display --indent 4 --text "- umask (/etc/login.defs)" --result "${STATUS_OK}" --color GREEN
                AddHP 2 2
            else
                LogText "结果：发现 umask ${FIND}，可以进一步收紧"
                Display --indent 4 --text "- umask (/etc/login.defs)" --result "${STATUS_SUGGESTION}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "可以将 /etc/login.defs 中的默认 umask 设置得更严格，例如 027"
                AddHP 0 2
            fi
        else
            LogText "结果：文件 /etc/login.defs 不存在"
        fi

        # Red Hat /etc/init.d/functions
        LogText "检查：检查 /etc/init.d/functions"
        if [ -f /etc/init.d/functions ]; then
            LogText "结果：文件 /etc/init.d/functions 存在"
            LogText "检查：检查 /etc/init.d/functions 中的 umask 值"
            FIND=$(${GREPBINARY} "^umask" /etc/init.d/functions | ${AWKBINARY} '{ print $2 }')
            if [ "${FIND}" = "" ]; then
                LogText "结果：未配置 umask"
                Display --indent 4 --text "- umask (/etc/init.d/functions)" --result "${STATUS_NONE}" --color WHITE
            elif [ "${FIND}" = "077" -o "${FIND}" = "027" -o "${FIND}" = "0077" -o "${FIND}" = "0027" ]; then
                LogText "结果：umask 为 ${FIND}，设置正常"
                Display --indent 4 --text "- umask (/etc/init.d/functions)" --result "${STATUS_OK}" --color GREEN
                AddHP 2 2
            else
                LogText "结果：发现 umask ${FIND}，可以进一步收紧"
                Display --indent 4 --text "- umask (/etc/init.d/functions)" --result "${STATUS_SUGGESTION}" --color YELLOW
                AddHP 0 2
            fi
        else
            LogText "结果：文件 /etc/init.d/functions 不存在"
        fi

        # /etc/init.d/rc
        LogText "检查：检查 /etc/init.d/rc"
        if [ -f /etc/init.d/rc ]; then
            LogText "结果：文件 /etc/init.d/rc 存在"
            LogText "检查：检查 /etc/init.d/rc 中的 UMASK 值"
            FIND=$(${GREPBINARY} -i "^UMASK" /etc/init.d/rc | ${AWKBINARY} '{ print $2 }')
            if [ "${FIND}" = "" ]; then
                LogText "结果：未配置 UMASK 值，通常会使用默认值 022"
                Display --indent 4 --text "- 检查 umask（/etc/init.d/rc）" --result "${STATUS_SUGGESTION}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "未在 /etc/init.d/rc 中找到默认 umask；通常默认为 022，可以改为更严格的 027"
                AddHP 1 2
            elif [ "${FIND}" = "077" -o "${FIND}" = "027" -o "${FIND}" = "0077" -o "${FIND}" = "0027" ]; then
                LogText "结果：umask 为 ${FIND}，设置正常"
                Display --indent 4 --text "- umask (/etc/init.d/rc)" --result "${STATUS_OK}" --color GREEN
                AddHP 2 2
            else
                LogText "结果：发现 umask ${FIND}，可以进一步收紧"
                Display --indent 4 --text "- umask (/etc/init.d/rc)" --result "${STATUS_SUGGESTION}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "可以将 /etc/init.d/rc 中的默认 umask 设置得更严格，例如 027"
                AddHP 0 2
            fi
          else
            LogText "结果：文件 /etc/init.d/rc 不存在"
        fi

        # FreeBSD
        if [ -f /etc/login.conf ]; then
            FOUND=0
            WEAK_UMASK=0
            LogText "结果：文件 /etc/login.conf 存在"
            FIND=$(${GREPBINARY} "umask" /etc/login.conf | ${SEDBINARY} 's/#.*//' | ${SEDBINARY} -E 's/^[[:cntrl:]]//' | ${GREPBINARY} -v '^$' | ${AWKBINARY} -F: '{ print $2}' | ${AWKBINARY} -F= '{ if ($1=="umask") { print $2 }}')
            if [ ! "${FIND}" = "" ]; then
                for UMASK_VALUE in ${FIND}; do
                    case ${UMASK_VALUE} in
                        027|0027|077|0077)
                            LogText "结果：发现 umask 值 ${UMASK_VALUE}，设置正常"
                            AddHP 2 2
                            FOUND=1
                        ;;
                        *)
                            AddHP 0 2
                            FOUND=1
                            WEAK_UMASK=1
                            LogText "结果：发现 umask 值 ${UMASK_VALUE}，可以设置得更严格"
                        ;;
                    esac
                done
            fi
            if [ ${FOUND} -eq 1 ]; then
                if [ ${WEAK_UMASK} -eq 0 ]; then
                    Display --indent 4 --text "- umask (/etc/login.conf)" --result "${STATUS_OK}" --color GREEN
                else
                    Display --indent 4 --text "- umask (/etc/login.conf)" --result "${STATUS_WEAK}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "可以将 /etc/login.conf 中的 umask 设置得更严格，例如 027"
                fi
            else
                LogText "结果：未在 /etc/login.conf 中发现 umask 配置，这不符合预期"
                Display --indent 4 --text "- umask (/etc/login.conf)" --result "${STATUS_NONE}" --color YELLOW
            fi
        fi

        # /etc/init.d/rcS
        LogText "检查：检查 /etc/init.d/rcS"
        if [ -f /etc/init.d/rcS ]; then
            LogText "结果：文件 /etc/init.d/rcS 存在"
            LogText "检查：确认脚本是否会执行另一个脚本。"
            FIND=$(${GREPBINARY} -i "^exec " /etc/init.d/rcS | ${AWKBINARY} '{ print $2 }')
            if [ "${FIND}" = "" ]; then
                FIND2=$(${GREPBINARY} -i "^UMASK" /etc/init.d/rcS | ${AWKBINARY} '{ print $2 }')
                if [ "${FIND2}" = "" ]; then
                    LogText "结果：未配置 UMASK 值，通常会使用默认值 022"
                    Display --indent 4 --text "- 检查 umask（/etc/init.d/rcS）" --result "${STATUS_SUGGESTION}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "未在 /etc/init.d/rcS 中找到默认 umask；通常默认为 022，可以改为更严格的 027"
                    AddHP 1 2
                elif [ "${FIND2}" = "077" -o "${FIND2}" = "027" ]; then
                    LogText "结果：umask 为 ${FIND2}，设置正常"
                    Display --indent 4 --text "- umask (/etc/init.d/rcS)" --result "${STATUS_OK}" --color GREEN
                    AddHP 2 2
                else
                    LogText "结果：发现 umask ${FIND2}，可以进一步收紧"
                    Display --indent 4 --text "- umask (/etc/init.d/rcS)" --result "${STATUS_SUGGESTION}" --color YELLOW
                    ReportSuggestion "${TEST_NO}" "可以将 /etc/init.d/rcS 中的默认 umask 设置得更严格，例如 027"
                    AddHP 0 2
                fi
            else
                # Improve check
                LogText "结果：文件中存在 exec 行，此脚本无需单独设置 umask"
                LogText "输出：${FIND}"
            fi
          else
            LogText "结果：文件 /etc/init.d/rcS 不存在"
        fi

    fi
#
#################################################################################
#
    # Test        : AUTH-9340
    # Description : Solaris 账户锁定
    Register --test-no AUTH-9340 --os Solaris --weight L --network NO --category security --description "Solaris 账户锁定"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        if [ -f ${ROOTDIR}etc/security/policy.conf ]; then
            LogText "结果：发现 ${ROOTDIR}etc/security/policy.conf"
            FIND=$(${GREPBINARY} "^LOCK_AFTER_RETRIES" /etc/security/policy.conf)
            if [ ! "${FIND}" = "" ]; then
                FOUND=1
                LogText "结果：已设置账户锁定选项"
                LogText "输出：${FIND}"
                AddHP 2 2
            else
                LogText "结果：未设置 LOCK_AFTER_RETRIES 选项"
                AddHP 1 2
            fi
        else
            LogText "结果：${ROOTDIR}etc/security/policy.conf 不存在"
        fi
        # If policy.conf does not exist, we most likely deal with a Solaris version below 10
        # and we proceed with checking the softer option RETRIES in /etc/default/login
        # which does not lock account, but discourages brute force password attacks.
        if [ ${FOUND} -eq 0 ]; then
            LogText "检查：检查 ${ROOTDIR}etc/default/login"
            if [ -f ${ROOTDIR}etc/default/login ]; then
                LogText "结果：文件 ${ROOTDIR}etc/default/login 存在"
                FIND=$(${GREPBINARY} "^RETRIES" ${ROOTDIR}etc/default/login)
                if [ -n "${FIND}" ]; then
                    FOUND=1
                    LogText "结果：已配置重试次数选项"
                    LogText "输出：${FIND}"
                    AddHP 2 2
                else
                    LogText "结果：未配置重试次数选项"
                    AddHP 1 2
                fi
            else
                LogText "结果：文件 ${ROOTDIR}etc/default/login 不存在"
            fi
        fi
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 检查账户锁定" --result "${STATUS_ENABLED}" --color GREEN
        else
            Display --indent 2 --text "- 检查账户锁定" --result "${STATUS_NOT_ENABLED}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9402
    # Description : 查询 LDAP 身份验证支持
    Register --test-no AUTH-9402 --weight L --network NO --category security --description "查询 LDAP 身份验证支持"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f ${ROOTDIR}etc/nsswitch.conf ]; then
            FIND=$(${GREPBINARY} -E "^passwd" ${ROOTDIR}etc/nsswitch.conf | ${GREPBINARY} "ldap")
            if [ "${FIND}" = "" ]; then
                LogText "结果：未启用 LDAP 身份验证"
                Display --indent 2 --text "- LDAP 身份验证支持" --result "${STATUS_NOT_ENABLED}" --color WHITE
            else
                LogText "结果：已启用 LDAP 身份验证"
                Display --indent 2 --text "- LDAP 身份验证支持" --result "${STATUS_ENABLED}" --color GREEN
                LDAP_AUTH_ENABLED=1
            fi
        else
            LogText "结果：未找到 /etc/nsswitch.conf"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9406
    # Description : Check LDAP servers in client configuration
    if [ ${LDAP_AUTH_ENABLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9406 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "查询客户端配置中的 LDAP 服务器"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 ldap.conf 选项"
        for FILE in ${LDAP_CONF_LOCATIONS}; do
            LogText "检查：检查 ${FILE}"
            if [ -f ${FILE} ]; then
                LogText "结果：文件 ${FILE} 存在, LDAP being used"
                LDAP_CLIENT_CONFIG_FILE="${FILE}"
                LogText "检查：检查文件 ${FILE} 中的 LDAP 服务器"
                FIND=$(${GREPBINARY} -E "^host " ${FILE} | ${AWKBINARY} '{ print $2 }')
                for SERVER in ${FIND}; do
                    Display --indent 6 --text "LDAP 服务器：${SERVER}"
                    LogText "结果：发现 LDAP 服务器 ${SERVER}"
                    Report "ldap_server[]=${SERVER}"
                done
            else
                LogText "结果：${FILE} 不存在"
            fi
        done
        unset FILE FIND SERVER
    fi
#
#################################################################################
#
    # Test        : AUTH-9408
    # Description : 记录失败的登录尝试
    Register --test-no AUTH-9408 --weight L --network NO --category security --description "记录失败的登录尝试"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -f "${ROOTDIR}etc/pam.conf" -o -d "${ROOTDIR}etc/pam.d" ]; then
            FOUND_PAM_TALLY2=0
            FOUND_TALLYLOG=0
            FOUND_PAM_FAILLOCK=0
            FOUND_FAILLOCKDIR=0
            if [ -d "${ROOTDIR}var/run/faillock" ]; then
                FOUND_FAILLOCKDIR=1
                LogText "结果：发现 ${ROOTDIR}var/run/faillock 目录"
            elif [ -s "${ROOTDIR}var/log/tallylog" ]; then
                FOUND_TALLYLOG=1
                LogText "结果：发现 ${ROOTDIR}var/log/tallylog，且文件大小大于 0"
            else
                LogText "结果：未找到 ${ROOTDIR}var/run/faillock 目录或 ${ROOTDIR}var/log/tallylog 文件，或者文件大小为 0"
            fi
            # Determine if pam_faillock is available
            for D in $(GetReportData --key "pam_module\\\[\\\]"); do
                if ContainsString "pam_faillock" "${D}"; then
                    LogText "结果：磁盘上发现 pam_faillock 模块"
                    FOUND_PAM_FAILLOCK=1
                fi
            done
            if [ ${FOUND_PAM_FAILLOCK} -eq 0 ]; then
                # Determine if pam_tally2 is available
                for D in $(GetReportData --key "pam_module\\\[\\\]"); do
                    if ContainsString "pam_tally2" "${D}"; then
                        LogText "结果：磁盘上发现 pam_tally2 模块"
                        FOUND_PAM_TALLY2=1
                    fi
                done
            fi
            if [ ${FOUND_PAM_FAILLOCK} -eq 1 -a ${FOUND_FAILLOCKDIR} -eq 1 ]; then
                LogText "结论：使用 pam_faillock 记录身份验证失败"
                AUTH_FAILED_LOGINS_LOGGED=1
                Report "auth_failed_logins_tooling[]=pam_faillock"
            elif [ ${FOUND_PAM_TALLY2} -eq 1 -a ${FOUND_TALLYLOG} -eq 1 ]; then
                LogText "结论：使用 pam_tally2 记录身份验证失败"
                AUTH_FAILED_LOGINS_LOGGED=1
                Report "auth_failed_logins_tooling[]=pam_tally2"
            else
                LogText "结论：pam_faillock 或 pam_tally2 似乎未配置为记录失败的登录尝试"
            fi

            unset FOUND_PAM_TALLY2 FOUND_TALLYLOG FOUND_PAM_FAILLOCK FOUND_FAILLOCKDIR
        fi
        # Also check /etc/logins.defs, although its usage decreased over the years
        if [ -f ${ROOTDIR}etc/login.defs ]; then
            LogText "检查：检查 ${ROOTDIR}etc/login.defs 中的 FAILLOG_ENAB 选项 "
            FIND=$(${GREPBINARY} "^FAILLOG_ENAB" ${ROOTDIR}etc/login.defs | ${AWKBINARY} '{ if ($1=="FAILLOG_ENAB") { print $2 } }')
            # Search for enabled status (yes), otherwise consider it to be disabled (e.g. empty, or other value)
            if [ "${FIND}" = "yes" ]; then
                AUTH_FAILED_LOGINS_LOGGED=1
                Report "auth_failed_logins_tooling[]=/etc/login.defs"
                LogText "结果：FAILLOG_ENAB 设置为 'yes'"
                LogText "结论：失败的登录尝试记录在 ${ROOTDIR}var/log/faillog"
                Display --indent 2 --text "- 记录失败的登录尝试" --result "${STATUS_ENABLED}" --color GREEN
            else
                LogText "结果：失败的登录尝试可能未被记录"
                Display --indent 2 --text "- 记录失败的登录尝试" --result "${STATUS_DISABLED}" --color YELLOW
            fi
        fi

        if [ ${AUTH_FAILED_LOGINS_LOGGED} -eq 1 ]; then
            AddHP 3 3
        else
            AddHP 0 1
            #ReportSuggestion "${TEST_NO}" "Configure failed login attempts to be logged using pam_tally2 or /etc/login.defs"
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9409
    # Description : Check for doas file
    DOAS_FILE=""
    Register --test-no AUTH-9409 --os OpenBSD --weight L --network NO --category security --description "检查 /etc/doas.conf 文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查：确认 /etc/doas.conf 是否存在"
        if [ -f /etc/doas.conf ]; then
        DOAS_FILE=/etc/doas.conf
            FOUND=1
            LogText "结果：发现 /etc/doas.conf 文件"
        else
            LogText "结果：未找到 /etc/doas.conf 文件"
        fi
        if [ ${FOUND} -eq 1 ]; then
            LogText "结果：发现 /etc/doas.conf 文件"
            Display --indent 2 --text "- doas 文件" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未找到 doas 文件"
            Display --indent 2 --text "- doas 文件" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : AUTH-9410
    # Description : Check for doas file permissions
    if [ -n "${DOAS_FILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no AUTH-9410 --os OpenBSD --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 /etc/doas.conf 文件权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 /etc/doas.conf 权限"
        FIND=$(ls -l ${DOAS_FILE} | ${CUTBINARY} -c 2-10)
        LogText "结果：/etc/doas.conf 文件权限为 ${FIND}"
        case "${FIND}" in
            r[w-]-[r-][w-]---- )
                LogText "结果：/etc/doas.conf 文件权限正确"
                Display --indent 4 --text "- 检查 doas 文件权限" --result "${STATUS_OK}" --color GREEN
                ;;
            * )
                LogText "结果：文件权限可能不安全"
                Display --indent 4 --text "- 检查 doas 文件权限" --result "${STATUS_WARNING}" --color RED
                ;;
        esac
    fi
#
#################################################################################
#

Report "auth_failed_logins_logged=${AUTH_FAILED_LOGINS_LOGGED}"
Report "ldap_auth_enabled=${LDAP_AUTH_ENABLED}"
Report "ldap_pam_enabled=${LDAP_PAM_ENABLED}"
if [ -n "${LDAP_CLIENT_CONFIG_FILE}" ]; then Report "ldap_config_file=${LDAP_CLIENT_CONFIG_FILE}"; fi
Report "password_min_days=${PASSWORD_MINIMUM_DAYS}"
Report "password_max_days=${PASSWORD_MAXIMUM_DAYS}"

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
