#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Name services
#
#################################################################################
#
    InsertSection "${SECTION_NAME_SERVICES}"
#
#################################################################################
#
    BIND_RUNNING=0
    BIND_CONFIG_LOCS="${ROOTDIR}etc ${ROOTDIR}etc/bind ${ROOTDIR}usr/local/etc ${ROOTDIR}usr/local/etc/namedb"
    BIND_CONFIG_LOCATION=""
    POWERDNS_RUNNING=0
    POWERDNS_CONFIG_LOCS="${ROOTDIR}etc/powerdns ${ROOTDIR}usr/local/etc"
    POWERDNS_AUTH_CONFIG_LOCATION=""
    POWERDNS_AUTH_MASTER=0
    POWERDNS_AUTH_SLAVE=0
    UNBOUND_CONFIG_OK=0
    YPBIND_RUNNING=0
#
#################################################################################
#
    # Test        : NAME-4016
    # Description : Check main domain (domain <domain name> in /etc/resolv.conf)
    Register --test-no NAME-4016 --weight L --network NO --category security --description "检查/etc/resolv.conf默认域"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 ${ROOTDIR}etc/resolv.conf 是否为默认域"
        if [ -f ${ROOTDIR}etc/resolv.conf ]; then
            LogText "结果：找到 ${ROOTDIR}etc/resolv.conf"
            FIND=$(${AWKBINARY} '/^domain/ { print $2 }' ${ROOTDIR}etc/resolv.conf)
            if [ -z "${FIND}" ]; then
                LogText "结果：未找到默认域"
                if IsVerbose; then Display --indent 2 --text "- 检查默认的DNS搜索域" --result "${STATUS_NONE}" --color WHITE; fi
            else
                LogText "结果：找到默认域"
                LogText "输出：${FIND}"
                Report "resolv_conf_domain=${FIND}"
                Display --indent 2 --text "- 检查默认的DNS搜索域" --result "${STATUS_FOUND}" --color GREEN
                RESOLV_DOMAINNAME="${FIND}"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4018
    # Description : Check search domains in /etc/resolv.conf
    # Notes       : Maximum of one search keyword is allowed in /etc/resolv.conf
    Register --test-no NAME-4018 --weight L --network NO --category security --description "检查 /etc/resolv.conf 搜索域"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "测试：检查 ${ROOTDIR}etc/resolv.conf 的搜索域"
        if [ -f ${ROOTDIR}etc/resolv.conf ]; then
            LogText "结果：找到 ${ROOTDIR}etc/resolv.conf"
            FIND=$(${AWKBINARY} '/^search/ { print $2 }' ${ROOTDIR}etc/resolv.conf)
            if IsEmpty "${FIND}"; then
                LogText "结果：未找到搜索域，正在使用默认域"
            else
                for ITEM in ${FIND}; do
                    LogText "找到搜索域：${ITEM}"
                    Report "resolv_conf_search_domain[]=${ITEM}"
                    COUNT=$((COUNT + 1))
                done
                # Warn if we have more than 6 search domains, which is maximum in most resolvers
                if [ ${COUNT} -gt 6 ]; then
                    LogText "结果：找到 ${COUNT} 搜索域"
                    Display --indent 2 --text "- 检查搜索域" --result "${STATUS_WARNING}" --color YELLOW
                    ReportWarning "${TEST_NO}" "发现超过 6 个搜索域，通常已超过多数解析器允许的最大数量"
                else
                    LogText "结果：找到 ${COUNT} 搜索域"
                    Display --indent 2 --text "- 检查搜索域" --result "${STATUS_FOUND}" --color GREEN
                fi
            fi
            # Check amount of search domains (max 1)
            FIND=$(${GREPBINARY} -c "^search" ${ROOTDIR}etc/resolv.conf)
            if [ ! "${FIND}" = "0" -a ! "${FIND}" = "1" ]; then
                LogText "结果：通过搜索语句找到 ${FIND} 行（预计少于 2 行）"
                Display --indent 4 --text "- 检查搜索域行" --result "配置错误" --color YELLOW
                ReportWarning "${TEST_NO}" "在 /etc/resolv.conf 中发现多条 search 配置，可能存在配置错误"
            else
                LogText "结果：通过搜索语句找到 ${FIND} 行（预计少于 2 行）"
            fi
        else
            LogText "结果：${ROOTDIR}etc/resolv.conf 不存在，跳过检查"
            Display --indent 2 --text "- 检查搜索域" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4020
    # Description : Check non default resolv.conf options
    Register --test-no NAME-4020 --weight L --network NO --category security --description "检查非默认选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 ${ROOTDIR}etc/resolv.conf 是否有非默认选项"
        if [ -f ${ROOTDIR}etc/resolv.conf ]; then
            LogText "结果：找到 ${ROOTDIR}etc/resolv.conf"
            FIND=$(${GREPBINARY} "^options" ${ROOTDIR}etc/resolv.conf | ${AWKBINARY} '{ print $2 }')
            if IsEmpty "${FIND}"; then
                LogText "结果：/etc/resolv.conf 中没有配置特定的其他选项"
                if IsVerbose; then Display --indent 2 --text "- 检查 /etc/resolv.conf 选项" --result "${STATUS_NONE}" --color WHITE; fi
            else
                for ITEM in ${FIND}; do
                    LogText "找到选项：${ITEM}"
                    Report "resolv_conf_option[]=${ITEM}"
                    # TODO add suggestions for the related options
                    # rotate --> add performance tune point
                    # timeout --> add performance tune point when smaller than 3 seconds
                done
                Display --indent 2 --text "- 检查 /etc/resolv.conf 选项" --result "${STATUS_FOUND}" --color GREEN
            fi
        else
            LogText "结果：未找到 /etc/resolv.conf，跳过检查"
            Display --indent 2 --text "- 检查 /etc/resolv.conf 选项" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4024
    # Description : Check Solaris uname -n output
    Register --test-no NAME-4024 --os Solaris --weight L --network NO --category security --description "Solaris uname -n 输出"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${UNAMEBINARY} -n)
        LogText "结果：'uname -n' 返回 ${FIND}"
        Display --indent 2 --text "- 检查 uname -n 输出" --result "${STATUS_DONE}" --color GREEN
    fi
#
#################################################################################
#
    # Test        : NAME-4026
    # Description : Check Solaris /etc/nodename
    # Notes       : If a system is standalone, /etc/nodename should contain a system name only, not FQDN
    Register --test-no NAME-4026 --os Solaris --weight L --network NO --category security --description "检查/etc/nodename"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查/etc/nodename"
        if [ -f /etc/nodename ]; then
            LogText "结果：文件 /etc/nodename 存在"
            FIND=$(cat /etc/nodename)
            LogText "输出：${FIND}"
            Display --indent 2 --text "- 检查/etc/nodename" --result "${STATUS_DONE}" --color GREEN
        else
            LogText "结果：找不到文件 /etc/nodename"
            Display --indent 2 --text "- 检查/etc/nodename" --result "未找到" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4028
    # Description : Check DNS domain name
    # To Do       : ${GREPBINARY} ^DOMAINNAME /etc/conf.d/domainname (remove "'s)
    Register --test-no NAME-4028 --weight L --network NO --category security --description "检查域名"
    if [ ${SKIPTEST} -eq 0 ]; then
        DOMAINNAME=""
        LogText "测试：检查 dnsdomainname 命令是否可用"
        if HasData "${DNSDOMAINNAMEBINARY}"; then
            FIND2=$(${DNSDOMAINNAMEBINARY} 2> /dev/null)
            if HasData "${FIND2}"; then
                LogText "结果：dnsdomainname 命令返回一个值"
                LogText "查到域名：${FIND2}"
                DOMAINNAME="${FIND2}"
            else
                LogText "结果：dnsdomainname 命令未返回任何值"
            fi
        else
            LogText "结果：未找到 dnsdomainname 程序，跳过该项检查"
        fi

        # If files and commands can't be found, use defined value from resolv.conf
        if [ -z "${DOMAINNAME}" ]; then
            if [ -n "${RESOLV_DOMAINNAME}" ]; then
                LogText "结果：使用来自 ${ROOTDIR}etc/resolv.conf 的域名"
                DOMAINNAME=${RESOLV_DOMAINNAME}
            else
                LogText "结果：使用 FQDN 主机名 (${FQDN}) 中的域名"
                DOMAINNAME=$(echo ${FQDN} | ${AWKBINARY} -F. '{print $2}')
            fi
        fi

        if [ -n "${DOMAINNAME}" ]; then
            LogText "结果：找到域名"
            Report "domainname=${DOMAINNAME}"
            Display --indent 2 --text "- 搜索DNS域名" --result "${STATUS_FOUND}" --color GREEN
            Display --indent 6 --text "域名：${DOMAINNAME}"
        else
            Display --indent 2 --text "- 搜索DNS域名" --result "${STATUS_UNKNOWN}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "检查 dns 域名的 DNS 配置"
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4032
    # Description : Check name service caching daemon (NSCD) status
    Register --test-no NAME-4032 --weight L --network NO --category security --description "检查 nscd 状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 nscd 状态"
        if IsRunning "nscd"; then
            NAME_CACHE_USED=1
            LogText "结果：nscd 正在运行"
            Display --indent 2 --text "- 检查 nscd 状态" --result "${STATUS_RUNNING}" --color GREEN
        else
            LogText "结果：nscd 未运行"
            if IsVerbose; then Display --indent 2 --text "- 检查 nscd 状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4034
    # Description : Check name service caching daemon (Unbound) status
    Register --test-no NAME-4034 --weight L --network NO --category security --description "检查Unbound状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查Unbound（unbound）状态"
        if IsRunning "unbound"; then
            UNBOUND_RUNNING=1
            NAME_CACHE_USED=1
            LogText "结果：Unbound 守护进程正在运行"
            Display --indent 2 --text "- 检查Unbound状态" --result "${STATUS_RUNNING}" --color GREEN
        else
            LogText "结果：Unbound 守护进程未运行"
            if IsVerbose; then Display --indent 2 --text "- 检查Unbound状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4036
    # Description : Checking Unbound configuration file
    if [ ${UNBOUND_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4036 --preqs-met ${PREQS_MET}  --weight L --network NO --category security --description "检查Unbound配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(which unbound-checkconf | grep -v "no [^ ]* in ")
        if [ ! "${FIND}" = "" ]; then
            LogText "测试：运行 unbound-checkconf"
            # Don't capture any output, just gather exit code (0 is fine, otherwise bad)
            FIND=$(unbound-checkconf > /dev/null 2>&1)
            if [ $? -eq 0 ]; then
                UNBOUND_CONFIG_OK=1
                LogText "结果：配置没问题"
                Display --indent 2 --text "- 检查配置文件" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果：Unbound 守护进程未运行"
                Display --indent 2 --text "- 检查配置文件" --result "不正常" --color YELLOW
                ReportWarning "${TEST_NO}" "发现Unbound配置文件问题（运行unbound-checkconf）"
            fi
        else
            LogText "结果：找不到 unbound-checkconf 工具，已跳过"
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4202
    # Description : Check if BIND is running
    Register --test-no NAME-4202 --weight L --network NO --category security --description "检查BIND状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查正在运行的 BIND 实例"
        if IsRunning "named"; then
            LogText "结果：找到BIND进程"
            Display --indent 2 --text "- 检查BIND状态" --result "${STATUS_FOUND}" --color GREEN
            BIND_RUNNING=1
        else
            LogText "结果：BIND 未运行"
            if IsVerbose; then Display --indent 2 --text "- 检查BIND状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4204
    # Description : Check configuration file of BIND
    if [ ${BIND_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4204 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "搜索BIND配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索BIND配置文件"
        for I in ${BIND_CONFIG_LOCS}; do
            if [ -f ${I}/named.conf ]; then
                BIND_CONFIG_LOCATION="${I}/named.conf"
                LogText "结果：找到配置文件（${BIND_CONFIG_LOCATION}）"
            fi
        done
        if [ -n "${BIND_CONFIG_LOCATION}" ]; then
            Display --indent 4 --text "- 检查BIND配置文件" --result "${STATUS_FOUND}" --color GREEN
        else
            Display --indent 4 --text "- 检查BIND配置文件" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4206
    # Description : Check BIND configuration file consistency
    if [ ${BIND_RUNNING} -eq 1 -a ! "${BIND_CONFIG_LOCATION}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4206 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查BIND配置一致性"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索named-checkconf二进制文件"
        if [ ! "${NAMEDCHECKCONFBINARY}" = "" ]; then
            LogText "结果：named-checkconf 已安装"
            FIND=$(${NAMEDCHECKCONFBINARY} ${BIND_CONFIG_LOCATION}; echo $?)
            if [ "${FIND}" = "0" ]; then
                LogText "结果：配置文件${BIND_CONFIG_LOCATION}似乎没问题"
                Display --indent 4 --text "- 检查BIND配置一致性" --result "${STATUS_OK}" --color GREEN
            else
                LogText "结果：在${BIND_CONFIG_LOCATION}中发现可能的错误"
                Display --indent 4 --text "- 检查BIND配置一致性" --result "${STATUS_WARNING}" --color RED
                ReportWarning "${TEST_NO}" "BIND 配置文件中发现错误"
            fi
        else
            LogText "结果：未找到 named-checkconf，跳过检查"
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4210
    # Description : Check if we can determine useful information from banner
    if [ ${BIND_RUNNING} -eq 1 -a ! "${BIND_CONFIG_LOCATION}" = "" -a ! "${DIGBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4210 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 DNS 横幅"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：尝试从横幅确定版本"
        FIND=$(${DIGBINARY} @localhost version.bind chaos txt | ${GREPBINARY} "^version.bind" | ${GREPBINARY} TXT | ${GREPBINARY} -E "[0-9].[0-9].[0-9]*")
        if [ "${FIND}" = "" ]; then
            LogText "结果：横幅中没有找到有用的信息"
            Display --indent 4 --text "- 检查横幅中的 BIND 版本" --result "${STATUS_OK}" --color GREEN
            AddHP 2 2
        else
            LogText "结果：版本横幅中可能提供 BIND 版本"
            Display --indent 4 --text "- 检查横幅中的 BIND 版本" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "在横幅中找到 BIND 版本"
            ReportSuggestion "${TEST_NO}" "可在配置文件中设置 'version none' 隐藏 BIND 版本"
            AddHP 0 2
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4212 TODO
    # Description : Check version option in BIND configuration
    #if [ ${BIND_RUNNING} -eq 1 -a ! "${BIND_CONFIG_LOCATION}" = "" -a ! "${DIGBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no NAME-4212 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "Check version setting in configuration"
#
#################################################################################
#
    # Test        : NAME-4220 TODO
    # Description : Check if we can perform a zone transfer of primary domain
    #Register --test-no NAME-4220 --weight L --network NO --category security --description "Check zone transfer"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : NAME-4222 TODO
    # Description : Check if we can perform a zone transfer of PTR (of primary domain)
    #Register --test-no NAME-4222 --weight L --network NO --category security --description "Check zone transfer"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : NAME-4230
    # Description : Check if PowerDNS is running
    Register --test-no NAME-4230 --weight L --network NO --category security --description "检查PowerDNS状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查正在运行的 PowerDNS 实例"
        if IsRunning "pdns_server"; then
            LogText "结果：找到PowerDNS进程"
            Display --indent 2 --text "- 检查PowerDNS状态" --result "${STATUS_RUNNING}" --color GREEN
            POWERDNS_RUNNING=1
        else
            LogText "结果：PowerDNS 未运行"
            if IsVerbose; then Display --indent 2 --text "- 检查PowerDNS状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4232
    # Description : Check PowerDNS configuration file
    if [ ${POWERDNS_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4232 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "搜索PowerDNS配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索PowerDNS配置文件"
        for DIR in ${POWERDNS_CONFIG_LOCS}; do
            if [ -f ${DIR}/pdns.conf ]; then
                POWERDNS_AUTH_CONFIG_LOCATION="${DIR}/pdns.conf"
                LogText "结果：找到配置文件（${POWERDNS_AUTH_CONFIG_LOCATION}）"
            fi
        done
        if HasData "${POWERDNS_AUTH_CONFIG_LOCATION}"; then
            Display --indent 4 --text "- 检查PowerDNS配置文件" --result "${STATUS_FOUND}" --color GREEN
        else
            Display --indent 4 --text "- 检查PowerDNS配置文件" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
#    # Test        : NAME-4234
#    # Description : Check PowerDNS configuration file consistency
#    if [ ${POWERDNS_RUNNING} -eq 1 -a ! "${POWERDNS_AUTH_CONFIG_LOCATION}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
#    Register --test-no NAME-4234 --weight L --network NO --category security --description "Check PowerDNS configuration consistency"
#    if [ ${SKIPTEST} -eq 0 ]; then
#    fi
#
#################################################################################
#
    # Test        : NAME-4236
    # Description : Check PowerDNS server backends
    if [ ${POWERDNS_RUNNING} -eq 1 -a ! "${POWERDNS_AUTH_CONFIG_LOCATION}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4236 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 PowerDNS 后端"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 PowerDNS 后端"
        FIND=$(${AWKBINARY} -F= '/^launch/ { print $2 }' ${POWERDNS_AUTH_CONFIG_LOCATION})
        if HasData "${FIND}"; then
            for ITEM in ${FIND}; do
                LogText "发现后端：${ITEM}"
            done
            Display --indent 4 --text "- 检查 PowerDNS 后端" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未找到 PowerDNS 后端"
            Display --indent 4 --text "- 检查 PowerDNS 后端" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4238
    # Description : Check PowerDNS authoritative status
    if [ ${POWERDNS_RUNNING} -eq 1 -a -n "${POWERDNS_AUTH_CONFIG_LOCATION}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4238 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查PowerDNS权威状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 PowerDNS 主站状态"
        FIND=$(${GREPBINARY} "^master=yes" ${POWERDNS_AUTH_CONFIG_LOCATION})
        if [ -n "${FIND}" ]; then
            LogText "在配置文件中找到 master=yes"
            Display --indent 4 --text "- PowerDNS 权威大师：YES"
            POWERDNS_AUTH_MASTER=1
        else
            LogText "结果：很可能不是大师（没有 master=yes)"
            Display --indent 4 --text "- PowerDNS 权威大师：NO"
        fi
        LogText "测试：检查 PowerDNS 从站状态"
        FIND=$(${GREPBINARY} "^slave=yes" ${POWERDNS_AUTH_CONFIG_LOCATION})
        if [ -n "${FIND}" ]; then
            LogText "在配置文件中找到 slave=yes"
            Display --indent 4 --text "- PowerDNS 权威从机：YES"
            POWERDNS_AUTH_SLAVE=1
        else
            LogText "结果：很可能不是从机（没有 slave=yes)"
            Display --indent 4 --text "- PowerDNS 权威从机：NO"
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4304
    # Description : Check NIS ypbind daemon status
    Register --test-no NAME-4304 --weight L --network NO --category security --description "检查 NIS ypbind 状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 ypbind 守护进程的状态"
        if IsRunning "ypbind"; then
            LogText "结果：ypbind 正在运行"
            Display --indent 2 --text "- 检查 ypbind 状态" --result "${STATUS_FOUND}" --color GREEN
            YPBIND_RUNNING=1
            if IsRunning "ypldap"; then
                LogText "结果：ypldap 正在运行"
                Display --indent 2 --text "- 检查 ypldap 状态" --result "${STATUS_FOUND}" --color GREEN
            else
                ReportSuggestion "${TEST_NO}" "禁用 NIS/NIS+ 并使用 LDAP 或 Kerberos 等替代方案"
            fi
        else
            LogText "结果：ypbind 未激活"
            if IsVerbose; then Display --indent 2 --text "- 检查 ypbind 状态" --result "${STATUS_NOT_FOUND}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4306
    # Description : Check NIS domain
    # Notes       : FreeBSD: sysctl kern.domainname
    if [ ${YPBIND_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4306 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查NIS域名"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 $(domainname) 中的 NIS 域值"
        FIND=$(${DOMAINNAMEBINARY} | ${GREPBINARY} -v "(none)")
        if [ -n "${FIND}" ]; then
            LogText "值：${FIND}"
            NISDOMAIN="${FIND}"
        else
            LogText "结果：命令输出中未找到 NIS 域"
        fi
        # Solaris / Linux style
        LogText "测试：检查文件 ${ROOTDIR}etc/defaultdomain"
        if [ -f ${ROOTDIR}etc/defaultdomain ]; then
            LogText "结果：文件 ${ROOTDIR}etc/defaultdomain 存在"
            FIND2=$(cat ${ROOTDIR}etc/defaultdomain)
            if [ -n "${FIND2}" ]; then
                LogText "输出：${FIND2}"
                NISDOMAIN="${FIND2}"
            else
                LogText "结果：在文件中找不到 NIS 域"
            fi
        fi
        # Red Hat style
        LogText "测试：检查${ROOTDIR}etc/sysconfig/network"
        if [ -f ${ROOTDIR}etc/sysconfig/network ]; then
            LogText "结果：文件 ${ROOTDIR}etc/sysconfig/network 存在"
            LogText "测试：检查文件中的 NISDOMAIN 值"
            FIND3=$(${GREPBINARY} "^NISDOMAIN" ${ROOTDIR}etc/sysconfig/network | ${AWKBINARY} -F= '{ print $2 }' | ${SEDBINARY} 's/"//g')
            if [ -n "${FIND3}" ]; then
                LogText "找到 NIS 域名：${FIND3}"
                NISDOMAIN="${FIND3}"
            else
                LogText "结果：在文件中找不到 NIS 域"
            fi
        else
            LogText "结果：文件 ${ROOTDIR}etc/sysconfig/network 不存在"
        fi

        if [ ! "${SYSCTLBINARY}" = "" ]; then
            # Check sysctl (e.g. FreeBSD)
            LogText "测试：检查 sysctl 是否有 kern.domainname"
            FIND=$(${SYSCTLBINARY} -a 2>&1 | ${GREPBINARY} "^kern.domainname" | ${AWKBINARY} -F: '{ print $2 }' | ${SEDBINARY} 's/ //g' | ${GREPBINARY} -v "^$")
            if [ ! "${FIND}" = "" ]; then
                LogText "结果：通过 sysctl 找到 NIS 域"
                NISDOMAIN="${FIND}"
            fi
        fi
        # Check if we found any NIS domain
        if [ -n "${NISDOMAIN}" ]; then
            LogText "找到 NIS 域名：${NISDOMAIN}"
            Report "nisdomain=${NISDOMAIN}"
            Display --indent 4 --text "- 检查NIS域名" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未找到 NIS 域"
            Display --indent 4 --text "- 检查NIS域名" --result "${STATUS_UNKNOWN}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    if [ -f ${ROOTDIR}etc/hosts ]; then
        Display --indent 2 --text "- 检查/etc/hosts"
    else
        LogText "结果：未找到 /etc/hosts 文件"
    fi

    # Test        : NAME-4402
    # Description : Check /etc/hosts configuration
    if [ -f ${ROOTDIR}etc/hosts ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4402 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 /etc/hosts 中的重复行"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 ${ROOTDIR}etc/hosts 中的重复行"
        OUTPUT=$(${AWKBINARY} '{ print $1, $2 }' ${ROOTDIR}etc/hosts | ${GREPBINARY} -E -v '^(#|$)' | ${GREPBINARY} -E "[a-f0-9]" | ${SORTBINARY} | ${UNIQBINARY} -d)
        if [ -z "${OUTPUT}" ]; then
            LogText "结果：正常，未发现重复行"
            Display --indent 4 --text "- 主机文件中的重复条目" --result "${STATUS_NONE}" --color GREEN
        else
            LogText "发现重复行：${OUTPUT}"
            LogText "结果：发现重复行"
            Display --indent 4 --text "- 主机文件中的重复条目" --result "${STATUS_FOUND}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "删除 ${ROOTDIR}etc/hosts 中的重复行"
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4404
    # Description : Check /etc/hosts contains an entry for this server name
    if [ -f ${ROOTDIR}etc/hosts ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4404 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 /etc/hosts 包含此服务器名称的条目"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 /etc/hosts 包含此服务器名称的条目"
        if [ -n "${HOSTNAME}" ]; then
            DATA=$(${GREPBINARY} -E -v '^(#|$|^::1\s|localhost)' ${ROOTDIR}etc/hosts | ${GREPBINARY} -i ${HOSTNAME})
            if [ -n "${DATA}" ]; then
                LogText "结果：在 ${ROOTDIR}etc/hosts 中找到 ${HOSTNAME} 的条目"
                Display --indent 4 --text "- /etc/hosts 中存在配置的主机名" --result "${STATUS_FOUND}" --color GREEN
            else
                LogText "结果：在 ${ROOTDIR}etc/hosts 中找不到 ${HOSTNAME} 的条目"
                Display --indent 4 --text "- /etc/hosts 中存在配置的主机名" --result "${STATUS_NOT_FOUND}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "将 IP 名称和 FQDN 添加到 /etc/hosts 以进行正确的名称解析"
                LogText "风险：/etc/hosts 中没有服务器名称 [主机名] 条目可能会导致本地连接出现意外性能问题"
            fi
        else
            LogText "结果：未配置主机名，跳过检查"
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4406
    # Description : Check server hostname mapping
    if [ -n "${HOSTNAME}" -a -f ${ROOTDIR}etc/hosts ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4406 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查服务器主机名映射"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 ${ROOTDIR}etc/hosts 中未本地映射的服务器主机名"
        DATA=$(${GREPBINARY} -E -v '^(#|$)' ${ROOTDIR}etc/hosts | ${GREPBINARY} -E '^(localhost|::1)\s' | ${GREPBINARY} -w ${HOSTNAME})
        if [ -n "${DATA}" ]; then
            LogText "结果：发现该服务器主机名映射到本地地址"
            LogText "输出：${DATA}"
            Display --indent 4 --text "- 主机名映射到 localhost" --result "${STATUS_FOUND}" --color YELLOW
            LogText "信息：将主机名链接到 localhost 条目可能会破坏某些解析。拆分解析，以便 localhost 解析回 127.0.0.1（和 ::1），并将计算机的主机名解析为网络接口上的真实 IP 地址。"
            ReportSuggestion "${TEST_NO}" "localhost 和系统主机名之间的拆分解析"
        else
            LogText "结果：该服务器主机名未映射到本地地址"
            Display --indent 4 --text "- 主机名映射到 localhost" --result "${STATUS_NOT_FOUND}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : NAME-4408
    # Description : Check localhost entry
    if [ -n "${GETENT_BINARY}" ]; then PREQS_MET="YES"; SKIPREASON="没有 getent 二进制文件"; else PREQS_MET="NO"; SKIPREASON=""; fi
    Register --test-no NAME-4408 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "检查 localhost 条目"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查 /etc/hosts 中未本地映射的服务器主机名"
        FIND=$(${GETENT_BINARY} hosts localhost | ${AWKBINARY} '{print $1}' | ${SORTBINARY} | ${TRBINARY} -d '\n')
        if [ "${FIND}" = "127.0.0.1" ]; then
            LogText "结果：localhost 映射到 127.0.0.1"
            Display --indent 4 --text "- Localhost 映射到 IP 地址" --result "${STATUS_OK}" --color GREEN
            Report "localhost-mapped-to=${FIND}"
        elif [ "${FIND}" = "::1" ]; then
            LogText "结果：localhost 映射到 ::1"
            Display --indent 4 --text "- Localhost 映射到 IP 地址" --result "${STATUS_OK}" --color GREEN
            Report "localhost-mapped-to=${FIND}"
        elif [ "${FIND}" = "127.0.0.1::1" ]; then
            LogText "结果：localhost 映射到 127.0.0.1 和 ::1"
            Display --indent 4 --text "- Localhost 映射到 IP 地址" --result "${STATUS_OK}" --color GREEN
            Report "localhost-mapped-to=${FIND}"
        else
            LogText "输出：${FIND}"
            LogText "结果：该服务器主机名未映射到本地地址"
            Display --indent 4 --text "- Localhost 映射到 IP 地址" --result "${STATUS_SUGGESTION}" --color YELLOW
            LogText "信息：确保 localhost 解析回 127.0.0.1（和/或 ::1）。"
            ReportSuggestion "${TEST_NO}" "localhost 和系统主机名之间的拆分解析" "/etc/hosts" "text:检查您的 localhost 行"
        fi
    fi
#
#################################################################################
#

Report "name_cache_used=${NAME_CACHE_USED}"
WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
