#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Scheduled tasks
#
#################################################################################
#
    InsertSection "${SECTION_SCHEDULED_TASKS}"
#
#################################################################################
#
    ATD_RUNNING=0
    CROND_RUNNING=0
#
#################################################################################
#
    # Test        : SCHD-7702
    # Description : Check cron daemon
    Register --test-no SCHD-7702 --weight L --network NO --category security --description "检查 Cron 守护进程状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${PSBINARY} aux | ${GREPBINARY} -E "( cron$|/cron(d)? )")
        if IsEmpty "${FIND}"; then
            LogText "结果：未发现 Cron 守护进程"
        else
            LogText "结果：Cron 守护进程正在运行"
            CROND_RUNNING=1
            Report "crond_running=1"
            Report "scheduler[]=crond"
        fi
    fi
#
#################################################################################
#
    # Test        : SCHD-7704
    # Description : Check crontab / cronjobs
    Register --test-no SCHD-7704 --weight L --network NO --category security --description "检查 crontab 和 Cron 任务"
    if [ ${SKIPTEST} -eq 0 ]; then
        BAD_FILE_PERMISSIONS=0
        BAD_FILE_OWNERSHIP=0
        FindCronJob() {
            sCRONJOBS=$(${GREPBINARY} -E '^([0-9*])' $1 | ${TRBINARY} '\t' ' ' | ${TRBINARY} -s ' ' | ${TRBINARY} ' ' ',' | ${SORTBINARY})
        }

        CRONTAB_FILE="${ROOTDIR}etc/crontab"
        if [ -f ${CRONTAB_FILE} ]; then
            ${GREPBINARY} -E -q -s 'lynis audit system' ${CRONTAB_FILE} && LYNIS_CRONJOB="file:/etc/crontab"
            if IsWorldWritable ${CRONTAB_FILE}; then LogText "结果：Cron 任务文件 ${CRONTAB_FILE} 的权限不安全"; Report "insecure_fileperms_cronjob[]=${CRONTAB_FILE}"; BAD_FILE_PERMISSIONS=1; AddHP 0 5; fi
            if ! IsOwnedByRoot ${CRONTAB_FILE}; then LogText "结果：Cron 任务文件 ${CRONTAB_FILE} 的所有者不正确"; Report "bad_fileowner_cronjob[]=${CRONTAB_FILE}"; BAD_FILE_OWNERSHIP=1; AddHP 0 5; fi
            FindCronJob ${CRONTAB_FILE}
            for ITEM in ${sCRONJOBS}; do
                LogText "发现 Cron 任务（${CRONTAB_FILE}）：${ITEM}"
                Report "cronjob[]=${ITEM}"
            done
        fi

        CRON_DIRS="${ROOTDIR}etc/cron.d"
        for DIR in ${CRON_DIRS}; do
            LogText "检查：目录 ${DIR}"
            if [ -d ${DIR} ]; then
                if FileIsReadable ${DIR}; then
                    LogText "结果：发现目录 ${DIR}"
                    LogText "检查：搜索 ${DIR} 中的文件"
                    FIND=$(${FINDBINARY} -L ${DIR} -type f -print | ${GREPBINARY} -v ".placeholder")
                    if IsEmpty "${FIND}"; then
                        LogText "结果：${DIR} 中没有文件"
                    else
                        LogText "结果：${DIR} 中发现一个或多个文件，正在分析……"
                        for FILE in ${FIND}; do
                            if IsWorldWritable ${FILE}; then LogText "结果：Cron 任务文件 ${J} 的权限不安全"; Report "insecure_fileperms_cronjob[]=${J}"; BAD_FILE_PERMISSIONS=1; AddHP 0 5; fi
                            if ! IsOwnedByRoot ${FILE}; then LogText "结果：Cron 任务文件 ${J} 的所有者不正确"; Report "bad_fileowner_cronjob[]=${J}"; BAD_FILE_OWNERSHIP=1; AddHP 0 5; fi
                            FILENAME=$(echo ${FILE} | ${AWKBINARY} -F/ '{print $NF}')
                            if [ "${FILENAME}" = "lynis" ]; then ${GREPBINARY} -E -q -s 'lynis audit system' ${CRONTAB_FILE} && LYNIS_CRONJOB="file:${FILE}"; fi
                            FindCronJob ${FILE}
                            if HasData "${sCRONJOBS}"; then
                                for K in ${sCRONJOBS}; do
                                    LogText "结果：发现 Cron 任务（${FILE}）：${K}"
                                    Report "cronjob[]=${FILE}"
                                done
                            fi
                        done
                        LogText "结果：已完成 ${DIR} 中的文件分析"
                    fi
                else
                    LogText "结果：无法读取文件或目录 ${DIR}"
                fi
            else
                LogText "结果：目录 ${DIR} 不存在"
            fi
        done

        CRON_DIRS="${ROOTDIR}etc/cron.hourly ${ROOTDIR}etc/cron.daily ${ROOTDIR}etc/cron.weekly ${ROOTDIR}etc/cron.monthly"
        for I in ${CRON_DIRS}; do
            LogText "检查：目录 ${I}"
            if [ -d ${I} ]; then
                LogText "结果：发现目录 ${I}"
                if FileIsReadable ${I}; then
                    LogText "检查：搜索 ${I} 中的文件"
                    FIND=$(${FINDBINARY} -L ${I} -type f -print 2> /dev/null | ${GREPBINARY} -v ".placeholder")
                    if [ -z "${FIND}" ]; then
                        LogText "结果：${I} 中没有文件"
                    else
                        LogText "结果：${I} 中发现一个或多个文件，正在分析……"
                        for FILE in ${FIND}; do
                            if IsWorldWritable ${FILE}; then LogText "结果：Cron 任务文件 ${FILE} 的权限不安全"; Report "insecure_fileperms_cronjob[]=${FILE}"; BAD_FILE_PERMISSIONS=1; AddHP 0 5; fi
                            if ! IsOwnedByRoot ${FILE}; then LogText "结果：Cron 任务文件 ${FILE} 的所有者不正确"; Report "bad_fileowner_cronjob[]=${FILE}"; BAD_FILE_OWNERSHIP=1; AddHP 0 5; fi
                            FILENAME=$(echo ${FILE} | ${AWKBINARY} -F/ '{print $NF}')
                            if [ "${FILENAME}" = "lynis" ]; then ${GREPBINARY} -E -q -s 'lynis audit system' ${CRONTAB_FILE} && LYNIS_CRONJOB="file:${FILE}"; fi
                            LogText "结果：发现 Cron 任务（${I}）：${FILE}"
                            Report "cronjob[]=${FILE}"
                        done
                        LogText "结果：已完成 ${I} 中的文件分析"
                    fi
                else
                    LogText "结果：目录权限过于严格，无法进入（这也可能是合理的安全设置）"
                fi
            else
                LogText "结果：目录 ${I} 不存在"
            fi
        done

        # /var/spool/cron/* and /var/spool/cron/crontabs/*
        # Search only in one tree, to avoid searching the tree twice
        if [ -d /var/spool/cron/crontabs ]; then
            FIND=$(${FINDBINARY} /var/spool/cron/crontabs -xdev -type f -print 2> /dev/null)
            for I in ${FIND}; do
                if FileIsReadable ${I}; then
                    ${GREPBINARY} -E -q -s 'lynis audit system' ${I} && LYNIS_CRONJOB="file:${I}"
                    FindCronJob ${I}
                    for FILE in ${sCRONJOBS}; do
                        LogText "发现 Cron 任务（/var/spool/cron/crontabs）：${I}（${FILE}）"
                        Report "cronjob[]=${I}"
                    done
                fi
            done
        else
            if [ -d ${ROOTDIR}var/spool/cron ]; then
                FIND=$(find ${ROOTDIR}var/spool/cron -type f -print)
                for I in ${FIND}; do
                    if FileIsReadable ${I}; then
                        ${GREPBINARY} -E -q -s 'lynis audit system' ${I} && LYNIS_CRONJOB="file:${I}"
                        FindCronJob ${I}
                        for FILE in ${sCRONJOBS}; do
                            LogText "在 ${ROOTDIR}var/spool/cron 中发现 Cron 任务：${I}（${FILE}）"
                            LogText "定时任务[]=${I}"
                        done
                    fi
                done
            fi
        fi

        # Anacron
        if [ "${OS}" = "Linux" ]; then
            if [ -f /etc/anacrontab ]; then
                LogText "检查：anacrontab"
                sANACRONJOBS=$(${GREPBINARY} -E '^([0-9@])' /etc/anacrontab | ${TRBINARY} '\t' ' ' | ${TRBINARY} -s ' ' | ${TRBINARY} ' ' ',' | ${SORTBINARY})
                if [ -n "${sANACRONJOBS}" ]; then
                    Report "scheduler[]=anacron"
                    for I in ${sANACRONJOBS}; do
                        LogText "发现 Anacron 任务（/etc/anacrontab）：${I}"
                        Report "cronjob[]=${I}"
                    done
                fi
            fi
        fi

        # Show warning when an issue shows up. Even if *both* the permissions and ownership are wrong, just show one (prevent overload of warnings).
        if [ ${BAD_FILE_PERMISSIONS} -eq 1 ]; then
            ReportWarning "${TEST_NO}" "发现一个或多个权限不正确的 Cron 任务文件（详情请查看日志）"
            Display --indent 2 --text "- 正在检查 crontab 和 Cron 任务文件" --result "${STATUS_WARNING}" --color RED
        elif [ ${BAD_FILE_OWNERSHIP} -eq 1 ]; then
            ReportWarning "${TEST_NO}" "发现一个或多个所有者不正确的 Cron 任务文件（详情请查看日志）"
            Display --indent 2 --text "- 正在检查 crontab 和 Cron 任务文件" --result "${STATUS_WARNING}" --color RED
        else
            Display --indent 2 --text "- 正在检查 crontab 和 Cron 任务文件" --result "${STATUS_DONE}" --color GREEN
        fi

    fi
#
#################################################################################
#
    # Test        : SCHD-7718
    # Description : Check atd status
    Register --test-no SCHD-7718 --weight L --network NO --category security --description "检查 atd 状态"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：atd 状态"
        FIND=$(${PSBINARY} ax | ${GREPBINARY} "/atd" | ${GREPBINARY} -v "grep")
        if [ -n "${FIND}" ]; then
            LogText "结果：at 守护进程处于活动状态"
            Display --indent 2 --text "- 正在检查 atd 状态" --result "${STATUS_RUNNING}" --color GREEN
            ATD_RUNNING=1
            Report "scheduler[]=atd"
        else
            LogText "结果：at 守护进程未运行"
            if IsVerbose; then Display --indent 2 --text "- 正在检查 atd 状态" --result "${STATUS_NOT_RUNNING}" --color WHITE; fi
        fi
    fi
#
#################################################################################
#
    # Test        : SCHD-7720
    # Description : Check at users
    # Notes       : if at.allow exists, only users listed can schedule at jobs
    #               if at.allow does not exist, but at.deny does, everyone
    #               except the listed ones can schedule jobs. If both can't be
    #               found, only root can schedule jobs.
    if [ ${ATD_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SCHD-7720 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查允许使用 at 的用户"
    if [ ${SKIPTEST} -eq 0 ]; then
        AT_UNKNOWN=0
        case ${OS} in
            FreeBSD)          AT_ALLOW="${ROOTDIR}var/at/at.allow";        AT_DENY="${ROOTDIR}var/at/at.deny"         ;;
            HPUX)             AT_ALLOW="${ROOTDIR}usr/lib/cron/at.allow";  AT_DENY="${ROOTDIR}usr/lib/cron/at.deny"   ;;
            Linux)            AT_ALLOW="${ROOTDIR}etc/at.allow";           AT_DENY="${ROOTDIR}etc/at.deny"            ;;
            OpenBSD)          AT_ALLOW="${ROOTDIR}var/cron/at.allow";      AT_DENY="${ROOTDIR}var/cron/at.deny"       ;;
            SunOS)            AT_ALLOW="${ROOTDIR}etc/cron.d/at.allow";    AT_DENY="${ROOTDIR}etc/cron.d/at.deny"     ;;
            *)                AT_UNKNOWN=1; LogText "已跳过检查：无法确定此系统的 at 用户配置文件"            ;;
        esac
        if [ ${AT_UNKNOWN} -eq 0 ]; then
            LogText "检查：文件 ${AT_ALLOW}"
            if [ -f ${AT_ALLOW} ]; then
                FileIsReadable ${AT_ALLOW}
                if [ ${CANREAD} -eq 1 ]; then
                    LogText "结果：文件 ${AT_ALLOW} 存在，仅文件中列出的用户可以安排 at 任务"
                    FIND=$(${SORTBINARY} ${AT_ALLOW})
                    if IsEmpty "${FIND}"; then
                        LogText "结果：文件为空，没有用户被允许安排 at 任务"
                    else
                        for ITEM in ${FIND}; do
                           LogText "允许使用 at 的用户：${ITEM}"
                        done
                    fi
                else
                    LogText "结果：无法读取 ${AT_ALLOW}（权限不足）"
                fi
            else
                LogText "结果：文件 ${AT_ALLOW} 不存在"
                LogText "检查：文件 ${AT_DENY}"
                if [ -f ${AT_DENY} ]; then
                    FileIsReadable ${AT_DENY}
                    if [ ${CANREAD} -eq 1 ]; then
                        LogText "结果：文件 ${AT_DENY} 存在，只有未列出的用户可以安排 at 任务"
                        FIND=$(${SORTBINARY} ${AT_DENY})
                        if [ -z "${FIND}" ]; then
                            LogText "结果：文件为空，没有用户被禁止安排 at 任务"
                        else
                            for ITEM in ${FIND}; do
                                LogText "禁止使用 at 的用户：${ITEM}"
                            done
                        fi
                    else
                        LogText "结果：无法读取 ${AT_DENY}（权限不足）"
                    fi
                else
                    LogText "结果：${AT_ALLOW} 和 ${AT_DENY} 均不存在"
                    LogText "说明：只有 root 用户可以安排 at 任务"
                    AddHP 1 1
                fi
            fi
            Display --indent 4 --text "- 正在检查 at 用户" --result "${STATUS_DONE}" --color GREEN
        else
            Display --indent 4 --text "- 正在检查 at 用户" --result "${STATUS_SKIPPED}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : SCHD-7724
    # Description : Check scheduled at jobs
    if [ ${ATD_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SCHD-7724 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查已安排的 at 任务"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：已安排的 at 任务"
        FIND=$(atq | ${GREPBINARY} -v "no files in queue" | ${AWKBINARY} '{gsub("\t"," ");print}' | ${SEDBINARY} 's/ /!space!/g')
        if HasData "${FIND}"; then
            LogText "结果：发现一个或多个 at 任务"
            for ITEM in ${FIND}; do
                VALUE=$(echo ${ITEM} | ${SEDBINARY} 's/!space!/ /g')
                LogText "发现 at 任务：${VALUE}"
            done
            Display --indent 4 --text "- 正在检查 at 任务" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：没有待执行的 at 任务"
            Display --indent 4 --text "- 正在检查 at 任务" --result "${STATUS_NONE}" --color GREEN
        fi
    fi
#
#################################################################################
#

if [ -z "${LYNIS_CRONJOB}" ]; then
    LogText "结果：未发现计划执行的 Lynis 任务（例如 crontab 或 Cron 任务）"
else
    LogText "结果：发现计划执行的 Lynis 任务（${LYNIS_CRONJOB}）"
fi

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
