#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# SSH
#
#################################################################################
#
    SSH_DAEMON_CONFIG_LOCS="/etc /etc/ssh /usr/local/etc/ssh /opt/csw/etc/ssh /usr/etc/ssh"
    SSH_DAEMON_CONFIG=""
    SSH_DAEMON_PORT=""
    SSH_DAEMON_RUNNING=0
    SSH_DAEMON_OPTIONS_FILE=""
    OPENSSHD_RUNNING=0
    OPENSSHD_VERSION=0
    OPENSSHD_VERSION_MAJOR=0
    OPENSSHD_VERSION_MINOR=0
#
#################################################################################
#
    InsertSection "${SECTION_SSH_SUPPORT}"
#
#################################################################################
#
    # Test        : SSH-7402
    # Description : Check for a running SSH daemon
    Register --test-no SSH-7402 --weight L --network NO --category security --description "检查正在运行的 SSH 守护进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索 SSH 守护进程"
        if IsRunning "sshd"; then
            OPENSSHD_RUNNING=1
            SSH_DAEMON_RUNNING=1
            Display --indent 2 --text "- 正在检查 SSH 守护进程" --result "${STATUS_FOUND}" --color GREEN
            # Store settings in a temporary file
            CreateTempFile
            SSH_DAEMON_OPTIONS_FILE="${TEMP_FILE}"
            # Use a non-existing user, to ensure that systems that have a Match block configured, will be evaluated as well
            ${SSHDBINARY} -T -C user=doesnotexist,host=none,addr=none 2> /dev/null > ${SSH_DAEMON_OPTIONS_FILE}
        elif PortIsListening "TCP" 22; then
            Display --indent 2 --text "- 正在检查 SSH 守护进程" --result "${STATUS_FOUND}" --color GREEN
            SSH_DAEMON_RUNNING=1
        else
            Display --indent 2 --text "- 正在检查 SSH 守护进程" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : SSH-7404
    # Description : Determine SSH daemon configuration file location
    if [ ${OPENSSHD_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SSH-7404 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 SSH 守护进程配置文件位置"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        LogText "检查：搜索 sshd_config 文件"
        for I in ${SSH_DAEMON_CONFIG_LOCS}; do
            if [ -f "${I}/sshd_config" ]; then
                LogText "结果：${I}/sshd_config 存在"
                if [ ${FOUND} -eq 1 ]; then
                    ReportException "${TEST_NO}:01"
                    LogText "结果：此前已找到另一个 sshd_config 文件，将使用本次发现的文件替代之前的文件。"
                fi
                FileIsReadable ${I}/sshd_config
                if [ ${CANREAD} -eq 1 ]; then
                    FOUND=1
                    SSH_DAEMON_CONFIG="${I}/sshd_config"
                else
                    LogText "结果：无法读取 ${I}/sshd_config 文件（权限不足）"
                fi
            fi
        done
        if [ -z "${SSH_DAEMON_CONFIG}" ]; then
            LogText "结果：未找到 sshd 配置文件"
            Display --indent 4 --text "- 正在搜索 SSH 配置文件" --result "${STATUS_NOT_FOUND}" --color YELLOW
            ReportException "${TEST_NO}:1" "SSH 守护进程正在运行，但未找到可读取的配置文件"
        else
            LogText "结果：使用最后找到的配置文件：${SSH_DAEMON_CONFIG}"
            Display --indent 4 --text "- 正在搜索 SSH 配置文件" --result "${STATUS_FOUND}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : SSH-7406
    # Description : Check OpenSSH version
    if [ ${OPENSSHD_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SSH-7406 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "确定 OpenSSH 版本"
    if [ ${SKIPTEST} -eq 0 ]; then
        OPENSSHD_VERSION=$(${SSHDBINARY} -t -d 2>&1 | ${GREPBINARY} 'sshd version' | ${AWKBINARY} '{if($4~OpenSSH_){print $4}}' | ${AWKBINARY} -F_ '{print $2}' | ${TRBINARY} -d '[:cntrl:],')
        LogText "结果：检测到的 OpenSSH 版本为 ${OPENSSHD_VERSION}"
        if [ -n "${OPENSSHD_VERSION}" ]; then
            OPENSSHD_VERSION_MAJOR=$(echo ${OPENSSHD_VERSION%%p*} | ${AWKBINARY} -F. '{print $1}')
            LogText "结果：OpenSSH 主版本号：${OPENSSHD_VERSION_MAJOR}"
            OPENSSHD_VERSION_MINOR=$(echo ${OPENSSHD_VERSION%%p*} | ${AWKBINARY} -F. '{print $2}')
            LogText "结果：OpenSSH 次版本号：${OPENSSHD_VERSION_MINOR}"
        fi
    fi
#
#################################################################################
#
    # Test        : SSH-7408
    # Description : Check SSH specific defined options
    # Notes       : Instead of parsing the configuration file, we query the SSH daemon itself
    if [ ${OPENSSHD_RUNNING} -eq 1 -a -n "${SSH_DAEMON_OPTIONS_FILE}" -a \( ${OPENSSHD_VERSION_MAJOR} -gt 5 -o ${OPENSSHD_VERSION_MAJOR} -eq 5 -a ${OPENSSHD_VERSION_MINOR} -ge 1 \) ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SSH-7408 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 SSH 的特定配置选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：检查 ${SSH_DAEMON_OPTIONS_FILE} 中定义的特定选项"
        ## SSHOPTIONS scheme:
        ##      <OptionName>:<ExpectedValue>,<MediumScoreValue>,<WeakValue>:<TestType>
        ##
        ##      Test types:
        ##      (a) '='         -- equal to is better,
        ##      (b) '<'         -- less or equal is better,
        ##      (c) '>'         -- more or equal is better,
        ##      (d) '!'         -- not equal is better.
        ##
        ##      Example:
        ##      PermitRootLogin:NO,WITHOUT-PASSWORD,YES,:=
        SSHOPS="AllowTcpForwarding:NO,LOCAL,YES:=\
                ClientAliveCountMax:2,4,16:<\
                ClientAliveInterval:300,600,900:<\
                FingerprintHash:SHA256,MD5,:=\
                GatewayPorts:NO,,YES:=\
                IgnoreRhosts:YES,,NO:=\
                LoginGraceTime:120,240,480:<\
                LogLevel:VERBOSE,INFO,:=\
                MaxAuthTries:3,6,999:<\
                MaxSessions:2,4,8:<\
                PermitRootLogin:(FORCED-COMMANDS-ONLY|NO|PROHIBIT-PASSWORD|WITHOUT-PASSWORD),,YES:=\
                PermitUserEnvironment:NO,,YES:=\
                PermitTunnel:NO,,YES:=\
                Port:,,22:!\
                PrintLastLog:YES,,NO:=\
                StrictModes:YES,,NO:=\
                TCPKeepAlive:NO,,YES:=\
                UseDNS:NO,,YES:=\
                X11Forwarding:NO,,YES:=\
                AllowAgentForwarding:NO,,YES:="


        # OpenSSH had some options removed over time. Based on the version we add some additional options to check
        if [ ${OPENSSHD_VERSION_MAJOR} -lt 7 ]; then
            LogText "结果：为 OpenSSH 6.x 及更早版本加入额外检查选项"
            SSHOPS="${SSHOPS} Compression:(DELAYED|NO),,YES:= UsePrivilegeSeparation:SANDBOX,YES,NO:=  Protocol:2,,1:="
        elif [ ${OPENSSHD_VERSION_MAJOR} -eq 7 ]; then
            # Protocol 1 support removed (OpenSSH 7.4 and later)
            if [ ${OPENSSHD_VERSION_MINOR} -lt 4 ]; then
                LogText "结果：为 OpenSSH 7.4 之前的版本加入额外检查选项"
                SSHOPS="${SSHOPS} Compression:(DELAYED|NO),,YES:= Protocol:2,,1:="
            fi
            # UsePrivilegedSeparation removed (OpenSSH 7.5 and later)
            if [ ${OPENSSHD_VERSION_MINOR} -lt 5 ]; then
                LogText "结果：为 OpenSSH 7.5 之前的版本加入额外检查选项"
                SSHOPS="${SSHOPS} UsePrivilegeSeparation:SANDBOX,YES,NO:="
            fi
        fi

        # Go through our list of options
        for I in ${SSHOPS}; do
            OPTIONNAME=$(echo ${I} | ${CUTBINARY} -d ':' -f1)
            OPTIONNAME_LOWER=$(echo ${I} | ${CUTBINARY} -d ':' -f1 | ${AWKBINARY} '{ print tolower($1) }')
            EXPECTEDVALUE=$(echo ${I} | ${CUTBINARY} -d ':' -f2 | ${CUTBINARY} -d',' -f1)
            MEDIUMSCOREDVALUE=$(echo ${I} | ${CUTBINARY} -d ':' -f2 | ${CUTBINARY} -d',' -f2)
            WEAKVALUE=$(echo ${I} | ${CUTBINARY} -d ':' -f2 | ${CUTBINARY} -d',' -f3)
            TESTTYPE=$(echo ${I} | ${CUTBINARY} -d ':' -f3)
            RESULT="NONE"

            if ! SkipAtomicTest "${TEST_NO}:${OPTIONNAME_LOWER}"; then

                # Get value and use the last occurrence
                FOUNDVALUE=$(${AWKBINARY} -v OPT="${OPTIONNAME_LOWER}" 'index($0, OPT) == 1 { print toupper($2) }' ${SSH_DAEMON_OPTIONS_FILE} | tail -1)
                LogText "检查：检查 ${SSH_DAEMON_OPTIONS_FILE} 中的 ${OPTIONNAME}"

                if [ -n "${FOUNDVALUE}" ]; then
                    LogText "结果：发现选项 ${OPTIONNAME}"
                    LogText "结果：选项 ${OPTIONNAME} 的值为 ${FOUNDVALUE}"

                    if [ "${TESTTYPE}" = "=" ]; then
                        if [ "${FOUNDVALUE}" = "${EXPECTEDVALUE}" ]; then
                            RESULT="GOOD"
                        elif [ "${FOUNDVALUE}" = "${MEDIUMSCOREDVALUE}" ]; then
                            RESULT="MIDSCORED"
                        elif [ "${FOUNDVALUE}" = "${WEAKVALUE}" ]; then
                            RESULT="WEAK"
                        else
                            if [ -n "${EXPECTEDVALUE}" ]; then
                                LogText "预期值包含多个候选值，正在检查当前值是否位于列表中（${EXPECTEDVALUE}）"
                                FIND=$(echo ${FOUNDVALUE} | ${GREPBINARY} -E "${EXPECTEDVALUE}")
                                if [ $? -eq 0 ]; then
                                    LogText "结果：已找到匹配项"
                                    RESULT="GOOD"
                                else
                                    LogText "结果：未找到匹配项"
                                fi
                            fi
                            if [ -n "${MEDIUMSCOREDVALUE}" ]; then
                                LogText "中等评分值包含多个候选值，正在检查当前值是否位于列表中（${MEDIUMSCOREDVALUE}）"
                                FIND=$(echo ${FOUNDVALUE} | ${GREPBINARY} -E "${MEDIUMSCOREDVALUE}")
                                if [ $? -eq 0 ]; then
                                    LogText "结果：已找到匹配项"
                                    RESULT="MIDSCORED"
                                else
                                    LogText "结果：未找到匹配项"
                                fi
                            fi
                            # Set result to weak if we can't find any matches
                            if [ "${RESULT}" = "NONE" ]; then RESULT="WEAK"; fi
                        fi

                    elif [ "${TESTTYPE}" = "<" ]; then
                        if [ "${FOUNDVALUE}" -ge "${WEAKVALUE}" -o "${FOUNDVALUE}" -gt "${MEDIUMSCOREDVALUE}" ]; then
                            RESULT="WEAK"
                        elif [ "${FOUNDVALUE}" -le "${MEDIUMSCOREDVALUE}" -a "${FOUNDVALUE}" -gt "${EXPECTEDVALUE}" ]; then
                            RESULT="MIDSCORED"
                        elif [ "${FOUNDVALUE}" -le "${EXPECTEDVALUE}" ]; then
                            RESULT="GOOD"
                        else
                            RESULT="UNKNOWN"
                        fi

                    elif [ "${TESTTYPE}" = ">" ]; then
                        if [ "${FOUNDVALUE}" -le "${WEAKVALUE}" ]; then
                            RESULT="WEAK"
                        elif [ "${FOUNDVALUE}" -le "${WEAKVALUE}" -a "${FOUNDVALUE}" -ge "${MEDIUMSCOREDVALUE}" ]; then
                            RESULT="MIDSCORED"
                        elif [ "${FOUNDVALUE}" -ge "${EXPECTEDVALUE}" ]; then
                            RESULT="GOOD"
                        else
                            RESULT="UNKNOWN"
                        fi

                    elif [ "${TESTTYPE}" = "!" ]; then
                        if [ "${FOUNDVALUE}" = "${WEAKVALUE}" ]; then
                            RESULT="WEAK"
                        elif [ ! "${FOUNDVALUE}" = "${WEAKVALUE}" ]; then
                            RESULT="GOOD"
                        else
                            RESULT="UNKNOWN"
                        fi

                    else
                        RESULT="NONE"
                    fi
                fi

                if [ "${RESULT}" = "GOOD" ]; then
                    LogText "结果：OpenSSH 选项 ${OPTIONNAME} 配置良好"
                    Display --indent 4 --text "- OpenSSH 选项：${OPTIONNAME}" --result "${STATUS_OK}" --color GREEN
                    AddHP 3 3
                elif [ "${RESULT}" = "MIDSCORED" ]; then
                    LogText "结果：OpenSSH 选项 ${OPTIONNAME} 配置尚可"
                    ReportSuggestion "${TEST_NO}" "建议进一步加固 SSH 配置" "${OPTIONNAME}（将 ${FOUNDVALUE} 设置为 ${EXPECTEDVALUE}）" "-"
                    ReportDetails --test "${TEST_NO}" --service "sshd" --field "${OPTIONNAME}" --value "${FOUNDVALUE}" --preferredvalue "${EXPECTEDVALUE}" --description "sshd 选项 ${OPTIONNAME}"
                    Display --indent 4 --text "- OpenSSH 选项：${OPTIONNAME}" --result "${STATUS_SUGGESTION}" --color YELLOW
                    AddHP 1 3
                elif [ "${RESULT}" = "WEAK" ]; then
                    LogText "结果：OpenSSH 选项 ${OPTIONNAME} 配置较弱，建议修正"
                    ReportSuggestion "${TEST_NO}" "建议进一步加固 SSH 配置" "${OPTIONNAME}（将 ${FOUNDVALUE} 设置为 ${EXPECTEDVALUE}）" "-"
                    ReportDetails --test "${TEST_NO}" --service "sshd" --field "${OPTIONNAME}" --value "${FOUNDVALUE}" --preferredvalue "${EXPECTEDVALUE}" --description "sshd 选项 ${OPTIONNAME}"
                    Display --indent 4 --text "- OpenSSH 选项：${OPTIONNAME}" --result "${STATUS_SUGGESTION}" --color YELLOW
                    AddHP 0 3
                elif [ "${RESULT}" = "UNKNOWN" ]; then
                    LogText "结果：OpenSSH 选项 ${OPTIONNAME} 的值未知（未定义）"
                    Display --indent 4 --text "- OpenSSH 选项：${OPTIONNAME}" --result DEFAULT --color WHITE
                    Report "unknown_config_option[]=ssh|$SSH_DAEMON_CONFIG}|${OPTIONNAME}|"
                else
                    LogText "结果：输出中未找到选项 ${OPTIONNAME}"
                    Display --indent 4 --text "- OpenSSH 选项：${OPTIONNAME}" --result "${STATUS_NOT_FOUND}" --color WHITE
                fi
            else
                if IsVerbose; then Display --indent 4 --text "- OpenSSH 选项：${OPTIONNAME}" --result "已通过配置跳过" --color WHITE; fi
            fi
        done
    fi
#
#################################################################################
#
    # Test        : SSH-7440
    # Description : OpenSSH - AllowUsers / AllowGroups
    # Goal        : Check if only a specific amount of users/groups can log in to the system
    if [ ${OPENSSHD_RUNNING} -eq 1 -a -n "${SSH_DAEMON_OPTIONS_FILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no SSH-7440 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 OpenSSH 的 AllowUsers 和 AllowGroups 选项"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        # AllowUsers
        FIND=$(${GREPBINARY} -E -i "^AllowUsers" ${SSH_DAEMON_OPTIONS_FILE} | ${AWKBINARY} '{ print $2 }')
        if [ -n "${FIND}" ]; then
            LogText "结果：已设置 AllowUsers，值为 ${FIND}"
            Display --indent 4 --text "- OpenSSH 选项：AllowUsers" --result "${STATUS_FOUND}" --color GREEN
            FOUND=1
        else
            LogText "结果：未设置 AllowUsers"
            Display --indent 4 --text "- OpenSSH 选项：AllowUsers" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi

        # AllowGroups
        FIND=$(${GREPBINARY} -E -i "^AllowGroups" ${SSH_DAEMON_OPTIONS_FILE} | ${AWKBINARY} '{ print $2 }')
        if [ -n "${FIND}" ]; then
            LogText "结果：已设置 AllowGroups，值为 ${FIND}"
            Display --indent 4 --text "- OpenSSH 选项：AllowGroups" --result "${STATUS_FOUND}" --color GREEN
            FOUND=1
        else
            LogText "结果：未设置 AllowGroups"
            Display --indent 4 --text "- OpenSSH 选项：AllowGroups" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi

        if [ ${FOUND} -eq 1 ]; then
            LogText "结果：SSH 已限制为仅允许特定用户或用户组登录，此配置较好"
            AddHP 2 2
        else
            LogText "结果：SSH 未设置特定用户或用户组限制，系统中的有效用户很可能都能通过 SSH 登录。"
            AddHP 0 1
        fi
    fi
#
#################################################################################
#


Report "ssh_daemon_running=${SSH_DAEMON_RUNNING}"
Report "openssh_daemon_running=${OPENSSHD_RUNNING}"

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com