#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# LDAP Services
#
#################################################################################
#
    InsertSection "${SECTION_LDAP_SERVICES}"
#
#################################################################################
#
    SLAPD_CONF_LOCS="${ROOTDIR}etc/ldap ${ROOTDIR}etc/openldap ${ROOTDIR}usr/local/etc/openldap"
    SLAPD_CONF_LOCATION=""
    SLAPD_RUNNING=0
#
#################################################################################
#
    # Test        : LDAP-2219
    # Description : Check running OpenLDAP instance
    Register --test-no LDAP-2219 --weight L --network NO --category security --description "检查正在运行的 OpenLDAP 实例"
    if [ ${SKIPTEST} -eq 0 ]; then
        if IsRunning "slapd"; then
            Display --indent 2 --text "- 检查 OpenLDAP 实例" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：发现正在运行 slapd 进程"
            SLAPDFOUND=1
            SLAPD_RUNNING=1
        else    
            Display --indent 2 --text "- 检查 OpenLDAP 实例" --result "${STATUS_NOT_FOUND}" --color WHITE
            LogText "结果：未找到正在运行的 slapd 进程。"
        fi
    fi
#
#################################################################################
#
    # Test        : LDAP-2224
    # Description : Search slapd.conf
    if [ ${SLAPD_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no LDAP-2224 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查存在 slapd.conf"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：搜索slapd.conf"
        for I in ${SLAPD_CONF_LOCS}; do
            if [ -f ${I}/slapd.conf ]; then
                LogText "结果：找到 ${I}/slapd.conf"
                SLAPD_CONF_LOCATION="${I}/slapd.conf"
            else
                LogText "结果：${I} 不包含 slapd.conf"
            fi
        done
        # Check if we found a valid location
        if [ -n "${SLAPD_CONF_LOCATION}" ]; then
            Display --indent 4 --text "- 检查slapd.conf" --result "${STATUS_FOUND}" --color GREEN
        else
            Display --indent 4 --text "- 检查slapd.conf" --result "${STATUS_NOT_FOUND}" --color YELLOW
        fi
    fi
#
#################################################################################
#
    # Test        : LDAP-2228
    # Description : Check OpenLDAP slapd.conf file permissions
#
#################################################################################
#
    # Test        : LDAP-2232
    # Description : Check OpenLDAP ownership on files/directories
#
#################################################################################
#
    # Test        : LDAP-2236
    # Description : Check OpenLDAP database permissions
#
#################################################################################
#
    # Test        : LDAP-2240
    # Description : Check OpenLDAP plaintext RootDN password
#
#################################################################################
#
    # Test        : LDAP-2244
    # Description : Check for LDAP configured client (and inform about LDAPS)
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
