#!/bin/sh

InsertSection "${SECTION_KERBEROS}"

#
#########################################################################
#

    # Test        : KRB-1000
    # Description : Check that Kerberos principals have passwords that expire
    Register --test-no KRB-1000 --weight L --network NO --description "检查 用于 Kerberos KDC 工具"
    if [ -n "${KADMINLOCALBINARY}" ] && [ -n "${KDB5UTILBINARY}" ]
    then
        PREQS_MET="YES"
        # Make sure krb5 debugging doesn't mess up the output
        unset KRB5_TRACE
        PRINCS="$(${KADMINLOCALBINARY} listprincs 2>/dev/null | ${TRBINARY:-tr} '\n' ' ')"
        if [ -z "${PRINCS}" ]
        then
            PREQS_MET="NO"
        fi
    else
        PREQS_MET="NO"
    fi
    if [ "${PREQS_MET}" = "YES" ]; then
        Display --indent 2 --text "- 检查 用于 Kerberos KDC 和 principals" --result "${STATUS_FOUND}" --color GREEN
    else
        Display --indent 2 --text "- 检查 用于 Kerberos KDC 和 principals" --result "${STATUS_NOT_FOUND}" --color WHITE
    fi

    # Test        : KRB-1010
    # Description : Check that Kerberos principals have passwords that expire
    Register --test-no KRB-1010 --preqs-met ${PREQS_MET} --weight L --network NO --description "检查 该 Kerberos principals 有 passwords 该 expire"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for I in ${PRINCS}
        do
            FIND="$(${KADMINLOCALBINARY} getprinc "${I}" | ${GREPBINARY} '^Password expiration date:')"
            if [ "${FIND}" = "Password expiration date: [never]" ]
            then
                LogText "结果： Kerberos principal ${I} 有 一个 密码/键 该 never expires"
                FOUND=1
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 4 --text "- Principals 没有 expiring 密码" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "Make sure 所有 你的 Kerberos principals 有 expiring passwords"
        else
            Display --indent 4 --text "- Principals 没有 expiring 密码" --result "${STATUS_OK}" --color GREEN
        fi
    fi
#
#################################################################################
#

    # Test        : KRB-1020
    # Description : Check last password change for Kerberos principals
    Register --test-no KRB-1020 --preqs-met ${PREQS_MET} --weight L --network NO --description "检查 最后 密码 更改 用于 Kerberos principals"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for I in ${PRINCS}
        do
            FIND="$(${KADMINLOCALBINARY} getprinc "${I}" | ${SEDBINARY} -n '/^Last password change:\s\+/s/^Last password change:\s\+//p')"
            if [ "${FIND}" = "[never]" ]
            then
                LogText "结果： Kerberos principal ${I} 有 一个 密码/键 该 有 never 已 changed"
                FOUND=1
            else
                J="$(date -d "${FIND}" +%s)"
                if [ ${J} -lt $((NOW - 60 * 60 * 24 * 365)) ]
                then
                    LogText "结果： Kerberos principal ${I} 有 有 一个 密码/键 更改 over 一个 年 ago"
                    FOUND=1
                fi
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 4 --text "- Principals 使用 late 密码 更改" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "Enforce frequent 密码/键 更改 用于 你的 Kerberos principals"
        else
            Display --indent 4 --text "- Principals 使用 late 密码 更改" --result "${STATUS_OK}" --color GREEN
        fi
    fi

#
#################################################################################
#

    # Test        : KRB-1030
    # Description : Check that Kerberos principals have a policy associated to them
    Register --test-no KRB5-1030 --preqs-met ${PREQS_MET} --weight L --network NO --description "检查 该 Kerberos principals 有 一个 策略 associated 到 them"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for I in ${PRINCS}
        do
            FIND="$(${KADMINLOCALBINARY} getprinc "${I}" | ${GREPBINARY} '^Policy:')"
            if [ "${FIND}" = "Policy: [none]" ]
            then
                LogText "结果： Kerberos principal ${I} 不 有 一个 策略 associated 到 它"
                FOUND=1
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 4 --text "- Principals 没有 associated 策略" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "Make sure 所有 你的 Kerberos principals 有 一个 策略 associated 到 them"
        else
            Display --indent 4 --text "- Principals 没有 associated 策略" --result "${STATUS_OK}" --color GREEN
        fi
    fi

#
#################################################################################
#

    # Test        : KRB-1040
    # Description : Check various attributes for Kerberos principals
    Register --test-no KRB5-1040 --preqs-met ${PREQS_MET} --weight L --network NO --description "检查 various attributes 用于 Kerberos principals"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        for I in ${PRINCS}
        do
            J="$(${KADMINLOCALBINARY} getprinc "${I}" | ${SEDBINARY} -n 's/^Attributes:\s\+\(.\+\)$/\1/p')"
            if ContainsString "^K/M@" "${I}" || \
                ContainsString "^kadmin/admin@" "${I}" || \
                ContainsString "^kadmin/changepw@" "${I}" || \
                ContainsString "^krbtgt/" "${I}"
            then
                if ! ContainsString "\bLOCKDOWN_KEYS\b" "${J}"
                then
                    LogText "结果： Sensitive Kerberos principal ${I} 不 有 lockdown_键 attribute"
                    FOUND=1
                fi
            elif ContainsString "/admin@" "${I}"
            then
                if ! ContainsString "\bDISALLOW_TGT_BASED\b" "${J}"
                then
                    LogText "结果： Kerberos admin principal ${I} 不 有 disallow_tgt_based attribute"
                    FOUND=1
                fi
            elif ContainsString "^[^/$]+@" "${I}"
            then
                if ! ContainsString "\bREQUIRES_PRE_AUTH\b.+\bDISALLOW_SVR\b" "${J}"
                then
                    LogText "结果： Regular Kerberos 用户 principal ${I} 不 有 requires_pre_auth 和/或 disallow_svr attribute"
                    FOUND=1
                fi
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 4 --text "- 检查 principals 用于 various attributes" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "Harden 你的 Kerberos principals 使用 appropriate attributes"
        else
            Display --indent 4 --text "- 检查 principals 用于 various attributes" --result "${STATUS_OK}" --color GREEN
        fi
    fi

#
#################################################################################
#

    # Test        : KRB-1050
    # Description : Check for weak crypto
    Register --test-no KRB-1050 --preqs-met ${PREQS_MET} --weight L --network NO --description "检查 用于 较弱 crypto"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${KDB5UTILBINARY} tabdump keyinfo | ${AWKBINARY} '$4 ~ /(des|arcfour|cbc|sha1)/{print$1,$4}')
        if [ -n "${FIND}" ]; then
            while read I J
            do
                LogText "结果： Kerberos principal ${I} 有 一个 键 使用 较弱 cryptographic algorithm ${J}"
            done << EOF
${FIND}
EOF
            Display --indent 4 --text "- Principals 使用 较弱 crypto" --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "从主体中移除弱加密密钥（des|arcfour|cbc|sha1）"
        else
            Display --indent 4 --text "- Principals 使用 较弱 crypto" --result "${STATUS_OK}" --color GREEN
        fi
    fi

#
#################################################################################
#

unset PRINCS
unset I
unset J

#EOF
