#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Category: Boot and services
#
#################################################################################
#
    InsertSection "${SECTION_BOOT_AND_SERVICES}"
#
#################################################################################
#
    BOOT_LOADER="unknown"
    BOOT_LOADER_FOUND=0
    BOOT_LOADER_SEARCHED=0
    GRUB_VERSION=0
    if [ -z "${SERVICE_MANAGER}" ]; then
        SERVICE_MANAGER="unknown"
    fi
#
#################################################################################
#
    # Test        : BOOT-5102
    # Description : 检查 AIX 启动设备
    # Notes       : The AIX bootstrap is called as software ROS. Bootstrap contains IPL (Initial Program loader)
    #               TODO - binary detection of bootinfo and replace with variable
    Register --test-no BOOT-5102 --os AIX --weight L --network NO --root-only YES --category security --description "检查 AIX 启动设备"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        LogText "检查：通过 bootinfo 查询 AIX 启动设备"
        if [ -x /usr/sbin/bootinfo ]; then
            FIND=$(/usr/sbin/bootinfo -b)
            if [ -n "${FIND}" ]; then
                LogText "结果：发现启动设备 ${FIND}"
                Display --indent 2 --text "- 检查启动设备（bootinfo）" --result "${STATUS_FOUND}" --color GREEN
                BOOT_LOADER="ROS"
                BOOT_LOADER_FOUND=1
            else
                LogText "结果：bootinfo 未返回数据，可能未找到启动设备"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5104
    # Description : 确定服务管理器
    # Notes       :
    # initscripts     - Used by Arch before
    # runit           - Used by Artix, Devuan, Dragora and Void
    # systemd         - Common option with more Linux distros implementing it
    # upstart         - Used by Debian/Ubuntu
    Register --test-no BOOT-5104 --weight L --network NO --category security --description "确定服务管理器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        case ${OS} in
            "Linux")
                if [ -f /proc/1/cmdline ]; then
                    OUTPUT=$(${AWKBINARY} '/(^\/|init|runit)/ { print $1 }' /proc/1/cmdline | ${TRBINARY} '\0' ' ' | ${SEDBINARY} 's/ $//')
                    LogText "结果：发现命令行 = ${OUTPUT}"
                    FILENAME=$(echo "${OUTPUT}" | ${AWKBINARY} '{print $1}')
                    LogText "结果：磁盘上的文件 = ${FILENAME}"
                    ISFILE=$(echo ${FILENAME} | ${GREPBINARY} "^/")
                    if [ -n "${ISFILE}" ]; then
                        if [ -L ${ISFILE} ]; then
                            ShowSymlinkPath ${ISFILE}
                            FILENAME="${SYMLINK}"
                        elif [ -f ${ISFILE} ]; then
                            FILENAME="${ISFILE}"
                        else
                            LogText "结果：PID 1 的命令行不是文件路径"
                        fi
                    fi
                    if [ -n "${FILENAME}" ]; then
                        SHORTNAME=$(echo ${FILENAME} | ${AWKBINARY} -F/ '{ print $NF }')
                        LogText "发现：${SHORTNAME}"
                        if [ "${SERVICE_MANAGER}" = "unknown" ]; then
                            case ${SHORTNAME} in
                                busybox)
                                    SERVICE_MANAGER="busybox"
                                ;;

                                "init" | "initsplash")
                                    if [ -d ${ROOTDIR}etc/rc.d ]; then
                                        SERVICE_MANAGER="bsdrc.d"
                                    else
                                        SERVICE_MANAGER="SysV Init"
                                    fi
                                ;;
                                systemd)
                                    SERVICE_MANAGER="systemd"
                                ;;
                                upstart)
                                    SERVICE_MANAGER="upstart"
                                ;;
                                runit)
                                    SERVICE_MANAGER="runit"
                                ;;
				openrc-init)
                                    SERVICE_MANAGER="openrc"
                                ;;
                                *)
                                    CONTAINS_SYSTEMD=$(echo ${SHORTNAME} | ${GREPBINARY} "systemd")
                                    if [ -n "${CONTAINS_SYSTEMD}" ]; then
                                        SERVICE_MANAGER="systemd"
                                    else
                                        LogText "发现 ${SHORTNAME}，无法确定其服务管理器类型"
                                        ReportException "${TEST_NO}:001" "未知服务管理器"
                                    fi
                                ;;
                            esac
                        fi
                    else
                        LogText "结果：/proc/1/cmdline 似乎为空"
                        ReportException "${TEST_NO}:002" "/proc/1/cmdline 中未发现数据"
                    fi
                fi
                # Continue testing if we didn't find it yet
                if [ "${SERVICE_MANAGER}" = "unknown" ]; then
                    if [ -f /usr/bin/init-openrc ]; then SERVICE_MANAGER="openrc"; fi
                fi
            ;;
            "DragonFly" | "NetBSD" | "FreeBSD" | "OpenBSD")
                if [ -x /sbin/init -a -d ${ROOTDIR}etc/rc.d -a -f ${ROOTDIR}etc/rc ]; then
                    SERVICE_MANAGER="bsdrc"
                fi
            ;;
            "macOS")
                if [ -x ${ROOTDIR}sbin/launchd ]; then
                    SERVICE_MANAGER="launchd"
                fi
            ;;
            "Solaris")
                if [ -x "${ROOTDIR}usr/bin/svcs" ]; then
                    SERVICE_MANAGER="SMF (svcs)"
                elif [ -d "${ROOTDIR}etc/init.d" ]; then
                    SERVICE_MANAGER="SysV Init"
                fi
            ;;
            *)
                LogText "结果：未知服务管理器"
            ;;
        esac
        LogText "结果：发现服务管理器 = ${SERVICE_MANAGER}"
        if [ "${SERVICE_MANAGER}" = "" -o "${SERVICE_MANAGER}" = "unknown" ]; then
            Display --indent 2 --text "- 服务管理器" --result "${STATUS_UNKNOWN}" --color YELLOW
        else
            Display --indent 2 --text "- 服务管理器" --result "${SERVICE_MANAGER}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5106
    # Description : Check if boot.efi is found on macOS/macOS
    Register --test-no BOOT-5106 --os "macOS" --weight L --network NO --root-only YES --category security --description "检查 Mac OS X/macOS 的 EFI 启动文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        FileExists ${ROOTDIR}System/Library/CoreServices/boot.efi
        if [ ${FILE_FOUND} -eq 1 ]; then
            LogText "结果：发现 macOS/Mac OS X boot.efi 文件"
            BOOT_LOADER="macOS-boot-EFI"
            BOOT_LOADER_FOUND=1
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5108
    # Description : Check for Syslinux
    Register --test-no BOOT-5108 --os "Linux" --weight L --network NO --root-only YES --category security --description "检查 Syslinux 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        FileExists ${ROOTDIR}boot/syslinux/syslinux.cfg
        if [ ${FILE_FOUND} -eq 1 ]; then
            LogText "结果：发现 Syslinux"
            BOOT_LOADER="Syslinux"
            BOOT_LOADER_FOUND=1
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5109
    # Description : Check for rEFInd
    Register --test-no BOOT-5109 --os "Linux" --weight L --network NO --root-only YES --category security --description "检查 rEFInd 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        FileExists ${ROOTDIR}boot/refind_linux.conf
        if [ ${FILE_FOUND} -eq 1 ]; then
            LogText "结果：发现 rEFInd"
            BOOT_LOADER="rEFInd"
            BOOT_LOADER_FOUND=1
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5116
    # Description : 检查系统是否以 UEFI 模式启动
    Register --test-no BOOT-5116 --weight L --network NO --root-only YES --category security --description "检查系统是否以 UEFI 模式启动"
    if [ ${SKIPTEST} -eq 0 ]; then
        UEFI_TESTS_PERFORMED=0
        case ${OS} in
            Linux)
                UEFI_TESTS_PERFORMED=1
                # Check if UEFI is available in this boot
                LogText "检查：确认是否使用 UEFI"
                if [ -d ${ROOTDIR}sys/firmware/efi ]; then
                    LogText "结果：系统以 UEFI 模式启动"
                    UEFI_BOOTED=1
                else
                    LogText "结果：未使用 UEFI，找不到 /sys/firmware/efi 目录"
                fi

                # Test if Secure Boot is enabled
                LogText "检查：确定是否使用 Secure Boot"
                if [ -d ${ROOTDIR}sys/firmware/efi/efivars ]; then
                    FIND=$(${LSBINARY} ${ROOTDIR}sys/firmware/efi/efivars/SecureBoot-* 2> /dev/null)
                    if [ -n "${FIND}" ]; then
                        for FILE in ${FIND}; do
                            LogText "检查：检查文件 ${FILE}"
                            # TODO: add detection for od
                            J=$(od -An -t u1 ${FILE} | ${AWKBINARY} '{ print $5 }')
                            if [ "${J}" = "1" ]; then
                                LogText "结果：发现已启用状态的 SecureBoot 文件"
                                UEFI_BOOTED_SECURE=1
                            else
                                LogText "结果：系统未通过 Secure Boot 启动（文件 ${FILE} 中状态为 0）"
                            fi
                        done
                    fi
                else
                    LogText "结果：系统未通过 Secure Boot 启动（未找到 SecureBoot 文件）"
                fi
            ;;
            #macOS)
            # TODO: macOS ioreg -l -p IODeviceTree | ${GREPBINARY} firmware-abi
            #;;
            *)
                LogText "结果：尚未为此平台实现 UEFI 检查"
            ;;
        esac
        if [ ${UEFI_BOOTED} -eq 1 ]; then
            Display --indent 2 --text "- 检查 UEFI 启动" --result "${STATUS_ENABLED}" --color GREEN
            if [ ${UEFI_BOOTED_SECURE} -eq 1 ]; then
                Display --indent 2 --text "- 检查 Secure Boot" --result "${STATUS_ENABLED}" --color GREEN
            else
                Display --indent 2 --text "- 检查 Secure Boot" --result "${STATUS_DISABLED}" --color YELLOW
            fi
        else
            if [ ${UEFI_TESTS_PERFORMED} -eq 1 ]; then
                Display --indent 2 --text "- 检查 UEFI 启动" --result "${STATUS_DISABLED}" --color WHITE
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5117
    # Description : Check for systemd-boot boot loader
    if [ ! "${BOOTCTLBINARY}" = "" -a ${HAS_SYSTEMD} -eq 1 -a ${UEFI_BOOTED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no BOOT-5117 --preqs-met ${PREQS_MET} --os "Linux" --weight L --network NO --category security --description "检查 systemd-boot 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        CURRENT_BOOT_LOADER=$(${BOOTCTLBINARY} status --no-pager 2>/dev/null | ${AWKBINARY} '/Current Boot Loader/{ getline; print $2 }')
        if [ "${CURRENT_BOOT_LOADER}" = "systemd-boot" ]; then
	    Display --indent 2 --text "- 检查 systemd-boot" --result "${STATUS_FOUND}" --color GREEN
            LogText "结果：发现 systemd-boot"
            BOOT_LOADER="systemd-boot"
            BOOT_LOADER_FOUND=1
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5121
    # Description : Check for GRUB boot loader
    Register --test-no BOOT-5121 --weight L --network NO --category security --description "检查 GRUB 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        FOUND=0
        LogText "检查：查找 GRUB 配置文件（/boot/grub/grub.conf 或 /boot/grub/menu.lst）"
        if [ -f /boot/grub/grub.conf -o -f /boot/grub/menu.lst ]; then
            FOUND=1
            BOOT_LOADER="GRUB"
            BOOT_LOADER_FOUND=1
            GRUB_VERSION=1
            Display --indent 2 --text "- 检查 GRUB" --result "${STATUS_OK}" --color GREEN
            if [ -f /boot/grub/grub.conf ]; then GRUBCONFFILE="/boot/grub/grub.conf"; else GRUBCONFFILE="/boot/grub/menu.lst"; fi
        fi

        # GRUB2 configuration file
        if [ -f /boot/grub/grub.cfg -o -f /boot/grub2/grub.cfg ]; then
            FOUND=1
            BOOT_LOADER="GRUB2"
            BOOT_LOADER_FOUND=1
            GRUB_VERSION=2
            Display --indent 2 --text "- 检查 GRUB2" --result "${STATUS_FOUND}" --color GREEN
            if [ -f /boot/grub/grub.cfg ]; then
                GRUBCONFFILE="/boot/grub/grub.cfg"
            elif [ -f /boot/grub2/grub.cfg ]; then
                GRUBCONFFILE="/boot/grub2/grub.cfg"
            fi
            LogText "结果：发现 GRUB2 配置文件（${GRUBCONFFILE}）"
        fi

        # Some OSes like Gentoo do not have /boot mounted by default
        # TODO: root directory and rewrite ls statement
        if [ -d /boot ]; then
            if [ "$(ls /boot/* 2> /dev/null)" = "" -a -n "${GRUB2INSTALLBINARY}" ]; then
                BOOT_LOADER_FOUND=1
                LogText "结果：/boot 为空，但已安装 GRUB2 可执行文件；可能已安装 GRUB2，只是 /boot 尚未挂载"
                Display --indent 2 --text "- 检查 GRUB2" --result "可能匹配" --color YELLOW
                ReportManual "${TEST_NO}:01"
            fi
        fi

        if [ ${FOUND} -eq 0 ]; then
            LogText "结果：未找到 GRUB 配置文件。"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5122
    # Description : Check for GRUB boot loader configuration
    if [ -n "${GRUBCONFFILE}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no BOOT-5122 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 GRUB 启动密码"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0

        if [ -d "${ROOTDIR}etc/grub.d" ]; then
            CONF_FILES=$(${FINDBINARY} -L "${ROOTDIR}etc/grub.d" -type f -name "[0-9][0-9]*" -print0 | ${TRBINARY} '\0' ' ' | ${TRBINARY} -d '[:cntrl:]')
            CONF_FILES="${GRUBCONFFILE} ${ROOTDIR}boot/grub/custom.cfg ${CONF_FILES}"
        else
            CONF_FILES="${GRUBCONFFILE} ${ROOTDIR}boot/grub/custom.cfg"
        fi

        for FILE in ${CONF_FILES}; do
            if [ -f "${FILE}" ]; then
                LogText "发现文件 ${FILE}，继续执行检查。"
                if FileIsReadable "${FILE}"; then
                    FIND=$(${GREPBINARY} 'password --md5' ${FILE} | ${GREPBINARY} -v '^#')
                    FIND2=$(${GREPBINARY} 'password --encrypted' ${FILE} | ${GREPBINARY} -v '^#')
                    FIND3=$(${GREPBINARY} 'set superusers' ${FILE} | ${GREPBINARY} -v '^#')
                    FIND4=$(${GREPBINARY} 'password_pbkdf2' ${FILE} | ${GREPBINARY} -v '^#')
                    FIND5=$(${GREPBINARY} 'grub.pbkdf2' ${FILE} | ${GREPBINARY} -v '^#')
                    # GRUB1: Password should be set (MD5 or SHA1)
                    if [ -n "${FIND}" -o -n "${FIND2}" ]; then
                        FOUND=1
                    # GRUB2: Superusers AND password should be defined
                    elif [ -n "${FIND3}" ]; then
                        if [ -n "${FIND4}" -o -n "${FIND5}" ]; then FOUND=1; fi
                    else
                        LogText "结果：此文件中未找到密码哈希配置行"
                    fi
                else
                    LogText "结果：无法读取 '${FILE}'（权限不足？）"
                fi
            else
                LogText "结果：文件 '${FILE}' 不存在"
            fi
        done
        if [ ${FOUND} -eq 1 ]; then
                Display --indent 4 --text "- 检查密码保护" --result "${STATUS_OK}" --color GREEN
                LogText "结果：GRUB 已配置密码保护。"
                AddHP 4 4
        else
                Display --indent 4 --text "- 检查密码保护" --result "${STATUS_NONE}" --color RED
                LogText "结果：GRUB 配置中未找到密码哈希配置行"
                ReportSuggestion "${TEST_NO}" "为 GRUB 启动加载器设置密码，防止启动配置被修改（例如无需密码进入单用户模式）"
                AddHP 0 2
        fi
        unset CONF_FILES FILE FIND FIND2 FIND3 FIND4 FIND5 FOUND
    fi
#
#################################################################################
#
    # Test        : BOOT-5124
    # Description : Check for FreeBSD boot loader
    Register --test-no BOOT-5124 --os FreeBSD --weight L --network NO --category security --description "检查 FreeBSD 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        if [ -f ${ROOTDIR}boot/boot1 -a -f ${ROOTDIR}boot/boot2 -a -f ${ROOTDIR}boot/loader ]; then
            LogText "结果：在 ${ROOTDIR}boot 中发现 boot1、boot2 和 loader 文件"
            Display --indent 2 --text "- 检查 FreeBSD 启动加载器" --result "${STATUS_FOUND}" --color GREEN
            BOOT_LOADER="FreeBSD"
            BOOT_LOADER_FOUND=1
        else
            LogText "结果：${ROOTDIR}boot 中未找到全部预期文件"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5261
    # Description : Check for DragonFly boot loader
    Register --test-no BOOT-5261 --os DragonFly --weight L --network NO --category security --description "检查 DragonFly 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        if [ -f ${ROOTDIR}boot/boot1 -a -f ${ROOTDIR}boot/boot2 -a -f ${ROOTDIR}boot/loader ]; then
            LogText "结果：在 ${ROOTDIR}boot 中发现 boot1、boot2 和 loader 文件"
            Display --indent 2 --text "- 检查 DragonFly 启动加载器" --result "${STATUS_FOUND}" --color GREEN
            BOOT_LOADER="DragonFly"
            BOOT_LOADER_FOUND=1
        else
            LogText "结果：${ROOTDIR}boot 中未找到全部预期文件"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5126
    # Description : Check for NetBSD boot loader
    Register --test-no BOOT-5126 --os NetBSD --weight L --network NO --category security --description "检查 NetBSD 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        if [ -f ${ROOTDIR}boot.${HARDWARE} -o -f ${ROOTDIR}boot -o -f ${ROOTDIR}ofwboot ]; then
            LogText "结果：发现 NetBSD 第二阶段启动程序"
            Display --indent 2 --text "- 检查 NetBSD 启动加载器" --result "${STATUS_FOUND}" --color GREEN
            BOOT_LOADER="NetBSD"
            BOOT_LOADER_FOUND=1
        else
            LogText "结果：未找到 NetBSD 第二阶段启动程序"
            ReportException "${TEST_NO}:1" "NetBSD 上未找到启动加载器"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5139
    # Description : Check for LILO boot loader
    # Notes       : password= or password =
    Register --test-no BOOT-5139 --weight L --network NO --category security --description "检查 LILO 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        LILOCONFFILE="${ROOTDIR}etc/lilo.conf"
        LogText "检查：查找 LILO 配置文件"
        if [ -f ${LILOCONFFILE} ]; then
            FileIsReadable ${LILOCONFFILE}
            if [ ${CANREAD} -eq 1 ]; then
                BOOT_LOADER="LILO"
                BOOT_LOADER_FOUND=1
                Display --indent 2 --text "- 检查 LILO" --result "${STATUS_OK}" --color GREEN
                LogText "检查 LILO 密码选项"
                FIND=$(${GREPBINARY} -E 'password[[:space:]]?=' ${LILOCONFFILE} | ${GREPBINARY} -v "^#")
                if [ -z "${FIND}" ]; then
                    if [ "${MACHINE_ROLE}" = "server" -o "${MACHINE_ROLE}" = "workstation" ]; then
                        Display --indent 4 --text "- 密码选项 " --result "${STATUS_WARNING}" --color RED
                        LogText "结果：LILO 未设置密码，可能被用于进入单用户模式或未经授权访问设备和数据。"
                        ReportSuggestion "${TEST_NO}" "为 LILO 添加密码：在 lilo.conf 中第一个 'image=<name>' 行之前添加 password=<password>"
                        ReportWarning "${TEST_NO}" "LILO 启动加载器未设置密码"
                        AddHP 0 2
                    elif [ "${MACHINE_ROLE}" = "personal" ]; then
                        Display --indent 4 --text "- 密码选项 " --result "${STATUS_WARNING}" --color yellow
                        LogText "结果：LILO 未设置密码，可能被用于进入单用户模式或未经授权访问设备和数据。"
                        ReportSuggestion "${TEST_NO}" "LILO 启动加载器未设置密码。为 LILO 添加密码：在 lilo.conf 中第一个 'image=<name>' 行之前添加 password=<password>"
                        AddHP 1 2
                    else
                        LogText "结果：LILO 未设置密码，且计算机角色未知"
                    fi
                else
                    Display --indent 4 --text "- 密码选项 " --result "${STATUS_OK}" --color GREEN
                    LogText "结果：已设置 LILO 密码选项"
                    AddHP 4 4
                fi
            else
                LogText "结果：无法读取 ${LILOCONFFILE}（权限不足）"
            fi
        else
            LogText "结果：未找到 LILO 配置文件"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5140
    # Description : Check for ELILO boot loader
    Register --test-no BOOT-5140 --os "Linux" --weight L --network NO --root-only YES --category security --description "检查 ELILO 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        CONF_FILES="${ROOTDIR}etc/elilo.conf ${ROOTDIR}boot/efi/EFI/${LINUX_VERSION}/elilo.conf"
        for FILE in ${CONF_FILES}; do
            FileExists ${FILE}
            if [ ${FILE_FOUND} -eq 1 ]; then
                Display --indent 2 --text "- 检查 ELILO 启动加载器" --result "${STATUS_FOUND}" --color GREEN
                LogText "结果：发现 ELILO 启动加载器"
                BOOT_LOADER="ELILO"
                BOOT_LOADER_FOUND=1
            fi
        done
    fi
#
#################################################################################
#
    # Test        : BOOT-5142
    # Description : Check for SILO boot loader
    Register --test-no BOOT-5142 --weight L --network NO --category security --description "检查 SPARC Improved 启动加载器（SILO）"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        if [ -f ${ROOTDIR}etc/silo.conf ]; then
            LogText "结果：发现 SILO 配置文件（/etc/silo.conf）"
            Display --indent 2 --text "- 检查 SILO 启动加载器" --result "${STATUS_FOUND}" --color GREEN
            BOOT_LOADER="SILO"
            BOOT_LOADER_FOUND=1
        else
            LogText "结果：未找到 SILO 配置文件。"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5155
    # Description : Check for YABOOT boot loader
    Register --test-no BOOT-5155 --weight L --network NO --category security --description "检查 YABOOT 启动加载器配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        LogText "检查：查找 /etc/yaboot.conf"
        if [ -f /etc/yaboot.conf ]; then
            LogText "结果：发现 YABOOT 配置文件（/etc/yaboot.conf）"
            Display --indent 4 --text "- 检查 YABOOT 启动加载器" --result "${STATUS_FOUND}" --color GREEN
            BOOT_LOADER="YABOOT"
            BOOT_LOADER_FOUND=1
        else
            LogText "结果：未找到 YABOOT 配置文件。"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5159
    # Description : Check for OpenBSD boot loader
    # More info   : Only OpenBSD
    Register --test-no BOOT-5159 --os OpenBSD --weight L --network NO --category security --description "检查 OpenBSD 启动加载器"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        FOUND=0
        # Boot files
        # /usr/mdec/biosboot: first stage bootstrap
        # /boot             : second stage bootstrap
        if [ -f ${ROOTDIR}usr/mdec/biosboot -a -f ${ROOTDIR}boot ]; then
            FOUND=1
        fi
        # Configuration file
        if [ -f ${ROOTDIR}etc/boot.conf ]; then
            FOUND=1
            Display --indent 2 --text "- 检查 ${ROOTDIR}etc/boot.conf" --result "${STATUS_FOUND}" --color GREEN
            FIND=$(${GREPBINARY} '^boot' ${ROOTDIR}etc/boot.conf)
            if [ -z "${FIND}" ]; then
                Display --indent 4 --text "- 检查 boot 选项" --result "${STATUS_WARNING}" --color RED
                #ReportSuggestion "${TEST_NO}" "Add 'boot' to the ${ROOTDIR}etc/boot.conf file to disable the default 5 seconds waiting time, to disallow booting into single user mode."
                ReportWarning "${TEST_NO}" "系统可以在无需密码的情况下进入单用户模式"
            else
                Display --indent 4 --text "- 检查 boot 选项" --result "${STATUS_OK}" --color GREEN
                LogText "正常，boot 选项已启用。"
            fi
        else
            Display --indent 2 --text "- 检查 ${ROOTDIR}etc/boot.conf" --result "${STATUS_NOT_FOUND}" --color YELLOW
            LogText "结果：未找到 ${ROOTDIR}etc/boot.conf。使用默认启动加载器时，具有物理"
            LogText "访问权限的人员可能进入单用户模式。"
            ReportSuggestion "${TEST_NO}" "在 ${ROOTDIR}etc/boot.conf 中添加 'boot'，禁用默认的 5 秒等待时间。"
        fi
        if [ ${FOUND} -eq 1 ]; then
            LogText "结果：发现 OpenBSD 启动加载器"
            BOOT_LOADER="OpenBSD"
            BOOT_LOADER_FOUND=1
        fi
    fi
#
#################################################################################
#
    if [ ${BOOT_LOADER_FOUND} -eq 0 -a ${BOOT_LOADER_SEARCHED} -eq 1 ]; then
        # Your boot loader is not detected. Want to help supporting it, see the README
        # ReportException "BOOTLOADER" "No boot loader found"
        Display --indent 4 --text "- 启动加载器" --result "未找到" --color YELLOW
    fi
#
#################################################################################
#
    # Test        : BOOT-5165
    # Description : 检查 FreeBSD 启动服务
    Register --test-no BOOT-5165 --os FreeBSD --weight L --network NO --category security --description "检查 FreeBSD 启动服务"
    if [ ${SKIPTEST} -eq 0 ]; then
        if HasData "${SERVICEBINARY}"; then
            # FreeBSD (Ask services(8) for enabled services)
            LogText "搜索启动时运行的服务（service）"
            FIND=$(${SERVICEBINARY} -e | ${SEDBINARY} 's|^.*\/||' | ${SORTBINARY})
        else
            # FreeBSD (Read /etc/rc.conf file for enabled services)
            LogText "搜索启动时运行的服务（rc.conf）"
            FIND=$(${GREPBINARY} -E -v -i '^#|none' ${ROOTDIR}etc/rc.conf | ${GREPBINARY} -E -i '_enable.*(yes|on|1)' | ${SORTBINARY} | ${AWKBINARY} -F= '{ print $1 }' | ${SEDBINARY} 's/_enable//')
        fi
        COUNT=0
        for ITEM in ${FIND}; do
            LogText "发现服务（service/rc.conf）：${ITEM}"
            Report "boottask[]=${ITEM}"
            COUNT=$((COUNT + 1))
        done
        Display --indent 2 --text "- 检查启动服务（service/rc.conf）" --result "${STATUS_DONE}" --color GREEN
        Display --indent 6 --text "结果：发现 ${COUNT} 个已配置的服务/选项"
        LogText "发现 ${COUNT} 个将在启动时运行的服务/选项"
    fi
#
#################################################################################
#
    # Test        : BOOT-5170
    # Description : 检查 Solaris 启动守护进程
    Register --test-no BOOT-5170 --os Solaris --weight L --network NO --category security --description "检查 Solaris 启动守护进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ -n "${SVCSBINARY}" ]; then
            LogText "结果：使用 svcs 检查守护进程"
            LogText "SysV 风格服务可能被误计为正在运行。"

            Report "running_service_tool=svcs"

            # For the documentation of the states (field $1) see
            # "Managing System Services in Oracle Solaris 11.4" pp. 24, available
            # at https://docs.oracle.com/cd/E37838_01/pdf/E60998.pdf

            FIND=$("${SVCSBINARY}" -Ha | ${AWKBINARY} '{ if ($1 == "online" || $1 == "legacy_run") print $3 }')
            COUNT=0
            for ITEM in ${FIND}; do
                LogText "发现正在运行的守护进程：${ITEM}"
                Report "running_service[]=${ITEM}"
                COUNT=$((COUNT + 1 ))
            done
            Display --indent 2 --text "- 检查正在运行的守护进程（svcs）" --result "${STATUS_DONE}" --color GREEN
            Display --indent 8 --text "结果：发现 ${COUNT} 个正在运行的守护进程"
            LogText "结果：发现 ${COUNT} 个正在运行的守护进程"

            LogText "搜索已启用的守护进程（svcs）"
            Report "boot_service_tool=svcs"

            FIND=$("${SVCSBINARY}" -Ha | ${AWKBINARY} '{ if ($1 != "disabled" && $1 != "uninitialized") print $3 }')
            COUNT=0
            for ITEM in ${FIND}; do
                LogText "发现启动时启用的守护进程：${ITEM}"
                Report "boot_service[]=${ITEM}"
                COUNT=$((COUNT + 1 ))
            done
            LogText "提示：运行 svcs -a 查看所有服务"
            Display --indent 2 --text "- 检查启动时启用的守护进程（svcs）" --result "${STATUS_DONE}" --color GREEN
            Display --indent 8 --text "结果：发现 ${COUNT} 个启动时启用的守护进程"
            LogText "结果：发现 ${COUNT} 个启动时启用的守护进程"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5171
    # Description : Check for services with errors on solaris
#
#################################################################################
#
    # Test        : BOOT-5177
    # Description : Check for Linux boot services (systemd and chkconfig)
    # Notes       : We skip using chkconfig if systemd is being used.
    Register --test-no BOOT-5177 --os Linux --weight L --network NO --category security --description "检查 Linux 启动服务与正在运行的服务"
    if [ ${SKIPTEST} -eq 0 ]; then
        CHECKED=0
        LogText "检查：确认 systemctl 是否存在"
        # Determine if we have systemctl on board
        if HasData "${SYSTEMCTLBINARY}"; then
            LogText "结果：发现 systemctl，使用它收集服务信息"
            # Running services
            LogText "搜索正在运行的服务（仅 systemctl service 单元）"
            FIND=$(${SYSTEMCTLBINARY} --no-legend --full --type=service --state=running | ${AWKBINARY} -F.service '{ print $1 }')
            COUNT=0
            Report "running_service_tool=systemctl"
            for ITEM in ${FIND}; do
                LogText "发现正在运行的服务：${ITEM}"
                Report "running_service[]=${ITEM}"
                COUNT=$((COUNT + 1))
            done
            LogText "提示：运行 systemctl --full --type=service 查看所有服务"
            Display --indent 2 --text "- 检查正在运行的服务（systemctl）" --result "${STATUS_DONE}" --color GREEN
            Display --indent 8 --text "结果：发现 ${COUNT} 个正在运行的服务"
            LogText "结果：发现 ${COUNT} 个正在运行的服务"

            # Services at boot
            LogText "搜索已启用的服务（仅 systemctl service 单元）"
            FIND=$(${SYSTEMCTLBINARY} list-unit-files --no-legend --type=service --state=enabled | ${SORTBINARY} -u | ${AWKBINARY} -F.service '{ print $1 }')
            COUNT=0
            Report "boot_service_tool=systemctl"
            for ITEM in ${FIND}; do
                LogText "发现启动时启用的服务：${ITEM}"
                Report "boot_service[]=${ITEM}"
                COUNT=$((COUNT + 1))
            done
            LogText "提示：运行 systemctl list-unit-files --type=service 查看所有服务"
            Display --indent 2 --text "- 检查启动时启用的服务（systemctl）" --result "${STATUS_DONE}" --color GREEN
            Display --indent 8 --text "结果：发现 ${COUNT} 个已启用的服务"
            LogText "结果：发现 ${COUNT} 个已启用的服务"

        else

            LogText "结果：未找到 systemctl，继续检查 chkconfig"
            if [ -n "${CHKCONFIGBINARY}" ]; then
                LogText "结果：发现 chkconfig，使用它收集服务信息"
                LogText "搜索启动服务（chkconfig，运行级别 3 和 5）"
                FIND=$(${CHKCONFIGBINARY} --list | ${GREPBINARY} -E '3:on|5:on' | ${AWKBINARY} '{ print $1 }')
                COUNT=0
                Report "boot_service_tool=chkconfig"
                for ITEM in ${FIND}; do
                    LogText "发现启动服务（运行级别 3 或 5）：${ITEM}"
                    Report "boot_service[]=${ITEM}"
                    COUNT=$((COUNT + 1))
                done
                LogText "提示：运行 chkconfig --list 查看所有服务并禁用不需要的服务"
                Display --indent 2 --text "- 检查启动服务（chkconfig）" --result "${STATUS_DONE}" --color GREEN
                Display --indent 8 --text "结果：发现 ${COUNT} 个服务"
                LogText "结果：发现 ${COUNT} 个启动服务"
            else
                LogText "结果：未找到 systemctl 和 chkconfig，跳过此检查"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5180
    # Description : 检查 Linux 启动服务（Debian 风格）
    # Notes       : Debian 8+ shows runlevel 5
    if [ "${LINUX_VERSION}" = "Debian" ] || [ "${LINUX_VERSION}" = "Ubuntu" ] ||
           [ "${LINUX_VERSION_LIKE}" = "Debian" ] || [ "${LINUX_VERSION_LIKE}" = "Ubuntu" ]; then
        PREQS_MET="YES"
    else
        PREQS_MET="NO"
    fi

    Register --test-no BOOT-5180 --os Linux --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Linux 启动服务（Debian 风格）"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Runlevel check
        sRUNLEVEL=$(${RUNLEVELBINARY} | ${GREPBINARY} "N [0-9]" | ${AWKBINARY} '{ print $2} ')
        LogText "结果：发现运行级别 ${sRUNLEVEL}"
        if [ "${sRUNLEVEL}" = "2" ]; then
            LogText "结果：检测到运行级别 2，搜索 /etc/rc2.d"
            FIND=$(${FINDBINARY} ${ROOTDIR}etc/rc2.d -type l -print | ${CUTBINARY} -d '/' -f4 | ${SEDBINARY} "s/S[0-9][0-9]//g" | sort)
            if [ -n "${FIND}" ]; then
                COUNT=0
                for SERVICE in ${FIND}; do
                    LogText "发现启动服务（运行级别 2）：${SERVICE}"
                    COUNT=$((COUNT + 1))
                done
                Display --indent 2 --text "- 检查启动服务（rc2.d）" --result "${STATUS_DONE}" --color WHITE
                Display --indent 4 --text "结果：发现 ${COUNT} 个服务"
                LogText "结果：发现 ${COUNT} 个服务"
            fi
        elif [ -z "${sRUNLEVEL}" ]; then
            ReportSuggestion "${TEST_NO}" "确定运行级别和启动服务"
        else
            LogText "结果：跳过后续操作"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5184
    # Description : Check world writable startup scripts
    Register --test-no BOOT-5184 --os "Linux Solaris" --weight L --network NO --category security --description "检查启动文件和脚本权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        CHECKDIRS="${ROOTDIR}etc/init.d ${ROOTDIR}etc/rc.d ${ROOTDIR}etc/rcS.d"

        LogText "结果：检查 ${ROOTDIR}etc/init.d 脚本的可写权限"
        for DIR in ${CHECKDIRS}; do
            LogText "检查：确认目录 ${DIR} 是否存在"
            if [ -d ${DIR} ]; then
                LogText "结果：发现目录 ${DIR}"
                LogText "检查：搜索目录中的文件"
                FIND=$(${FINDBINARY} -L ${DIR} -type f -print | ${SORTBINARY})
                if [ -n "${FIND}" ]; then
                    LogText "结果：目录中发现文件，开始检查权限"
                    for FILE in ${FIND}; do
                        LogText "检查：检查文件 ${FILE} 的权限"
                        if IsWorldWritable ${FILE}; then
                            FOUND=1
                            LogText "结果：警告，文件 ${FILE} 可被所有用户写入"
                        else
                            LogText "结果：正常，文件 ${FILE} 不可被所有用户写入"
                        fi
                    done
                else
                    LogText "结果：目录中未发现文件。"
                fi
            else
                LogText "结果：未找到目录 ${DIR}，跳过。"
            fi
        done

        # /etc/rc[0-6].d
        for NO in 0 1 2 3 4 5 6; do
            LogText "检查：检查 ${ROOTDIR}etc/rc${NO}.d 脚本的可写权限"
            if [ -d ${ROOTDIR}etc/rc${NO}.d ]; then
                FIND=$(${FINDBINARY} -L ${ROOTDIR}etc/rc${NO}.d -type f -print | ${SORTBINARY})
                for I in ${FIND}; do
                    if IsWorldWritable ${I}; then
                        FOUND=1
                        LogText "结果：警告，文件 ${I} 可被所有用户写入"
                    else
                        LogText "结果：正常，文件 ${I} 不可被所有用户写入"
                    fi
                done
            fi
        done

        # Other files
        CHECKFILES="${ROOTDIR}etc/rc ${ROOTDIR}etc/rc.local ${ROOTDIR}etc/rc.d/rc.sysinit"
        for I in ${CHECKFILES}; do
            if [ -f ${I} ]; then
                ShowSymlinkPath "${I}"
                if [ ${FOUNDPATH} -eq 1 ]; then
                    CHECKFILE="${SYMLINK}"
                    LogText "结果：发现符号链接指向的路径（${CHECKFILE} --> ${I}）"
                else
                    CHECKFILE="${I}"
                fi
                LogText "检查：检查文件 ${CHECKFILE} 的可写权限"
                if IsWorldWritable ${CHECKFILE}; then
                    FOUND=1
                    ReportWarning "${TEST_NO}" "发现可写的启动脚本 ${CHECKFILE}"
                    LogText "结果：警告，文件 ${CHECKFILE} 可被所有用户写入"
                else
                    LogText "结果：正常，文件 ${CHECKFILE} 不可被所有用户写入"
                fi
            fi
        done

        # Check results
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 检查启动文件权限" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "发现可被所有用户写入的启动脚本" "-" "-"
            LogText "结果：发现一个或多个可能被其他用户写入的脚本"
            AddHP 0 3
        else
            Display --indent 2 --text "- 检查启动文件权限" --result "${STATUS_OK}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5202
    # Description : 检查系统运行时间
    Register --test-no BOOT-5202 --weight L --network NO --category security --description "检查系统运行时间"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        FIND=""
        UPTIME_IN_SECS=""
        case "${OS}" in
            Linux)
                # Idle time, not real uptime
                if [ -f /proc/uptime ]; then
                    UPTIME_IN_SECS=$(${CUTBINARY} -d ' ' -f1 /proc/uptime | ${CUTBINARY} -d '.' -f1)
                else
                    Display --indent 2 --text "- 检查运行时间" --result "${STATUS_SKIPPED}" --color YELLOW
                    ReportException "${TEST_NO}:1" "此操作系统没有可用的运行时间检查（缺少 /proc/uptime）"
                fi
            ;;

            DragonFly | FreeBSD | macOS)
                if [ -n "${SYSCTLBINARY}" ]; then
                    TIME_BOOT=$(${SYSCTLBINARY} kern.boottime | ${AWKBINARY} '{ print $5 }' | ${SEDBINARY} -e 's/,//' | ${GREPBINARY} "[0-9]")
                    TIME_NOW=$(date "+%s")
                    LogText "启动时间：${TIME_BOOT}"
                    LogText "当前时间：${TIME_NOW}"
                    if [ -n "${TIME_BOOT}" -a -n "${TIME_NOW}" ]; then
                        UPTIME_IN_SECS=$((TIME_NOW - TIME_BOOT))
                    else
                        ReportException "${TEST_NO}:5" "kern.boottime 可能为空，无法确定运行时间"
                    fi
                else
                    Display --indent 2 --text "- 检查运行时间" --result "${STATUS_SKIPPED}" --color YELLOW
                    ReportException "${TEST_NO}:4" "此操作系统没有可用的运行时间检查（缺少 sysctl）"
                fi
            ;;

            NetBSD | OpenBSD)
                if [ -n "${SYSCTLBINARY}" ]; then
                    TIME_BOOT=$(${SYSCTLBINARY} -n kern.boottime)
                    TIME_NOW=$(date "+%s")
                    LogText "启动时间：${TIME_BOOT}"
                    LogText "当前时间：${TIME_NOW}"
                    if [ -n "${TIME_BOOT}" -a -n "${TIME_NOW}" ]; then
                        UPTIME_IN_SECS=$((TIME_NOW - TIME_BOOT))
                    else
                        ReportException "${TEST_NO}:5" "kern.boottime 可能为空，无法确定运行时间"
                    fi
                else
                    Display --indent 2 --text "- 检查运行时间" --result "${STATUS_SKIPPED}" --color YELLOW
                    ReportException "${TEST_NO}:4" "此操作系统没有可用的运行时间检查（缺少 sysctl）"
                fi
            ;;

            Solaris)
                if [ -n "${KSTATBINARY}" ]; then
                    UPTIME_IN_SECS=$(${KSTATBINARY} -p unix:0:system_misc:snaptime | ${GREPBINARY} "^unix" | ${AWKBINARY} '{print $2}' | ${CUTBINARY} -d "." -f1)
                else
                    Display --indent 2 --text "- 检查运行时间" --result "${STATUS_SKIPPED}" --color YELLOW
                    ReportException "${TEST_NO}:2" "此操作系统没有可用的运行时间检查（缺少 kstat）"
                fi
            ;;

            *)
                Display --indent 2 --text "- 检查运行时间" --result "${STATUS_SKIPPED}" --color YELLOW

                # Want to help improving Lynis? Share your operating system and a way to determine the uptime (in seconds)
                ReportException "${TEST_NO}:3" "尚未为此操作系统提供运行时间检查"
            ;;
        esac

        if [ -n "${UPTIME_IN_SECS}" ]; then
            UPTIME_IN_DAYS=$((UPTIME_IN_SECS / 60 / 60 / 24))
            LogText "运行时间（秒）：${UPTIME_IN_SECS}"
            LogText "运行时间（天）：${UPTIME_IN_DAYS}"
            Report "uptime_in_seconds=${UPTIME_IN_SECS}"
            Report "uptime_in_days=${UPTIME_IN_DAYS}"
        else
            LogText "结果：没有可用的运行时间信息"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5260
    # Description : 检查 systemd 单用户模式保护
    Register --test-no BOOT-5260 --os Linux --weight L --network NO --category security --description "检查 systemd 单用户模式保护"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：查找 /usr/lib/systemd/system/rescue.service"
        if [ -f ${ROOTDIR}usr/lib/systemd/system/rescue.service ]; then
            LogText "结果：发现 /usr/lib/systemd/system/rescue.service 文件"
            LogText "检查：确认单用户模式是否使用 sulogin"
            FIND=$(${GREPBINARY} -E "^ExecStart=.*sulogin" ${ROOTDIR}usr/lib/systemd/system/rescue.service)
            if [ -n "${FIND}" ]; then
                FOUND=1
                LogText "结果：发现 sulogin，单用户模式已受保护"
                AddHP 3 3
            else
                LogText "结果：rescue.service 中未找到 sulogin"
                AddHP 1 3
                Display --indent 2 --text "- 检查 rescue.service 中的 sulogin" --result "${STATUS_NOT_FOUND}" --color YELLOW
                ReportSuggestion "${TEST_NO}" "使用 sulogin 保护 rescue.service"
            fi
        else
            LogText "结果：文件 ${ROOTDIR}usr/lib/systemd/system/rescue.service 不存在"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5262
    # Description : 检查 OpenBSD 启动守护进程
    Register --test-no BOOT-5262 --os OpenBSD --weight L --network NO --category security --description "检查 OpenBSD 启动守护进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        if HasData "${RCCTLBINARY}"; then
            LogText "结果：发现 rcctl，使用它收集守护进程信息"
            # OpenBSD (Ask rcctl(8) for running daemons)
            LogText "搜索正在运行的守护进程（rcctl）"
            FIND=$(${RCCTLBINARY} ls started)
            COUNT=0
            Report "running_service_tool=rcctl"
            for ITEM in ${FIND}; do
                LogText "发现正在运行的守护进程：${ITEM}"
                Report "running_service[]=${ITEM}"
                COUNT=$((COUNT + 1 ))
            done
            LogText "提示：运行 rcctl ls all | grep -E '^(pf|check_quotas|library_aslr)$' 查看所有守护进程"
            Display --indent 2 --text "- 检查正在运行的守护进程（rcctl）" --result "${STATUS_DONE}" --color GREEN
            Display --indent 8 --text "结果：发现 ${COUNT} 个正在运行的守护进程"
            LogText "结果：发现 ${COUNT} 个正在运行的守护进程"

            # OpenBSD (Ask rcctl(8) for enabled daemons)
            LogText "搜索已启用的守护进程（rcctl）"
            FIND=$(${RCCTLBINARY} ls on | ${GREPBINARY} -E -v '^(pf|check_quotas|library_aslr)$')
            COUNT=0
            Report "boot_service_tool=rcctl"
            for ITEM in ${FIND}; do
                LogText "发现启动时启用的守护进程：${ITEM}"
                Report "boot_service[]=${ITEM}"
                COUNT=$((COUNT + 1 ))
            done
            LogText "提示：运行 rcctl ls all | grep -E '^(pf|check_quotas|library_aslr)$' 查看所有守护进程"
            Display --indent 2 --text "- 检查启动时启用的守护进程（rcctl）" --result "${STATUS_DONE}" --color GREEN
            Display --indent 8 --text "结果：发现 ${COUNT} 个启动时启用的守护进程"
            LogText "结果：发现 ${COUNT} 个启动时启用的守护进程"
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5263
    # Description : 检查 OpenBSD 可被所有用户写入的启动脚本
    Register --test-no BOOT-5263 --os OpenBSD --weight L --network NO --category security --description "检查启动文件和脚本权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        CHECKDIR="${ROOTDIR}etc/rc.d"
        LogText "结果：检查 ${ROOTDIR}etc/rc.d 脚本的可写权限"
        LogText "检查：确认目录 ${DIR} 是否存在"
        if [ -d ${CHECKDIR} ]; then
            LogText "结果：发现目录 ${DIR}"
            LogText "检查：搜索目录中的文件"
            # OpenBSD uses symlinks to create another instance of daemons
            FIND=$(${FINDBINARY} -L ${CHECKDIR} -type f -print | ${SORTBINARY})
            if [ -n "${FIND}" ]; then
                LogText "结果：目录中发现文件，开始检查权限"
                for FILE in ${FIND}; do
                    LogText "检查：检查文件 ${FILE} 的权限"
                    ShowSymlinkPath "${FILE}"
                    if [ ${FOUNDPATH} -eq 1 ]; then
                        CHECKFILE="${SYMLINK}"
                        LogText "结果：发现符号链接指向的路径（${CHECKFILE} --> ${FILE}）"
                    else
                        CHECKFILE="${FILE}"
                    fi
                    if IsWorldWritable ${CHECKFILE}; then
                        FOUND=1
                        LogText "结果：警告，文件 ${CHECKFILE} 可被所有用户写入"
                    else
                        LogText "结果：正常，文件 ${CHECKFILE} 不可被所有用户写入"
                    fi
                done
            else
                LogText "结果：目录中未发现文件。"
            fi
        else
            LogText "结果：未找到目录 ${CHECKDIR}，跳过。"
        fi

        # Other files
        CHECKFILES="${ROOTDIR}etc/rc ${ROOT}etc/rc.conf ${ROOT}etc/rc.conf.local ${ROOTDIR}etc/rc.local"
        for I in ${CHECKFILES}; do
            if [ -f ${I} ]; then
                ShowSymlinkPath "${I}"
                if [ ${FOUNDPATH} -eq 1 ]; then
                    CHECKFILE="${SYMLINK}"
                    LogText "结果：发现符号链接指向的路径（${CHECKFILE} --> ${I}）"
                else
                    CHECKFILE="${I}"
                fi
                LogText "检查：检查文件 ${CHECKFILE} 的可写权限"
                if IsWorldWritable ${CHECKFILE}; then
                    FOUND=1
                    ReportWarning "${TEST_NO}" "发现可写的启动脚本 ${CHECKFILE}"
                    LogText "结果：警告，文件 ${CHECKFILE} 可被所有用户写入"
                else
                    LogText "结果：正常，文件 ${CHECKFILE} 不可被所有用户写入"
                fi
            fi
        done

        # Check results
        if [ ${FOUND} -eq 1 ]; then
            Display --indent 2 --text "- 检查启动文件权限" --result "${STATUS_WARNING}" --color RED
            ReportWarning "${TEST_NO}" "发现可被所有用户写入的启动脚本" "-" "-"
            LogText "结果：发现一个或多个可能被其他用户写入的脚本"
            AddHP 0 3
        else
            Display --indent 2 --text "- 检查启动文件权限" --result "${STATUS_OK}" --color GREEN
            AddHP 3 3
        fi
    fi
#
#################################################################################
#
    # Test        : BOOT-5264
    # Description : 运行 systemd-analyze security
    if [ -z "${SYSTEMDANALYZEBINARY}" ]; then SKIPREASON="systemd-analyze 不可用"; PREQS_MET="NO";
    else
        SYSTEMD_VERSION=$("${SYSTEMDANALYZEBINARY}" --version | ${AWKBINARY} '/^systemd / {print $2}')
        if [ "${SYSTEMD_VERSION}" -ge 240 ]; then PREQS_MET="YES"; else SKIPREASON="systemd-analyze 版本过旧（v${SYSTEMD_VERSION}），至少需要 v240"; PREQS_MET="NO"; fi
    fi
    Register --test-no BOOT-5264 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --os Linux --weight L --network NO --category security --description "运行 systemd-analyze security"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：运行 systemd-analyze security"
        Display --indent 2 --text "- 运行 'systemd-analyze security'"
        Display --indent 6 --text "单元名称（暴露值）和安全等级"
        Display --indent 6 --text "--------------------------------"
        ${SYSTEMDANALYZEBINARY} security | while read UNIT EXPOSURE PREDICATE HAPPY; do
            if [ "${UNIT}" = "UNIT" ]; then
                continue
            fi
            STATUS="UNKNOWN"
            COLOR="BLACK"
            case ${PREDICATE} in
                PERFECT | SAFE | OK)
                    STATUS="${STATUS_PROTECTED}"
                    COLOR=GREEN
                ;;
                MEDIUM)
                    STATUS="${STATUS_MEDIUM}"
                    COLOR=WHITE
                ;;
                EXPOSED)
                    STATUS="${STATUS_EXPOSED}"
                    COLOR=YELLOW
                ;;
                UNSAFE | DANGEROUS)
                    STATUS="${STATUS_UNSAFE}"
                    COLOR=YELLOW
                ;;
            esac
            Display --indent 4 --text "- ${UNIT}（值=${EXPOSURE}）" --result "${STATUS}" --color "${COLOR}"
            LogText "结果：${UNIT} 的暴露值为 ${EXPOSURE}，安全等级为 '${STATUS}'"
        done
        ReportSuggestion "${TEST_NO}" "考虑加强系统服务的安全配置" "对每个服务运行 '${SYSTEMDANALYZEBINARY} security SERVICE'"
    fi
#
#################################################################################
#

Report "boot_loader=${BOOT_LOADER}"
Report "boot_uefi_booted=${UEFI_BOOTED}"
Report "boot_uefi_booted_secure=${UEFI_BOOTED_SECURE}"
Report "service_manager=${SERVICE_MANAGER}"

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
