#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Software: webserver
#
#################################################################################
#
    InsertSection "${SECTION_WEBSERVER}"
#
#################################################################################
#
    # Reset Apache status
    APACHE_INSTALLED=0
    APACHE_MODULES_ENABLED_LOCS="${ROOTDIR}etc/apache2/mods-enabled"
    APACHE_MODULES_LOCS="${ROOTDIR}etc/httpd/modules ${ROOTDIR}opt/local/apache2/modules ${ROOTDIR}usr/lib/apache ${ROOTDIR}usr/lib/apache2 ${ROOTDIR}usr/lib/httpd/modules ${ROOTDIR}usr/libexec/apache2 ${ROOTDIR}usr/lib64/apache2 ${ROOTDIR}usr/lib64/apache2/modules ${ROOTDIR}usr/lib64/httpd/modules ${ROOTDIR}usr/local/libexec/apache ${ROOTDIR}usr/local/libexec/apache22 ${ROOTDIR}usr/local/libexec/apache24"
    NGINX_RUNNING=0
    NGINX_CONF_LOCS="${ROOTDIR}etc/nginx ${ROOTDIR}usr/local/etc/nginx ${ROOTDIR}usr/local/nginx/conf"
    NGINX_CONF_LOCATION=""
    NGINX_CONF_FILES=""
    NGINX_CONF_FILES_ADDITIONS=""
#
#################################################################################
#
    sTEST_APACHE_TARGETS="${ROOTDIR}etc/apache ${ROOTDIR}etc/apache2 ${ROOTDIR}etc/httpd \
        ${ROOTDIR}opt/apache \
        ${ROOTDIR}usr/local/apache ${ROOTDIR}usr/local/apache2 \
        ${ROOTDIR}usr/local/etc/apache ${ROOTDIR}usr/local/etc/apache2 ${ROOTDIR}usr/local/etc/apache22 \
        ${ROOTDIR}usr/pkg/etc/httpd ${ROOTDIR}etc/sysconfig/apache2 ${ROOTDIR}usr/local/etc/apache24"

    CreateTempFile || ExitFatal
    TMPFILE="${TEMP_FILE}"
    CreateTempFile || ExitFatal
    TMPFILE2="${TEMP_FILE}"
    CreateTempFile || ExitFatal
    TMPFILE3="${TEMP_FILE}"
#
#################################################################################
#
    # Test        : HTTP-6622
    # Description : Test for Apache installation
    # Notes       : Do not run on NetBSD, -v is unknown option for httpd binary
    #               On OpenBSD do not run /usr/sbin/httpd with -v: builtin non-Apache
    if [ ! "${OS}" = "NetBSD" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6622 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Apache 是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        if [ "${OS}" = "OpenBSD" -a "${HTTPDBINARY}" = "/usr/sbin/httpd" ]; then HTTPDBINARY=""; fi
        if IsEmpty "${HTTPDBINARY}"; then
            Display --indent 2 --text "- 检查Apache" --result "${STATUS_NOT_FOUND}" --color WHITE
        else
            LogText "测试：扫描 Apache 二进制文件"
            IS_APACHE=$(${HTTPDBINARY} -v 2> /dev/null | ${GREPBINARY} -E '[aA]pache')
            if IsEmpty "${IS_APACHE}"; then
                LogText "结果：${HTTPDBINARY} 不是 Apache"
                Display --indent 2 --text "- 检查 Apache（二进制 ${HTTPDBINARY}）" --result "无匹配项" --color WHITE
            else
                Display --indent 2 --text "- 检查 Apache（二进制 ${HTTPDBINARY}）" --result "${STATUS_FOUND}" --color GREEN
                LogText "结果：${HTTPDBINARY} 似乎是 Apache HTTP 守护进程"
                APACHE_INSTALLED=1
                APACHE_VERSION=$(${HTTPDBINARY} -v 2> /dev/null | ${GREPBINARY} "^Server version:" | ${AWKBINARY} '{ print $3 }' | ${AWKBINARY} -F/ '{ print $2 }')
                LogText "Apache 版本：${APACHE_VERSION}"
                Report "apache_version=${APACHE_VERSION}"
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6624
    # Description : Testing main Apache configuration file
    # Notes       : Do not run on OpenBSD/NetBSD, as -V is an unknown option for httpd binary
    if [ ${APACHE_INSTALLED} -eq 1 ]; then
        if [ ! "${OS}" = "NetBSD" -a ! "${OS}" = "OpenBSD" ]; then
            PREQS_MET="YES"
        else
            PREQS_MET="NO"
        fi
    else
        PREQS_MET="NO"
    fi
    Register --test-no HTTP-6624 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "测试主Apache配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        APACHE_CONFIGFILE=""
        APACHE_TEST=$(${HTTPDBINARY} -V 2> /dev/null | ${GREPBINARY} "\-D SERVER_CONFIG_FILE=" | ${SEDBINARY} 's/[ ]-D SERVER_CONFIG_FILE=//' | ${TRBINARY} -d '"' | ${TRBINARY} -d ' ' | ${TRBINARY} -d '[:cntrl:]')

        if IsEmpty "${APACHE_TEST}"; then
            LogText "结果：找不到配置文件，跳过部分 Apache 相关检查"
        else
            # We found a possible match. Checking if it's valid filename. If not, we need to add a prefix
            if [ -f ${APACHE_TEST} ]; then
                APACHE_CONFIGFILE="${APACHE_TEST}"
                Display --indent 6 --text "信息：找到配置文件（${APACHE_CONFIGFILE}）"
            else
                # Probably the prefix is missing, so we are going to search that
                APACHE_HTTPDROOT=$(${HTTPDBINARY} -V 2> /dev/null | ${GREPBINARY} "\-D HTTPD_ROOT=" | ${SEDBINARY} 's/[ ]-D HTTPD_ROOT=//' | ${TRBINARY} -d '"' | ${TRBINARY} -d ' ')
                APACHE_TESTFILE="${APACHE_HTTPDROOT}/${APACHE_TEST}"
                if [ -f ${APACHE_TESTFILE} ]; then
                    APACHE_CONFIGFILE="${APACHE_TESTFILE}"
                    Display --indent 6 --text "信息：找到配置文件（${APACHE_CONFIGFILE}）"
                    LogText "结果：找到配置文件（${APACHE_CONFIGFILE}）"
                else
                    LogText "结果：文件或目录${APACHE_TESTFILE}不存在"
                    Display --indent 6 --text "[注意] 发现可能的目录或文件片段，但仍无法确定实际配置文件，跳过部分 Apache 相关检查"
                    ReportException "${TEST_NO}:1" "在 Apache 配置中发现一些未知的目录或文件引用"
                    LogText "注意：如果只安装了 Apache 二进制软件包，配置文件可能缺失。请确认是否确实需要 Apache 软件包。"
                fi
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6626
    # Description : Testing other Apache configuration files
    if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6626 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "测试其他Apache配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        for DIR in ${sTEST_APACHE_TARGETS}; do
            if [ -d ${DIR} ]; then
                find ${DIR} -name "*.conf" -print >> ${TMPFILE2}
            fi
        done

        # Sort unsorted list, save it in temp file and then remove unsorted list
        if [ -f ${TMPFILE2} ]; then
            ${SORTBINARY} -u ${TMPFILE2} >> ${TMPFILE}
            rm -f ${TMPFILE2}
        fi
        cVHOSTS=0; tVHOSTS=""

        # Check every configuration file
        for I in $(cat ${TMPFILE}); do
            LogText "Apache 配置文件：${I}"

            FileIsReadable ${I}
            if [ ${CANREAD} -eq 1 ]; then
                # Search Virtual Hosts
                for J in $(${GREPBINARY} "ServerName" ${I} | ${GREPBINARY} -v "^#" | ${AWKBINARY} '{ if ($1=="ServerName" && $2!="*" && $2!="default") print $2 }'); do
                    if HasData "${J}"; then
                        tVHOSTS="${tVHOSTS} ${J}"
                        cVHOSTS=$((cVHOSTS + 1))
                    fi
                done
                # Search Server aliases
                for J in $(${GREPBINARY} "ServerAlias" ${I} | ${GREPBINARY} -v "^#" | ${SEDBINARY} "s/\s*ServerAlias //g" | ${SEDBINARY} "s/#.*//g"); do
                    if [ -n "${J}" ]; then
                        tVHOSTS="${tVHOSTS} ${J}"
                        cVHOSTS=$((cVHOSTS + 1))
                    fi
                done
            else
                LogText "结果：无法使用该用户读取配置文件 ID"
                ReportException "${TEST_NO}:1" "无法读取配置文件 $I"
            fi
        done

        # Log all virtual hosts we found
            for J in ${tVHOSTS}; do
                if [ -n "${J}" ]; then
                    LogText "虚拟主机：${J}"
                    #Report "apache_vhost_name[]=${J}"
                fi
            done

        # Show number of vhosts if we found any
        LogText "结果：找到${cVHOSTS}虚拟主机"
        if [ ${cVHOSTS} -gt 0 ]; then
            Display --indent 6 --text "信息：找到 ${cVHOSTS} 虚拟主机"
        else
            Display --indent 6 --text "信息：未找到虚拟主机"
        fi
    fi

    # Remove temp files
    if [ -f ${TMPFILE} -a -n "${TMPFILE}" ]; then
        rm -f ${TMPFILE}
    fi
    if [ -n "${TMPFILE2}" ]; then if [ -f ${TMPFILE2} ]; then rm -f ${TMPFILE2}; fi; fi
#
#################################################################################
#
    # TODO
    # Do you have Apache running and want to contribute? Help us testing this control and send in a pull request

    # Test        : HTTP-6630
    # Description : Search for all loaded modules
    #if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no HTTP-6630 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "Determining all loaded Apache modules"
    #if [ ${SKIPTEST} -eq 0 ]; then
    #    # Testing Debian style
    #    LogText "Test: searching loaded/enabled Apache modules"
    #    apachectl -t -D DUMP_MODULES 2>&1 | ${GREPBINARY} -E -v "(Loaded Modules|Syntax OK)" | ${SEDBINARY} 's/(\(shared\|static\))//' | ${SEDBINARY} 's/ //'
    #    for I in ${APACHE_MODULES_ENABLED_LOCS}; do
    #        LogText "Test: checking ${I}"
    #        if [ -d ${I} ]; then
    #            FIND=$(${GREPBINARY} -r LoadModule ${I}/* | ${GREPBINARY} -v "^#" | ${AWKBINARY} '{ print $2":"$3 }')
    #          else
    #            LogText "Result: ${I} does not exist"
    #        fi
    #    done
    #fi
#
#################################################################################
#
    # Test        : HTTP-6632
    # Description : Search for available Apache modules
    if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6632 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "确定所有可用的 Apache 模块"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索可用的 Apache 模块"
        COUNT=0
        for DIR in ${APACHE_MODULES_LOCS}; do
            DirectoryExists ${DIR}
            if [ ${DIRECTORY_FOUND} -eq 1 ]; then
                FIND=$(${FINDBINARY} ${DIR} -name "mod_*" -print | ${SORTBINARY})
                for ITEM in ${FIND}; do
                    Report "apache_module[]=${ITEM}"
                    LogText "结果：找到Apache模块${ITEM}"
                    COUNT=$((COUNT + 1))
                done
            fi
        done
        if [ ${COUNT} -eq 0 ]; then
            Display --indent 4 --text "* 可加载模块" --result "${STATUS_NONE}" --color WHITE
            ReportException "${TEST_NO}:1" "未找到可加载的 Apache 模块"
        else
            Display --indent 4 --text "* 可加载模块" --result "${STATUS_FOUND} (${COUNT})" --color GREEN
            Display --indent 8 --text "- 找到 ${COUNT} 可加载模块"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6640
    # Description : Search for special Apache modules: evasive
    if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6640 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "确定特定 Apache 模块是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check modules, module
        if CheckItem "apache_module" "/mod_evasive([0-9][0-9])?.so"; then
            Display --indent 10 --text "mod_evasive：防DoS/暴力破解" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        else
            Display --indent 10 --text "mod_evasive：防DoS/暴力破解" --result "${STATUS_NOT_FOUND}" --color WHITE
            AddHP 2 3
            ReportSuggestion "${TEST_NO}" "安装 Apache mod_evasive 以保护网络服务器免受 DoS/暴力尝试"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6641
    # Description : Search for special Apache modules: Quality of Service
    # Notes       : Was mod_qos before. Since Apache 2.2.15 mod_reqtimeout
    if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6641 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "确定特定 Apache 模块是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check modules, module
        if CheckItem "apache_module" "/mod_(reqtimeout|qos).so"; then
            Display --indent 10 --text "mod_reqtimeout/mod_qos" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        else
            Display --indent 10 --text "mod_reqtimeout/mod_qos" --result "${STATUS_NOT_FOUND}" --color WHITE
            AddHP 2 3
            ReportSuggestion "${TEST_NO}" "安装 Apache mod_reqtimeout 或 mod_qos 以保护网络服务器免受 Slowloris 攻击"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6643
    # Description : Search for special Apache modules: security
    if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6643 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "确定特定 Apache 模块是否存在"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check modules, module
        if CheckItem "apache_module" "/mod_security(2|3).so" ; then
            Display --indent 10 --text "ModSecurity：Web应用程序防火墙" --result "${STATUS_FOUND}" --color GREEN
            AddHP 3 3
        else
            Display --indent 10 --text "ModSecurity：Web应用程序防火墙" --result "${STATUS_NOT_FOUND}" --color WHITE
            AddHP 2 3
            ReportSuggestion "${TEST_NO}" "安装 Apache modsecurity 以保护 Web 服务器免受 Web 应用程序攻击"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6660
    # Description : Search for "TraceEnable off" in configuration files
    if [ ${APACHE_INSTALLED} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6660 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Apache 安全设置：TraceEnable"
    if [ ${SKIPTEST} -eq 0 ]; then
        for DIR in ${sTEST_APACHE_TARGETS}; do
            if [ -d ${DIR} ]; then
                find ${DIR} -name "*.conf" -print >> ${TMPFILE3}
            fi
        done

        # Check all Apache conf-files for TraceEnable
        if [ -f ${TMPFILE3} ]; then
            Display --indent 2 --text '- 检查以下文件中的 TraceEnable 设置：'
            for APACHE_CONFFILE in $(cat ${TMPFILE3}); do
                TRACEENABLE=$( ${GREPBINARY} -i -E '^TraceEnable' ${APACHE_CONFFILE} | ${AWKBINARY} '{print $2}' )
                if [ ! ${TRACEENABLE} ]; then
                    LogText "结果：在 ${APACHE_CONFFILE} 中找不到 TraceEnable 设置"
                    Display --indent 4 --text "  ${APACHE_CONFFILE}" --result "${STATUS_NOT_FOUND}" --color WHITE
                else
                    TRACEENABLED_SETTING=$( echo ${TRACEENABLE} | tr 'A-Z' 'a-z' )
                    if [ "x${TRACEENABLED_SETTING}" = 'xoff' ]; then
                        LogText "结果：在 ${APACHE_CONFFILE} 中发现 TraceEnable 设置为 'off'"
                        Report "Apache setting: 'TraceEnable Off' in ${APACHE_CONFFILE}"
                        Display --indent 4 --text "  ${APACHE_CONFFILE}" --result "${STATUS_FOUND}" --color GREEN
                    else
                        LogText "结果：发现 TraceEnable 设置为 '"${TRACEENABLE}"' in ${APACHE_CONFFILE}"
                        Report "Apache setting: 'TraceEnable "${TRACEENABLE}"' in ${APACHE_CONFFILE}"
                        Display --indent 4 --text "  ${APACHE_CONFFILE}" --result "${STATUS_SUGGESTION}" --color YELLOW
                        ReportSuggestion "${TEST_NO}" "建议在 ${APACHE_CONFFILE} 中设置 'TraceEnable Off'" "仅在测试和诊断时将 TraceEnable 设置为 'On' 或 'extended'。"
                    fi
                fi
            done
            rm -f ${TMPFILE3}
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6702
    # Description : Search for nginx process
    Register --test-no HTTP-6702 --weight L --network NO --category security --description "检查nginx进程"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索正在运行的nginx进程"
        if IsRunning "nginx"; then
            LogText "结果：发现正在运行 nginx 进程"
            Display --indent 2 --text "- 检查nginx" --result "${STATUS_FOUND}" --color GREEN
            NGINX_RUNNING=1
            Report "nginx_running=1"
        else
            LogText "结果：未找到正在运行的 nginx 进程"
            Display --indent 2 --text "- 检查nginx" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6704
    # Description : Search for nginx configuration file
    if [ ${NGINX_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6704 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查nginx配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：搜索nginx配置文件"
        for DIR in ${NGINX_CONF_LOCS}; do
            if [ -f ${DIR}/nginx.conf ]; then
                NGINX_CONF_LOCATION="${DIR}/nginx.conf"
                LogText "找到文件 ${NGINX_CONF_LOCATION}"
                NGINX_CONF_FILES="${DIR}/nginx.conf"
            fi
        done
        if HasData "${NGINX_CONF_LOCATION}"; then
            LogText "结果：找到nginx配置文件"
            Report "nginx_main_conf_file=${NGINX_CONF_LOCATION}"
            Display --indent 4 --text "- 搜索nginx配置文件" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "结果：未找到 nginx 配置文件"
            Display --indent 2 --text "- 搜索nginx配置文件" --result "${STATUS_NOT_FOUND}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6706
    # Description : Search for includes within nginx configuration file
    # Notes       : Daemon nginx should be running, nginx.conf should be found
    if [ ${NGINX_RUNNING} -eq 1 -a -n "${NGINX_CONF_LOCATION}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6706 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查其他 nginx 配置文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        CreateTempFile || ExitFatal
        TMPFILE="${TEMP_FILE}"

        COUNT=0
        ${SEDBINARY} -e 's/^[ \t]*//' ${NGINX_CONF_LOCATION} | ${GREPBINARY} -v "^#" | ${GREPBINARY} -v "^$" | ${SEDBINARY} 's/[\t]/ /g' | ${SEDBINARY} 's/  / /g' | ${SEDBINARY} 's/  / /g' >> ${TMPFILE}
        # Search for included configuration files (may include directories and wild cards)
        FIND=$(${GREPBINARY} "include" ${NGINX_CONF_LOCATION} | ${AWKBINARY} '{ if ($1=="include") { print $2 }}' | ${SEDBINARY} 's/;$//g')
        for I in ${FIND}; do
            FIND2=$(${LSBINARY} ${I} 2>/dev/null)
            for J in ${FIND2}; do
                # Ensure that we are parsing normal files
                if [ -f ${J} ]; then
                    COUNT=$((COUNT + 1))
                    LogText "结果：找到Nginx配置文件${J}"
                    Report "nginx_sub_conf_file[]=${J}"
                    FileIsReadable ${J}
                    if [ ${CANREAD} -eq 1 ]; then
                        NGINX_CONF_FILES="${NGINX_CONF_FILES} ${J}"
                        FIND3=$(sed -e 's/^[ \t]*//' ${J} | ${GREPBINARY} -v "^#" | ${GREPBINARY} -v "^$" | ${SEDBINARY} 's/[\t]/ /g' | ${SEDBINARY} 's/  / /g' | ${SEDBINARY} 's/  / /g' >> ${TMPFILE})
                    else
                        ReportException "${TEST_NO}:1" "文件 ${J} 不可读，无法解析"
                    fi
                fi
            done
        done

        # Sort all discovered configuration lines and store unique ones. Also strip out the mime types configured in nginx
        SORTFILE=$(${SORTBINARY} -u ${TMPFILE} | ${SEDBINARY} 's/ /:space:/g' | ${GREPBINARY} -E -v "(application|audio|image|text|video)/" | ${GREPBINARY} -E -v "({|})")
        for I in ${SORTFILE}; do
            I=$(echo ${I} | ${SEDBINARY} 's/:space:/ /g')
            Report "nginx_config_option[]=${I}";
        done

        # Remove unsorted file for next tests
        if [ -f ${TMPFILE} ]; then rm -f ${TMPFILE}; fi

        if [ ${COUNT} -eq 0 ]; then
            LogText "结果：未找到 nginx include 语句"
        else
            Display --indent 6 --text "- 找到 nginx 包括" --result "${COUNT} FOUND" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6708
    # Description : Check discovered nginx configuration settings for further hardening
    # Notes       : Daemon of nginx should be running, nginx.conf should be found
    if [ ${NGINX_RUNNING} -eq 1 -a -n "${NGINX_CONF_FILES}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6708 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查发现的 nginx 配置设置"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：开始解析所有发现的 nginx 选项"
        Display --indent 4 --text "- 解析配置选项"
        for FILE in ${NGINX_CONF_FILES}; do
            FILENAME=$(echo ${FILE} | ${AWKBINARY} -F/ '{print $NF}')
            if [ ! "${FILENAME}" = "mime.types" ]; then
                if FileIsReadable ${FILE}; then
                    Display --indent 8 --text "- ${FILE}"
                    ParseNginx ${FILE}
                else
                    Display --indent 8 --text "- ${FILE}" --result "已跳过（不可读）" --color YELLOW
                fi
            else
                LogText "结果：该配置文件通常不包含有价值的信息，已跳过"
            fi
        done
        if [ -n "${NGINX_CONF_FILES_ADDITIONS}" ]; then
            for I in ${NGINX_CONF_FILES_ADDITIONS}; do
                FILENAME=$(echo ${I} | ${AWKBINARY} -F/ '{print $NF}')
                if [ ! "${FILENAME}" = "mime.types" ]; then
                    if FileIsReadable ${I}; then
                        Display --indent 8 --text "- ${I}"
                        ParseNginx ${I}
                    else
                        Display --indent 8 --text "- ${I}" --result "已跳过（不可读）" --color YELLOW
                    fi
                else
                    LogText "结果：该配置文件通常不包含有价值的信息，已跳过"
                fi
            done
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6710
    # Description : Check SSL configuration of nginx
    # Notes       : Daemon of nginx should be running, nginx.conf should be found
    if [ ${NGINX_RUNNING} -eq 1 -a -n "${NGINX_CONF_LOCATION}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6710 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 nginx SSL 配置设置"
    if [ ${SKIPTEST} -eq 0 ]; then
        NGINX_SSL_SUGGESTION=0
        if [ ${NGINX_SSL_ON} -eq 1 ]; then
            LogText "结果：在一台或多台虚拟主机上的 nginx 中配置了 SSL"
            Display --indent 6 --text "- SSL 配置" --result "${STATUS_YES}" --color GREEN
            AddHP 5 5
            # Cipher tests
            if [ ${NGINX_SSL_CIPHERS} -eq 1 ]; then
                Display --indent 8 --text "- 配置密码" --result "${STATUS_YES}" --color GREEN
            else
                Display --indent 8 --text "- 配置密码" --result "${STATUS_NO}" --color RED
                NGINX_SSL_SUGGESTION=1
            fi

            if [ ${NGINX_SSL_PREFER_SERVER_CIPHERS} -eq 1 ]; then
                Display --indent 8 --text "- 更喜欢服务器密码" --result "${STATUS_YES}" --color GREEN
            else
                Display --indent 8 --text "- 更喜欢服务器密码" --result "${STATUS_NO}" --color RED
                NGINX_SSL_SUGGESTION=1
            fi

            if [ ${NGINX_SSL_PROTOCOLS} -eq 1 ]; then
                Display --indent 8 --text "- 配置协议" --result "${STATUS_YES}" --color GREEN
                if [ ${NGINX_WEAK_SSL_PROTOCOL_FOUND} -eq 0 ]; then
                    Display --indent 10 --text "- 发现不安全协议" --result "${STATUS_NO}" --color GREEN
                else
                    Display --indent 10 --text "- 发现不安全协议" --result "${STATUS_YES}" --color RED
                    ReportSuggestion "${TEST_NO}" "在 nginx 配置中禁用弱协议"
                fi
            else
                Display --indent 8 --text "- 配置协议" --result "${STATUS_NO}" --color RED
                NGINX_SSL_SUGGESTION=1
            fi
        else
            LogText "结果：未找到 SSL 配置"
            Display --indent 6 --text "- SSL 配置" --result "${STATUS_NO}" --color RED
            ReportSuggestion "${TEST_NO}" "将 HTTPS 添加到 nginx 虚拟主机，以增强对敏感数据和隐私的保护"
            AddHP 1 5
        fi
        if [ ${NGINX_SSL_SUGGESTION} -eq 1 ]; then
            LogText "结果：nginx 配置的一个或多个部分可以针对 SSL 进行增强"
            ReportSuggestion "${TEST_NO}" "更改 HTTPS 和 SSL 设置以增强对敏感数据和隐私的保护"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6712
    # Description : Check logging configuration of nginx
    # Notes       : Daemon of nginx should be running, nginx.conf should be found
    if [ ${NGINX_RUNNING} -eq 1 -a -n "${NGINX_CONF_LOCATION}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6712 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 nginx 访问日志记录"
    if [ ${SKIPTEST} -eq 0 ]; then
        NGINX_LOG_SUGGESTION=0
        Display --indent 6 --text "- 检查日志文件配置"

        # Check for missing access log
        if [ ${NGINX_ACCESS_LOG_MISSING} -eq 1 ]; then
            NGINX_LOG_SUGGESTION=1
            Display --indent 8 --text "- 缺少日志文件（access_log）" --result "${STATUS_YES}" --color RED
        else
            Display --indent 8 --text "- 缺少日志文件（access_log）" --result "${STATUS_NO}" --color GREEN
        fi
        # Access log disabled
        if [ ${NGINX_ACCESS_LOG_DISABLED} -eq 1 ]; then
            NGINX_LOG_SUGGESTION=1
            LogText "结果：发现一个或多个虚拟主机的访问日志被禁用"
            Display --indent 8 --text "- 禁用访问日志记录" --result "${STATUS_YES}" --color RED
            AddHP 2 3
        else
            LogText "结果：未找到禁用访问日志的虚拟主机"
            Display --indent 8 --text "- 禁用访问日志记录" --result "${STATUS_NO}" --color GREEN
            AddHP 3 3
        fi
        # Report suggestion
        if [ ${NGINX_LOG_SUGGESTION} -eq 1 ]; then
            ReportSuggestion "${TEST_NO}" "检查您的 nginx 访问日志是否正常运行"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6714
    # Description : Check missing error logs in nginx
    if [ ${NGINX_RUNNING} -eq 1 -a -n "${NGINX_CONF_LOCATION}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6714 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 nginx 中是否缺少错误日志"
    if [ ${SKIPTEST} -eq 0 ]; then
        NGINX_LOG_SUGGESTION=0
        # Check for missing access log
        if [ ${NGINX_ERROR_LOG_MISSING} -eq 1 ]; then
            NGINX_LOG_SUGGESTION=1
            Display --indent 8 --text "- 缺少日志文件（error_log）" --result "${STATUS_YES}" --color RED
        else
            Display --indent 8 --text "- 缺少日志文件（error_log）" --result "${STATUS_NO}" --color GREEN
        fi
        # Report suggestion
        if [ ${NGINX_LOG_SUGGESTION} -eq 1 ]; then
            ReportSuggestion "${TEST_NO}" "检查您的 nginx error_log 语句"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6716
    # Description : Check debug mode on error log in nginx
    if [ ${NGINX_RUNNING} -eq 1 -a -n "${NGINX_CONF_LOCATION}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6716 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 nginx 中错误日志的调试模式"
    if [ ${SKIPTEST} -eq 0 ]; then
        NGINX_LOG_SUGGESTION=0
        # Access log in debug mode
        if [ ${NGINX_ERROR_LOG_DEBUG} -eq 1 ]; then
            NGINX_LOG_SUGGESTION=1
            LogText "结果：找到一个或多个虚拟主机，其错误日志处于调试模式"
            Display --indent 8 --text "- error_log 的调试模式" --result "${STATUS_YES}" --color RED
            AddHP 2 3
        else
            LogText "结果：找不到在调试模式下有错误日志的虚拟主机"
            Display --indent 8 --text "- error_log 的调试模式" --result "${STATUS_NO}" --color GREEN
            AddHP 3 3
        fi
        # Report suggestion
        if [ ${NGINX_LOG_SUGGESTION} -eq 1 ]; then
            ReportSuggestion "${TEST_NO}" "检查您的 nginx error_log 语句并禁用调试模式"
        fi
    fi
#
#################################################################################
#
    # Test        : HTTP-6720
    # Description : Search for nginx log files
    if [ ${NGINX_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no HTTP-6720 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查Nginx日志文件"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "测试：检查具有日志文件定义的文件目录"
        for DIR in ${NGINX_CONF_LOCS}; do
            LogText "测试：检查${DIR}"
            if [ -d ${DIR} ]; then
                LogText "结果：目录 ${DIR} 存在，将作为搜索路径"
                FIND=$(find ${DIR} -type f -exec ${GREPBINARY} access_log \{\} \; | ${GREPBINARY} -v "#" | ${AWKBINARY} '{ if($1=="access_log") { print $2 } }' | ${SEDBINARY} 's/;$//g' | ${SORTBINARY} -u)
                if IsEmpty "${FIND}"; then
                    LogText "结果：未找到日志文件"
                else
                    LogText "结果：找到一个或多个日志文件"
                    for FILE in ${FIND}; do
                        if [ -f ${FILE} ]; then
                            LogText "找到日志文件：${FILE}"
                            Report "log_file=${FILE}"
                        else
                            LogText "发现不存在的日志文件：${FILE}"
                        fi
                    done
                fi
            else
                LogText "结果：未找到目录 ${DIR}，跳过在该目录中的搜索。"
            fi
        done
        unset DIR FILE FIND
    fi
#
#################################################################################
#
    # Remove temp file (double check)
    if [ -n "${TMPFILE}" ]; then if [ -f ${TMPFILE} ]; then rm -f ${TMPFILE}; fi; fi
    if [ -n "${TMPFILE2}" ]; then if [ -f ${TMPFILE2} ]; then rm -f ${TMPFILE2}; fi; fi
    if [ -n "${TMPFILE3}" ]; then if [ -f ${TMPFILE3} ]; then rm -f ${TMPFILE3}; fi; fi

    WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
