#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright (c) Michael Boelen, CISOfy, and many contributors.
#
# Website  : https://cisofy.com/
# Blog     : https://linux-audit.com/
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Containers, Zones, Jails
#
#################################################################################
#
    InsertSection "${SECTION_CONTAINERS}"
#
#################################################################################
#
    DOCKER_CONTAINERS_RUNNING=0
    DOCKER_CONTAINERS_TOTAL=0
    DOCKER_FILE_PERMISSIONS_WARNINGS=0
    RUN_DOCKER_TESTS=0
#
#################################################################################
#
    # Test        : CONT-8004
    # Description : Query running Solaris zones
    if [ -x ${ROOTDIR}usr/sbin/zoneadm ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CONT-8004 --os Solaris --weight L --network NO --category security --description "查询正在运行的 Solaris 区域"
    if [ ${SKIPTEST} -eq 0 ]; then
        LogText "检查：使用 zoneadm 查询全部正在运行的区域"
        FIND=$(${ROOTDIR}usr/sbin/zoneadm list -p | ${AWKBINARY} -F: '{ if ($2!="global") print $0 }')
        if [ -n "${FIND}" ]; then
            COUNT=0
            for ITEM in ${FIND}; do
                COUNT=$((COUNT + 1))
                ZONEID=$(echo ${ITEM} | ${CUTBINARY} -d ':' -f1)
                ZONENAME=$(echo ${ITEM} | ${CUTBINARY} -d ':' -f2)
                LogText "结果：发现正在运行的区域 ${ZONENAME}"
                Report "solaris_running_zone[]=${ZONENAME} [id:${ZONEID}]"
            done
            LogText "结果：共有 ${COUNT} 个正在运行的区域"
            Display --indent 2 --text "- 正在检查 Solaris 区域" --result "发现 ${COUNT} 个区域" --color GREEN
        else
            LogText "结果：未发现正在运行的区域"
            Display --indent 2 --text "- 正在检查 Solaris 区域" --result "${STATUS_NONE}" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Do you have Xen running? Help us testing this test and submit a pull request on GitHub

    # Test        : CONT-1906 TODO
    # Description : Query running Xen zones
    #if [ -x /usr/bin/xm ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no CONT-1906 --weight L --network NO --category security --description "Query Xen guests"
    #if [ ${SKIPTEST} -eq 0 ]; then
        # Show Xen guests
        #FIND=$(xm list | ${AWKBINARY} '$1 != "Name|Domain-0" {print $1","$2}')
        #for I in ${FIND}; do
            #XENGUESTNAME=$(echo ${I} | ${CUTBINARY} -d ':' -f1)
            #XENGUESTID=$(echo ${I} | ${CUTBINARY} -d ':' -f2)
            #LogText "Result: found Xen guest ${XENGUESTNAME} (ID: ${XENGUESTID})"
        #done
    #fi
#
#################################################################################
#
    # Test        : CONT-8102
    # Description : Checking Docker daemon status and basic information for later tests
    Register --test-no CONT-8102 --weight L --network NO --category security --description "检查 Docker 状态和基本信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        if IsRunning "dockerd"; then
            LogText "结果：发现正在运行的 Docker 守护进程"
            Report "docker_daemon_running=1"
            DOCKER_DAEMON_RUNNING=1
            RUN_DOCKER_TESTS=1
            Display --indent 4 --text "- Docker"
            Display --indent 6 --text "- Docker 守护进程" --result "${STATUS_RUNNING}" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : CONT-8104
    # Description : Checking Docker info for any warnings
    # Notes       : Hardening points are awarded, as usually warnings are the result of missing controls to restrict boundaries like memory
    if HasData "${DOCKERBINARY}"; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CONT-8104 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Docker 信息中是否存在警告"
    if [ ${SKIPTEST} -eq 0 ]; then
        COUNT=0
        LogText "检查：Docker 是否存在警告"
        FIND=$(${DOCKERBINARY} version 2>&1)
        if [ $? -gt 0 ]; then
            Display --indent 8 --text "- Docker 状态" --result "${STATUS_ERROR}" --color RED
            LogText "结果：docker version 返回非零退出码，已停止后续 Docker 检查"
            RUN_DOCKER_TESTS=0
        fi
        FIND=$(${DOCKERBINARY} info 2>&1 | ${GREPBINARY} -E "^WARNING:|^ERROR:" | ${CUTBINARY} -d " " -f 2- | ${SEDBINARY} 's/ /:space:/g')
        if [ ! "${FIND}" = "" ]; then
            LogText "结果：输出中发现警告"
            for I in ${FIND}; do
                J=$(echo ${I} | ${SEDBINARY} 's/:space:/ /g')
                LogText "输出：${J}"
                COUNT=$((COUNT + 1))
            done
            Display --indent 8 --text "- Docker 信息输出（警告）" --result "${COUNT}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "执行 'docker info' 查看适用于 Docker 守护进程的警告"
            AddHP 3 4
        else
            LogText "结果：'docker info' 输出中未发现警告"
            Display --indent 8 --text "- Docker 信息输出（警告）" --result "${STATUS_NONE}" --color GREEN
            AddHP 1 1
        fi
    fi
#
#################################################################################
#
    # Test        : CONT-8106
    # Description : Checking Docker containers (basic stats)
    # Notes       : Hardening points are awarded, if there aren't a lot of stopped containers
    if [ -n "${DOCKERBINARY}" -a ${RUN_DOCKER_TESTS} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CONT-8106 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "收集 Docker 的基本统计信息"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 6 --text "- 容器"

        # Check total of containers
        LogText "检查：Docker 容器总数"
        DOCKER_CONTAINERS_TOTAL=$(${DOCKERBINARY} info 2> /dev/null | ${GREPBINARY} -E "^[ \t]?Containers: " | ${AWKBINARY} '{ print $2 }')
        if [ -z "${DOCKER_CONTAINERS_TOTAL}" ]; then
            DOCKER_CONTAINERS_TOTAL=0
        fi

        LogText "结果：docker info 显示 ${DOCKER_CONTAINERS_TOTAL} 个容器"
        DOCKER_CONTAINERS_TOTAL2=$(${DOCKERBINARY} ps -a 2> /dev/null | ${GREPBINARY} -c -v "CONTAINER")
        LogText "结果：docker ps -a 显示 ${DOCKER_CONTAINERS_TOTAL2} 个容器"
        if [ ! "${DOCKER_CONTAINERS_TOTAL}" = "${DOCKER_CONTAINERS_TOTAL2}" ]; then
            LogText "结果：检测到数量差异，此情况不符合预期"
            ReportSuggestion "${TEST_NO}" "检查 'docker ps -a' 和 'docker info' 的输出，确认二者报告不同容器数量的原因"
            Display --indent 8 --text "- 容器总数" --result "${STATUS_UNKNOWN}" --color RED
        else
            Display --indent 8 --text "- 容器总数" --result "${DOCKER_CONTAINERS_TOTAL}" --color WHITE
        fi

        # Check running instances
        DOCKER_CONTAINERS_RUNNING=$(${DOCKERBINARY} ps 2> /dev/null | ${GREPBINARY} -c -v "CONTAINER")
        if [ ${DOCKER_CONTAINERS_RUNNING} -gt 0 ]; then
            Display --indent 10 --text "- 正在运行的容器" --result "${DOCKER_CONTAINERS_RUNNING}" --color GREEN
            LogText "结果：当前有 ${DOCKER_CONTAINERS_RUNNING} 个活动容器"
            Report "docker_containers_running=${DOCKER_CONTAINERS_RUNNING}"
        else
            LogText "结果：没有活动容器"
            Report "docker_containers_running=0"
        fi
    fi
#
#################################################################################
#
    # Test        : CONT-8107
    # Description : Checking Docker number of unused containers
    # Notes       : Hardening points are awarded, if there aren't a lot of stopped containers
    if [ -n "${DOCKERBINARY}" -a ${RUN_DOCKER_TESTS} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CONT-8107 --preqs-met ${PREQS_MET} --weight L --network NO --category performance --description "检查 Docker 容器数量"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if there aren't too many unused containers on the system
        if [ ${DOCKER_CONTAINERS_TOTAL} -gt 0 ]; then
            DOCKER_CONTAINERS_UNUSED=$((DOCKER_CONTAINERS_TOTAL - DOCKER_CONTAINERS_RUNNING))
            if [ ${DOCKER_CONTAINERS_UNUSED} -gt 10 ]; then
                ReportSuggestion "${TEST_NO}" "系统中发现超过 10 个未使用的容器。可根据 'docker ps -a' 的输出清理旧容器"
                Display --indent 8 --text "- 未使用的容器" --result "${DOCKER_CONTAINERS_UNUSED}" --color RED
                AddHP 0 2
            else
                LogText "结果：发现 ${DOCKER_CONTAINERS_UNUSED} 个未使用的容器"
                Display --indent 8 --text "- 未使用的容器" --result "${DOCKER_CONTAINERS_UNUSED}" --color YELLOW
                AddHP 1 1
            fi
        fi
    fi
#
#################################################################################
#
    # Test        : CONT-8108
    # Description : Checking Docker file permissions
    # Notes       : /var/run/docker.sock - Usually root as owner, docker as group - should not be world writable
    if [ -n "${DOCKERBINARY}" -a ${RUN_DOCKER_TESTS} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CONT-8108 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "检查 Docker 文件权限"
    if [ ${SKIPTEST} -eq 0 ]; then
        NOT_WORLD_WRITABLE="${ROOTDIR}var/run/docker.sock"
        for FILE in ${NOT_WORLD_WRITABLE}; do
            LogText "检查：${FILE}"
            if [ -f ${FILE} ]; then
                LogText "结果：发现文件 ${FILE}，将检查其权限"
                if IsWorldWritable ${FILE}; then
                    LogText "结果：该文件允许其他用户写入，存在安全风险，例如权限提升"
                    ReportWarning "${TEST_NO}" "Docker 文件允许所有用户写入" "${FILE}" "-"
                    DOCKER_FILE_PERMISSIONS_WARNINGS=$((DOCKER_FILE_PERMISSIONS_WARNINGS + 1))
                else
                    LogText "结果：文件 ${FILE} 不允许其他用户写入，权限正常"
                fi
            fi
        done
        if [ ${DOCKER_FILE_PERMISSIONS_WARNINGS} -gt 0 ]; then
            Display --indent 4 --text "- 文件权限" --result "${STATUS_WARNING}"S --color YELLOW
            AddHP 0 5
        else
            Display --indent 4 --text "- 文件权限" --result "${STATUS_OK}" --color GREEN
            AddHP 5 5
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

# EOF
